cli/nep11_test.go, pkg/smartcontract/manifest/manifest.go, pkg/smartcontract/manifest/manifest_test.go, pkg/vm/stackitem/serialization.go
Close #2021. 
State root at that height matches the one specified in task.
Also found and fixed another bug which affected `getapplicationlog` response.
=> Fix manifest `Extra` field marshaling

pkg/core/blockchain.go, pkg/core/blockchain_test.go, pkg/core/stateroot/module.go
With StateRootInHeader setting on only one header of height N+1
can be added to the chain of height N, because we need local stateroot
to verify headers (which is calculated for the last stored block N).
Thus, adding chunk of headers starting from the current chain's heigh
is impossible and (*Blockchain).AddHeaders doesn't have much sense.
Verify header.PrevStateRoot only for header N+1. Rest of the
headers should be added without PrevStateRoot verification.
=> core: allow to add several headers with StateRootInHeader on

cli/smartcontract/smart_contract.go, cli/wallet/nep11.go, cli/wallet/nep17.go
Sometimes on-chain invocations need a bit more GAS than expected after test
invocations, so let the user compensate for that. 2.x has similar option since
483fefbb628123b7fe9ecb16f13062bf93d68156.
=> cli/sc: add sysgas option to add some gas

pkg/core/mpt/batch.go, pkg/core/mpt/batch_test.go, pkg/core/native/native_nep17.go
If the only child left is hash node, we need to retrieve it from storage.
Another commit fixes only state dump.
After the restore node seems (waited for a couple of minutes) to be adding state roots without errors.
=> Fix MPT branch node strip after deletion

pkg/services/oracle/jsonpath/jsonpath_test.go
Turns out, nothing should be changed in our implementation because
nil-check is done implicitly by type casts or type switches.
=> jsonpath: add tests for `null` objects, fix #2039

pkg/vm/vm.go, pkg/vm/vm_test.go
We should copy all primitive types, so it is a DUP essentially.
The bug is quite severe, e.g. this function compiled will return 2:
```
func minus2() int {
x := 1
return -x + (-x)
}
```
This fixes state difference at height 275663
for tx 3c498317684d63849b03e4c58ad57ce4b19bb206b7b01bcc64233de3b3e207f4
=> vm: copy integers for unary operations, fix #2051

pkg/io/binaryWriter.go, pkg/vm/stackitem/json.go, pkg/vm/stackitem/json_test.go, pkg/vm/stackitem/serialization.go, pkg/vm/stackitem/serialization_test.go
Cache already marshaled values.
The expected memory overhead is linear (map itself + living references to the old buffer memory in case it grows with reallocation).
=> Speedup stackitem json serialization

pkg/core/helper_test.go, pkg/core/interop_system.go, pkg/core/interop_system_test.go, pkg/core/storage/memory_store.go
=> Optimize `storageFind`

cli/dump_test.go, cli/server/server.go, cli/server/server_test.go
Close #1991 .
Testing done:
1. Restore from ground for neo-go emitted dump + incremental dump from C# node (link in task).
2. Restore from specific height for both kinds of dumps.
For incremental dumps `skip` value is overridden. I propose to remove it completely, as essentialy it isn't a parameter, it has only 1 possible value (that is `chain height + 1`) with some peculiarities for genesis block.
=> Support incremental dumps

pkg/core/blockchain.go, pkg/core/native/policy.go, pkg/core/stateroot/module.go, pkg/network/extpool/pool.go
=> Tune fixed GAS limits

pkg/rpc/request/param.go, pkg/rpc/request/param_test.go
Turns out, it's completely legal in C#, see neo-project/neo#2543.
=> rpc/request: support passing accounts as addresses

pkg/core/oracle_test.go, pkg/services/oracle/oracle.go, pkg/services/oracle/request.go, pkg/services/oracle/response.go
We don't have many of the problems neo-project/neo-modules#608 fixes, but we have one of our own.
=> Fix oracle service behaviour

cli/contract_test.go, cli/executor_test.go, cli/main.go, cli/query/query.go, cli/query_test.go, docs/cli.md, docs/consensus.md
Implement a way to check if tx has been persisted on blockchain and
to get general info about transaction. Much more convenient than
handwritten curl queries.
=> cli: add `query tx` command, close #2069

go.mod, go.sum, pkg/consensus/block.go, pkg/consensus/consensus.go
It was broken somewhere between 2f490a3403fea308a80609c0086b331deca4b1ba and
85ce207f4065c642de314b2c0cf9851627d552fa leading to panic on watch only node:
2021-07-21T16:21:39.201+0200    INFO    received Commit {"validator": 3}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xbcc59e]
goroutine 486 [running]:
github.com/nspcc-dev/neo-go/pkg/consensus.(*service).newBlockFromContext(0xc0001629a0, 0xc000308000, 0xc0010fa000, 0x2cb417800)
github.com/nspcc-dev/neo-go/pkg/consensus/consensus.go:664 +0xbe
github.com/nspcc-dev/dbft.(*Context).MakeHeader(...)
github.com/nspcc-dev/dbft@v0.0.0-20210302103605-cc75991b7cfb/context.go:270
github.com/nspcc-dev/dbft.(*DBFT).onCommit(0xc000308000, 0x138c998, …
=> consensus: fix nonce handling

pkg/vm/emit/emit.go
Show unsupported type instead of value.
=> vm/emit: improve error message

cli/candidate_test.go, cli/query/query.go, cli/query_test.go, cli/wallet/validator.go, docs/cli.md, docs/consensus.md, pkg/rpc/client/rpc.go, pkg/rpc/client/rpc_test.go, pkg/rpc/response/result/mpt.go, pkg/rpc/server/server.go, pkg/rpc/server/server_test.go
I wanted to add a bit more, but we need this now.
=> New query commands

pkg/core/interop/contract/call.go, pkg/core/oracle_test.go, pkg/vm/vm.go
Log:
2021-07-23T09:59:18.948+0300    WARN    contract invocation failed      {"tx": "de3e3c1f1d37e4528990f894dea5583fd320485ad3862a95eb0e8823eecf4a5f", "block": 9643, "error": "error encountered at instruction 1 (SYSCALL): error during call from native: error encountered at instruction 745 (CAT): invalid conversion: Map/ByteString"}
The word "error" appears 4 times here.
=> *: simplify some error messages

cli/wallet_test.go, pkg/wallet/wallet.go
If wallet size decreases, we need to remove trailing garbage if it
exists. This can happen when removing account or reading pretty-printed
wallet. It doesn't affect our CLI (we decode only file prefix), but
it is nice to always have a valid JSON file.
=> wallet: truncate file after writing

docs/rpc.md, internal/fakechain/fakechain.go, pkg/core/blockchain.go, pkg/core/blockchainer/blockchainer.go, pkg/core/dao/cacheddao.go, pkg/core/dao/dao.go, pkg/core/helper_test.go, pkg/core/native/management.go, pkg/core/native/management_test.go, pkg/core/native/native_gas.go, pkg/core/native/native_neo.go, pkg/core/native/native_nep17.go, pkg/core/native_gas_test.go, pkg/core/native_management_test.go, pkg/core/state/nep17.go, pkg/core/state/nep17_test.go, pkg/core/storage/store.go, pkg/rpc/server/server.go, pkg/smartcontract/manifest/manifest.go, pkg/smartcontract/manifest/manifest_test.go
Non-archival nodes are unable to retrieve NEP17 balances states via regular NEP17 tracking mechanism.
Get rid of NEP17 balances tracking and dynamically ask NEP17 contracts for balances instead.
1. We can't get rid of LastUpdatedBlock tracking, because NEP17 contracts can return balances only (`balanceOf` method), so keep tracking it.
2. We still need to save service information about NEP17 transfers batches, because it's a nice optimisation of NEP17 transfer logs that is worth keeping.
TODO:
=> core: implement dynamic NEP17 balances tracking

pkg/core/native/std.go, pkg/vm/stackitem/json.go, pkg/vm/stackitem/json_test.go
=> native/std: restrint amount of items in JSON deserialization

pkg/core/blockchain.go, pkg/core/blockchain_test.go, pkg/core/native_contract_test.go, pkg/core/native_policy_test.go, pkg/core/storage/memcached_store.go, pkg/core/storage/memcached_store_test.go
This is important in making our node performing the way it should. Now profiler data really means something and other optimizations will have more direct effect.
=> Improve (*MemCachedStore).Persist

pkg/core/transaction/bench_test.go, pkg/core/transaction/transaction.go, pkg/network/message.go
Transaction decoding is used a lot, but it's far from being optimal.
On a micro-level this improves decoding a lot. But in neo-bench it doesn't change anything. The only thing I'm not sure about here probably is `ReadArray` change, it adds some substantial amount of code, yet at the same time our blockchain is all about transactions, so decoding them should be as fast as it can be.
=> Optimize tx decoding

pkg/compiler/native_test.go, pkg/core/interop_system_test.go, pkg/core/native/native_gas.go, pkg/core/native_gas_test.go, pkg/interop/native/gas/gas.go
It can be used to attack the network (amplifying DOS), so it's broken
beyond repair. See also neo-project/neo#2560 and neo-project/neo#2561.
=> native: drop Refuel method from GAS

pkg/network/server.go
NewPing accepts block index first and nonce then. Use block height also, that's what is to be sent here.
=> network: fix Ping messages

pkg/core/bench_test.go, pkg/core/blockchain.go
We know it already, but with current loading code VM will hash it once more. I
have not measured consequences of this change, but it just can't be bad.
=> core: don't recalculate witness script hash

cli/contract_test.go, cli/executor_test.go, cli/smartcontract/manifest.go, cli/smartcontract/smart_contract.go, cli/wallet_test.go, docs/compiler.md
Close #2098 .
There are possible problems, but I haven't found a way for them to occur:
1. Sent manifest will differ from the one we read. This is ok, because contract hash calculation uses only manifest name, so `calc-hash` will continue to work.
2. One might want to have multiple groups in different wallets (for some multisig transactions). This is not supported.
=> cli/smartcontract: provide manifest groups on deploy

pkg/core/mpt/base.go, pkg/core/mpt/batch.go, pkg/core/mpt/batch_test.go, pkg/core/mpt/branch.go, pkg/core/mpt/empty.go, pkg/core/mpt/extension.go, pkg/core/mpt/hash.go, pkg/core/mpt/leaf.go, pkg/core/mpt/node.go, pkg/core/mpt/node_test.go, pkg/core/mpt/proof.go, pkg/core/mpt/trie.go, pkg/core/mpt/trie_test.go, pkg/core/state/notification_event.go, pkg/core/state/notification_event_test.go, pkg/core/transaction/bench_test.go, pkg/core/transaction/transaction.go, pkg/vm/stackitem/serialization.go
1. Don't allocate `NodeObject` just for serialization.
2. Use `EmptyNode = struct{}` instead of `HashNode`.
3. Don't allocate new slice for big integers during stackitem serialization.
There is some quirk here: `ToPreallocatedBytes` will perform a rough estimation of size, which differs from the real size. This will be fixed later.
4. Inline frequently called  `BinWriter.WriteArray` invocations.
Will update this with 1 more MPT optimization.
=> Some allocation optimizations

pkg/core/native/native_gas.go, pkg/core/state/native_state.go, pkg/core/state/native_state_test.go, pkg/core/state/nep17.go, pkg/core/state/nep17_test.go
1. GAS balances are used frequently, it makes sense to optimize them. We can't reuse the `state.StorageItem` though because it can modify the real items in test invocations (`GetStorageItem` doesn't copy slice). `bigint.Size` can be replaced with rough estimation (33 bytes).
2. Reuse buffer in `Append` to transfer log.
=> Improve NEP17 transfer serialization

pkg/core/blockchain.go
Prevent this:
2021-08-12T15:24:00.750+0300    INFO    shutting down service   {"service": "Prometheus", "endpoint": ":2112"}
2021-08-12T15:24:00.752+0300    INFO    shutting down service   {"service": "Pprof", "endpoint": ":2113"}
2021-08-12T15:24:00.868+0300    INFO    blockchain persist completed    {"persistedBlocks": 14, "persistedKeys": 3145, "headerHeight": 7806078, "blockHeight": 7794173, "took": "652.243264ms"}
2021-08-12T15:24:00.974+0300    INFO    blockchain persist completed    {"persistedBlocks": 1, "persistedKeys": 259, "headerHeight": 7806078, "blockHeight": 7794174, "took": "221.955904ms"}
panic: assignment to entry in nil map
goroutine 132 [running]:
github.com/nspcc-dev/neo-go/pkg/core/storage.(*MemoryStore).drop(...) …
=> core: take an addblock lock on exit

pkg/compiler/codegen.go, pkg/smartcontract/convertor.go, pkg/vm/context.go, pkg/vm/json_test.go, pkg/vm/ref_counter.go, pkg/vm/ref_counter_test.go, pkg/vm/stackitem/item.go, pkg/vm/stackitem/item_test.go, pkg/vm/stackitem/json.go, pkg/vm/stackitem/reference.go, pkg/vm/stackitem/serialization.go, pkg/vm/vm.go, pkg/vm/vm_test.go
1. Simplify `BigInteger` and `Bool` items.
2. Remove map from refcounter.
3. Don't copy the parameter.
=> Some VM optimizations

pkg/rpc/client/wsclient_test.go, pkg/rpc/request/param.go, pkg/rpc/request/param_test.go, pkg/rpc/server/server.go
It is rather costly to try to unmarshal many structs in order.
=> rpc/request: delay parameter unmarshaling

pkg/util/uint256.go, pkg/util/uint256_test.go
It is used a lot in clients (including our benchmark).
`Uint160` is already optimized.
```
name                     old time/op    new time/op    delta
Uint256DecodeStringLE-8     150ns ±15%     112ns ± 3%  -25.23%  (p=0.000 n=10+10)
name                     old alloc/op   new alloc/op   delta
Uint256DecodeStringLE-8     96.0B ± 0%     64.0B ± 0%  -33.33%  (p=0.000 n=10+10)
name                     old allocs/op  new allocs/op  delta
Uint256DecodeStringLE-8      2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=10+10)
```
Another reasonable step would be to use `hex.Decode` instead of `DecodeString` but then string is converted to `[]byte` argument so there is still 1 allocation.
=> util: reduce allocations in `util.Uint256DecodeStringLE`

pkg/core/block/block.go, pkg/core/blockchain.go, pkg/core/interop/context.go, pkg/io/binaryBufWriter.go
TXs ≈ 1000000
RPS ≈ 31678.809
RPC Errors  ≈ 0 / 0.000%
TPS ≈ 31219.756
DefaultMSPerBlock = 1000
CPU ≈ 34.589%
Mem ≈ 528.872MB
:wink: 
The key to single-node performance is allocations now (and a bit of locking of course).
=> Drop some useless allocations

cli/server/dump_test.go
`getPath` returns paths without leading dot.
```
=== RUN   TestGetPath
dump_test.go:20: 
Error Trace:	dump_test.go:20
Error:      	Not equal: 
expected: "./746297090/BlockStorage_100000/dump-block-1000.json"
actual  : "746297090/BlockStorage_100000/dump-block-1000.json"
```
This is most likely related to changes in `io.TempDir` package rather than `filepath.Join` (`filepath.Clean` was already there in go1.16).
=> cli: fix tests for go1.17

docs/cli.md, docs/notary.md, docs/notifications.md
Close #1848.
The document contains a massive part of notary-related proposals text because I consider they are well-constructed and we can reuse it in the documentation. The proposals have been slightly changed during implementation, so the text is adjusted.
The document content is based on FAQ of neo-fs developers (@alexvanin, @carpawell), so I'll appreciate comments.
=> docs: add Notary subsystem documentation

pkg/rpc/client/client.go
=> rpc/client: add `MaxConnsPerHost` option, fix #2149

cli/wallet/wallet.go
N3 migration works via sends to blackhole ANeo2toNeo3MigrationAddressxwPB2Hz
address with Remark14 attribute set to target N3 address [1]. This option
allows to create such transaction (but it doesn't check target address in any
way, if you make a mistake there you'll lose your assets forever). It works
like this:
$ neo-go wallet transfer -p file.wallet -r https://rpc-node:10331 --from AZ81H31DMWzbSnFDLFkzh9vHwaDLayV7fU --to ANeo2toNeo3MigrationAddressxwPB2Hz --asset NEO --amount 10 --remark14 NVTiAjNgagDkTr5HTzDmQP9kPwPHN5BgVq
[1]: https://docs.neo.org/tutorials/en-us/migrationB.html
=> wallet: add remark14 option to migrate UTXO assets to N3

pkg/rpc/server/client_test.go
=> *: gofmt -s

pkg/rpc/client/client.go, pkg/rpc/response/result/version.go, pkg/rpc/server/server.go, pkg/rpc/server/server_test.go
`StateRootInHeader` is duplicated similarly to `Network`.
It will be removed in future as it is surely a protocol parameter.
=> rpc: return protocol parameters in `getversion`, fix #2160

internal/fakechain/fakechain.go, pkg/network/helper_test.go, pkg/network/server_test.go
Register peers properly and set protocol configuration values before server start.
=> network: fix race in StateSync module tests

pkg/rpc/server/server.go
Follow the reference behaviour, see https://github.com/neo-project/neo-modules/blob/master-2.x/RpcWallet/RpcWallet.cs#L251.
=> rpc: do not return error if account is not found for `getunclaimed` call

pkg/smartcontract/parameter.go, pkg/smartcontract/parameter_test.go
Fix a bug where marshaling/unmarshaling transformed absent value to the empty string.
=> Smartcontract parameter JSON marshaling fixes

pkg/core/native/native_nep17.go, pkg/core/native_neo_test.go
States diff at 131795 block of mainnet.
This PR makes us compatible up to 218k of mainnet. The issue with testnet states diff is still under investigation.
Transaction:
```
NEO-GO-VM > loadbase64 DAAQDBSPsxdYh6cITC3gUKI4oWmYxJs49gwUj7MXWIenCEwt4FCiOKFpmMSbOPYUwB8MCHRyYW5zZmVyDBT1Y+pAvCg9TQ4FxI6jBbPyoHNA70FifVtSOQwAEQwUj7MXWIenCEwt4FCiOKFpmMSbOPYMFL1Mb4Fqp6gHiEwzM6xSc8fLS+RpFMAfDAh0cmFuc2ZlcgwU9WPqQLwoPU0OBcSOowWz8qBzQO9BYn1bUjk=
READY: loaded 176 instructions
NEO-GO-VM 0 > ops
INDEX    OPCODE       PARAMETER
0        PUSHDATA1     ("")                                       <<
2        PUSH0
3        PUSHDATA1    8fb3175887a7084c2de050a238a16998c49b38f6
25       PUSHDATA1    8fb3175887a7084c2de050a238a16998c49b38f6
47       PUSH4
48       PACK
49       PUSH15
50       PUSHDATA1 …
```
=> core: allow transfer 0 GAS/NEO with zero balance

pkg/core/transaction/oracle.go
Fix testnet block 311487 block processing and synchronization errors:
2021-09-14T15:18:53.611+0300    WARN    peer disconnected       {"addr": "20.198.226.132:20333", "reason": "invalid oracle response code", "peerCount": 10}
Fix 8e9302f40b76964e0af1c7f8812a1f81cd67be2c.
=> transaction: fix ContentTypeNotSupported oracle code processing

go.mod, go.sum, pkg/services/oracle/filter.go, pkg/services/oracle/jsonpath/jsonpath.go, pkg/services/oracle/jsonpath/jsonpath_test.go, pkg/smartcontract/manifest/manifest.go
States diff at 284177 block of testnet.
Escape non-ASCII characters during manifest.Extra to stackitem conversion. This PR makes us compatible up to 290k of testnet.
Manifest bytes (got from transaction script):
```
7b226e616d65223a22696f75222c2267726f757073223a5b5d2c226665617475726573223a7b7d2c22737570706f727465647374616e6461726473223a5b5d2c22616269223a7b226d6574686f6473223a5b7b226e616d65223a22646563696d616c73222c22706172616d6574657273223a5b5d2c2272657475726e74797065223a22496e7465676572222c226f6666736574223a302c2273616665223a66616c73657d2c7b226e616d65223a2273796d626f6c222c22706172616d6574657273223a5b5d2c2272657475726e74797065223a22537472696e67222c226f6666736574223a322c2273616665223a66616c73657d2c7b226e616d65223a2262616c616e63654f66222c22706172616d6574657273223a5b5d2c2272657475726e74797065 …
```
=> smartcontract: escape non-ascii characters for manifest.Extra SI

examples/timer/timer.go
See https://github.com/nspcc-dev/neofs-contract/issues/128.
It's a remnant from N2, so this PR unifies style of all
update-related methods.
=> examples: rename Migrate methods to Update

cli/candidate_test.go, cli/contract_test.go, cli/input/input.go, cli/multisig_test.go, cli/nep11_test.go, cli/nep17_test.go, cli/query_test.go, cli/smartcontract/smart_contract.go, cli/wallet/nep11.go, cli/wallet/nep17.go, cli/wallet_test.go
=> cli/wallet: show tx fee before relaying

go.mod, go.sum, internal/fakechain/fakechain.go, pkg/core/block/block.go, pkg/core/block/block_test.go, pkg/network/blockqueue.go, pkg/network/blockqueue_test.go
Use circular buffer which is a bit more appropriate. The problem is that
priority queue accepts and stores equal items which wastes memory even in
normal usage scenario, but it's especially dangerous if the node is stuck for
some reason. In this case it'll accept from peers and put into queue the same
blocks again and again leaking memory up to OOM condition.
=> network: remove priority queue from block queue

pkg/vm/cli/cli.go, pkg/vm/cli/cli_test.go
In application logs hashes are serialized as base64 so it is useful
to convert them back to address via `util convert`.
=> vmcli: convert base64 string to address in `parse`

cli/contract_test.go, cli/smartcontract/smart_contract.go, docs/compiler.md, examples/storage/storage.go, examples/storage/storage.yml, pkg/compiler/compiler.go, pkg/compiler/debug.go, pkg/compiler/debug_test.go
This is a feature we are currently missing and it is nice to have for our container (`put`, `putNamed`) and NNS (`resolve`) contracts.
=> compiler: allow to overload methods in manifest

cli/input/input.go, cli/smartcontract/smart_contract.go, cli/wallet/validator.go, cli/wallet/wallet.go
Before:
```
$ echo qwe | ./bin/neo-go wallet export --wallet test.json --decrypt NNcXZaE2H2YCizC8FfDMvekMT8Ynirdvqg
panic: inappropriate ioctl for device
github.com/nspcc-dev/neo-go/cli/input.ReadPassword(0x1075746, 0x11, 0x0, 0x0, 0x0, 0x0)
github.com/nspcc-dev/neo-go/cli/input/input.go:55 +0x2be
github.com/nspcc-dev/neo-go/cli/wallet.exportKeys(0xc0002e2420, 0xc0002a2b00, 0xc0002a2b60)
github.com/nspcc-dev/neo-go/cli/wallet/wallet.go:373 +0x54a
github.com/urfave/cli.HandleAction(0xed2a20, 0x11d59b8, 0xc0002e2420, 0xc0002e2420, 0x0)
github.com/urfave/cli@v1.22.5/app.go:524 +0x105
github.com/urfave/cli.Command.Run(0x106b35f, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x107c985, 0x17, 0x1096870, ...)
github.com/urfave/cli@v1.22.5/command.go:173 +0x579 …
```
=> Dont panic on stdin ioctl issues

Makefile, README.md, cli/input/input.go
Related to #2008.
This PR fixes compilation errors and allows to build NeoGo node with `GOOS=windows` and `GOARCH=amd64` envs. The resulting binary is runnable (tested `node` command on the current testnet/mainnet), but the most of the tests are failing, the issue needs additional investigation.
At least, we're able to build/run the node, and it works somehow.
=> *: allow to build NeoGo binaries on Windows

examples/token-sale/token_sale.go, examples/token/nep17/nep17.go
Do not store zero receiver balance in the contract storage.
Refs. https://github.com/nspcc-dev/nex-contracts/pull/4#discussion_r742114449.
=> examples: adjust NEP17 and token-sale examples

pkg/rpc/server/server.go
Invalid `gettransactionheight` error response (it should start with a capital letter and match the `getrawtransaction` error response and the reference implementation).
=> rpc: fix `Unknown transaction` response for `gettransactionheight`

pkg/compiler/codegen.go
CONVERT call base price is 8192. DUP, ISTYPE and JMPIF all cost 2. So we add
0.07% overhead in the worst case and save 99.93% otherwise.
At the same time, old code was just two bytes and new one is seven, but I
think it's tolerable considering how much GAS it can potentially save.
Fix #2250.
=> compiler: optimize GAS cost of type conversion

pkg/compiler/codegen.go, pkg/compiler/defer_test.go
=> compiler: correctly handle defer in functions without return values

pkg/core/helper_test.go, pkg/core/interop/context.go, pkg/core/interop/runtime/witness.go, pkg/core/interop_system_test.go, pkg/core/native/oracle.go, pkg/core/native_oracle_test.go
Oracle responses must use the same set of signers as oracle requests even
though the transaction itself is signed by oracle nodes/contract.
We can probably improve interop.Context by removing Tx field completely and
adding more functionality to Container, but it's not very convenient for
VerifyWitness and will require adding more stub-like methods for Block, so Tx
is used for now (and we do have it in every relevant case).
=> native/interop: use oracle request signers for oracle response witness

examples/nft-nd-nns/tests/nonnative_name_service_test.go, pkg/neotest/account.go, pkg/neotest/basic.go
* Export `nonce()` method for external usage.
* Check deployed contract hash against precalculated one.
* Add the ability to check notification events.
=> neotest: minor usability improvements

Makefile
Turns out that there's already special goenv variable to build with proper extension.
It seems to be cleaner than https://github.com/nspcc-dev/neo-go/pull/2239.
=> Makefile: use GOEXE to build on windows

pkg/neotest/basic.go
* Add `(*Executor).InvokeScript*` helpers.
* Add `DeployContractCheckFAULT` helper.
=> neotest: minor usability improvements, part 2

cli/contract_test.go, cli/testdata/deploy/main.go, pkg/rpc/client/rpc.go, pkg/rpc/server/client_test.go
Passing CustromContracts to CreateTxFromScript leads to witness failure.
=> Fix custom sender scopes in CreateTxFromScript

pkg/core/blockchain.go, pkg/core/blockchain_test.go, pkg/core/dao/dao.go, pkg/core/native_contract_test.go, pkg/core/native_policy_test.go, pkg/core/storage/memcached_store.go
b9be892bf9f658652e2d1f074f366914dc62e830 has made Persist asynchronous which
is very effective in allowing the system to continue processing
blocks/transactions while flushing things to disk. It at the same time is very
dangerous in that if the disk is slow and it takes much time to flush KV set
(more than persisting interval), there might be even bigger new KV set in
MemCachedStore by the time it finishes. Even if the system immediately starts
to flush this new data set it (being bigger) can take more time than the
previous one. And while doing so a new data set will appear in memory,
potentially again bigger than this.
So we can easily end up with the system going out of control, consuming more
and more memory and taking more and more time to persist a single set of
data. To avoid this …
=> core: add and use synchronous persist to avoid OOM

pkg/compiler/codegen.go, pkg/compiler/slice_test.go
It makes no sense to restrict to identifiers.
From https://github.com/nspcc-dev/neofs-contract/issues/169#issuecomment-981832196 (the problem was not really in cast itself).
=> compiler: allow to slice struct field

cli/wallet/multisig.go, pkg/core/oracle_test.go, pkg/services/oracle/response.go
We shouldn't cache transaction hash if the transaction is incomplete.
=> services: fix Oracle response creation algorithm

pkg/vm/cli/cli_test.go
* Remove extra symbols during command execution.
* Fix test contract paths.
Related to #2268. Tests are fixed, but the same patch doesn't solve problem for real OS, thus leave it as is for now.
=> vm: fix cli tests

pkg/vm/invocation_tree.go
As neo-project/neo-modules#657 currently does.
=> vm: put child invocation tree nodes into `call` element

pkg/interop/storage/storage.go
ffaae0f7736119d9c7a60436c983b2566869c887 changed the behavior long time ago,
we're actually stripping whole requested prefix.
=> interop/storage: fix outdated RemovePrefix comment

pkg/core/blockchain.go
8537700b7b006ee317ce3a25c4ce4831d18eee48 was a bit wrong in its witness
treatment, contract-based verification scripts have zero length and this
script has a hash different from the target script hash to check, so sorting
can break witnesses in some cases.
=> core: don't sort witnesses prior to check, fix #2301

pkg/util/uint160.go
A follow-up to #2302, sort hashes using reverse order. Fixes
f9c68613f41ca85ddb01ec757153c0d86018d2324f6ff85a4afc708bb598b722 validation.
Hi, neo-project/neo#938.
=> util: reverse the order of uint160 comparsion

pkg/core/block/block.go, pkg/core/block/block_test.go, pkg/core/blockchain.go, pkg/core/blockchain_test.go, pkg/core/dao/dao.go, pkg/core/dao/dao_test.go, pkg/core/native_ledger_test.go, pkg/core/native_management_test.go, pkg/core/statesync/module.go, pkg/core/storage/store.go, pkg/core/storage/store_test.go
We're a bit slow.
Increase da TPS.
It will interfere with #2299, so we can wait for a while before merging it, maybe improve some naming or things along the way (for example, RPC server can now technically get both tx and aer for `getrawtransaction` request in a single query, but I'm not sure it's worth doing this, there are no other similar simultaneous uses).
=> Store applog with tx

pkg/vm/vm.go, pkg/vm/vm_test.go
When there is a single big instruction (like PUSHDATA4) in script,
all other instructions are padded to the right with spaces.
This makes it hard to view script in terminal, because long lines
are usually wrapped at the screen boundary and printed as multiple lines.
The culprit is our `cursor` field which is printed in the last column
and causes all previous fields to have the same length for every
instruction. One way to fix this is to omit cursor field if it is empty.
=> vm: cut trailing spaces in `PrintOps`

pkg/core/blockchain.go, pkg/core/blockchain_test.go, pkg/core/dao/dao.go, pkg/core/helper_test.go, pkg/core/interop_system.go, pkg/core/native/management.go, pkg/core/native/native_neo.go, pkg/core/native_neo_test.go, pkg/core/stateroot/module.go, pkg/core/statesync/module_test.go, pkg/core/statesync_test.go, pkg/core/storage/boltdb_store.go, pkg/core/storage/leveldb_store.go, pkg/core/storage/memcached_store.go, pkg/core/storage/memcached_store_test.go, pkg/core/storage/memory_store.go, pkg/core/storage/memory_store_test.go, pkg/core/storage/store.go, pkg/core/storage/storeandbatch_test.go
=> storage: allow to Seek from some point and backwards

pkg/core/blockchain.go
It should be performed before we're able to process blocks or before we
shutdown (which uses addition lock), fix
panic: assignment to entry in nil map
goroutine 5755 [running]:
github.com/nspcc-dev/neo-go/pkg/core/storage.(*MemoryStore).drop(...)
/home/rik/dev/neo-go/pkg/core/storage/memory_store.go:74
github.com/nspcc-dev/neo-go/pkg/core/storage.(*MemoryStore).PutChangeSet(0xc00093e700, 0xc0002051a0, 0xc000205200, 0x1, 0x1)
/home/rik/dev/neo-go/pkg/core/storage/memory_store.go:100 +0x25c
github.com/nspcc-dev/neo-go/pkg/core/storage.(*MemoryStore).PutBatch(...)
/home/rik/dev/neo-go/pkg/core/storage/memory_store.go:90
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).removeOldStorageItems(0xc000206a00)
/home/rik/dev/neo-go/pkg/core/blockchain.go:495 +0x33a
created by …
=> core: lock block addition on state jump

pkg/rpc/client/doc.go, pkg/rpc/client/rpc.go, pkg/rpc/client/rpc_test.go, pkg/rpc/server/server.go
Turns out we're missing it from RPC client. Thanks to @carpawell.
=> rpc: add `getstateroot` to RPC client

pkg/core/native/notary.go, pkg/interop/native/notary/notary.go
It changes states and calls `transfer` method of GAS which emits `transfer`
notification, so it requires States | AllowCall | AllowNotify, i.e. the
widest permission.
See
https://github.com/nspcc-dev/neo-go/issues/1990#issuecomment-1014911528.
=> core: adjust native Notary `withdraw` call flags

internal/fakechain/fakechain.go, pkg/core/bench_test.go, pkg/core/blockchain.go, pkg/core/blockchain_test.go, pkg/core/blockchainer/blockchainer.go, pkg/core/dao/dao.go, pkg/core/native/management.go, pkg/core/native/native_neo.go, pkg/core/state/tokens.go, pkg/core/stateroot/module.go, pkg/core/statesync/module_test.go, pkg/core/statesync_test.go, pkg/core/storage/boltdb_store.go, pkg/core/storage/leveldb_store.go, pkg/core/storage/memcached_store.go, pkg/core/storage/memcached_store_test.go, pkg/core/storage/memory_store.go, pkg/core/storage/memory_store_test.go, pkg/core/storage/store.go, pkg/core/storage/storeandbatch_test.go, pkg/rpc/server/server.go
Close #2322, close #2263.
TODO:
=> core: improve Seek and optimise seek time for transfer logs

examples/README.md, examples/nft-d/go.mod, examples/nft-d/go.sum, examples/nft-d/nft.go, examples/nft-d/nft.yml, pkg/compiler/debug.go, pkg/smartcontract/manifest/standard/comply.go, pkg/smartcontract/manifest/standard/nep11.go
Seems that #2292 is almost ready, so there will be no painful rebases anymore and I can safely open this PR.
Close #1940.
=> examples: add NEP11 Divisible token example

pkg/compiler/codegen.go, pkg/compiler/defer_test.go, pkg/compiler/inline_test.go
=> compiler: do not traverse `defer` function literals twice

.circleci/config.yml, codecov.yml
1. Set explicitly all required values in the codecov.yml. Keep `require_ci_to_pass: no` so that codecov is be able to upload coverage reports irrespectively to the other tests.
2. Keep the only coverage reporting job, so that CircleCI's reports do not conflict with GithubActions's ones.
=> codecov: fix coverage reporting

.github/workflows/publish_to_dockerhub.yml, Dockerfile.wsc, cli/server/server.go, cli/server/server_test.go, cli/server_test.go, pkg/compiler/analysis.go, pkg/network/server_test.go, pkg/vm/cli/cli_test.go
Close #2269, close #2277.
Part of #2268 is also fixed, but dealing with `NEO-GO-VM > ←[J←[2K` is still in progress.
=> *: fix windows tests

pkg/core/blockchain.go, pkg/core/blockchain_test.go, pkg/core/storage/store.go, pkg/core/storage/store_test.go
Initially I thought of doing it in the next persist cycle, but testing shows
that it needs just ~2-5% of the time MPT GC does, so doing it in the same
cycle doesn't affect anything.
Also, for the record, we've got just slightly more than 33K entries after mainnet's 1050K blocks processing with MaxTraceableBlocks of 10K.
=> core: remove stale transfer entries, fix #2096

pkg/rpc/request/param.go
Port a part of https://github.com/neo-project/neo-modules/pull/694. Waiting for the reference PR to settle.
=> rpc: add Rules signer scope to request parameters

pkg/compiler/assign_test.go, pkg/compiler/binary_expr_test.go, pkg/compiler/convert_test.go, pkg/compiler/for_test.go, pkg/compiler/native_test.go, pkg/compiler/slice_test.go, pkg/compiler/struct_test.go, pkg/compiler/switch_test.go, pkg/compiler/syscall_test.go
The longest compiler tests are the ones that check some specific construction using it in multiple ways.
We can put such tests in functions in a single file.
For other tests this is more tricky because some of them are specifically crafted to handle particular import/global variables
configuration, so leave them as they are.
```
ok      github.com/nspcc-dev/neo-go/pkg/compiler        15.357s
ok      github.com/nspcc-dev/neo-go/pkg/compiler        9.553s
```
Related #2379 .
=> compiler: optimize tests

pkg/vm/vm.go, pkg/vm/vm_test.go
As can be seen in https://dotnetfiddle.net/s7eg21 (int) conversions
result in an exception in C# code.
=> vm: fix integer conversions

pkg/vm/context.go, pkg/vm/vm_test.go
Check instruction offset to be positive. C# node is not affected, because everything is executed in `try/catch` block. I will create a PR to update JSON tests there.
I think we can't do this in `IsScriptCorrect`, because this is inherently about runtime execution flow.
=> Return error on negative instruction pointer in `Context.Next`

pkg/core/block/block.go, pkg/core/block/block_test.go, pkg/core/dao/dao.go
The only user of (*Block).Trim() is in DAO and it already has a nice buffer
usually, so creating another one makes no sense. It also simplifies error
handling a lot.
=> block/dao: simplify trimming, avoid allocations

.github/workflows/publish_to_dockerhub.yml
In case if something goes wrong during release version publishing.
=> github: add ability to manually trigger publishing workflow with `latest` tag

pkg/rpc/server/prometheus.go, pkg/rpc/server/server.go, pkg/rpc/server/server_test.go
=> Fix log entries with user input

cli/smartcontract/generate.go
The usage text to the new `contract generate-wrapper` command suggested to me that you can call it without the `--hash` parameter
> USAGE:
neo-go contract generate-wrapper --manifest manifest.json --out file.go
but when doing so you get an invalid contract hash error
> ./neo-go contract generate-wrapper --manifest ../../demo/boa/cpm/mycontract.manifest.json --out bla
invalid contract hash: expected string size of 40 got 0
update usage text
=> Update generate-wrapper usage text to reflect requirements

LICENSE.md, pkg/interop/LICENSE.md
Seems like pkg.go.dev can't pick it up from the symlink.
=> interop: add a physical copy of LICENSE.md

pkg/rpc/client/wsclient.go, pkg/rpc/client/wsclient_test.go
Although it's the caller's duty to avoid WSClient re-closing, we
still can handle it.
Fixes the following neofs-node error:
```
panic: close of closed channel
goroutine 98 [running]:
github.com/nspcc-dev/neo-go/pkg/rpc/client.(*WSClient).Close(...)
github.com/nspcc-dev/neo-go@v0.98.3-pre.0.20220321144433-3b639f518ebb/pkg/rpc/client/wsclient.go:120
github.com/nspcc-dev/neofs-node/pkg/morph/subscriber.(*subscriber).Close(0x13)
github.com/nspcc-dev/neofs-node/pkg/morph/subscriber/subscriber.go:108 +0x29
github.com/nspcc-dev/neofs-node/pkg/morph/event.listener.Stop(...)
github.com/nspcc-dev/neofs-node/pkg/morph/event/listener.go:573
created by github.com/nspcc-dev/neofs-node/pkg/innerring.(*Server).Stop
github.com/nspcc-dev/neofs-node/pkg/innerring/innerring.go:285 +0x12f
```
=> rpc: avoid panic on double-call to *WSClient.Close()

pkg/rpc/response/result/version.go, pkg/rpc/server/server.go
Reference implementation includes `initialgasdistribution` as integer
value with decimals.
C# response:
```
{
"id": 1,
"jsonrpc": "2.0",
"result": {
"nonce": 1677922561,
"protocol": {
"addressversion": 53,
"initialgasdistribution": 5200000000000000,
"maxtraceableblocks": 2102400,
"maxtransactionsperblock": 512,
"maxvaliduntilblockincrement": 5760,
"memorypoolmaxtransactions": 50000,
"msperblock": 15000,
"network": 860833102,
"validatorscount": 7
},
"tcpport": 10333,
"useragent": "/Neo:3.1.0/",
"wsport": 10334
}
}
```
Neo-Go response:
```
{
"id": 1,
"jsonrpc": "2.0",
"result": {
"network": 860833102,
"nonce": 2847278838,
"protocol": {
"addressversion": 53,
"initialgasdistribution": "52000000",
"maxtraceableblocks": 2102400,
"maxtransactionsperblock": 512,
"maxvaliduntilblockincrement": …
```
=> rpc: adjust `getversion` RPC response

pkg/compiler/interop_test.go, pkg/consensus/consensus.go, pkg/core/blockchain.go, pkg/core/blockchain_core_test.go, pkg/core/interop/context.go, pkg/core/interop/crypto/ecdsa_test.go, pkg/core/interop_system.go, pkg/core/native/interop.go, pkg/core/native/management.go, pkg/core/native/native_test/common_test.go
Outdated and non-unified BaseExecFee and StoragePrice values used for interop context pricing.
Merge.
=> core: use proper BaseExecFee and StoragePrice for interop context

.circleci/config.yml
Problem - failing CircleCI test jobs:
```
go test -v -race ./...
Too long with no output (exceeded 10m0s): context deadline exceeded
```
=> ci: increase output waiting timeout for CircleCI test jobs

pkg/core/blockchain.go, pkg/core/blockchain_neotest_test.go, pkg/core/stateroot/store.go
Store stateroot by DataMPTAux prefix instead of storing it by index only.
Costs me a lot...
=> core: fix broken stateroot storage

pkg/core/transaction/signer.go, pkg/core/transaction/signer_test.go
Transaction with Rules witness scope can't be decoded due to the following error:
```
Error:      	Received unexpected error:
unknown witness scope
```
=> core: consider Rules witness scope as valid

cli/executor_test.go, go.mod, go.sum, pkg/config/config.go, pkg/rpc/response/result/version.go, pkg/rpc/response/result/version_test.go, pkg/rpc/server/server.go, pkg/rpc/server/server_helper_test.go, pkg/rpc/server/server_test.go
https://github.com/nspcc-dev/neo-go/pull/2435 breaks compatibility between newer RPC clients and older RPC servers with the following
error:
```
failed to get network magic: json: cannot unmarshal string into Go struct field Protocol.protocol.initialgasdistribution of type int64
```
This behaviour is expected, but we can't allow this radical change.
Thus, the following solution is implemented:
1. RPC server responds with proper non-stringified
InitialGasDistribution value. The value represents an integral
of fixed8 multiplied by the decimals.
2. RPC client is able to distinguish older and newer responses. For
older one the stringified value without decimals part is
expected. For newer responses the int64 value with decimal part
is expected.
The cludge will be present in the code for a …
=> rpc: support InitialGasDistribution response from older Neo-Go nodes

pkg/core/native/native_neo.go
(*Simple).Seek cuts search prefix, thus to remove voterRewardPerCommittee
we need to append it again to the height value. May affect dumps.
=> core: remove voter reward per committee properly

pkg/core/native/contract.go, pkg/core/native/management.go, pkg/core/native/management_test.go, pkg/core/native/native_test/management_test.go, pkg/core/native/policy.go
=> core: block destroyed contracts and restrict maximum contract updates

pkg/rpc/response/result/invoke.go
See neo-project/neo-modules#696. Unmarshaller is left unchanged to be
compatible.
=> rpc: signal JSON marshalling errors through exception

pkg/rpc/response/result/version.go, pkg/rpc/response/result/version_test.go, pkg/rpc/server/server_helper_test.go, pkg/rpc/server/server_test.go
Version 0.98.3 is officially released with the old behavior.
=> rpc: move latest getversion compat to 0.98.3

pkg/services/notary/notary.go
Originally found by Lint GA in #2389.
Fix the following warning:
```
S1001: should use copy() instead of a loop (gosimple)
```
=> services: fix gosimple warning

pkg/vm/context.go
Reference implementation:
https://github.com/neo-project/neo-vm/blob/e167f03e25abd8232316fa96b54fbbc01526f0ab/src/neo-vm/ExecutionContext.cs#L77.
Turns out that exception-related code (try\finally handling) is the only
place where next instruction pointer bounds are not pre-checked before
assignment. This statement is true for both go and C# implementations.
However, C# code has duplicate check located inside the
InstructionPointer setter for all instructions except the
exception-related ones. Neo-go code doesn't perform this duplicate check.
Thus, C# VM FAULTs execution in case of invalid TRY/FINALLY offsets, and
neo-go VM does not.
This commit reverts a part of
https://github.com/nspcc-dev/neo-go/pull/2396. This bug is discovered
thanks to test added in …
=> vm: check instruction offset is valid before subsequent IP move

pkg/rpc/response/result/version.go, pkg/rpc/response/result/version_test.go, pkg/rpc/server/server_helper_test.go, pkg/rpc/server/server_test.go
Version 0.98.4 is officially released with the old behaviour. The same thing
as #2472.
=> rpc: bump getversion compat again

scripts/compare-states/compare-states.go
Make it usable as a status checker, returning 0 if everything is fine and 1 (with relevant output) otherwise.
=> Improve compare-states.go script

pkg/rpc/response/result/version.go, pkg/rpc/response/result/version_test.go, pkg/rpc/server/server_helper_test.go, pkg/rpc/server/server_test.go
Version 0.98.5 is officially released with the old behaviour. The same thing
as #2479.
=> rpc: bump getversion compat

pkg/vm/opcodebench_test.go, pkg/vm/ref_counter.go, pkg/vm/ref_counter_test.go, pkg/vm/slot.go, pkg/vm/slot_test.go, pkg/vm/vm.go, pkg/vm/vm_test.go
Thanks @ixje for spotting these.
=> Fix some refcounter issues

pkg/core/transaction/transaction.go, pkg/core/transaction/transaction_test.go
Allows to avoid panic:
```
(18:28:29)[sergio@transient:morph-control-load]% downloads/neofs-adm morph -c configuration/config.yaml init --contracts downloads/neofs-contract-v0.15.1
Stage 1: transfer GAS to alphabet nodes.
Waiting for transactions to persist...
Stage 2: set notary and alphabet nodes in designate contract.
Stage 2: already performed.
Stage 3: deploy NNS contract.
NNS contract is already deployed.
Stage 4: deploy NeoFS contracts.
Alphabet contract #0 is already deployed.
Alphabet contract #1 is already deployed.
Alphabet contract #2 is already deployed.
Alphabet contract #3 is already deployed.
audit contract is already deployed.
balance contract is already deployed.
container contract is already deployed.
neofsid contract is already deployed.
netmap contract is already …
```
=> rpc: check transaction for validness before network fee calculation

pkg/vm/slot.go, pkg/vm/vm.go, pkg/vm/vm_test.go
=> Fix INITSSLOT refs

pkg/core/interop_system.go, pkg/core/native/native_neo.go
PR https://github.com/nspcc-dev/neo-go/pull/2495 is not enought, the problem is reproduced during dump restore
with the stacktrace attached down below.
The reason is that SeekAsync starts goroutine that performs Seek
operation over private MemCachedStore. The goroutine iterates over
MemCachedStore's map without holding the lock (it's OK, because it's
private), whereas the main thread continues invocation and
performs writes to the same map. To fix that ic.Exec() needs to
wait until all goroutines are properly exited.
```
2022-05-17T08:34:50.430+0300	INFO	persisted to disk	{"blocks": 632, "keys": 16546, "headerHeight": 54091, "blockHeight": 54091, "took": "57.904387ms"}
fatal error: concurrent map iteration and map write
goroutine 218853 [running]:
runtime.throw({0xf56a31, 0x614968}) …
```
=> core: avoid concurrent map iteration and map write during SeekAsync over private MemCachedStore

config/protocol.mainnet.yml
See neo-project/neo-node#862. It's not yet official, but this change makes
testing against mainnet dumps easier for now.
=> config: set Aspidochelone hard fork for mainnet

pkg/core/native/native_neo.go, pkg/core/native/native_test/neo_test.go, pkg/rpc/server/server_test.go
Follow neo-project/neo#2754.
I'll probably add some tests.
=> native: emit vote/candidate events

pkg/compiler/native_test.go, pkg/core/interop/context.go, pkg/core/interop_system_core_test.go, pkg/core/native/management.go, pkg/core/native/native_neo.go, pkg/core/native/native_test/management_test.go, pkg/rpc/server/server_test.go
This PR makes us compatible up to 187157 block of T5.
=> core: fix T5 statediffs

Makefile
=> Makefile: alias `build` target as `bin`

pkg/wallet/regenerate_test.go, pkg/wallet/wallet.go
Client code can make use of it, see nspcc-dev/neofs-node#1498.
=> wallet: export `SavePretty` method

pkg/rpc/response/errors.go, pkg/rpc/response/types.go, pkg/rpc/server/error.go, pkg/rpc/server/server.go
We can use Data field for the same purposes.
=> rpc: remove Cause field from RPC error

pkg/core/interop/context.go, pkg/rpc/server/server_test.go
Port https://github.com/neo-project/neo/pull/2768.
This partially reverts commit ca127f161596c2d7b26f9fe20b526ae648333986.
=> core: sort native methods in ASCII-compatible way

docs/rpc.md, pkg/core/blockchain.go, pkg/rpc/server/server.go
Specifying a certain stateroot R as `invoke*historic` RPC-call
parameter, we're willing to perform historic call based on the storage
state of root R. Thus, next block should be of the height h(R)+1. This
allows to use historic functionality for the current blockchain height.
=> core, rpc: fix height-related issue of historic call functionality

pkg/rpc/server/server.go
Message is always non-empty; Data is allowed to be empty.
=> rpc: extend error log message for failed RPC requests

pkg/consensus/consensus.go
consensus.OnTransaction is a callback, so it can be called at any time.
We need to check whether service (and dBFT) is started before the
subsequent transaction handling like it is done inside the OnPayload
callback.
=> consensus: check whether server is started before transaction handling

go.mod, go.sum
=> go.mod: update dbft

pkg/core/native/management.go, pkg/core/native/native_test/management_test.go, pkg/vm/context.go
Close #2534 and port https://github.com/neo-project/neo-vm/pull/476.
=> core: check methods offsets while contract deploying

cli/smartcontract/smart_contract.go
```
> neo-go contract testinvokefunction 152d147a02525ccfa46ed98e2c983bb70f0472e1 notexist -r http://172.21.0.2:30333
Warning: FAULT VM state returned from the RPC node: at instruction 36 (SYSCALL): failed to invoke syscall 1381727586: method not found: notexist/0
. Use --force flag to save the transaction anyway.
```
1. Do not print info about `--force` flag if we don't send or save a transaction.
2. Do not print dots on a new line.
=> smartcontract: print proper error message on failed testinvoke

pkg/network/server.go
Always return true if sync was reached once. Fix #2564.
=> network: adjust the way (*Server).IsInSync() works

pkg/rpc/client/rpc_test.go, pkg/rpc/response/result/tokens.go, pkg/rpc/server/server.go, pkg/rpc/server/server_test.go
See neo-project/neo-modules#738 and neo-project/neo-modules#741.
=> rpc: add decimals/name/symbol data to getNEPXXBalance

docs/compiler.md, pkg/compiler/analysis.go, pkg/compiler/codegen.go, pkg/compiler/convert_test.go, pkg/compiler/inline.go, pkg/compiler/inline_test.go, pkg/compiler/testdata/inline/inline.go, pkg/core/block/block.go, pkg/interop/native/ledger/block.go
Turned out to be more of a compiler problem than interop one.
=> Stateroot-enabled GetBlock 

pkg/compiler/codegen.go, pkg/compiler/func_scope.go, pkg/compiler/function_call_test.go, pkg/compiler/testdata/inline/inline.go, pkg/compiler/testdata/method/struct.go
=> compiler: allow to call methods on return values

pkg/compiler/codegen.go, pkg/compiler/inline.go, pkg/compiler/inline_test.go, pkg/compiler/jumps_test.go, pkg/compiler/testdata/inline/c/null.go
=> compiler: allow to use multiple returns in inlined functions

pkg/core/block/block.go, pkg/core/block/block_test.go
=> block: JSONize tx-less block as `[]` instead of `null`

cli/wallet/validator.go, internal/testchain/transaction.go, pkg/consensus/consensus_test.go, pkg/core/bench_test.go, pkg/core/interop/runtime/ext_test.go, pkg/core/native/native_test/oracle_test.go, pkg/core/native/oracle.go, pkg/neotest/basic.go, pkg/rpcclient/helper.go, pkg/rpcclient/nep11.go, pkg/rpcclient/nep17.go, pkg/smartcontract/builder.go, pkg/smartcontract/doc.go, pkg/smartcontract/doc_test.go, pkg/smartcontract/entry.go, scripts/gendump/main.go
=> Move code generation from rpcclient to smartcontract

pkg/core/native/native_neo.go
It can change the committee even if noone voted. Fixes state diff at block
390726 of T5 testnet where there are no transactions, but committee changes
because there were some registrations in previous 21 blocks.
=> native: trigger committee update on candidate registration

cli/executor_test.go, cli/server/server.go, cli/server/signals_unix.go, cli/server/signals_windows.go, docs/cli.md, pkg/config/application_config.go, pkg/config/application_config_test.go, pkg/config/protocol_config.go, pkg/config/protocol_config_test.go, pkg/consensus/consensus.go, pkg/consensus/recovery_message.go, pkg/core/blockchain.go, pkg/core/native/designate.go, pkg/core/native/oracle.go, pkg/network/helper_test.go, pkg/network/payload/extensible.go, pkg/network/server.go, pkg/network/server_config.go, pkg/network/server_test.go, pkg/services/metrics/metrics.go, pkg/services/notary/notary.go, pkg/services/oracle/broadcaster/oracle.go, pkg/services/oracle/oracle.go, pkg/services/oracle/oracle_test.go, pkg/services/oracle/request.go, pkg/services/rpcsrv/server.go, pkg/services/stateroot/validators.go
This fixes #1949. It works like this:
No config changes:
```
2022-07-27T11:32:46.376+0300    INFO    signal received {"name": "hangup"}
2022-07-27T11:32:46.378+0300    INFO    shutting down RPC server        {"endpoint": "[::]:10332"}
2022-07-27T11:32:46.379+0300    INFO    starting rpc-server     {"endpoint": ":10332"}
2022-07-27T11:32:46.379+0300    INFO    shutting down service   {"service": "Prometheus", "endpoint": ":2112"}
2022-07-27T11:32:46.380+0300    INFO    service hasn't started since it's disabled      {"service": "Pprof"}
2022-07-27T11:32:46.381+0300    INFO    service is running      {"service": "Prometheus", "endpoint": ":2112"}
```
Enabled/disabled services:
```
2022-07-27T11:33:18.936+0300    INFO    signal received {"name": "hangup"}
2022-07-27T11:33:18.938+0300    INFO …
```
=> Fancy service restart

pkg/core/interop/contract/call.go, pkg/core/interop/runtime/engine.go, pkg/core/interop/runtime/engine_test.go, pkg/core/interop/runtime/witness.go, pkg/core/transaction/witness_condition.go, pkg/core/transaction/witness_condition_test.go, pkg/core/transaction/witness_scope.go, pkg/vm/context.go, pkg/vm/interop.go, pkg/vm/json_test.go, pkg/vm/opcodebench_test.go, pkg/vm/vm.go
=> Exec changes for 3.4.0

pkg/rpcclient/helper.go, pkg/rpcclient/native.go, pkg/rpcclient/nep.go, pkg/rpcclient/nep11.go, pkg/rpcclient/policy.go, pkg/rpcclient/rpc.go, pkg/rpcclient/unwrap/unwrap.go, pkg/rpcclient/unwrap/unwrap_test.go
Which will be reused by upper-layer packages. It can be extended with more
types in future.
=> rpcclient: move result processing code into unwrap package

cli/wallet/nep17.go, pkg/core/interop/context.go, pkg/core/state/contract.go, pkg/rpcclient/gas/gas.go, pkg/rpcclient/gas/gas_test.go, pkg/rpcclient/native.go, pkg/rpcclient/policy.go, pkg/rpcclient/policy/policy.go, pkg/rpcclient/policy/policy_test.go, pkg/rpcclient/rolemgmt/roles.go, pkg/rpcclient/rolemgmt/roles_test.go, pkg/services/rpcsrv/client_test.go
=> Policy/GAS/Designation contracts RPC wrappers

pkg/compiler/codegen.go
An attempt to compile unexisting file via neo-go-vm CLI leads to the following
panic:
```
NEO-GO-VM > loadgo ./1-print.go
panic: runtime error: index out of range [0] with length 0
github.com/nspcc-dev/neo-go/pkg/compiler.codeGen(0xc000047300)
github.com/nspcc-dev/neo-go/pkg/compiler/codegen.go:2188 +0x60c
github.com/nspcc-dev/neo-go/pkg/compiler.CompileWithOptions({0xc000047300, 0xf66c92}, {0x0, 0x0}, 0xc0003a0000)
github.com/nspcc-dev/neo-go/pkg/compiler/compiler.go:218 +0x65
github.com/nspcc-dev/neo-go/pkg/vm/cli.handleLoadGo(0xc0000f5340)
github.com/nspcc-dev/neo-go/pkg/vm/cli/cli.go:480 +0x1a5
github.com/urfave/cli.HandleAction({0xde74a0, 0x10d61d0}, 0x6)
github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0xf632f0, 0x6}, {0x0, …
```
=> compiler: avoid panic on empty package list

pkg/compiler/codegen.go, pkg/compiler/function_call_test.go
An attempt to compile the following code leads to runtime panic:
```
package foo
type CustomInt int
func Main() int {
var i CustomInt
i = 5
return i.Do(2)
}
func (CustomInt) Do(arg int) int {
return arg
}
```
The panic:
```
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
goroutine 22 [running]:
testing.tRunner.func1.2({0xa341c0, 0xc0001606d8})
/usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1212 +0x218
panic({0xa341c0, 0xc0001606d8})
/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).convertFuncDecl(0xc00015e3c0, {0xc753b8, 0xc000152c80}, 0xc000266300, 0x30) …
```
=> compiler: fix nil method receiver handling

Makefile
**Summary:** 
only tags that start with "v" will be accounted for in VERSION calculation.
**Motivation:** 
this allows us to use any custom tags along with tags that denote releases
=> Makefile: Filter version tags for version calculation

pkg/compiler/codegen.go, pkg/compiler/vardecl_test.go
An attempt to compile the following code leads to a runtime
panic:
```
package foo
var a, b = f()
func Main() int {
return a + b
}
func f() (int, int) {
return 1, 2
}
```
```
panic: runtime error: index out of range [1] with length 1 [recovered]
panic: runtime error: index out of range [1] with length 1
goroutine 22 [running]:
testing.tRunner.func1.2({0xa341c0, 0xc0001647f8})
/usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1212 +0x218
panic({0xa341c0, 0xc0001647f8})
/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).Visit(0xc0001623c0, {0xc75520, 0xc000155d80})
/home/anna/Documents/GitProjects/nspcc-dev/neo-go/pkg/compiler/codegen.go:591 +0x6559
go/ast.Walk({0xc6c4e0, …
```
=> compiler: allow multi-return variables declaration

pkg/vm/fuzz_test.go, pkg/vm/ref_counter.go, pkg/vm/ref_counter_test.go
Found by `TestFuzzVMDontPanic`.
1. Add new benchmark for refcount.
2. Split `Array` and `Struct` cases in `switch`.
3. Remove interface cast,
=> vm: optimize refcount

cli/server/server.go
That's the expected and desired behavior, SIGKILL is always there to do bad
things.
=> cli/server: handle SIGTERM gracefully

pkg/rpcclient/native.go, pkg/rpcclient/nns/contract.go, pkg/rpcclient/nns/contract_test.go, pkg/rpcclient/nns/record.go, pkg/rpcclient/nns/record_test.go, pkg/services/rpcsrv/client_test.go
We need to move these methods out even if we can't provide complete NNS support yet.
=> rpcclient: add enough of NNS into nns to deprecate NNS methods

cli/nep11_test.go, cli/nep17_test.go, cli/wallet/nep11.go, cli/wallet/nep17.go, docs/cli.md, pkg/rpcclient/nep11.go, pkg/rpcclient/nep11/base.go, pkg/rpcclient/nep17.go, pkg/rpcclient/nep17/nep17.go, pkg/rpcclient/neptoken/base.go, pkg/rpcclient/neptoken/base_test.go, pkg/rpcclient/neptoken/info.go, pkg/rpcclient/neptoken/info_test.go, pkg/services/rpcsrv/client_test.go
And update CLI commands. I think that's the last one for №4 from #2597.
=> Drop NEPXXTokenInfo from the RPC client

cli/multisig_test.go, cli/paramcontext/context.go, cli/smartcontract/smart_contract.go, cli/util/convert.go, cli/util/send.go, cli/wallet/multisig.go, cli/wallet/nep17.go, cli/wallet/validator.go, cli/wallet/wallet.go, cli/wallet_test.go, docs/cli.md, pkg/smartcontract/context/context.go, pkg/smartcontract/context/context_test.go
=> CLI signing improvements

pkg/rpcclient/invoker/invoker.go, pkg/rpcclient/invoker/invoker_test.go, pkg/rpcclient/rpc.go, pkg/services/rpcsrv/client_test.go
util.Uint256 is util.Uint256 and it's same RPC behind the scenes, so we can make it a bit easier to digest. See #2545 also.
Probably will need a rebase after #2683.
=> rpcclient: simplify historic API

pkg/services/stateroot/validators.go
Stateroot service is always active, but it might have no wallet.
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc57d41]
github.com/nspcc-dev/neo-go/pkg/wallet.(*Wallet).Close(...)
github.com/nspcc-dev/neo-go/pkg/wallet/wallet.go:175
github.com/nspcc-dev/neo-go/pkg/services/stateroot.(*service).Shutdown(0xc000105880?)
github.com/nspcc-dev/neo-go/pkg/services/stateroot/validators.go:77 +0x81
github.com/nspcc-dev/neo-go/pkg/network.(*Server).Shutdown(0xc000105880)
github.com/nspcc-dev/neo-go/pkg/network/server.go:271 +0x205
github.com/nspcc-dev/neo-go/cli/server.startServer(0xc0002702c0)
github.com/nspcc-dev/neo-go/cli/server/server.go:641 +0x2675 …
=> stateroot: fix panic on shutdown

examples/nft-nd-nns/nns.go, examples/nft-nd-nns/nns_test.go
Port https://github.com/neo-project/non-native-contracts/pull/23.
=> examples: NNS update, part 1

pkg/core/native/std_test.go
See neo-project/neo#2804 and neo-project/neo#2813. We're already compatible.
=> native: add some tests for stdlib's atoi

pkg/interop/iterator/iterator.go
The only way to get Iterator is as a result of storage.Find.
=> interop: adjust Iterator documentation

docs/compiler.md, pkg/compiler/codegen.go, pkg/compiler/convert_test.go
=> compiler: prohibit to compile type assertion with two return values

pkg/core/transaction/transaction.go
~VUB documentation doesn't match the behaviour.~ Thanks to @KirillovDenis.
It matches perfectly, my bad.
=> core: add example to VUB comment

pkg/smartcontract/parameter.go, pkg/smartcontract/parameter_test.go
Value of PublicKey parameter always stores public key bytes, not the deserialized representation. All other code (CLI parameters parsing, RPC-related code, etc.) is based on the idea that value of PublicKey is []byte.
=> smartcontract: fix underlying PublicKey parameter value

pkg/network/server.go, pkg/network/tcp_peer.go
Peers can be slow, very slow, slow enough to affect node's regular operation. We can't wait for them indefinitely, there has to be a timeout for send operations.
This patch uses TimePerBlock as a reference for its timeout. It's relatively big and it doesn't affect tests much, 4+1 scenarios tend to perform a little worse with while 7+2 scenarios work a little better. The difference is in some percents, but all of these tests easily have 10-15% variations from run to run.
It's an important step in making our gossip better because we can't have any behavior where neighbors directly block the node forever, refs. #2678 and #608.
This is set of tests this patch was tried on (4+1/7+2 with no 0 or 200ms delay):
One more thing I've tried today is making the timeout adaptive …
=> network: don't wait indefinitely for packet to be sent

pkg/network/helper_test.go, pkg/network/peer.go, pkg/network/server.go, pkg/network/tcp_peer.go
We have a number of queues for different purposes:
* regular broadcast queue
* direct p2p queue
* high-priority queue
And two basic egress scenarios:
* direct p2p messages (replies to requests in Server's handle* methods)
* broadcasted messages
Low priority broadcasted messages:
* transaction inventories
* block inventories
* notary inventories
* non-consensus extensibles
High-priority broadcasted messages:
* consensus extensibles
* getdata transaction requests from consensus process
* getaddr requests
P2P messages are a bit more complicated, most of the time they use p2p queue,
but extensible message requests/replies use HP queue.
Server's handle* code is run from Peer's handleIncoming, every peer has this
thread that handles incoming messages. When working with the peer it's
important …
=> Rework broadcast logic

cli/cmdargs/parser.go, cli/smartcontract/smart_contract.go, cli/vm/cli.go, cli/vm/cli_test.go, pkg/smartcontract/context/context.go, pkg/smartcontract/param_type.go, pkg/smartcontract/param_type_test.go, pkg/smartcontract/parameter.go, pkg/smartcontract/parameter_test.go, pkg/vm/stackitem/item.go, pkg/vm/stackitem/item_test.go, pkg/vm/vm.go
=> cli: improve VM CLI a bit more

config/protocol.mainnet.yml, config/protocol.testnet.yml, docs/node-configuration.md, pkg/config/application_config.go, pkg/network/discovery.go, pkg/network/discovery_test.go, pkg/network/helper_test.go, pkg/network/prometheus.go, pkg/network/server.go, pkg/network/server_config.go
Fixes #608, #2678. A new configuration option is added, `BroadcastFactor` that allows to configure the number of fan-out node between optimal (log-dependent on the size of the network, default) and all available peers.
=> Logarithmic gossip fan out

cli/server/server.go, go.mod, go.sum, internal/testcli/executor.go, pkg/consensus/consensus.go, pkg/consensus/consensus_test.go, pkg/network/server.go, pkg/network/server_test.go
It makes sense in general (further narrowing down the time window when transactions are processed by consensus thread) and it improves block times a little too, especially in the 7+2 scenario.
Related to #2744.
=> network/consensus: use new dbft StopTxFlow callback

config/protocol.mainnet.neofs.yml
We can't make it before 2550000, so move to 2600000. @anatoly-bogatyrev, please ensure you're using this new height for mainnet NeoFS configurations next week.
=> config: reschedule Aspidochelone fork block for NeoFS mainnet

pkg/network/server.go, pkg/network/server_test.go
=> Improve P2P transaction handling

pkg/network/helper_test.go, pkg/network/peer.go, pkg/network/server.go, pkg/network/tcp_peer.go
This is not exactly the protocol-level batching as was tried in #1770 and proposed by neo-project/neo#2365, but it's a TCP-level change in that we now Write() a set of messages and given that Go sets up TCP sockets with TCP_NODELAY by default this is a substantial change, we have less packets generated with the same amount of data. It doesn't change anything on properly connected networks, but the ones with delays benefit from it a lot.
This also improves queueing because we no longer generate 32 messages to deliver on transaction's GetData, it's just one stream of bytes with 32 messages inside.
Do the same with GetBlocksByIndex, we can have a lot of messages there too.
But don't forget about potential peer DoS attacks, if a peer is to request a lot of big blocks we need to flush them …
=> network: batch getdata replies

pkg/network/server.go
Sometimes we already have it, but it's not yet processed, so we can save on getdata request. It only affects very high-speed networks like 4-1 scenario and it doesn't affect it a lot, but still we can do it.
Tests on top of #2757:
=> network: check inv against currently processed transactions

pkg/core/blockchain.go
When block is being spread through the network we can get a lot of invs with the same hash. Some more stale nodes may also announce previous or some earlier block. We can avoid full DB lookup for them and minimize inv handling time (timeouts in inv handler had happened in #2744).
It doesn't affect tests, just makes node a little less likely to spend some considerable amount of time in the inv handler.
=> core: optimize HasBlock check for recent blocks

pkg/network/server.go
32 is a very good number, but we all know 42 is a better one. And it can even be proven by tests with higher peaking TPS values.
You may wonder why is it so good? Because we're using packet-switching networks mostly and a packet is a packet almost irrespectively of how big it is. Yet a packet has some maximum possible size (hi, MTU) and this size most of the time is 1500 (or a little less than that, hi VPN). Subtract IP header (20 for IPv4 or 40 for IPv6 not counting options), TCP header (another 20) and Neo message/payload headers (~8 for this case) and we have just a little more than 1400 bytes for our dear hashes. Which means that in a single packet most of the time we can have 42-44 of them, maybe 45. Choosing between these numbers is not hard then.
Inspired by #2757. (invcheck is in …
=> network: it is 42

cli/query/query_test.go
Problem - failing TestQueryTx test (see https://app.circleci.com/pipelines/github/nspcc-dev/neo-go/9623/workflows/5bdf01d9-c5e2-41da-9cf9-e5e945e9f4d5/jobs/64191):
```
=== RUN   TestQueryTx/verbose/FAULT
=== CONT  TestQueryTx
logger.go:130: 2022-10-26T10:47:51.414Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
logger.go:130: 2022-10-26T10:47:51.415Z	DEBUG	processing rpc request	{"method": "getnativecontracts", "params": "[]"}
logger.go:130: 2022-10-26T10:47:51.612Z	DEBUG	processing rpc request	{"method": "getversion", "params": "[]"}
logger.go:130: 2022-10-26T10:47:51.615Z	DEBUG	processing rpc request	{"method": "invokefunction", "params": "[11fdb7bc30a306a60dac874711a2b37b7da402c4 randomMethod  ]"}
logger.go:130: 2022-10-26T10:47:51.617Z	DEBUG	processing rpc …
```
=> cli: fix race in TestQueryTx

config/protocol.mainnet.neofs.yml
We're still 0.98.5 on this network.
=> config: move NeoFS mainnet Aspidochelone fork again

docs/node-configuration.md, pkg/services/rpcsrv/server.go
Break origin checks even more. Alternative to #2772.
=> rpcsrv: allow any Origin in WS connections if EnableCORSWorkaround

pkg/services/rpcsrv/prometheus.go, pkg/services/rpcsrv/server.go
They're a bit more useful and they're naturally grouped under rpc prefix. Simple counters will be removed eventually to avoid duplication.
=> rpcsrv: provide Prometheus histograms for calls

cli/smartcontract/contract_test.go, cli/smartcontract/generate_test.go, cli/smartcontract/testdata/nameservice/nns.go, cli/smartcontract/testdata/nonepiter/iter.go, cli/smartcontract/testdata/nonepiter/iter.manifest.json, docs/compiler.md, pkg/smartcontract/binding/generate.go, pkg/smartcontract/rpcbinding/binding.go
A substantial part of #2768, we can't unwrap stack items, but we can at least simplify the way to get them. And some nitpicking along the way.
=> Initial iterator support for RPC bindings

ROADMAP.md
I think it's useful to have this publicly available.
=> ROADMAP: add deprecated code removal schedule

cli/server/server.go, cli/server/server_test.go
And fix failing test along the way:
```
2022-11-11T12:37:47.0413934Z === RUN   TestResetDB
2022-11-11T12:37:47.0414557Z 2022-11-11T12:36:54.510Z	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
2022-11-11T12:37:47.0415288Z 2022-11-11T12:36:54.510Z	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2022-11-11T12:37:47.0416020Z 2022-11-11T12:36:54.510Z	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2022-11-11T12:37:47.0416786Z 2022-11-11T12:36:54.510Z	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2022-11-11T12:37:47.0417725Z 2022-11-11T12:36:54.510Z	INFO	MaxValidUntilBlockIncrement is not set or …
```
=> cli: properly close storage on `db reset`

cli/vm/cli_test.go
Problem: failing part of TestLoad:
```
=== RUN   TestLoad/loadgo,_check_signers
cli_test.go:160:
Error Trace:	/home/circleci/go/src/github.com/nspcc-dev/neo-go/cli/vm/cli_test.go:160
/home/circleci/go/src/github.com/nspcc-dev/neo-go/cli/vm/cli_test.go:147
/home/circleci/go/src/github.com/nspcc-dev/neo-go/cli/vm/cli_test.go:444
Error:      	command took too long time
Test:       	TestLoad/loadgo,_check_signers
```
Solution: split the test into multiple parts to reduce test execution time.
=> cli: split TestLoad into multiple parts

pkg/network/discovery.go, pkg/network/discovery_test.go, pkg/network/helper_test.go, pkg/network/peer.go, pkg/network/server.go, pkg/network/server_test.go, pkg/network/tcp_peer.go, pkg/network/tcp_peer_test.go, pkg/network/tcp_transport.go, pkg/network/transport.go
#2796
It's quite complicated, but I've tested:
* mainnet
* testnet
* 4-node private network
* damaged 3-out-of-4 private network with MinPeers 3
* mainnet with unplugged cable on startup
* mainnet with cable plugged out during regular operation, all connections dying because of timeout and cable plugged in again
All of these scenarios work better this way, less flapping, more useful connections, following MinPeers if possible, not doing useless attempts if not.
=> Network connections fix

pkg/compiler/assign_test.go, pkg/compiler/binary_expr_test.go, pkg/compiler/convert_test.go, pkg/compiler/for_test.go, pkg/compiler/vm_test.go, pkg/core/interop/contract/call.go, pkg/core/interop/runtime/engine.go, pkg/core/native/oracle.go, pkg/vm/context.go, pkg/vm/invocation_tree_test.go, pkg/vm/json_test.go, pkg/vm/vm.go, pkg/vm/vm_test.go
In fact I wanted to do something like `s/v.estack/ctx.sc.estack` to always use context-bound stack and use `v.estack` for result only. But it turns out that assumptions about global `v.estack` are so deeply integrated into various parts of our codebase that this change breaks almost everything. 
This PR only has some "good" changes made while looking at all this, `v.estack` will remain for some time.
=> Improve vm istack/estack handling

docs/node-configuration.md, pkg/config/rpc_config.go, pkg/rpcclient/wsclient.go, pkg/services/rpcsrv/client_test.go, pkg/services/rpcsrv/server.go, pkg/services/rpcsrv/server_helper_test.go, pkg/services/rpcsrv/subscription_test.go
#2818
Add a new server-side configuration as well.
=> Improve wsclient handshake error

cli/vm/cli_test.go, pkg/core/interop/storage/basic.go, pkg/vm/vm.go
~~Contracts loaded with `loadnef` and `loadgo` can't properly work with notifications and contract storages. Strictly, it's not a bug, because they are scripts actually, but as a user, I would expect them to behave like a loaded contracts and properly handle `runtime.Notify` and `storage.GetContext` calls.~~
Invocation errors are not detailed enough.
~~A bad cludge, but at least it allows to properly handle these things. Also, documentation is improved a bit.~~
Add some details.
=> core, vm: improve script invocation errors

pkg/core/blockchain.go, pkg/core/blockchain_neotest_test.go
They can stay in the memory pool forever because consensus process will never accept these transactions (and maybe even block consensus process at all).
=> core: filter out txes with system fee > MaxBlockSystemFee

pkg/core/blockchain.go, pkg/core/native/management.go, pkg/core/native/native_test/management_test.go, pkg/services/rpcsrv/client_test.go, pkg/services/rpcsrv/server_test.go
It doesn't store id->hash mappings for native contracts. We need blockchain's GetContractScriptHash to serve both anyway, so it was changed a bit. The only other direct user of native.GetContractScriptHash is the VM CLI, but I doubt anyone will use it for native contracts (they have ~zero VM code anyway).
=> native: make management compatible with C# node 3.5.0

pkg/config/basic_service.go, pkg/config/basic_service_test.go, pkg/config/config.go, pkg/config/rpc_config_test.go
6b4dd5703e3a2255c915406c60c2d91bb83fee06 made it to be a uint16 which was somewhat important for RPC, but now it's irrelevant and the fact that it was a string in some cases may lead to errors like these:
failed to unmarshal config YAML: yaml: unmarshal errors:
line 48: cannot unmarshal !!str `20011` into uint16
line 52: cannot unmarshal !!str `40001` into uint16
So for maximum backwards compatibility we better have string here and eventually it'll be deleted anyway.
=> config: use string type for Port

pkg/core/blockchain.go, pkg/network/server.go, pkg/network/tcp_transport.go, pkg/services/rpcsrv/server.go
It's a bit more efficient in case we're not logging the message (mostly for debug), makes the code somewhat simpler as well.
=> *: use zap.Stringer instead of zap.String where it can be used

pkg/encoding/bigint/fuzz_test.go, pkg/vm/fuzz_test.go
Add a couple of fuzz tests. Implemented by @fyrchik.
=> *: add fuzz tests for `bigint.FromBytes` and `vm.ParseMultisigContract`

pkg/network/blockqueue.go, pkg/network/blockqueue_test.go, pkg/network/payload/getblockbyindex.go, pkg/network/server.go
The problem is in peer disconnection due to invalid GetBlockByIndex payload (the logs are from some patched neo-go version):
```
дек 15 16:02:39 glagoli neo-go[928530]: 2022-12-15T16:02:39.490Z        INFO        new peer connected        {"addr": "10.78.69.115:50846", "peerCount": 3}
дек 15 16:02:39 glagoli neo-go[928530]: 2022-12-15T16:02:39.490Z        WARN        peer disconnected        {"addr": "10.78.69.115:50846", "error": "invalid block count", "peerCount": 2}
дек 15 16:02:39 glagoli neo-go[928530]: 2022-12-15T16:02:39.490Z        INFO        started protocol        {"addr": "10.78.69.115:50846", "userAgent": "/NEO-GO:1.0.0/", "startHeight": 0, "id": 1339571820}
дек 15 16:02:39 glagoli neo-go[928530]: 2022-12-15T16:02:39.491Z        INFO        new peer connected        {"addr": …
```
=> network: do not allow to request invalid block count

pkg/core/blockchain.go, pkg/core/state/tokens.go, pkg/core/state/tokens_test.go, pkg/encoding/bigint/bench_test.go, pkg/encoding/bigint/bigint.go, pkg/encoding/bigint/bigint_test.go, pkg/services/rpcsrv/server.go
This fixes #2864, but unfortunately it requires DB resynchronization. But if we're resynchronizing anyway, then we can make some additional adjustments as well.
=> Fix applog values

pkg/core/state/notification_event.go
Fortunately, this is backwards-compatible in any direction. See 98b5e2b3538af80bf94d18364f745bc9ef0a843b also.
=> state: always marshal applog exception into JSON, fix #2869

pkg/rpcclient/actor/actor.go
`Actor.MakeUnsignedUncheckedRun` method imposes restriction to `CalculateNetworkFee` method's implementations: `Hash` or `Size` methods must not be called on the pointer to the given transaction.
Add docs to adjust described requirement.
=> rpcclient/actor: Document `RPCActor.CalculateNetworkFee` method

pkg/services/rpcsrv/server.go
I'm trying to use `rpcsrv.Server` type in the developing application. I have global error channel which is used to sync app's error signals. In current implementation `New` contstructor accepts parameter of type `chan error`. Thus, I can't be sure that `Server` errors won't "disappear" from my application's view.
According to docs (and, accordingly, implementation), `Server` only writes errors to the channel. It seems that it is enough to accept a write-only channel.
Similar work can be made for cases like https://pkg.go.dev/github.com/nspcc-dev/neo-go@v0.100.1/pkg/core#Blockchain.SubscribeForTransactions.
=> services/rpcsrv: Strengthen `Server` error channel's type

pkg/rpcclient/wsclient.go
Add a warning about consequences of unproper notifications reading. Ref. https://github.com/morphbits/neofs-cdn-edge-manager/pull/88#discussion_r1088007680.
Ported from the outdated `Notifications` channel doc: https://github.com/nspcc-dev/neo-go/blob/b56dff2b1e1065be337d9c187bf48dca59983c7a/pkg/rpcclient/wsclient.go#L33-L34
Thanx to @masterSplinter01 for the problem description.
=> rpcclient: adjust new subscriptions API doc

pkg/rpcclient/client.go, pkg/rpcclient/client_test.go
Endpoint data not accessible
expose with method as string as per https://github.com/nspcc-dev/neo-go/issues/2912#issuecomment-1427110975
=> rpcclient: expose endpoint (fixes #2912)

pkg/core/storage/store.go
It is used in different context (seeking through the storage or through the contract storage), and sometimes empty prefix is not supported.
Thanks to @cthulhu-rider for the discussion.
=> core: adjust the documentation of SeekRange's Prefix field

pkg/rpcclient/local.go, pkg/rpcclient/local_test.go, pkg/rpcclient/wsclient.go, pkg/services/rpcsrv/client_test.go, pkg/services/rpcsrv/local_test.go, pkg/services/rpcsrv/params/params.go, pkg/services/rpcsrv/params/params_test.go, pkg/services/rpcsrv/server.go, pkg/services/rpcsrv/subscription.go
#2909.
Instead of RPC server rework we just provide a (wrapped) WSClient that does calls in the same process. RPC server rework is something that can be done, but:
* RPC client and RPC server interfaces do not exactly match in the way they handle inputs and outputs
* we'll have to manage concurrency in this client (and manage it again in the RPC server for subscriptions!)
This structure is better in that:
* for `Internal` user it's absolutely the same interface as `WSClient` has, they can be interchanged easily and we can have this link configurable (go via RPC or use internal)
* it has much simpler implementation
* subscriptions are much easier with `WSClient` interface (and more robust, RPC server has some buffers and already manages queue overflows)
But:
* it adds a little JSON in/out …
=> Not so local RPC client

pkg/network/tcp_peer.go
Fix potential memory leak with a lot of connected clients that keep requesting things from node and then disconnect.
=> network: drain send queues on peer disconnection

cli/vm/cli.go, pkg/core/blockchain.go, pkg/core/interop/contract/call.go, pkg/core/storage/boltdb_store.go, pkg/rpcclient/actor/waiter.go, pkg/services/oracle/neofs/neofs.go, pkg/services/oracle/network.go, pkg/vm/stackitem/json.go
Failing Linter job, see :
```
Error: non-wrapping format verb for fmt.Errorf. Use `%w` to format errors (errorlint)
```
Due to a set of places where multiple errors should be wrapped. However, multiple errors wrapping is a part of go 1.20, thus we can't use it now.
Explicitly specify go version (although it should be fetched from environment anyway).
=> *: add nolint comments to multiple errors wrapping

docs/node-configuration.md
Make it clear for the node operator.
=> docs: add minor note to `MinPeers` config section

pkg/services/rpcsrv/client_test.go, pkg/services/rpcsrv/params/txBuilder.go
Thanks to fyrchik for reporting. Need to test it wrt C# node compatibility and (if not compatible) apply another fix.
Otherwise it leads to the following error in the TestActor_CallWithNilParam:
```
=== RUN   TestActor_CallWithNilParam
logger.go:130: 2023-04-03T15:58:27.672+0300	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
logger.go:130: 2023-04-03T15:58:27.672+0300	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
logger.go:130: 2023-04-03T15:58:27.672+0300	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
logger.go:130: 2023-04-03T15:58:27.672+0300	INFO	MaxBlockSystemFee is not set or wrong, setting default value …
```
=> rpc: do not omit value of Null parameter on marshalling

ROADMAP.md, cli/vm/cli_test.go, examples/nft-d/nft.go, examples/nft-nd/nft.go, examples/runtime/runtime.go, examples/timer/timer.go, examples/token/token.go, internal/basicchain/testdata/test_contract.go, internal/basicchain/testdata/verify/verification_contract.go, pkg/compiler/analysis.go, pkg/compiler/codegen.go, pkg/compiler/function_call_test.go, pkg/compiler/interop_test.go, pkg/core/blockchain_neotest_test.go, pkg/interop/util/util.go, pkg/services/rpcsrv/prometheus.go
We can drop these small things now, RPC client is intentionally left for 0.103.0, configurations can sit for a bit longer time as well.
=> Drop some deprecated things in 0.102.0

ROADMAP.md, pkg/neorpc/result/peers.go, pkg/neorpc/result/peers_test.go, pkg/rpcclient/rpc_test.go
#2910 type mismatch
Change type from string to int.
=> neorpc: change peer port to int type (fixes #2910)

pkg/core/blockchain.go
This PR is aimed to make the state reset process faster and thriftier.
Firstly, we need to try to make a separate persisting routine (this optimisation is moved from #2813). After that we need to reduce amount of time spent on storage items removal/addition as described in https://github.com/nspcc-dev/neo-go/pull/2813#issuecomment-1324131712. The results of optimisations will be attached in the comment.
=> core: some state reset oprimizations

cli/util/convert.go, cli/util/util_test.go
Close #2911.
Works like a magic:
```
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go$ ./bin/neo-go util ops CxAMFHTn5bEoAfIH/wRZ1zATce9uZ6v2DBR05+WxKAHyB/8EWdcwE3Hvbmer9hTAHwwIdHJhbnNmZXIMFPVj6kC8KD1NDgXEjqMFs/Kgc0DvQWJ9W1I=
INDEX    OPCODE       PARAMETER
0        PUSHNULL         <<
1        PUSH0        
2        PUSHDATA1    74e7e5b12801f207ff0459d7301371ef6e67abf6
24       PUSHDATA1    74e7e5b12801f207ff0459d7301371ef6e67abf6
46       PUSH4        
47       PACK         
48       PUSH15       
49       PUSHDATA1    7472616e73666572 ("transfer")
59       PUSHDATA1    f563ea40bc283d4d0e05c48ea305b3f2a07340ef
81       SYSCALL      System.Contract.Call (627d5b52)
```
=> cli: extend `util` with `ops` command

pkg/core/blockchain.go
I've carefully checked the way how new service can be added to the Blockchain instance or to be removed from it. Current implemention of SetNotary and SetOracle methods doesn't contain dangerous code, and native contracts have atomic values everywhere where service is stored.
Current implementation of Notary, Oracle and StateRoot services' reload/disabling/enabling on SIGUSR1 is safe and doesn't require any adjustment.
=> core: improve documentation of SetOracle/SetNotary

cli/server/server.go, pkg/services/rpcsrv/server.go, pkg/services/rpcsrv/server_test.go
* closes #2896
special attention to b6e34b23631fe49af3afce7ab847f1407c156814, maybe I missed the hidden meaning
=> rpc: Fix deadlock produced during server shutdown

docs/notary.md
All Notary contract witnesses in incomplete transaction (both main and fallback) should have invocation scripts pushing dummy signature on stack. See the 7-th step of the notary request creation documentation: https://github.com/nspcc-dev/neo-go/blob/master/docs/notary.md#2-request-submission.
This bug is closely related to #2955 and prevents the neofs-node code from migration to Notary Actor, as far as the behaviour of notary request creation has been changed.
=> docs: adjust Notary request submission documentation

pkg/core/blockchain.go, pkg/core/native/management.go, pkg/core/native/native_test/management_test.go, pkg/services/rpcsrv/client_test.go, pkg/services/rpcsrv/server_test.go
This reverts commit 236e633ee488889a63f59ac9649cbfc10e4783d3.
Close #2859.
=> Revert "native: make management compatible with C# node 3.5.0"

pkg/core/blockchain.go, pkg/core/stateroot/module.go
Initialize Prometheus metrics on node start where appropriate and review the usage of the following metrics:
```
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go$ find | grep prometheus.go
./pkg/network/prometheus.go
./pkg/core/stateroot/prometheus.go
./pkg/core/prometheus.go
./pkg/services/rpcsrv/prometheus.go
./pkg/services/metrics/prometheus.go
```
Close #2970.
=> *: adjust Prometheus metrics initialisation on node start

pkg/core/blockchain.go
Should be a part of 67d4d891ef847a8979fce36a37073ff4d74316b6.
=> core: add nolint comment for deprecated error format style

.github/workflows/run_tests.yml
It should be this way because we can't provide some features golangci-lint require us to do due to the need to support not only the latest Go version, but also two versions below.
=> github: use minimum supported go version for Linter job

pkg/rpcclient/wsclient.go, pkg/rpcclient/wsclient_test.go
Regular Client doesn't care much about connections, because HTTP client's Do method can reuse old ones or create additional ones on the fly. So one request can fail and the next one easily succeed. WSClient is different, it works via a single connection and if it breaks, it breaks forever for this client. Callers will get some error on every request afterwards and it'd be nice for this error to be the same so that API users could detect disconnection this way too.
Related to nspcc-dev/neofs-node#2325.
=> rpcclient: provide some exported error for disconnected WSClient

pkg/consensus/consensus_test.go, pkg/core/block/block_test.go, pkg/core/blockchain_core_test.go, pkg/core/blockchain_neotest_test.go, pkg/core/chaindump/dump_test.go, pkg/core/dao/dao_test.go, pkg/core/interop/interopnames/convert_test.go, pkg/core/interop/storage/storage_test.go, pkg/core/mempool/mem_pool_test.go, pkg/core/mpt/billet_test.go, pkg/core/native_designate_test.go, pkg/core/transaction/oracle_test.go, pkg/core/transaction/transaction_test.go, pkg/network/extpool/pool_test.go, pkg/network/payload/extensible_test.go, pkg/network/payload/merkleblock_test.go, pkg/network/server_test.go, pkg/rpcclient/rpc_test.go, pkg/rpcclient/wsclient_test.go, pkg/services/oracle/neofs/neofs_test.go, pkg/services/oracle/network_test.go, pkg/services/stateroot/service_test.go, pkg/smartcontract/manifest/standard/comply_test.go, pkg/smartcontract/nef/method_token_test.go, pkg/smartcontract/nef/nef_test.go, pkg/vm/stackitem/json_test.go, pkg/vm/stackitem/serialization_test.go
This is just a much better way to do the same thing. Inspired by nspcc-dev/neofs-sdk-go#407.
=> *: use require.ErrorIs instead of require.True(t, error.Is())

.github/workflows/build.yml
Close #3001.
Here's the workflow example: https://github.com/AnnaShaleva/neo-go/actions/runs/4939304132/jobs/8829920604
Here's the release example with binaries attached: https://github.com/AnnaShaleva/neo-go/releases/tag/v0.104.0
=> github: automatically attach binaries to the release

ROADMAP.md, pkg/network/prometheus.go, pkg/network/server.go
=> network: add `neogo_version` metric, deprecate `serv_node_version`

cli/options/options.go, cli/server/server.go, cli/server/server_test.go, cli/vm/vm.go, docs/cli.md
=> cli: allow to provide single node config file

cli/smartcontract/contract_test.go, cli/smartcontract/smart_contract.go, cli/vm/cli.go, cli/vm/cli_test.go, docs/compiler.md
Close #2993.
This PR contains implementation of the first suggestion mentioned in the issue (manifest filename autocompletion). I've tried to implement the second one as far, but turns out it's not that easy. We use the a separate [github.com/chzyer/readline`](https://github.com/chzyer/readline) library to read user input, and this library doesn't provide enough functionality for proper paths autocompletion. I was able to properly autocomplete the top-level paths only (as presented in the [example](https://github.com/chzyer/readline/blob/7f93d88cd5ffa0e805d58d2f9fc3191be15ec668/example/readline-demo/readline-demo.go#L39)), going deeper causes too much cludges and doesn't work good. @roman-khimov, if we need an autocomplete functionality for filepaths, let's create a separate issue for …
=> cli: autocomplete contract-related filenames for `compile` and `loadnef` commands

pkg/core/native/native_test/notary_test.go, pkg/rpcclient/nep11/base_test.go, pkg/rpcclient/nep11/divisible_test.go, pkg/rpcclient/nep17/nep17_test.go, pkg/rpcclient/notary/contract.go, pkg/rpcclient/notary/contract_test.go, pkg/rpcclient/notary/doc_test.go, pkg/smartcontract/builder.go, pkg/vm/emit/emit.go, pkg/vm/emit/emit_test.go, pkg/vm/stackitem/item.go, pkg/vm/stackitem/item_test.go
=> vm: allow to emit stackitem.Convertible

cli/cmdargs/parser.go, docs/compiler.md
They can't even be used now because they'll fail the conversion.
=> *: drop legacy addresses from examples

pkg/core/mempool/mem_pool.go, pkg/core/mempool/mem_pool_test.go
Pay for all the conflicts if you'd like to went in. Close https://github.com/nspcc-dev/neo-go/issues/3028.
=> mempool: adjust the rule of conflicting transaction ranking

go.mod, go.sum
Refs. nspcc-dev/neofs-node#999, it fixes a number of other Windows-related issues as well.
Let me run it through neo-bench before the merge.
=> go.mod: upgrade bolt to v1.3.7

cli/smartcontract/testdata/nameservice/nns.go, cli/smartcontract/testdata/verifyrpc/verify.go, pkg/smartcontract/rpcbinding/binding.go
Should be a part of #3035, otherwise generated bindings are failed to be compiled.
=> rpcbinding: call `scriptFor*` as method

pkg/core/native/crypto.go, pkg/core/native/crypto_blspoints.go, pkg/core/native/native_test/cryptolib_test.go, pkg/vm/stackitem/item.go, pkg/vm/vm_test.go
It's the way how C# node works. Also, add missing GT points equality check to CryptoLib's `bls12381Equal` method.
Ref. https://github.com/nspcc-dev/neo-go/issues/3002#issuecomment-1591220501.
=> native: allow to use EQUAL opcode for BLS12-381 points comparison

pkg/core/interop/contract/call.go, pkg/core/interop/contract/call_test.go, pkg/vm/context.go, pkg/vm/vm.go
Our wrapping optimization relied on the caller context having a TRY block, but each context (including internal calls!) has an exception handling stack of its own, which means that for an invocation stack of
entry
A.someMethodFromEntry()   # this one has a TRY
A.internalMethodViaCALL() # this one doesn't
B.someMethod()
we get `HasTryBlock() == false` for `A.internalMethodViaCALL()` context, which leads to missing wrapper and missing rollbacks if B is to THROW. What this patch does instead is it checks for any context within contract boundaries.
Fixes #3045.
=> interop/contract: fix state rollbacks for nested contexts

pkg/core/native/management.go, pkg/core/native/native_test/management_test.go
This check is good and was present here since #1729, but it was accidently removed from the reference implementation (see the discussion in https://github.com/neo-project/neo/issues/2848). The removal of this check from the C# node leaded to the T5 testnet state diff since 1670095 heigh which causes inability to process new blocks since 2272533 height (see #3049). This check was added back to the C# node in https://github.com/neo-project/neo/pull/2849, but it is planned to be the part of the upcoming 3.6.0 C# node release.
We need to keep our testnet healthy, thus, strict contract script check will be temporary removed from the node code and is planned to be added back to be a part of the next 3.6.0-compatible release.
Close #3049.
=> core: remove contract script check on deploy/update

CHANGELOG.md, pkg/core/native/management.go, pkg/core/native/native_test/management_test.go
Depends on #3052.
The release plan is the following:
1. Merge #3052, update `rel-0.101.3` branch which is based on v0.101.2 + two commits.
2. Merge `rel-0.101.3` into master.
3. Create `v0.101.3` tag pointing to CHANGELOG update for 0.101.3 (00e076b2993cca149ccb61daa35c71bbbdafc11d).
4. Release accoarding to the release notes.
=> Release 0.101.3

pkg/network/server.go, pkg/network/server_test.go
This prevents the possible attack on notary request sender when malicious partie is allowed to send notary request with main transaction being someone else's fallback.
=> network: forbid Notary contract to be a sender of main transaction

pkg/core/transaction/witness_scope.go, pkg/core/transaction/witness_scope_test.go, pkg/neorpc/types.go, pkg/neorpc/types_test.go, pkg/services/rpcsrv/params/param_test.go
Close #3059. C#'s rules for RPC-server signers unmarshalling are not as strict as for core signers. Not sure whether it's worth bug in C# node, because it's a valid behaviour. Let's fix it in our side.
=> neorpc: adjust `SignerWithWitness` marshalling scheme

pkg/smartcontract/parameter.go, pkg/smartcontract/parameter_test.go
Error on passing `nil` as an argument to `(*Invoker).Call`
Merge.
=> smartcontract: allow to pass nil as parameter to (*Invoker).Call

pkg/core/blockchain.go, pkg/core/blockchain_neotest_test.go, pkg/core/dao/dao.go, pkg/core/dao/dao_test.go, pkg/core/mempool/mem_pool.go, pkg/core/transaction/transaction.go
On-chain conflicting transaction is treated as "good" and valid by default, which may prevent the main transaction from entering the chain in case of an attack. The problem is described by @shargon in https://github.com/neo-project/neo/pull/2818#issuecomment-1632651314.
Check the signers of conflicting transaction and treat conlflict as valid only if the list of signers intersects with signers of incoming main transaction. The check in mempool is updated as far.
=> core: check the signers of on-chained conflicting transaction during new transaction verification

pkg/rpcclient/management/management.go, pkg/rpcclient/management/management_test.go
There may be no such contract, then Null stackitem is expected on stack.
=> rpcclient: adjust `unwrapContract` helper

cli/server/server.go, cli/vm/cli_test.go, pkg/services/rpcsrv/server.go, pkg/services/rpcsrv/server_helper_test.go
Invalid `submitoracleresponse` RPC handler behaviour in case of disabled Oracle service: no `neorpc.NewRPCError("Oracle is not enabled", "")` error is returned. Thanks to @tatiana-nspcc for the report.
Check for typed nil value while setting Oracle service. I know, that we don't want to import the whole `oracle` package from the `rpcsrv`, but the alternatives I see looks worser to me:
1. Check that Oracle service is a proper nil value each time when `rpcsrv.New(...)` is used. It's not very convinient; there are three places in the code and a couple more in tests.
2. Use reflection inside `rpcsrv` to ensure that Oracle service is really nil. We'd better avoid reflection untill there are no other choices.
=> rpcsrv: carefully store Oracle service instance

pkg/compiler/debug.go
Thanks to @fyrchik, see the
https://github.com/neo-project/neo-devpack-dotnet/pull/154/files#diff-ebf53d00d5ba1f1197fedd2b8111fe9a8f44fb96699ef1314d54d05d5ceeb3f3R27
Not tested yet, need to take more careful look at it.
=> compiler: fix sequence point boundaries

docs/compiler.md, pkg/compiler/analysis.go, pkg/compiler/codegen.go, pkg/compiler/func_scope.go, pkg/compiler/generics_test.go
This PR includes the following changes:
1. Properly retrieve name of generic functions (fix panic described in #3040).
2. Disallow generics usages in the following cases:
* Generic method receiver
* Generic function parameters
* Generic type declaration
Close #3040. Ref. #2377.
=> compiler: temporary disallow generics usages

pkg/config/config.go, pkg/services/rpcsrv/server.go, pkg/services/rpcsrv/server_test.go
Ref. https://github.com/nspcc-dev/neo-go/issues/3106. This PR makes the life of NeoFS IR supernode better.
=> rpcsrv: enforce default config values on server creation if malformed value specified

pkg/services/rpcsrv/server.go
=> rpcsrv: drop unused method from the Ledger interface

docs/rpc.md, pkg/core/mempool/mem_pool.go, pkg/core/mempool/mem_pool_test.go, pkg/neorpc/result/raw_notary_pool.go, pkg/rpcclient/doc.go, pkg/rpcclient/rpc.go, pkg/rpcclient/rpc_test.go, pkg/services/rpcsrv/client_test.go, pkg/services/rpcsrv/server.go, pkg/services/rpcsrv/server_test.go, pkg/services/rpcsrv/subscription_test.go
We have notary pool subscriptions, but it's not enough for debugging some unexpected things that may happen while submitting notary requests.
The problem is described in https://github.com/nspcc-dev/neo-go/issues/2951
Add the following RPC extensions:
- `getRawNotaryPool` returns hashes from all the verified transactions, including both main and fallback transactions. 
- `getRawNotaryRequest` takes a transaction hash and attempts to find the corresponding transaction in the notary requests mempool. It searches through all the verified main and fallback transactions.
Close https://github.com/nspcc-dev/neo-go/issues/2951.
=> Implement `getrawnotaryrequest` and `getrawnotarytransaction` RPC extensions

pkg/core/storage/dbconfig/store_config.go
There are incorrect values for Type in the DBConfiguration struct description.
The problem is described in https://github.com/nspcc-dev/neo-go/issues/2931
Add the correct supported types (`Type`) in the `DBConfiguration` struct.
Close https://github.com/nspcc-dev/neo-go/issues/2931
=> Fix `DBConfiguration` description

pkg/rpcclient/unwrap/unwrap.go, pkg/rpcclient/unwrap/unwrap_test.go
A check for successful invocation (in the HALT state) that returns nothing is required.
The problem is described in https://github.com/nspcc-dev/neo-go/issues/3070
Add unwrap.Nothing(aer, error) error for it, which should expect zero stack items and the HALT state.
Close https://github.com/nspcc-dev/neo-go/issues/3070
=> Add `unwrap.Nothing` function

pkg/vm/vm.go
Having difficulties manually converting hashes in opcode dumps.
The problem is described in https://github.com/nspcc-dev/neo-go/issues/3030 
If the parameter in the opcode dump is a 20-byte value, then add converted values, such as the address and the swapped endianness.
Close https://github.com/nspcc-dev/neo-go/issues/3030
=> Add address and swap endianness to vm opcode dump for hashes

pkg/neotest/doc.go
We don't want anyone to have the same problem.
=> neotest: improve doc based on #3120

pkg/core/state/native_state.go, pkg/core/state/native_state_test.go
It can be non-zero even if VoteTo is NULL. Fixes state diff with 3.6.0:
block 41660: value mismatch for key +////xTrvgat3qG/w8hQoD/I4MgUz6rygA==: QQQhAS8hA7yiAAAhAA== vs QQQhAS8hA7yiAAAhB+POSWfBCAE=
Related to #2844.
=> state: always deserialize LastGasPerVote

config/protocol.mainnet.neofs.yml
For some reason it got out of sync with the reality, Notary is enabled since April there.
=> config: fix mainnet neofs config

pkg/core/state/contract_test.go, pkg/smartcontract/manifest/manifest.go
If manifest trusts presented as Null stackitem, then they should be treated as wildcard, not as restricted.
It's not the same problem as described and fixed in https://github.com/neo-project/neo/pull/2901 and
https://github.com/neo-project/neo/pull/2892, although these two PRs are related.
=> smartcontract: fix wildcard trusts deserialization

pkg/compiler/codegen.go, pkg/compiler/numeric_test.go
Currently we take int64 value from the Go parser and push it to the stack. It is not a common practice (usually we just use `int`), but can be a problem while doing bit arithmetic and serializing numbers.
Make a separate case for uint64. Because `emit.BigInt` checks whether an integer is small, the emitted byte-code should be the same in other cases.
=> compiler: Fix emitting big uint64 constants

pkg/core/storage/boltdb_store.go
To dump the DB, the service must be stopped. If this is not the case `dump` command just hangs without any output.
This _may_ be unexpected from the ops POV (hello, @532910).
Introduce timeout for bbolt db open. I have decided not to put it in the configuration, because 5 seconds is more than enough, given that flock retry is 50 milliseconds
https://github.com/etcd-io/bbolt/blob/db45d0d6b1f6d173baad00019fdc7c58ad0ab002/db.go#L19
https://github.com/etcd-io/bbolt/blob/db45d0d6b1f6d173baad00019fdc7c58ad0ab002/db.go#L222
Do you think this is worth having in the configuration (like I dump and _then_ stop the service and _expect_ dump to work for such a usecase)?
=> storage: Use timeout for boltdb database opening

pkg/consensus/consensus.go, pkg/core/blockchain.go, pkg/core/blockchain_core_test.go, pkg/core/native/native_neo.go, pkg/core/native/native_test/neo_test.go
Fix validators/committee cache of native Neo contract. See the bug description in the commit messages.
Close #2989 along the way.
=> Fix race caused by design of native Neo validators/committee cache

.github/workflows/tests.yml
Currently it's failing, but no token is required for public repos:
```
[2023-10-10T10:35:11.917Z] ['error'] There was an error running the uploader: Error uploading to https://codecov.io: Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```
=> .github: upgrade coverage uploading action

pkg/rpcclient/local.go, pkg/rpcclient/wsclient.go
* Rename c.done channel to c.readerDone
* Introduce c.writerDone channel that is closed if the wsWriter's loop is done
* Make the error returned by makeWsRequests verbose
Fix #3135
=> rpcclient: fix wsclient hang on making request

pkg/rpcclient/rpc.go
=> rpcclient: always provide `start` parameter for `findstorage` RPC

config/protocol.unit_testnet.single.yml, config/protocol.unit_testnet.yml, pkg/network/payload/address_test.go
Ref. #2975.
Here's the example of successful run: https://github.com/nspcc-dev/neo-go/actions/runs/6562296558/job/17823936017. I'll run it a couple of times to ensure that the problem is gone before the merge. Thus, currently is in draft.
Just for the record, an alternative to this PR was a Dialler fix at 6ec8126d0042f3ad01e403c31d7caa80250696da. I've also considered to enable IPv6 on our Windonws GA runner, but it's not possible at the current moment due to GitHub infrastructure constraints, see the https://github.com/actions/runner-images/issues/668.
=> Fix timeout of RPC tests on Windows

pkg/neorpc/types.go, pkg/network/payload/inventory_test.go, pkg/rpcclient/invoker/doc_test.go, pkg/vm/stackitem/json.go
Probably, the Linter job was updated, and there are a set of linter warnings discovered in https://github.com/nspcc-dev/neo-go/pull/3165 Lint job run.
=> Fix linter problems

pkg/core/blockchain.go, pkg/core/blockchain_neotest_test.go, pkg/core/dao/dao.go, pkg/core/native/policy.go
Refactored native NeoToken cache scheme introduced in #3110 sometimes requires validators list recalculation during native cache initialization process (when initializing with the existing storage from the block that is preceded each N-th block). To recalculate validators from candidates, native NeoToken needs an access to cached native Policy blocked accounts. By the moment of native Neo initialization, the cache of native Policy is not yet initialized, thus we need a direct DAO access for Policy to handle blocked account check.
Close #3181. Also refactor native Policy cache a bit.
=> Fix native Neo cache initialization

pkg/core/native/native_nep17.go, pkg/core/native/native_test/neo_test.go
Close #3190.
I'm struggling with the fact that we have `updateAccBalance`. It's the third time when I'm trying to fix roundtrips. We already have `TestNEO_Roundtrip`, `TestNEO_TransferZeroWithNonZeroBalance` and `TestNEO_TransferZeroWithZeroBalance`, and I'm still not sure that it works correctly. To be honest, I would love to rewrite `TransferInternal` and remove `updateAccBalance` at all, to match C# code perfectly, line-by-line.
Node sync is in progress to check that the bug is fixed.
=> native: prohibit non-zero GAS/NEO roundtrip with zero balance

pkg/neorpc/errors_test.go
Close #3188. Seems that I misused `errors.As` in neo-bench, because it works OK in tests without any additional changes in code, so no fix is needed.
=> neorpc: ensure errors.Is and errors.As work properly with neorpc.Error

CHANGELOG.md
By the moment of PR opening:
Mainnet states match:
```
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go$ go run scripts/compare-states/compare-states.go http://seed1.neo.org:10332 http://localhost:10332
at 0: d34893828a2ddb99c87226a92f764ae2dfadd0d2dc53fb33ae425be83b8d30b4 vs d34893828a2ddb99c87226a92f764ae2dfadd0d2dc53fb33ae425be83b8d30b4
at 4380541: 5079978907885577433845bfd317ea125e81e32cec4fc7290943cd111d44a1b2 vs 5079978907885577433845bfd317ea125e81e32cec4fc7290943cd111d44a1b2
```
Testnet states match:
```
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go$ go run scripts/compare-states/compare-states.go http://seed1t5.neo.org:20332 http://localhost:20332
at 0: ed359c92fd2e5d3fb6cc57c1599481b223b9eea82bcf940dd1a3db354a9b99d6 vs …
```
=> Release 0.103.1

pkg/vm/stackitem/item.go, pkg/vm/stackitem/json_test.go
To prevent possible DoS. Port the https://github.com/neo-project/neo-vm/pull/514, close #3170.
Draft until some proximity to 0.104.0.
=> vm: reduce maximum stckitem size

cli/smartcontract/contract_test.go, pkg/compiler/compiler_test.go, pkg/core/state/contract.go, pkg/smartcontract/nef/nef.go, pkg/smartcontract/nef/nef_test.go
In this PR:
- Port the https://github.com/neo-project/neo/pull/2939;
- Introduce NEF size check on file serialization and forbid large NEFs compilation;
- Add `--no-nef-check` option to `contract compile` CLI command and compiler.
Ref. #3170 and depends on #3185. Draft until some real proximity to 0.104.0.
=> Restrict maximum serialized NEF file size

docs/rpc.md, pkg/rpcclient/doc.go
Refs. neo-project/neo-modules#837.
=> docs: canceltransaction is not going to be supported

.github/CODEOWNERS, README.md
His account is disabled (which technically leads to an invalid CODEOWNERS file) and he's no longer active, unfortunately.
=> *: drop fyrchik from code owners

cli/smartcontract/manifest.go, pkg/compiler/compiler.go, pkg/core/blockchain_neotest_test.go, pkg/core/native/management.go, pkg/core/native/management_test.go, pkg/smartcontract/manifest/manifest.go, pkg/smartcontract/manifest/manifest_test.go, pkg/vm/stackitem/json.go, pkg/vm/stackitem/serialization.go, pkg/vm/stackitem/serialization_test.go
Close #3197.
Draft until the following TODOs are done:
=> Introduce stackitem serialization limits

pkg/compiler/debug.go
It affects both Debug data and bindings, otherwise two unnamed structures can get any of unnamed/unnamedx names depending on particular invocation.
=> compiler: walk over functions in reproducible order, fix #3219

go.mod, go.sum
Close #3224.
This PR makes us compatible up to 3057589 of T5:
```
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go$ go run ./scripts/compare-states/compare-states.go http://localhost:20332 http://seed1t5.neo.org:20332
at 0: 62fd8ff9b0543aea352257db5b00bbb01d1bc0d2cc665e1f24cf5de0d16ebc7b vs 62fd8ff9b0543aea352257db5b00bbb01d1bc0d2cc665e1f24cf5de0d16ebc7b
at 3057589: ee43eda779de38ad67763e012aa5734f787c545f0fee8b1294811394ffe133b7 vs ee43eda779de38ad67763e012aa5734f787c545f0fee8b1294811394ffe133b7
```
=> *: upgrade go-ordered-json version

docs/node-configuration.md, pkg/config/config.go, pkg/config/rpc_config.go, pkg/neorpc/types.go, pkg/neorpc/types_test.go, pkg/services/rpcsrv/params/param.go, pkg/services/rpcsrv/server.go
=> Anti-DOS RPC limitations

cli/options/options.go, cli/server/server.go, cli/server/server_test.go, cli/vm/cli_test.go, cli/vm/vm.go, pkg/config/config.go
=> cli: add --relative-path option

examples/zkp/cubic_circuit/go.mod, examples/zkp/cubic_circuit/go.sum
0.103.1 contains all necessary changes to run tests. Otherwise every change in the parent's go.mod requires updating the example's go.mod.
=> examples: do not replace neo-go library for ZKP examples

pkg/core/blockchain.go, pkg/services/notary/core_test.go, pkg/services/notary/notary.go, pkg/services/oracle/oracle.go, pkg/services/oracle/oracle_test.go, pkg/services/stateroot/service.go, pkg/services/stateroot/service_test.go
1. Initialise services dependant on roles designation based on N+1 block so that Genesis roles extension work properly. There's not much sence to fetch node roles information for the latest persisted block because Designation contract itself makes designated nodes responsible since the next subsequent block.
2. Perform initialisation of StateRoot service with designated StateValidator's node list in the service constructor. There's no need to wait until the next role update event, and it may lead to inaccuraces in service work on SIGHUP/server restart.
Close #3228.
=> core, services: fix Designation-dependant service initialisation

pkg/vm/emit/emit.go
No functional changes, just moved a part of emit.Array to a separate exported method. It may be useful for contract-based witness invocation scripts construction and not only. Ref.
https://github.com/nspcc-dev/neo-go/pull/3233#discussion_r1407786333.
=> vm: allow to emit `any` based on its type

pkg/core/state/contract.go
Although it doesn't rais an exception on our side, we still have this unrelevant information in the resulting RPC call response structure. This should be a part of https://github.com/nspcc-dev/neo-go/pull/3212.
Port https://github.com/neo-project/neo-modules/pull/851.
=> core: remove UpdateHistory from NativeContract structure

pkg/core/native/management_neotest_test.go
I had some reason to suspect something is wrong here (but it's all OK). Even though this is kinda tested in TestDeployGetUpdateDestroyContract, it uses internal APIs and with neotest we can ensure it work OK for a complete tx/block environment. So, won't hurt having these tests as well.
=> native: test immediate contract availability

pkg/core/native/native_test/ledger_test.go, pkg/neotest/basic.go, pkg/neotest/signer.go
When using another contract for verification in unit tests, the transaction cost is calculated incorrectly.
...
To calculate the transaction cost, a test neo-vm is started on which the verification is performed.
...
=> neotest: Add contract signer support

.github/workflows/build.yml
=> github: enable amd64 builds for osx

go.mod, go.sum
Nothing special, the changelog is rather small, but let's use the latest anyway.
=> go.mod: upgrade BoltDB to 1.3.8

docs/notifications.md, pkg/neorpc/filters.go, pkg/neorpc/rpcevent/filter.go, pkg/neorpc/rpcevent/filter_test.go, pkg/rpcclient/wsclient.go, pkg/rpcclient/wsclient_test.go, pkg/services/rpcsrv/server.go, pkg/services/rpcsrv/subscription_test.go
=> rpc: add an ability to filter out NotaryRequestEvents

pkg/rpcclient/wsclient_test.go
Must be a part of #3257.
Waiting for working tests...
=> rpcclient: fix failing initialisation-based tests

pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
=> wallet: Add new wallet constructors

pkg/consensus/consensus.go, pkg/core/native/native_neo.go
=> native: prevent improper Neo cache invalidation

pkg/neotest/basic.go, pkg/neotest/signer.go, pkg/rpcclient/actor/maker.go, pkg/wallet/account.go
Close #3015 
Implement second option from https://github.com/nspcc-dev/neo-go/issues/3015#issuecomment-1546110354
In the first one (interface instead of `wallet.Account`) we still have a problem with network fee calculation: actor modifiers are executed after network fee is calculated and there are no hooks to change invocation script.
This implementation disallows providing signature as an argument (though in a backward compatible way).
It is a restriction, but not a sad one: if we have a private key, we can always add a simple signer and provide its address to `verify()`, which can use `runtime.CheckWitness` to effectively perform the same check (with proper scopes it could be _exactly_ the same).
Also, not sure about the meaning of `CanSign`, so didn't touch it here.
TBH I would remove …
=> Allow complex contract signature schemes in `wallet.Account`

docs/notifications.md, pkg/neorpc/filters.go, pkg/neorpc/filters_test.go, pkg/neorpc/rpcevent/filter.go, pkg/neorpc/rpcevent/filter_test.go, pkg/rpcclient/wsclient.go, pkg/rpcclient/wsclient_test.go, pkg/services/rpcsrv/client_test.go, pkg/services/rpcsrv/server.go, pkg/services/rpcsrv/subscription.go, pkg/services/rpcsrv/subscription_test.go
Change BlockFilter Primary field from int to byte. Additional check of filters parameters added for filter validation.
Closes: #3241
=> rpc: subscription filters validity check

pkg/rpcclient/unwrap/unwrap.go, pkg/rpcclient/unwrap/unwrap_test.go, pkg/smartcontract/entry.go, pkg/vm/iterator_test.go
=> Allow to partially unwrap session iterator

CHANGELOG.md, ROADMAP.md
Depends on #3265, #3274, ~#3281~, #3260.
T5 states match:
```
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go$ go run scripts/compare-states/compare-states.go http://localhost:20332 http://seed1t5.neo.org:20332
at 0: 62fd8ff9b0543aea352257db5b00bbb01d1bc0d2cc665e1f24cf5de0d16ebc7b vs 62fd8ff9b0543aea352257db5b00bbb01d1bc0d2cc665e1f24cf5de0d16ebc7b
at 3243902: eb1080d5de43b4db4f1df860cb8f36e2a83e939300992d30f1f83fd7bdcbb5cd vs eb1080d5de43b4db4f1df860cb8f36e2a83e939300992d30f1f83fd7bdcbb5cd
```
Mainnet states match:
```
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go$ go run scripts/compare-states/compare-states.go http://localhost:10332 http://seed1.neo.org:10332
at 0: 58a5157b7e99eeabf631291f1747ec8eb12ab89461cda888492b17a301de81e8 vs …
```
=> CHANGELOG: release 0.105.0

pkg/services/notary/notary.go
Let the user know whether it's main or fallback transaction that failed to be relayed to the network.
=> services: improve notary service logging

pkg/config/protocol_config.go, pkg/config/protocol_config_test.go
=> config: update validation with check committee

pkg/rpcclient/nns/contract.go, pkg/rpcclient/nns/contract_test.go, pkg/rpcclient/nns/iterators.go
Added missing function from nns smart-contract manifest.
Closes #2732.
=> smartcontract: update nns wrapper

cli/wallet/wallet.go, cli/wallet/wallet_test.go, pkg/wallet/account.go
Made --wif optional if one of the provided public keys is already in the wallet.
Closes #3266
=> cli: update import-multisig with making --wif optional

cli/server/server_test.go, cli/server/testdata/protocol.testnet.windows.yml
Failing test caused by hardcoded relative path check which is different for Windows.
Close #3305
=> config: fix TestGetConfigFromContext on Windows

cli/smartcontract/smart_contract.go, go.mod
It is necessary to update dependencies in the test for go1.18 and above to match with the interop module.
Close #3152
=> smartcontract: fix go version mismatch in TestContractInitAndCompile

.github/workflows/build.yml, .github/workflows/tests.yml
I'm tired of warnings for our workflow runs.
The only unupdated is Codecov, we can't switch to token-based uploads at the moment (and it's required for new version).
=> workflows: update actions

cli/vm/cli_test.go
t.TempDir calls t.Cleanup while the levelDB file is still open.
Close #3154
=> vm: fix exit in vm tests

pkg/rpcclient/doc_test.go
This one doesn't really work now, it's Legacy. Replace with something N3-ish.
Thanks @lock9 for reporting.
=> rpcclient: fix address used in doc

.github/workflows/tests.yml
For linter job only, port
https://github.com/nspcc-dev/neofs-contract/pull/389/commits/e0ec4d24cb992232935a17b59c09927cbc842444.
=> .github: use minimum required Go version from go.mod

cli/server/server.go, internal/testcli/executor.go, pkg/consensus/consensus.go, pkg/core/blockchain.go, pkg/network/server.go, pkg/network/server_test.go, pkg/services/metrics/metrics.go, pkg/services/notary/notary.go, pkg/services/oracle/oracle.go, pkg/services/rpcsrv/server.go, pkg/services/rpcsrv/subscription_test.go, pkg/services/stateroot/validators.go
The problem is writing to logs after the end of the test execution.
Added sync logs for every service separately to provide the ability to have a custom logger for each service. 
Data race is caused by missing synchronization channels in the network server. Shutdown doesn't wait for all goroutines to finish properly.
Close #2973
Close #2974
Close #3112
=> services: fix logging data race after shutdown

pkg/services/rpcsrv/params/param.go, pkg/services/rpcsrv/params/param_test.go, pkg/services/rpcsrv/params/txBuilder.go, pkg/services/rpcsrv/params/tx_builder_test.go
We have smartcontract.ParameterPair structure that can be properly marshalled and passed to RPC server as an element of smartcontract.Map structure. However, RPC server can't unmarshal map values properly without this change.
This change is compatible with C# node.
=> rpcsrv: support Map parameter in `invokefunction` RPC handler

go.mod, go.sum
Fetch C# node compatibility fixes for the rest of corner cases. Ref. https://github.com/nspcc-dev/go-ordered-json/pull/11.
=> go.mod: upgrade go-ordered-json

pkg/services/notary/core_test.go
The theory is:
* we add a block
* it triggers notary
* which can process the fallback before we're to setFinalizeWithError
* it'll fail and require an additional block to enter, but it's never added
* FAIL
The solution is:
* always add an additional block, but treat the first fb specially
=> notary: fix "Condition never satisfied" in Notary test, fix #2422

.github/workflows/tests.yml
See https://github.com/golang/go/issues/65653, the fix can be postponed up to Go 1.23 and we need green.
=> workflows: workaround Go 1.22 coverage problem

pkg/rpcclient/wsclient_test.go, pkg/services/rpcsrv/client_test.go, pkg/services/rpcsrv/server_helper_test.go, pkg/services/rpcsrv/server_test.go, pkg/services/rpcsrv/subscription_test.go
=> rpcsrv: fix TestFailedPreconditionShutdown shutdown

.github/workflows/tests.yml
We have more and more timeouts happening for test runs, so 10m is not enough for busy GH machines sometime. I think we can just give them a bit more time.
Refs. #2379 though.
=> workflows: give tests more time

pkg/services/rpcsrv/client_test.go
=> rpcsrv: fix concurrent test TestClient_IteratorSessions

pkg/services/rpcsrv/server_test.go
This doesn't fix anything, but why not (at least let's see how it behaves on GH).
Just FYI, I've also tried
```patch
--- a/pkg/services/rpcsrv/server_test.go
+++ b/pkg/services/rpcsrv/server_test.go
@@ -2223,7 +2223,16 @@ var rpcTestCases = map[string][]rpcTestCase{
func TestRPC(t *testing.T) {
t.Run("http", func(t *testing.T) {
-               testRPCProtocol(t, doRPCCallOverHTTP)
+               cl := http.Client{Timeout: time.Second}
+               testRPCProtocol(t, func(rpcCall string, url string, t *testing.T) []byte {
+                       resp, err := cl.Post(url, "application/json", strings.NewReader(rpcCall))
+                       require.NoErrorf(t, err, "could not make a POST request")
+                       body, err := gio.ReadAll(resp.Body)
+ …
```
=> rpcsrv: close idle client connections in doRPCCallOverHTTP

pkg/services/rpcsrv/client_test.go
This commit doesn't fix anything, but clients should be closed, it's just a good practice.
Ref. https://github.com/nspcc-dev/neo-go/pull/3350#issuecomment-1996766890.
=> rpcsrv: properly close RPC clients in tests

pkg/core/native/native_neo.go, pkg/core/native/native_test/neo_test.go
Port neo-project/neo#3173.
Close #3345
=> native: clear LastGasPerVote when voting for NULL

pkg/services/rpcsrv/server.go, pkg/services/rpcsrv/server_test.go
Implementation doesn't match https://github.com/neo-project/proposals/pull/156 wrt mempool-related transaction fee check on submitting new transaction to the node. Thanks to @carpawell for pointing that out.
Fix the implementation.
@roman-khimov, I'd like to highlight: whereas it's quite easy to fix this compatibility problem on our side, C# node has the same divergence from the standard and requires more changes to fix it: `TransactionVerificationContext.CheckTransaction` should be adjusted to return some new special error, this error should be detached from `VerifyResult.InsufficientFunds` and ported to other components (ref. https://github.com/neo-project/neo/blob/b05501af882a0d1f2a1a7841c6ddc4d0504e5fc1/src/Neo/Network/P2P/Payloads/Transaction.cs#L368).
I may port it to C# or create …
=> rpcsrv: fix RPC error codes proposal compatibility

pkg/services/rpcsrv/server.go, pkg/services/rpcsrv/server_test.go
This is not the way intended in https://github.com/neo-project/proposals/pull/156. -511 covers _both_ cases because users hardly can distinguish one from another, it's just that our mempool implementation has error codes for both..
Refs. https://github.com/nspcc-dev/neo-go/pull/3360.
=> rpcsrv: fix insufficient funds use

pkg/core/native/native_test/notary_test.go, pkg/core/native/notary.go
If we're withdrawing funds to contract that has onNEP17Payment method, then it may call Notary's withdraw one more time, but the account's state is not yet updated by this moment.
The problem is similar to https://github.com/neo-project/neo/pull/2734.
@roman-khimov, if I'm not mistaken and the problem exists, then you'll be glad to see this fix. I'll create test for it.
=> core: prohibit reentry to Notary withdraw

pkg/rpcclient/unwrap/unwrap.go, pkg/rpcclient/unwrap/unwrap_test.go
Consider this test.
```golang
func TestItem(t *testing.T) {
bigSlice := stackitem.NewByteArray(make([]byte, stackitem.MaxSize/2))
arr := stackitem.NewArray([]stackitem.Item{bigSlice, bigSlice})
res := &result.Invoke{
State:          "HALT",
GasConsumed:    237626000,
Script:         []byte{10},
Stack:          []stackitem.Item{arr},
FaultException: "",
Notifications:  []state.NotificationEvent{},
}
data, err := json.Marshal(res)
require.NoError(t, err)
var received result.Invoke
require.NoError(t, json.Unmarshal(data, &received))
_, err = Item(&received, nil)
require.True(t, len(received.FaultException) != 0)
require.Contains(t, err.Error(), received.FaultException)
}
```
It fails with
```
--- FAIL: TestItem (0.00s)
/repo/neo-go/pkg/rpcclient/unwrap/unwrap_test.go:204: 
Error Trace: …
```
=> rpcclient: return FaultException in checkResOk if any

pkg/core/native/native_neo.go, pkg/core/native/native_test/neo_test.go, pkg/core/native/neo_types.go, pkg/rpcclient/neo/neo.go, pkg/services/rpcsrv/server_test.go
Port neo-project/neo#3158.
Close #3326
=> native: add committee change events

pkg/network/server_test.go
An additional goroutine was added in TestServerNotSendsVerack in f8dc5ec44f5ed855ed78c82fe03479eb2da22c19 so it can be the cause of race.
Close #3316
=> network: fix logging data race in the package

pkg/services/rpcsrv/server_test.go, pkg/services/rpcsrv/subscription_test.go
During the empirical selection of parameters got https://github.com/nspcc-dev/neo-go/issues/3367 so seems rpc test package is still big and therefore slow for gh windows runner. But with setup in this commit haven't got test timeout yet.
Close #2975.
Close #3314.
=> rpcsrv: fix TestRPC failing

pkg/core/interop/crypto/ecdsa.go, pkg/vm/stack.go
Might be helpful for users, no functional changes.
=> *: improve error text for System.Crypto.CheckMultisig handling

go.mod, go.sum, pkg/consensus/block.go, pkg/consensus/block_test.go, pkg/consensus/cache_test.go, pkg/consensus/change_view.go, pkg/consensus/change_view_test.go, pkg/consensus/commit.go, pkg/consensus/commit_test.go, pkg/consensus/consensus.go, pkg/consensus/consensus_test.go, pkg/consensus/crypto.go, pkg/consensus/payload.go, pkg/consensus/payload_test.go, pkg/consensus/prepare_request.go, pkg/consensus/prepare_request_test.go, pkg/consensus/prepare_response.go, pkg/consensus/prepare_response_test.go, pkg/consensus/recovery_message.go, pkg/consensus/recovery_message_test.go, pkg/consensus/recovery_request.go, pkg/consensus/recovery_request_test.go, pkg/core/block/header.go
Try out unreleased version to see how the integration is going.
=> consensus: integrate dBFT pre-0.2.0

docs/node-configuration.md
Add a note about elements order.
=> docs: adjust StandByCommittee node config documentation

pkg/services/rpcsrv/client_test.go
=> rpcsrv: fix TestSubClientWaitWithMissedEvent

.github/workflows/tests.yml
Warning: CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
=> workflows: update CodeQL version

pkg/services/rpcsrv/server_test.go
Increase timeout to prevent `context deadline exceeded (Client.Timeout exceeded while awaiting headers)`.
Close #2975
=> rpc: fix TestRPC timeout

pkg/services/notary/core_test.go
Close #3366. Roll back the test structure to the one that it has before d2a7162217e2c429600ff583690caeebc07e28a2. Add one extra block to ensure that main transaction won't be finilized. Add NVB increment slippage to avoid race between the first fallback acceptance and block acceptance.
=> services: fix race in TestNotary

cli/util/cancel.go, cli/util/util_test.go, internal/testcli/executor.go
Always return "Target transaction accepted" if the target transation was either accepted by the moment of command run or during the command handling. Exit with code 0 in both cases. Adjust TestAwaitUtilCancelTx correspondingly, allow both cases in test. Simplify the test along the way, remove useless code.
Close #3365.
=> cli: unify `canceltx` command output

pkg/rpcclient/notary/actor.go, pkg/rpcclient/notary/doc_test.go
This commit allows to override only MainModifier omitting overriding MainCheckerModifier.
@smallhive, welcome to review.
=> rpcclient: make default Notary actor options customizable

pkg/services/notary/core_test.go
1. Allow 1-block slippage for multisignature request block generation to ensure that PostPersist for fb's NVB-th block is properly finished.
2. Allow 1-block slippage before sent request checks to ensure that PostPersist for NVB fb's NVB-th block was finished and all stale mains were properly marked by Notary service.
Overall, this commits ports the approach of #3390 to the whole test.
Close #3366.
=> services: allow some slippage in TestNotary

pkg/services/rpcsrv/client_test.go
Close #2956. The failure reason is similar to the one described in #3396 for TestNotary: Blockchain's notificationDispatcher is listening to block events from storeBlock via separate channel. By the moment single block addition is finished, notification may or may not be properly handled by notificationDispatcher, especially given the fact that our runners are slow. As a result, assert.Eventually with 1-second awaiting period may fail. This issue is solved by adding one more block, because the second AddBlock finishes only when it sends block addition event to notificationDispatcher loop, which means that the previous event was handled.
=> rpcsrv: allow one-block slippage in TestWSClient_SubscriptionsCompat

pkg/services/rpcsrv/subscription_test.go
Do not wait until wsReader routine gracefully finishes its work before WS connection close. Instead, firstly close the connection, and after that wait for proper wsReader exit.
It's a harsh way, but I don't have any other options to try, because wsReader routine hangs on `ws.ReadMessage()` operation for more than ReadDeadline (more than 5 seconds) during test cleanup which results in the test timeout.
Close #3378.
=> rpcsrv: enforce WS connection close on test cleanup

pkg/network/server_test.go
We don't have a reliable way to know when transports are started since their start is being performed in a separate goroutine:
https://github.com/nspcc-dev/neo-go/blob/927dbb6dc48d578ae731e5a067c82d0611642338/pkg/network/server.go#L297-L299
And transports start is not connected with main server routine, thus, just wait for some time for the transports goroutine to be started.
Also wait for the peer to be properly registered.
Close #3399.
=> network: take care of TestServerStartAndShutdown

cli/wallet/wallet.go
```
./bin/neo-go wallet import --wif qweqweqweqwe -w wallet1.json
failed to read wallet: open wallet: open wallet.json: no such file or directory
touch wallet.json
./bin/neo-go wallet import --wif qweqweqweqwe -w wallet.json
failed to read wallet: unmarshal wallet: EOF
```
@532910 is it a more understandable error?
Close #3134
=> cli: improve wallet read related errors

pkg/core/native/policy.go
Close #3311
Perhaps we should consider modifying the error message further.
=> native: adjust error message for ExecFeeFactor and StoragePrice

.github/workflows/tests.yml
=> workflows: update CodeCov action, use token for upload

cli/smartcontract/smart_contract.go, cli/util/convert.go
Always put blank line in the end of the command description.
=> cli: unify commands description

cli/cmdargs/parser_test.go, cli/query/query.go, cli/smartcontract/permission.go, cli/smartcontract/smart_contract_test.go, cli/wallet/candidate_test.go, cli/wallet/multisig_test.go, cli/wallet/wallet_test.go, internal/basicchain/basic.go, pkg/config/protocol_config_test.go, pkg/crypto/keys/publickey.go, pkg/crypto/keys/publickey_test.go, pkg/neotest/chain/chain.go, pkg/services/oracle/response.go, pkg/smartcontract/context/context_test.go, pkg/smartcontract/context/item.go, pkg/smartcontract/context/item_test.go, pkg/smartcontract/manifest/group.go, pkg/smartcontract/manifest/permission.go, pkg/wallet/account_test.go
=> crypto: add StringCompressed() for PublicKey

pkg/smartcontract/context/item_test.go
Ensure that ParameterContext's Item with nil script can be properly marshalled. Ref. https://github.com/neo-project/neo/pull/3198.
=> smartcontract: ensure nil ParameterContext Item's script is marshallable

.github/workflows/tests.yml
Ref. https://github.com/golangci/golangci-lint-action/issues/135. Otherwies we've got a set of errors on attempt to setup linter:
```
Run golangci/golangci-lint-action@v4
with:
version: latest
github-token: ***
only-new-issues: false
skip-cache: false
skip-pkg-cache: false
skip-build-cache: false
install-mode: binary
prepare environment
Checking for go.mod: go.mod
Received 125829120 of 781115092 (16.1%), 119.8 MBs/sec
Received 331350016 of 781115092 (42.4%), 157.8 MBs/sec
Received 541065216 of 781115092 (69.3%), 171.9 MBs/sec
Received 738197504 of 781115092 (94.5%), 175.8 MBs/sec
Cache Size: ~745 MB (781115092 B)
/usr/bin/tar -xf /home/runner/work/_temp/6de9500e-163b-4dda-a82b-d6b2ee7b1625/cache.tzst -P -C /home/runner/work/neo-go/neo-go --use-compress-program unzstd
Received 781115092 of …
```
=> workflows: disable cache for golangci-lint

pkg/core/transaction/attribute.go, pkg/core/transaction/attribute_test.go, pkg/core/transaction/conflicts.go, pkg/core/transaction/not_valid_before.go, pkg/core/transaction/notary_assisted.go, pkg/core/transaction/oracle.go, pkg/core/transaction/reserved.go, pkg/core/transaction/signer.go, pkg/core/transaction/signer_test.go, pkg/core/transaction/transaction.go, pkg/core/transaction/transaction_test.go, pkg/core/transaction/witness.go, pkg/core/transaction/witness_condition.go, pkg/core/transaction/witness_condition_test.go, pkg/core/transaction/witness_rule.go, pkg/core/transaction/witness_rule_test.go, pkg/core/transaction/witness_test.go, pkg/crypto/keys/publickey.go, pkg/crypto/keys/publickey_test.go, pkg/network/payload/notary_request.go, pkg/network/payload/notary_request_test.go, pkg/services/notary/notary.go
=> *: add Copy() to transaction.Transaction and payload.P2PNotaryRequest

examples/zkp/cubic_circuit/go.mod, examples/zkp/cubic_circuit/go.sum
This reverts commit 874ed1ac2e38da24c1a4b1559ff8050ca8e2bc6f. We can't allow this gnark update since minimum required Go version for NeoGo and all examples is 1.20. It will be done as a part of #3089.
=> Revert "build(deps): bump github.com/consensys/gnark"

pkg/core/blockchain.go, pkg/core/blockchain_neotest_test.go, pkg/core/dao/dao.go, pkg/core/dao/dao_test.go, pkg/core/transaction/transaction.go
Close #3426, close #3427.
A possible solution (the best from my POW) is implemented. The part with verification of such conflicting transactions may be discussed since I'm not quite sure it's a good solution to allow to pass verification for these transactions. We may forbid them since we have `VerifyTransactions` set to `false` in mainnet anyway.
@roman-khimov, the only question I have right now is: why our CN has successfully accepted PrepareRequest, verified the block and responded with PrepareReqponse. The node shouldn't ever accept this transaction to the mempool since `verifyTxAttributes` call should fail without e6ceee0f230a21c87006a9297636be29c0d8ea47 implemented.
=> core: take care of block-targeted Conflicts attributes processing

internal/fakechain/fakechain.go, pkg/core/blockchain.go, pkg/core/state/contract.go, pkg/rpcclient/rpc.go, pkg/services/rpcsrv/server.go, pkg/services/rpcsrv/server_test.go
This is somewhat deeper than its C# counterpart, but the essence is the same, we return proper []state.Contract from getnativecontracts RPC and thus many of older types are no longer needed. Some hacks around UpdateCounter are removed as well.
The change can potentially affect third-party apps, but should be easy to adopt.
UPD: simplified.
=> state: drop NativeContract, fix #3430

pkg/rpcclient/unwrap/unwrap.go, pkg/rpcclient/unwrap/unwrap_test.go
Fix #3130. "Exception" is used for name since it's shorter and that's the name used in JSON. "VMFault" was also considered as well as "FaultException" (which mirrors result.Invoke).
=> unwrap: implement Exception type for better exception handling

pkg/core/blockchain_neotest_test.go, pkg/core/native/native_test/neo_test.go, pkg/core/native/policy.go
Account is blocked when it's in the Policy's storage, not when it's missing from the storage. Introduced in bbbc6805a8261bca51428ae9e96340fc62704b61.
This bug leads to the fact that during native Neo cache initialization at the last block in the dBFT epoch, all candidates accounts are "blocked", and thus, stand-by committee and validators are used in the subsequent new epoch. Close #3424.
This bug may lead to the consequences described in #3273, but it needs to be confirmed. @fyfyrchik, is it possible for your network to check whether "faulty" node has been restarted in the last block of some dBFT epoch? And then check what the receivers of block rewards in the next dBFT epoch are stand-by validators/committee. If so, then the problem is the same, since this bug leads to the wrong block …
=> native: fix Policy's IsBlocked behaviour

config/protocol.mainnet.neofs.yml, config/protocol.mainnet.yml, config/protocol.testnet.yml
=> config: enable Cockatrice hardfork

pkg/core/native/management.go
=> native: perform initialisation for the set of hardforks

go.mod, go.sum
Was accidentally added in
https://github.com/nspcc-dev/neo-go/pull/3452/commits/aa5a0cb49bc3d768ad8e9f31d16ac5912957853d.
=> go.mod: remove unused dependency

.github/workflows/tests.yml
Avoid situations like #3458. Checked by https://github.com/nspcc-dev/neo-go/actions/runs/9228208591/job/25391785174.
=> workflows: protect go.mod from unexpected imports

cli/vm/cli.go, pkg/core/blockchain.go, pkg/core/interop/contract/call.go, pkg/core/interop/runtime/engine.go, pkg/core/interop/runtime/ext_test.go, pkg/vm/context.go, pkg/vm/debug_test.go, pkg/vm/vm.go
Do not use the updated contract state from native Management to perform permissions checks. We need to use the currently executing state instead got from the currently executing VM context until context is unloaded.
Close #3471.
Mainnet check is in progress.
=> interop: use executing contract state for permissions checks

cli/options/options.go
=> logs: hide timestamp if the program is run not in TTY

pkg/core/blockchain.go, pkg/services/oracle/request.go
=> Adjust minor SAST warnings

pkg/network/server.go
Peer disconnections are not warnings.
Close #3182
some errors that can be in the `peer disconnected` message:
```
err = msg.Decode(r)
errors.New("invalid payload size")
br.ReadBytes(m.compressedPayload)
fmt.Errorf("bind address for connection '%s' is not registered", localAddr.String())
errors.New("invalid handshake: already sent Version")
_, err = p.conn.Write(b) 
fmt.Errorf("handling %s message: %w", msg.Command.String(), err)
err = p.conn.SetWriteDeadline(time.Now().Add(writeTimeout))
s.requestBlocks(bq, p)
b, err := msg.Bytes()
errGone           = errors.New("the peer is gone already")
errStateMismatch  = errors.New("tried to send protocol message before handshake completed")
errPingPong       = errors.New("ping/pong timeout")
errUnexpectedPong = errors.New("pong message wasn't …
```
=> logs: distinguish WARN and INFO for `peer disconnected`

pkg/core/blockchain_neotest_test.go, pkg/vm/stackitem/item.go, pkg/vm/vm.go
This test ensures that NeoGo node doesn't have the DeepCopy problem described in https://github.com/neo-project/neo/issues/3300 and fixed in https://github.com/neo-project/neo/pull/3301. This problem leads to the fact that Notifications items are not being properly refcounted by C# node which leads to possibility to build an enormously large object on stack. Go node doesn't have this problem.
The reason (at least, as I understand it) is in the fact that C# node performs objects refcounting inside the DeepCopy even if the object itself is not yet on stack. I.e. System.Runtime.Notify handler immediately adds references to the notification argumetns inside DeepCopy:
https://github.com/neo-project/neo/blob/b1d27f0189861167b8005a7e40e6d8500fb48cc4/src/Neo.VM/Types/Array.cs#L108 …
=> Ensure System.Runtime.GetNotifications can't break MaxStackSize constraint

pkg/rpcclient/actor/actor.go, pkg/rpcclient/actor/actor_test.go, pkg/rpcclient/notary/actor.go, pkg/rpcclient/notary/actor_test.go
Most of the time people are interested in successful executions. Unfortunately, unwrap package can't help here because of a different result structure (some interface abstract can help, but it's still mostly stack-oriented and sessions can be a problem), so this additional interface is needed.
=> actor: add a new WaitSuccess API

pkg/rpcclient/actor/actor.go, pkg/rpcclient/actor/actor_test.go, pkg/rpcclient/invoker/invoker.go, pkg/rpcclient/invoker/invoker_test.go
Signers are very important for notary checks and keeping/passing an additional copy of them is very inconvenient. Exposing them from invoker makes them available in actors too.
=> invoker: add Signers() API

docs/rpc.md, pkg/neorpc/result/peers.go, pkg/neorpc/result/peers_test.go, pkg/network/peer.go, pkg/network/server.go, pkg/rpcclient/rpc_test.go
Close #3480
I have `OldPeerHeight` because I followed `peers.go` as an example, but I expect it may be pointless here. Please remove if so.
=> Extend getpeers RPC method to provide useragent and last known height

cli/options/options.go, config/config_embed.go, pkg/config/config.go, pkg/config/config_test.go
If `config-path` is not provided then the default config is used. If  `config-path` is provided but the directory does not contain a configuration file for the desired passed network and this directory isn't our default `./config`, the error "config '%s' doesn't exist" will be received.
Close #3450.
Close #3459.
=> cli: add embedded node config

pkg/vm/vm.go, pkg/vm/vm_test.go
This MR implements the proposed Hooks API from #3415 that can be used for coverage collection, tracing, breakpoints, and etc
This is a very small change. The main points are as follows:
1. A new field is added to the VM
```
+	// All registered hooks.
+	// Each hook should never be nil.
+	hooks hooks
```
2. `hooks` is a structure meant to store all of the VM hooks:
```
// OnExecHook is a type for a callback that is invoked
// for each executed instruction
type OnExecHook = func(scriptHash util.Uint160, offset int, opcode opcode.Opcode)
// A struct that contains all VM hooks
type hooks struct {
onExec OnExecHook
}
```
3. The default value of the OnExec hooks is a NOP function
4. A `VM.SetOnExecHook` method is added to register hooks
```
// SetOnExecHook sets the value of OnExecHook which
// …
```
=> Implement OnExecHook VM API

pkg/network/payload/mptdata_test.go
The following [coverage report](https://app.codecov.io/gh/nspcc-dev/neo-go/commit/f5794e91a224f403223f73cd46cf4a9152d70963/blob/pkg/network/payload/mptdata.go) indicates that the following branch is not covered by tests:
```
// mptdata.go
31:		if r.Err != nil {
32:			return  // <--- this line
33:		}
34:	}
``` 
This PR adds a single test that covers this branch.
This line is reached when there is an error parsing a single row in the array `Nodes: [][]byte`. An error occurs when the line length exceeds the maximum array size.
=> Add a missing `mptdata` test

pkg/config/config.go
This code was accidentally removed by
https://github.com/nspcc-dev/neo-go/pull/3477, it's important to have these fields set by default.
=> config: get back default node configuration values

pkg/core/interop/context.go, pkg/core/interop/runtime/util.go, pkg/util/uint160.go, pkg/util/uint256.go
https://github.com/nspcc-dev/neo-go/blob/5566e354d451fd14d3b2a856cfe4b1b654a7343e/pkg/core/blockchain.go#L1185-L1186 also looks like a candidate, but (un)fortunately the slice len is not checked, so the conversion cannot be used
=> *: Convert slices to arrays instead of `copy` where possible

pkg/core/blockchain.go, pkg/services/rpcsrv/server.go
It's needed to give user a hint about what's wrong with the witness during `calculatenetworkfee` RPC request processing.
=> rpcsrv: improve witness verification error

pkg/core/chaindump/dump.go
=> chaindump: microoptimize memory management

config/protocol.mainnet.neofs.yml, config/protocol.testnet.neofs.yml
We want to cut the tail more aggressively, what matters is state, but not old blocks and transactions that contracts don't use in any way. #3493 suggests that it's safe to limit the tail to one day, but let's be a bit more conservative for now.
As a sidenote, EVM only allows to fetch things from the recent 256 blocks.
=> config: drop MTB value for NeoFS networks to three days

pkg/rpcclient/wsclient.go
Every client's (Un)Subscription call does two things: an RPC call and a subscription map lock (two of maps currently). If we imagine that there is one routine that tries to subscribe (A) and one routine that tries to unsubscribe (B), the following sequence can happen:
0. Current number of subscriptions is X
1. B does an RPC and makes number of subscriptions X-1
2. A does an RPC and makes number of subscriptions X again
3. A holds subscription locks and rewrites client's subscription state (subscription with ID X now points to a different channel; channel that was registered by B is lost and is not related to any real subscription but is still included in the `receivers` map)
4. B holds subscription locks and drops subscription X (first, it is an error and we have just lost a subscription …
=> rpcclient/WS: fix data race on concurrent (un)subscription

docs/compiler.md, docs/node-configuration.md
Fix some of the old bugs related to this.
=> Documentation improvements

pkg/rpcclient/wsclient.go
`makeWsRequest` creates a channel for response and waits for it. If between creating the channel and starting the reading `select` connection is lost (`writerDone` channel is closed), nothing reads from the channel and a deadlock appears. Looking at "done" channels when transferring RPC data solves the issue. Closes #3530.
=> rpcclient/WS: do not deadlock on connection loss

docs/node-configuration.md
It's dangerous to change `Max*` ProtocolConfiguration settings:
* Changes in MaxBlockSize, MaxBlockSystemFee and MaxTransactionsPerBlock may lead to the fact that accepted block or transaction becomes invalid. I agree that these settings are not written in the DB, but at the same time it's not correct to compare databases that have these settings mismatched.
* Changes in MaxTraceableBlocks may lead to the fact that some transaction will be processed differently, it's a possible contract state mismatch.
* Changes in MaxValidUntilBlockIncrement may lead to the fact that `setMaxNotValidBeforeDelta` method of native Notary contract may be processed in a different way which is also a possible contract state mismatch.
Ref. 5d29a3fdabb5f643b843e874fd8ffd8872ad01aa.
=> docs: adjust DB compatibility notes

pkg/core/mempool/mem_pool.go, pkg/core/mempool/mem_pool_test.go, pkg/core/mempool/subscriptions_test.go
Fixed pretty much accidentally.
=> Fix mempool fees

pkg/smartcontract/manifest/container.go, pkg/smartcontract/manifest/container_test.go
Starting from b10af1ed313283e081199a24cbda5ae5c99427b0 (*WildPermissionDescs).Add method's call is not enough to construct a proper restricted permission descriptor, because Wildcard field should be set properly at the same time. Ref. #3523.
There's nothing critical in the current implementation, but at the same time this PR allows to avoid possible future bug.
=> smartcontrct: take care of manifest permission descriptor wildcardness

.docker/docker-compose.yml, Makefile, docs/consensus.md
Docker Compose V1 is deprecated since June 2023, ref. https://docs.docker.com/compose/migrate/ and
https://github.com/nspcc-dev/neo-bench/issues/166.
=> *: migrate to Docker Compose V2

pkg/core/native/management_neotest_test.go, pkg/core/native/native_test/cryptolib_verification_test.go, pkg/core/native/native_test/ledger_test.go, pkg/neotest/basic.go
1. Bind `neotest.AddSystemFee` and `neotest.TestInvoke` to `Executor` state.
2. Calculate system fee for deployment transactions.
Reasons are explained in the commit messages. @roman-khimov, these commits made in a breaking way, but if we care about our users a lot, then I can mark related methods as "deprecated" and introduce new `Executor` methods in a soft way. Do we?
A ground for #3462.
=> Improve neotest to serve coverage needs

internal/random/random_util.go, pkg/core/blockchain.go, pkg/core/interop/iterator/interop.go, pkg/core/mpt/trie.go, pkg/core/native/management.go, pkg/core/native/native_neo.go, pkg/core/native/native_test/common_test.go, pkg/core/stateroot/module.go, pkg/rpcclient/unwrap/unwrap.go, pkg/services/rpcsrv/client_test.go
Linter is updated up to v1.60.1, the following issue is fixed:
```
predeclared  variable max has same name as predeclared identifier
```
=> *: fix linter issues

pkg/rpcclient/actor/actor.go, pkg/rpcclient/waiter/waiter.go, pkg/services/rpcsrv/client_test.go
Networks with short block time can't use `1s` as a default poll interval, it's too harsh for them. Ref. https://github.com/nspcc-dev/neofs-node/issues/2864.
=> Make PollingBased waiter more flexible

.github/workflows/tests.yml, Makefile, pkg/neotest/basic.go, pkg/neotest/client.go, pkg/neotest/compile.go, pkg/neotest/coverage.go, pkg/neotest/doc.go
~~Requires #3460~~
Neotest doesn't provide coverage collection support when running contract tests
Executed opcodes collected by using `OnExecHook` for each script.
Then, using `DebugSeqPoints`, coverage for source file is evaluated and saved in file after each test.
Current implementation has some quirks with it:
- File is written during each test cleanup, which can be heavy / slow down test execution significantly
- In order to save coverage, `coverProfile` flag is reset, so go tooling doesn't overwrite coverage file. This can be a problem when running both contract and non-contract tests in the same project.
- Scripts from dependencies are added to coverage file too, which is overkill.
- Only `set` mode is supported.
=> Add initial coverage support to neotest

.golangci.yml, internal/testchain/address.go, pkg/core/blockchain_core_test.go, pkg/core/mpt/helpers.go, pkg/core/native/native_test/neo_test.go, pkg/vm/vm.go
It checks that go 1.22's range-over-numbers feature is not skipped. Also, fix some warnings it found.
=> .golangci.yml: add `intrange` linter

pkg/smartcontract/parameter.go, pkg/smartcontract/parameter_test.go
Contracts with `methods(some []string)` generate RPC bindings with `[]string` parameters. But these bindings are unusable by default because we can't convert `[]string` to parameters.
Extend accepted type list.
=> Extend accepted parameters

cli/server/dump_bin.go, cli/server/dump_bin_test.go, cli/server/server.go, config/protocol.testnet.yml, docs/neofs-blockstorage.md, docs/node-configuration.md, go.mod, pkg/config/application_config.go, pkg/config/application_config_test.go, pkg/config/blockfetcher_config.go, pkg/config/config.go, pkg/network/bqueue/queue.go, pkg/network/bqueue/queue_test.go, pkg/network/server.go, pkg/network/server_config.go, pkg/services/blockfetcher/blockfetcher.go, pkg/services/blockfetcher/blockfetcher_test.go, pkg/services/oracle/neofs/neofs.go
=> services: add new block fetching from NeoFS service

docs/vm.md
=> docs: update vm loadhex example

pkg/core/native/native_neo.go, pkg/core/native/native_test/neo_test.go
Fix difference with C#:
```
(base) ekaterinapavlova@MacBook-Air-4 neo-go % curl -X POST
http://seed1t5.neo.org:20332 -H 'Content-Type: application/json' -d '{
"jsonrpc": "2.0",
"method": "getapplicationlog",
"params":
["61681ce24dffea5481e9a50b10159b43b7ebfc21967b0b06fee7ff69c7123e3f"],
"id": 1
}' | json_pp
% Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
Dload  Upload   Total   Spent    Left
Speed
100   429    0   269  100   160    582    346 --:--:-- --:--:-- --:--:--
930
{
"id" : 1,
"jsonrpc" : "2.0",
"result" : {
"executions" : [
{
"exception" : null,
"gasconsumed" : "198754",
"notifications" : [],
"stack" : [
{
"type" : "Integer",
"value" : "0"
}
],
"trigger" : "Application",
"vmstate" : "HALT"
}
],
"txid" : …
```
=> vm: fix unclaimedGas calculation

pkg/compiler/syscall_test.go, pkg/vm/vm.go, pkg/vm/vm_test.go
Resolves #3598
Use `Rem` operation instead of `Mod`, same as in `MOD` opcode
=> vm: fix modmul operation

pkg/neotest/coverage.go
Users are allowed to provide any contract to neotest, including those contracts that don't have DebugInfo filled in. Neotest should filter them out, otherwise panic may occur on attempt to write coverage profile:
```
--- FAIL: TestDeploys (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc6f5b5]
goroutine 1735 [running]:
testing.tRunner.func1.2({0xd7aa80, 0x1723f60})
/usr/local/go/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1634 +0x377
panic({0xd7aa80?, 0x1723f60?}) …
```
=> neotest: don't collect coverage for contracts with empty DI

cli/util/uploader.go
=> cli: adjust error of `upload-bin` command

cli/util/uploader.go
=> cli: increase NeoFS pool deadlines for upload-bin command

cli/util/uploader.go
=> cli: fix empty block uploading in `util upload-bin`

pkg/services/blockfetcher/blockfetcher.go
=> blockfetcher: add more details to errors

cli/util/uploader.go, cli/util/util_test.go, config/protocol.testnet.yml, docs/neofs-blockstorage.md
=> BlockFetcher/BlockUploader: fix and add additional attributes

cli/util/convert.go, cli/util/uploader.go, docs/neofs-blockstorage.md
=> cli: add flag workers to `upload-bin` command

pkg/vm/stackitem/json_test.go
Inspired by https://github.com/neo-project/neo/pull/3558, although this PR fixes different implementation of stackitem serializatior that is used outside of VM.
=> stackitem: extend ToJSON test

pkg/compiler/syscall_test.go, pkg/vm/vm.go, pkg/vm/vm_test.go
=> vm: fix MODPOW operation

cli/util/convert.go, cli/util/uploader.go, docs/neofs-blockstorage.md
Close #3647
check empty oids in progress
=> cli: add retries if search results are not expected length in `upload-bin`

.github/workflows/build.yml, .github/workflows/tests.yml
Support for macos-12 will be deprecated 10/7/24 and the image will be fully unsupported by 12/3/24. Ref.
https://github.com/actions/runner-images/issues/10721.
Get rid of the build warning:
```
A brownout will take place on November 4, 14:00 UTC - November 5, 00:00
UTC to raise awareness of the upcoming macOS-12 environment removal.
```
=> workflows: remove macos-12 support

cli/nep_test/nep17_test.go, cli/wallet/nep11.go, cli/wallet/nep17.go
Checking the balance should be easy without any wallets involved, the data is available anyway.
Adding the command to "query nep1X" is not so trivial, so let's have it this way for now.
=> cli: make nep1X balance commands work without a wallet, fix #3275

cli/server/server.go, internal/testcli/executor.go, pkg/services/rpcsrv/server.go, pkg/services/rpcsrv/server_helper_test.go
Before, a new server was returned by value which could cause a panic `unlock of unlocked mutex` on SIGHUP handling. It's because the new server overwrites a locked mutex of the already existing server.
```
oct‚ 22 13:51:15 node1 neo-go[1183338]: fatal error: sync: Unlock of unlocked RWMutex oct‚ 22 13:51:15 node1 neo-go[1183338]: goroutine 538 [running]: oct‚ 22 13:51:15 node1 neo-go[1183338]: sync.fatal({0xf83d64?, 0xc001085880?})
oct‚ 22 13:51:15 node1 neo-go[1183338]:         runtime/panic.go:1007 +0x18
oct‚ 22 13:51:15 node1 neo-go[1183338]: sync.(*RWMutex).Unlock(0xc00019a4c8)
oct‚ 22 13:51:15 node1 neo-go[1183338]:         sync/rwmutex.go:208 +0x45
oct‚ 22 13:51:15 node1 neo-go[1183338]: github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).dropSubscriber(0xc00019a2c8, …
```
=> services/rpcsrv: Return a new server by pointer

pkg/io/binaryBufWriter.go
=> io: specify Bytes() behavior a bit better for BufBinWriter

config/protocol.mainnet.neofs.yml, config/protocol.mainnet.yml, config/protocol.testnet.neofs.yml, config/protocol.testnet.yml
=> config: add NeoFSBlockFetcher section

pkg/services/rpcsrv/error.go, pkg/services/rpcsrv/server.go
=> rpcsrv: align default error code with C# implementation

cli/vm/cli.go, cli/vm/cli_test.go, pkg/vm/debug_test.go, pkg/vm/vm.go
https://github.com/nspcc-dev/neo-go/issues/3673
add function
=> vm: add RemoveBreakPoint support

ROADMAP.md, cli/vm/cli.go, pkg/vm/context.go, pkg/vm/json_test.go, pkg/vm/slot.go, pkg/vm/slot_test.go, pkg/vm/vm.go
as per https://github.com/nspcc-dev/neo-go/pull/3674#issuecomment-2473644389
=> vm: make slots public

cli/util/upload_bin.go
=> cli: fix fetchLatestMissingBlockIndex and uploadIndexFiles in `upload-bin` command

pkg/vm/ref_counter_test.go, pkg/vm/vm.go
We're popping an item (array) off the stack, OK, it triggers refs.Remove() for it. Then we're pushing an inner item to the stack, OK, it triggers refs.Add() for this element. Why are we removing it afterwards? Looks like something went wrong in 324107b31ee113a60d7739fee867e01beb30c298 (and https://github.com/nspcc-dev/neo-go/pull/1670) since a simple test shows zero counter after POPITEM and -1 after popping the only item left on the stack.
=> vm: fix incorrect refcounting in POPITEM

pkg/vm/stackitem/item.go, pkg/vm/stackitem/serialization_test.go, pkg/vm/vm.go, pkg/vm/vm_test.go
=> vm: fix packmap operation

pkg/core/blockchain_core_test.go, pkg/core/stateroot/module.go
=> core: fix restoring chain with `StateRootInHeader = true`

docs/notifications.md, pkg/neorpc/filters.go, pkg/neorpc/filters_test.go, pkg/neorpc/rpcevent/filter.go, pkg/neorpc/rpcevent/filter_test.go, pkg/rpcclient/wsclient_test.go, pkg/services/rpcsrv/client_test.go, pkg/services/rpcsrv/server_test.go, pkg/services/rpcsrv/subscription_test.go
=> ws: allow filtering notification by parameters

Dockerfile, Dockerfile.wsc
Fix the following Docker image build warning that stops privnet image build:
```
1 warning found (use docker --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 3)
```
=> Dockerfile: migrate to AS keyword usage

pkg/neotest/compile.go, pkg/neotest/compile_test.go
=> neotest: extend cached compiled contract identifier in CompileFile

config/protocol.mainnet.neofs.yml, config/protocol.mainnet.yml, config/protocol.testnet.neofs.yml, config/protocol.testnet.yml
Best and newest features have to be shown to our users!
=> config: enable NeoFSBlockFetcher by default

cli/server/metrics.go, cli/server/server.go, pkg/network/prometheus.go, pkg/network/server.go
=> *: move metric `neogo_version` out of pkg/network

config/protocol.testnet.neofs.yml
Otherwise all hardforks enabled by default from genesis which leads to errors like this if we introduce new hardfork:
```
Dec 04 02:46:46 titan1 neofs-node[157390]: warn        client/multi.go:43        could not establish connection to RPC node        {"endpoint": "wss://rpc.morph.t5.fs.neo.org/ws", "error": "WS client initialization: failed to get network magic: unexpected hardfork: Echidna"}
```
=> config: enable hardforks for default NeoFS testnet config

pkg/services/blockfetcher/blockfetcher.go
Dealing is fast, we don't need 10 minutes to check that connection can (or can't) be established. Improve documentation along the way.
Close #3721.
=> blockfetcher: decrease default pool deal timeout

pkg/network/server.go
Consider 10-node network. FanOut is 6 for it. optimalN is 12. But it's a 10-node network, you can't have more than 9 peers there. So adjust the formula for netSize-1.
=> network: optimize optimalN for small networks

pkg/services/blockfetcher/blockfetcher.go
=> services: fix defer function in `retry` of NeoFSBlockFetcher

pkg/services/rpcsrv/server.go
=> services: fix timer draining

docs/node-configuration.md, pkg/config/ledger_config.go, pkg/core/blockchain.go, pkg/core/blockchain_core_test.go, pkg/core/dao/dao.go, pkg/core/dao/dao_test.go, pkg/network/server.go
Keeping headers we no longer need.
Remove them along with blocks.
=> RemoveUntraceableHeaders

go.mod, pkg/services/blockfetcher/blockfetcher_test.go, pkg/services/helpers/neofs/neofs.go
=> services: fix error check for NeoFS client Dial 

pkg/neotest/compile.go
Close #3679
Currently, `neotest` lacks functionality to load compiled contracts. This feature would be useful for testing migrations between different contract versions.
Add `LoadContract` method to load a contract from a `NEF` file.
While implementing this, I used [contractDeploy](https://github.com/nspcc-dev/neo-go/blob/6d2077271499733ff847ab47306a97c9233ee599/cli/smartcontract/smart_contract.go#L771) as a reference.
=> Add 'neotest.ReadNEF' method

cli/smartcontract/testdata/rpcbindings/nft-nd/rpcbindings.out, cli/smartcontract/testdata/rpcbindings/nft-nd/rpcbindings_dynamic_hash.out, cli/smartcontract/testdata/rpcbindings/notifications/rpcbindings_extended.out, cli/smartcontract/testdata/rpcbindings/notifications/rpcbindings_guessed.out, cli/smartcontract/testdata/rpcbindings/structs/rpcbindings.out, cli/smartcontract/testdata/rpcbindings/structs/rpcbindings_dynamic_hash.out, cli/smartcontract/testdata/rpcbindings/types/rpcbindings.out, cli/smartcontract/testdata/rpcbindings/types/rpcbindings_dynamic_hash.out, pkg/smartcontract/rpcbinding/binding.go, pkg/vm/stackitem/item.go
We need it for structs to be usable as function parameters, otherwise they're not implementing stackitam.Convertible and they fail at transaction script creation phase:
2025/01/22 20:31:26 bootstrap error: could not invoke method (addNode): test invocation failed: unsupported operation: *netmap.NetmapNode2 type
Related to https://github.com/nspcc-dev/neofs-node/pull/3088.
=> rpcbindings: produce ToStackItem companion method

cli/smartcontract/testdata/rpcbindings/nft-nd/rpcbindings.out, cli/smartcontract/testdata/rpcbindings/nft-nd/rpcbindings_dynamic_hash.out, cli/smartcontract/testdata/rpcbindings/notifications/rpcbindings_extended.out, cli/smartcontract/testdata/rpcbindings/notifications/rpcbindings_guessed.out, cli/smartcontract/testdata/rpcbindings/structs/rpcbindings.out, cli/smartcontract/testdata/rpcbindings/structs/rpcbindings_dynamic_hash.out, cli/smartcontract/testdata/rpcbindings/types/rpcbindings.out, cli/smartcontract/testdata/rpcbindings/types/rpcbindings_dynamic_hash.out, pkg/smartcontract/rpcbinding/binding.go
... not enough return values
have (error)
want (stackitem.Item, error)
An omission of 00e22b975179cb548444c11fb5531ed48ca11356.
=> rpcbindings: fix missing return item

pkg/smartcontract/zkpbinding/binding.go
=> zkpbinding: remove range usage from smartcontract

internal/fakechain/fakechain.go, pkg/config/config.go, pkg/config/ledger_config.go, pkg/config/protocol_config.go, pkg/consensus/consensus.go, pkg/consensus/consensus_test.go, pkg/core/block/block.go, pkg/core/block/header.go, pkg/core/blockchain.go, pkg/core/statesync/module.go, pkg/network/bqueue/queue.go, pkg/network/bqueue/queue_test.go, pkg/network/bqueue_adapters.go, pkg/network/server.go, pkg/network/state_sync.go, pkg/services/blockfetcher/blockfetcher.go, pkg/services/blockfetcher/blockfetcher_test.go
=> Headers fetching via NeoFS BlockFetcher service

docs/rpc.md, pkg/core/blockchain.go, pkg/neorpc/result/block_notifications.go, pkg/rpcclient/rpc.go, pkg/services/rpcsrv/notification_comparator.go, pkg/services/rpcsrv/server.go, pkg/services/rpcsrv/server_test.go
Fixes #3779. Incorporates and replaces #3781.
=> Block notifications

pkg/core/mpt/billet.go, pkg/core/mpt/trie.go, pkg/core/mpt/trie_store.go, pkg/core/statesync/module.go
No functional changes, but we need at least some basic doc in order not to confuse new developers.
=> MPT: extend Billet documentation

cli/options/options.go, cli/server/dump_bin.go, cli/server/server.go, cli/server/server_test.go, cli/util/convert.go, cli/util/upload_bin.go, cli/util/upload_state.go, cli/util/util_test.go, docs/neofs-blockstorage.md, pkg/core/blockchain.go, pkg/services/blockfetcher/blockfetcher.go, pkg/services/helpers/neofs/blockstorage.go
`./bin/neo-go util upload-state --cid C425E7TxRHsrRNYjn7BVyWzvJGNyAXz8da4LFdvvej5X -fsr st4.storage.fs.neo.org:8080 -fsr st2.storage.fs.neo.org:8080 -fsr st3.storage.fs.neo.org:8080 -fsr st1.storage.fs.neo.org:8080 --wallet-config ./wallet-config.yml -t
`
Close #3782
=> cli: add `upload-state ` command

docs/node-configuration.md, docs/notifications.md, pkg/config/rpc_config.go, pkg/services/rpcsrv/server.go, pkg/services/rpcsrv/subscription.go, pkg/services/rpcsrv/subscription_test.go
We have already implemented this in our private fork, so it was being in use for some time.
Close #3823
=> rpcsrv: allow to configure subscription limit

pkg/core/blockchain.go, pkg/core/interop/context.go, pkg/core/native/management.go
Ported from #3478, required for #3835.
=> core: fix native contract initialization process

config/protocol.mainnet.neofs.yml, config/protocol.testnet.neofs.yml
=> config: upgrade NeoFS networks configuration

cli/server/dump_bin.go, cli/server/server.go, cli/server/server_test.go, cli/util/convert.go, cli/util/upload_state.go
Ref. https://github.com/nspcc-dev/neo-go/issues/3782
=> cli: adjust `upload-state` command to upload key-value pairs instead of full MPT traversal

pkg/vm/vm.go
No functional changes.
I was doing some long-long-script & many-many-keys tests to check boundary behaviour of my contract.
Then I see this thing in pprof: it is small, but noticeable.
=> vm: Skip GetCurrentScriptHash() call unless onExec hook is provided

scripts/compare-dumps/compare-dumps.go
NeoFS chains don't fit 6M limit anymore as far as N3.
=> scripts: increase dump index comparison range

go.mod, go.sum, pkg/crypto/hash/hash.go, scripts/go.mod, scripts/go.sum
It's the same code (everyone just copy/pastes it) in a simple small module. Bonus: it's not deprecated.
This doesn't change much for now, but with #3812 and a bit of copy-pasting we could drop `x/crypto` from `pkg/crypto` dependencies which again doesn't change much for NeoGo (we need `x/crypto` for legacy sha3 aka Keccak), but changes a lot for downstream repositories using `pkg/crypto` (and not importing `core/native` which no one should import really except for IR).
=> hash: switch to dcrd for ripemd160

pkg/config/protocol_config.go
This feature is not fully supported yet, #3793 is missing hence NeoFS-based state synchronisation from checkpoint won't work properly.
=> config: prohibit NeoFSStateSyncExtensions enabling

pkg/core/blockchain_core_test.go, pkg/core/blockchain_neotest_test.go, pkg/core/native/native_test/designate_test.go, pkg/core/native/native_test/policy_test.go
Echidna is a stable hardfork now, this commit should be a part of 23a78767acddec2d775f6f82718fd7c54fb5c08c.
=> core: fix Echidna-dependent tests

pkg/core/native/native_neo.go
Port https://github.com/neo-project/neo/pull/3234, should be a part of https://github.com/nspcc-dev/neo-go/pull/3351.
=> native: move CommitteeChanged event emission under Cockatrice

pkg/rpcclient/wsclient.go
Close #3093.
@roman-khimov, it's the best option that I can offer based on https://github.com/nspcc-dev/neo-go/issues/3093#issuecomment-2839415360 since I still don't understand the source of the problem. The same effect can be reached with additional mutex without any `subscriptionDispatcher` routine, so probably I'm doing something wrong, need your review.
Also, I'm still trying to reproduce the original problem locally with privnet.
=> rpcclient: manage subscriptions sequentially

pkg/services/notary/notary.go
When err is nil we're fine and there is no need to log. Regression of 13b75c9d1af2b84cb1d89c1d0930e1249653c5f5.
=> notary: do not make noise when there are no issues

pkg/core/statesync/mptpool.go, pkg/services/stateroot/signature.go
In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.
...
=> *: use the built-in max/min to simplify the code and fix a bug

pkg/core/statesync/mptpool.go
Ported from https://github.com/nspcc-dev/neo-go/pull/3897.
=> statesync: fix slice allocation size

pkg/compiler/codegen.go, pkg/compiler/slice_test.go
According to code, compiler currently supports slice expressions only for `[]byte` and triggers an error otherwise. However, using them with `string` type fails silently:
```
s := "abc"
return s[:2] == "ab" // oops, false!
```
This happens, because the resulting type for this operation is `Buffer`, but "ab" has type `ByteString`. So, we have 2 options:
- improve validation and trigger an error,
- or just support strings.
This commit implements the latter.
=> compiler: Support slice expressions for string

pkg/core/blockchain.go, pkg/core/dao/dao.go, pkg/core/storage/memcached_store.go
`cache` and `aerCache` should be persisted to the underlying DAO cache atomically, otherwise it's possible that `persist()` routine will persist only `aerCache` content to the DB. Combined with node shutdown, it will lead to MPT initialization failure after restart since stateroot changes belong to `cache`.
Fixes the first problem described in #3082, ref. https://github.com/nspcc-dev/neo-go/issues/3082#issuecomment-2922888710. Close #3082 since the second problem is moved to a separate issue.
=> core: persist storeBlock cache atomically

cli/options/options.go, cli/util/upload_bin.go, cli/util/upload_state.go, pkg/services/blockfetcher/blockfetcher.go, pkg/services/blockfetcher/blockfetcher_test.go, pkg/services/helpers/neofs/blockstorage.go, pkg/services/helpers/neofs/neofs.go, pkg/services/statefetcher/statefetcher.go
Close https://github.com/nspcc-dev/neo-go/issues/3656
Close https://github.com/nspcc-dev/neo-go/issues/3825
Close https://github.com/nspcc-dev/neo-go/issues/3707
=> cli, blockfetcher, statefetcher: migrate to searchv2

pkg/core/native/std.go, pkg/core/native/std_test.go
RFC 4648 specifies that non-alphabet characters must be rejected, but that other specifications that depend on RFC 4648 such as MIME (RFC 2045) and PEM (RFC 7468) may specify additional characters (e.g., whitespace) that are to be ignored. C# node uses Convert.FromBase64String that ignores tab, new line, carriage return and whitespace characters during decoding:
https://github.com/neo-project/neo/blob/9b9be47357e9065de524005755212ed54c3f6a11/src/Neo/SmartContract/Native/StdLib.cs#L132
See the behaviour remarks:
https://learn.microsoft.com/ru-ru/dotnet/api/system.convert.frombase64string?view=net-8.0#remarks
Standard Go library strictly follows RFC 4648 and ignores new line and carriage return characters by default, whereas other characters that are missing from decoder's alphabet lead to …
=> native: strip spases for StdLib's `base64Decode` and `base64UrlDecode`

go.mod, go.sum
Similar to a1b2467850fd3d24a418c5aa88a8ae171dffbed5, but with a more stable and improved version now. The same one as in https://github.com/nspcc-dev/neofs-node/pull/3389
=> go.mod: use faster Bolt

ROADMAP.md, pkg/rpcclient/rpc.go, pkg/rpcclient/rpc_test.go, pkg/services/rpcsrv/client_test.go
Requested by @carpawell, will be useful for NeoFS node.
=> rpcclient: add missing GetBlockHeaderByIndex[Verbose] APIs

pkg/rpcclient/local.go, pkg/rpcclient/local_test.go, pkg/services/rpcsrv/server.go
Looks like this existed since a55a01d45658a778e9b2edb1f0dd4c61e131ca90 and I have no idea why we haven't seen this before https://github.com/nspcc-dev/neofs-node/pull/3456 which is totally unrelated. But what we have in the end is
panic: close of closed channel
goroutine 182 [running]:
github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleLocalNotifications(0xc00033aa08, {0x1557f10, 0xc0002283c0}, 0xc00020d180, 0xc000206700, 0xc00011c7b0)
github.com/nspcc-dev/neo-go@v0.110.0/pkg/services/rpcsrv/server.go:679 +0x105
created by github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).RegisterLocal in goroutine 1
github.com/nspcc-dev/neo-go@v0.110.0/pkg/services/rpcsrv/server.go:574 +0x193
and that's exactly true, we're closing it both sides. Solve it by making client wait for …
=> rpcclient: fix local client panic

cli/smartcontract/testdata/rpcbindings/nft-d/rpcbindings.out, cli/smartcontract/testdata/rpcbindings/nft-d/rpcbindings_dynamic_hash.out, cli/smartcontract/testdata/rpcbindings/nft-nd/rpcbindings.out, cli/smartcontract/testdata/rpcbindings/nft-nd/rpcbindings_dynamic_hash.out, pkg/smartcontract/rpcbinding/binding.go
An attempt to use some autogenerated binding quickly results in
rpc/netmap/rpcbinding.go:128:48: cannot use nep22.NewContract(actor, hash) (value of type *nep22.Contract) as nep22.Contract value in struct literal
because of type mismatch. Defect of a3bea1f0f0abf4505dda0599c73e976f8a8ef6dd and 89c00915b4f4f5b2a42a22718bee9d4eacc749bf.
=> rpcbinding: fix bindings using NEP-22/NEP-31 modules
