- .gitignore
- Makefile
- README.md
- glide.lock
- glide.yaml
Saw that a few things were missing from the repo.
- Update README
- Add `Makefile`, with `make test`
- Add Glide config
- Add Git ignore config
- None
> Repo Setup

- .github/PULL_REQUEST_TEMPLATE.md
Relates to https://github.com/CityOfZion/neo-go/issues/110#issuecomment-444820802 / https://github.com/CityOfZion/neo-go/pull/111
> Remove mention of the bump version

- pkg/rpc/client.go
- pkg/rpc/neoScanBalanceGetter.go
- pkg/rpc/rpc.go
- pkg/rpc/txBuilder.go
- pkg/rpc/txTypes.go
- pkg/rpc/types.go
- go fmt's
- make `NeoScanBalancer.GetBalance()` public
- new type for `sendtoaddress` response
- make `GetInvocationScript()` public
> Small fixes

- pkg/rpc/stack_param.go
- pkg/rpc/stack_param_test.go
- pkg/rpc/types.go
It is very convenient when StackParam is correctly unmarshaled from JSON.
Implement custom UnmarshalJSON
> Add StackParam JSON Unmarshaler

- pkg/crypto/public_key.go
- optimize crypto/PublicKey.DecodeBinary
- add new method crypto/PublicKey.DecodeBytes
> Simplify code and improve performance (crypto/PublicKey.DecodeBinary)

- pkg/core/blockchain.go
- pkg/core/blockchainer.go
- pkg/network/helper_test.go
- pkg/rpc/server.go
- pkg/rpc/server_test.go
- pkg/rpc/wrappers/account_state.go
Implemented rcp method GetAccountState
Added tests and compared output with neo-python
> Implemented rcp method GetAccountState

- config/config.go
- pkg/core/asset_state.go
- pkg/core/blockchain.go
- pkg/core/header_test.go
- pkg/core/storage/helpers.go
- pkg/core/storage/memory_store.go
- pkg/crypto/base58.go
- pkg/crypto/elliptic_curve.go
- pkg/network/discovery.go
- pkg/network/server.go
- pkg/network/server_config.go
- pkg/rpc/README.md
- pkg/rpc/server_test.go
- pkg/util/array_test.go
- pkg/util/endpoint.go
- pkg/vm/cli/cli.go
- pkg/vm/compiler/analysis.go
- pkg/vm/compiler/codegen.go
- pkg/vm/compiler/emit.go
- pkg/vm/emit.go
- pkg/vm/stack.go
- pkg/vm/syscall.go
- pkg/vm/vm.go
- pkg/wallet/wallet.go
- typos
- gofmt -s
- govet warnings
- golangci-lint run
> Fix typos and warnings for GoReport / GolangCiLinter

- pkg/rpc/client.go
- pkg/rpc/rpc.go
- balancer / wif / http.Client could be with data race
- add getter / setter with sync.Mutex
- now http.Client is pointer
- now you can provide your http.Client to rpcClient
> Fix possible data race

- go.mod
- pkg/rpc/errors.go
- pkg/rpc/params.go
- pkg/rpc/server.go
- pkg/rpc/server_test.go
- pkg/rpc/wrappers/account_state.go
- fixed RPC Server response
- fixed RPC Server tests
- remove unused package from go.mod
> Fix #130: Wrong answer for RPC server method getaccountstate

- go.sum
- pkg/rpc/README.md
- pkg/rpc/server.go
- pkg/rpc/server_test.go
- pkg/rpc/wrappers/validate_address.go
- implement rpc method validateaddress (https://docs.neo.org/en-us/node/cli/2.9.4/api/validateaddress.html)
- add tests
- add to README.md
It's just implementation taken from [C#](https://github.com/neo-project/neo/blob/bbbc0cf5e401e425e7d749f26b23b824953da10a/neo/Network/RPC/RpcServer.cs#L566-L580)
> Add RPC Server method ValidateAddress

- pkg/rpc/README.md
> Fix API documentation link

- cli/server/server.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/storage/leveldb_store.go
- pkg/rpc/server_test.go
- fix #138
- stop blockchain goroutine
- close leveldb database
---
cc @decentralisedkev @anthdm @fabwa
> Blockchain graceful shutdown

- pkg/core/blockchain_test.go
- pkg/core/storage/helpers.go
- pkg/network/tcp_transport.go
- pkg/rpc/neoScanBalanceGetter.go
- pkg/rpc/stack_param_test.go
- pkg/util/array_test.go
- pkg/util/io.go
- pkg/util/uint160.go
- pkg/util/uint256.go
- pkg/vm/compiler/codegen.go
- pkg/vm/state_test.go
- pkg/wallet/nep2.go
- simplify code
- prealoc slices
- check errors in tests
- regexp Compile replaced with MustCompile
- uint* cannot be negative
> Code refactoring

- Gopkg.lock
- circle.yml
- pkg/rpc/server_test.go
> Replace assertion for rpc/server_test.go

- pkg/peer/stall/stall.go
- pkg/peer/stall/stall_test.go
fix #162
---
cc @decentralisedkev
> Fix possible data race in pkg/peer/stall

- .circleci/config.yml
Pipeline:
- vet
- lint
- go1.11
- go1.12
> Add CircleCI to dev-branch

- pkg/database/leveldb.go
Remove unnecesary methods. closes #201
> [Database] clean-up

- pkg/connmgr/config.go
- pkg/connmgr/connmgr.go
- pkg/connmgr/connmgr_test.go
- pkg/connmgr/readme.md
- pkg/connmgr/request.go
- Refactor Connmgr
- Remove un-needed async code
- Clean up comments
> [connmgr] Refactor Connmgr

- pkg/wire/payload/block_test.go
- pkg/wire/payload/mheaders_test.go
- pkg/wire/payload/transaction/claim_test.go
- pkg/wire/payload/transaction/contract_test.go
- pkg/wire/payload/transaction/enrollment_test.go
- pkg/wire/payload/transaction/invocation_test.go
- pkg/wire/payload/transaction/miner_test.go
- pkg/wire/payload/transaction/publish_test.go
- pkg/wire/payload/transaction/register_test.go
- pkg/wire/payload/transaction/state_test.go
- pkg/wire/util/uint256.go
- pkg/wire/util/uint256_test.go
> Fixed String method in Uint256

- pkg/chain/chaindb.go
- pkg/chain/chaindb_test.go
- pkg/database/leveldb.go
- pkg/database/leveldb_test.go
- pkg/database/table.go
- pkg/peer/peer.go
- pkg/wire/protocol/protocol.go
Closes #203
- small clean in peer
- Adds a String method to protocol Magic
> Add Chain saving functionality to Database

- pkg/wire/payload/transaction/Attribute.go
- pkg/wire/payload/transaction/invocation_test.go
> Fixed Txn Attribute econding/decoding

- pkg/vm/vm_ops.go
- pkg/vm/vm_ops_exceptions.go
- pkg/vm/vm_ops_maths.go
- pkg/vm/vm_test.go
> VM:Implement THROW opcode

- pkg/vm/vm_ops.go
- pkg/vm/vm_ops_maths.go
- pkg/vm/vm_ops_maths_test.go
> VM: Implement INC, DEC opcode 

- pkg/vm/vm_ops.go
- pkg/vm/vm_ops_maths.go
- pkg/vm/vm_ops_maths_test.go
> VM: Implemented SIGN, NEGATE opcode

- pkg/vm/stack/Int.go
- pkg/vm/stack/boolean.go
- pkg/vm/stack/stack.go
- pkg/vm/vm_ops.go
- pkg/vm/vm_ops_maths.go
- pkg/vm/vm_ops_maths_test.go
> VM: Implement, ABS, NOT opcode

- pkg/chain/chain.go
- pkg/chain/errors.go
- pkg/chaincfg/chaincfg.go
- pkg/chaincfg/chaincfg_test.go
- Add custom error types to distinguish between validation and database errors
- Added basic chaincfg function
- Added feature to insert the genesis block when there is a new database
> [chain] Refactor, add chaincfg and database initialisation

- pkg/syncmgr/blockmode.go
- pkg/syncmgr/config.go
- pkg/syncmgr/headermode.go
- pkg/syncmgr/mockhelpers_test.go
- pkg/syncmgr/normalmode.go
- pkg/syncmgr/syncmgr.go
- pkg/syncmgr/syncmgr_onblock_test.go
- pkg/syncmgr/syncmgr_onheaders_test.go
> Syncmgr: Implement synchronisation manager

- pkg/vm/vm_ops.go
- pkg/vm/vm_ops_maths.go
- pkg/vm/vm_ops_maths_test.go
> VM: Implement SHL, SHR opcode

- pkg/vm/stack/Int.go
- pkg/vm/vm_ops.go
- pkg/vm/vm_ops_maths.go
- pkg/vm/vm_ops_maths_test.go
> Implemented LT, GT opcode

- pkg/vm/stack/boolean.go
- pkg/vm/vm_ops.go
- pkg/vm/vm_ops_maths.go
- pkg/vm/vm_ops_maths_test.go
> VM: Implement BOOLAND, BOOLOR opcode

- pkg/vm/vm_ops.go
- pkg/vm/vm_ops_maths.go
- pkg/vm/vm_ops_maths_test.go
> VM: Implement NUMEQUAL, NUMNOTEQUAL opcode

- pkg/vm/stack/Int.go
- pkg/vm/vm_ops.go
- pkg/vm/vm_ops_maths.go
- pkg/vm/vm_ops_maths_test.go
> Implemented LTE, GTE opcode

- pkg/wire/util/address/address.go
- pkg/wire/util/address/address_test.go
- pkg/wire/util/uint160.go
- pkg/wire/util/uint160_test.go
> Add ReverseString, ToReverseScriptHash method

- ROADMAP.md
I've been tasked by the CoZ council with driving the development of a roadmap and vision for future development of neo-go. 
I think this is best achieved as a collaborative process among all the active contributors to the project, so to facilitate that, I've added an empty roadmap markdown document to the project to be shaped over time by all interested parties.
This thread can be left open and used to discuss potential milestones and other roadmap-related items until a consensus has been reached. Please add your thoughts below.
> Create a roadmap for future development

- .dockerignore
- Dockerfile
- Makefile
- README.md
- cli/main.go
- Make Dockerfile useful and minimal
- Update Makefile commands build / build-image
- Update Readme: fix Dep-manager and minimal requirements
- Docker should not ignore vendor (go build -mod=vendor)
> Fix build node and docker-image

- pkg/core/storage/memory_store.go
- Add RWMutex to MemoryStore struct
- Use Lock/Unlock for writing
- Use RLock/RUnlock for reading
> Fix DataRace in MemoryStore

- .circleci/config.yml
Codecov should give us some real badge, not just write "unknown".
> circleci: fix codecov integration

- pkg/vm/stack.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
Implements NZ, PICK, TUCK, XDROP, INVERT. Fixes XTUCK.
> Some VM opcodes and fixes

- pkg/vm/stack.go
- pkg/vm/stack_item.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
Add UNPACK, REVERSE, REMOVE, plus some tests for PACK. Fixes #195.
> Complete vm array instructions

- pkg/util/size.go
- pkg/util/size_test.go
- pkg/vm/compiler/codegen.go
- pkg/vm/tests/for_test.go
> Fix some easy TODO items

- cli/server/server.go
- config/config.go
- config/protocol.mainnet.yml
- config/protocol.privnet.docker.four.yml
- config/protocol.privnet.docker.one.yml
- config/protocol.privnet.docker.three.yml
- config/protocol.privnet.docker.two.yml
- config/protocol.privnet.yml
- config/protocol.testnet.yml
- config/protocol.unit_testnet.yml
- go.mod
- go.sum
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/storage/leveldb_store.go
- pkg/core/storage/redis_store.go
- pkg/core/storage/redis_store_test.go
- pkg/core/storage/store.go
- pkg/core/storage/store_config.go
- pkg/rpc/server_test.go
Closes #336
First step for #305 and #335
> storage: support of Redis and configuration for DB

- pkg/vm/context.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
And improve PUSHDATA along the way. Fixes #387.
> VM: harden substr/left/right against bad indexes

- pkg/vm/vm.go
- pkg/vm/vm_test.go
> VM: APPEND should push no value on stack

- pkg/core/blockchain.go
- pkg/core/storage/helpers.go
Based on my experience running node connected to the testnet.
> Assorted db handling fixes and optimizations

- cli/server/server.go
- pkg/core/blockchain.go
- pkg/core/storage/boltdb_store.go
- pkg/core/storage/boltdb_store_test.go
- pkg/core/storage/leveldb_store.go
- pkg/core/storage/memory_store.go
- pkg/core/storage/memory_store_test.go
- pkg/core/storage/redis_store.go
- pkg/core/storage/redis_store_test.go
- pkg/core/storage/store.go
- pkg/rpc/server_test.go
Did a small pair programming with @im-kulikov during Friday and this PR is the first to step further.
> storage: refactor store | The obvious starting blockchain and closing the database

- cli/server/server.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/rpc/server_test.go
rework initBlockChain in order to have controllable way of running
blockchain;
remove context from initBlockChain func;
ps. Second part of pair programming session with @im-kulikov
> blockchain: server runs goroutine instead of blockchain init

- pkg/io/size.go
> Unexport things from io

- pkg/core/blockchain.go
- pkg/core/storage/boltdb_store.go
- pkg/core/storage/boltdb_store_test.go
- pkg/network/message.go
This fixes some behavior observed when synchronizing with mainnet (again). Tiny logging fixes and two more serious things --- SIGSEGV in networking code and BoltDB batched Put() issue.
> Bolt Put(), sigsegv and logging fixes

- pkg/vm/cli/cli.go
- pkg/vm/vm.go
Original C# vm debugger behavior implemented.
closes #187
> vm: add stepInto,stepOver,stepOut

- pkg/network/message.go
- pkg/network/server.go
- pkg/network/server_test.go
This fixes useless disconnects in testnet/mainnet.
> Disconnection fixes

- cli/smartcontract/smart_contract.go
- pkg/core/block_test.go
- pkg/core/transaction/contract_test.go
- pkg/core/unspent_coin_state.go
- pkg/smartcontract/contract_test.go
- pkg/util/fixed8.go
- pkg/vm/cli/cli.go
- pkg/vm/compiler/compiler.go
- pkg/vm/compiler/emit.go
- pkg/vm/emit.go
- pkg/vm/stack_item.go
- pkg/vm/tests/assign_test.go
- pkg/vm/tests/binary_expr_test.go
- pkg/vm/tests/numeric_test.go
- pkg/vm/tests/struct_test.go
- pkg/vm/tests/vm_test.go
Run inspection on out source code while working under #297 and decided to fix part of them as a separate PR
> Inspection fixes

- cli/main.go
- cli/server/server.go
- cli/smartcontract/smart_contract.go
- cli/vm/vm.go
- cli/wallet/wallet.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
#436.
This patchset.
It also fixes some associated functionality along the way like properly persisting things on exit.
> DB dump and restore

- pkg/vm/vm.go
- pkg/vm/vm_test.go
Fixes #437.
It is draft, because I haven't yet checked the behaviour of original VM.
> vm: copy slice in NEWARRAY/NEWSTRUCT

- cli/vm/vm.go
- pkg/core/blockchain.go
- pkg/core/storage/boltdb_store.go
- pkg/rpc/request.go
- pkg/vm/cli/cli.go
- pkg/vm/compiler/compiler.go
- pkg/vm/tests/vm_test.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
> Change fmt.Println to log

- pkg/vm/vm.go
#426 broke tests, fix that. Turns out my suggestion to return errors in the `Run()` loop for halt and break states was wrong. Improve state checking in general while at it.
> vm: fix tests failing, follow-up to #426

- pkg/core/blockchain.go
- pkg/smartcontract/param_context.go
PropertyState bug fix and missing issue functionality.
> TX processing fixes

- pkg/vm/context.go
- pkg/vm/instruction_string.go
- pkg/vm/instructions.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
No tests yet, that's gonna be a separate issue.
> vm: implement stack isolation opcodes, fix #192

- pkg/network/discovery.go
- pkg/network/discovery_test.go
> Fix discoverer races (#445)

- cli/server/server.go
- config/config.go
- config/protocol.mainnet.yml
- config/protocol.privnet.docker.four.yml
- config/protocol.privnet.docker.one.yml
- config/protocol.privnet.docker.three.yml
- config/protocol.privnet.docker.two.yml
- config/protocol.privnet.yml
- config/protocol.testnet.yml
- config/protocol.unit_testnet.yml
- go.mod
- pkg/network/server.go
- pkg/rpc/request.go
- pkg/rpc/server.go
- pkg/rpc/server_helper_test.go
Better variant of #464 and a fix for unconfigured MinPeers.
> Cors and minpeers

- pkg/core/interop_neo.go
- pkg/core/interops.go
- pkg/vm/interop.go
- pkg/vm/serialization.go
- pkg/vm/stack.go
- pkg/vm/stack_item.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
This PR implements Serialize/Deserialize interops.
Closes #419.
> VM: Implement serialization and deserealization interops

- pkg/vm/stack.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
There is a limitation on total number of items on stack.
To not to recalculate it after every stack modification we can cache total number of items.
In some cases (when a struct is cloned) there is a need to force full recalculation.
> vm: restrict total stack item count

- pkg/wallet/wallet_test.go
Week coverage
...
This patchset increases coverage for wallet package
...
> wallet: unit tests

- pkg/core/blockchain.go
Various issues when the node can be stuck and not init properly with the only way to recover is by dropping the DB.
This patchset.
> Fix init corner cases

- cli/server/server.go
> cli: compatible with NGD reading/writing blockchain dump

- pkg/core/blockchain.go
> core: add proper claim transactions processing

- Makefile
- neo-go.service
- neo-go.service.template
> added systemd unit file and target for make

- pkg/consensus/prepare_request.go
- pkg/consensus/recovery_message.go
- pkg/core/account_state.go
- pkg/core/block.go
- pkg/core/contract_state.go
- pkg/core/header_hash_list.go
- pkg/core/transaction/claim.go
- pkg/core/transaction/state.go
- pkg/core/transaction/transaction.go
- pkg/io/binaryReader.go
- pkg/io/binaryrw_test.go
- pkg/io/size_test.go
- pkg/network/payload/address.go
- pkg/network/payload/getblocks.go
- pkg/network/payload/inventory.go
- pkg/network/payload/merkleblock.go
- pkg/smartcontract/param_context.go
- pkg/util/uint256.go
- pkg/util/uint256_test.go
This PR implements first item from #494 .
> io: implement io.Serializable for Uint256

- pkg/io/binaryReader.go
- pkg/io/binaryrw_test.go
> io: restrict ReadArray max array size

- docs/rpc.md
- pkg/core/account_state.go
- pkg/core/account_state_test.go
- pkg/core/blockchain.go
- pkg/core/interop_neo.go
- pkg/core/notification_event.go
- pkg/rpc/neoScanBalanceGetter.go
- pkg/rpc/neoScanTypes.go
- pkg/rpc/prometheus.go
- pkg/rpc/server.go
- pkg/rpc/server_helper_test.go
- pkg/rpc/server_test.go
- pkg/rpc/wrappers/account_state.go
- pkg/rpc/wrappers/unspents.go
#473
Merge button. Fixes serialization issue for NotificationEvent along the way.
> Implement getunspents RPC API

- pkg/core/interop_neo_test.go
We have weak coverage in core/interops
...
This patchset is first step to increase coverage
...
I wonder if there are any opinions against using reflect for refactoring interops since most of them have very generic code.
> core: add unit tests for interops_neo

- cli/smartcontract/smart_contract.go
- pkg/core/account_state.go
- pkg/core/blockchain.go
- pkg/core/transaction/invocation.go
- pkg/core/transaction/transaction_test.go
- pkg/rpc/client.go
- pkg/rpc/doc.go
- pkg/rpc/neoScanBalanceGetter.go
- pkg/rpc/neoScanTypes.go
- pkg/rpc/rpc.go
- pkg/rpc/scdetails.go
- pkg/rpc/stack_param.go
- pkg/rpc/txBuilder.go
- pkg/rpc/types.go
> Contract deployment

- pkg/core/blockchain.go
- pkg/core/blockchain_state.go
- pkg/core/blockchain_state_test.go
- pkg/core/blockchainer.go
- pkg/core/interop_neo.go
- pkg/core/interops.go
- pkg/core/util.go
- pkg/core/validator_state.go
- pkg/core/validator_state_test.go
- pkg/crypto/keys/publickey.go
- pkg/crypto/keys/publickey_test.go
- pkg/network/helper_test.go
> core: Implement getvalidators interop

- pkg/util/array_test.go
- pkg/util/fixed8_test.go
- pkg/util/uint160_test.go
- pkg/util/uint256_test.go
> util: add missing tests

- cli/smartcontract/smart_contract.go
- docs/rpc.md
- pkg/rpc/param.go
- pkg/rpc/param_test.go
- pkg/rpc/server.go
- pkg/rpc/server_helper_test.go
- pkg/rpc/server_test.go
- pkg/rpc/stack_param.go
- pkg/rpc/txBuilder.go
- pkg/rpc/tx_builder_test.go
- pkg/smartcontract/param_context.go
- pkg/smartcontract/param_context_test.go
- pkg/vm/output.go
- pkg/vm/stack.go
- pkg/vm/stack_test.go
#347 and client-side invocations.
Über-solution is presented here.
> Invokefunction

- README.md
- docs/consensus.md
Add documentation describing how to act as a consensus node in your own privnet.
> docs: add consensus.md

- pkg/crypto/hash/hash_test.go
- pkg/crypto/keys/nep2_test.go
- pkg/crypto/keys/private_key_test.go
- pkg/crypto/keys/publickey_test.go
- pkg/crypto/keys/sign_verify_test.go
- pkg/crypto/keys/wif_test.go
- pkg/internal/keytestcases/testcases.go
- pkg/wallet/account_test.go
I am not sure if this is the most beautiful approach though. Maybe it is better to have a separate test vector with different errors.
> crypto: add more test for error cases

- cli/smartcontract/smart_contract.go
- docs/rpc.md
- pkg/rpc/server.go
- pkg/rpc/server_test.go
- pkg/rpc/txBuilder.go
#346, yet another invoker.
Merge button.
> Invoke RPC

- docs/consensus.md
And instruct to clean things using updated Makefile.
...
...
> docs: update consensus doc with more details

- pkg/network/server.go
Don't ask peers about the items we already have.
> network: rework inventory handling, check for item presence

- pkg/core/mem_pool.go
Fix some mempool locking issues mentioned in the #526 and related to the #533.
> Mempool locking fixes

- cli/server/server.go
- cli/smartcontract/smart_contract.go
- pkg/consensus/payload.go
- pkg/consensus/recovery_message.go
- pkg/core/blockchain.go
- pkg/core/blockchain_state.go
- pkg/core/contract_state.go
- pkg/core/storage_item.go
- pkg/core/transaction/attribute.go
- pkg/core/transaction/invocation.go
- pkg/core/transaction/publish.go
- pkg/core/transaction/register.go
- pkg/core/transaction/state_descriptor.go
- pkg/core/transaction/witness.go
- pkg/crypto/keys/publickey.go
- pkg/io/binaryBufWriter.go
- pkg/io/binaryWriter.go
- pkg/io/binaryrw_test.go
- pkg/network/payload/merkleblock.go
- pkg/network/payload/version.go
- pkg/vm/compiler/analysis.go
- pkg/vm/compiler/codegen.go
- pkg/vm/compiler/compiler.go
- pkg/vm/compiler/emit.go
- pkg/vm/serialization.go
Multiple errchecks #297 
...
this patchset
...
closes #297 and #457
> add bufBinWriter to emit functions in order to catch errors

- pkg/io/binaryrw_test.go
> io: add missing test

- go.mod
> mod: remove unused deps

- .circleci/config.yml
- pkg/vm/json_test.go
We succeeded this test without running anything real which is certainly not
good and I think we should always run this tests.
> vm: force neo-vm tests presence

- go.mod
- go.sum
- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/consensus/recovery_message.go
- pkg/consensus/recovery_message_test.go
We need to process only signed payloads and also sign them on send .
> consensus: sign and verify consensus payloads

- pkg/compiler/emit.go
- pkg/consensus/commit.go
- pkg/consensus/payload.go
- pkg/consensus/prepare_request.go
- pkg/consensus/prepare_response.go
- pkg/consensus/recovery_message.go
- pkg/core/account_state.go
- pkg/core/asset_state.go
- pkg/core/block.go
- pkg/core/block_base.go
- pkg/core/blockchain.go
- pkg/core/header.go
- pkg/core/notification_event.go
- pkg/core/spent_coin_state.go
- pkg/core/transaction/input.go
- pkg/core/transaction/output.go
- pkg/core/transaction/register.go
- pkg/core/unspent_coin_state.go
- pkg/io/binaryWriter.go
- pkg/io/binaryrw_test.go
- pkg/network/message.go
- pkg/network/payload/address.go
- pkg/network/payload/getblocks.go
- pkg/smartcontract/param_context.go
- pkg/util/uint256.go
- pkg/vm/serialization.go
Very slow block import.
Some speedups are made here, more to come from @fyrchik.
> Write optimizations

- pkg/core/blockchain.go
- pkg/core/cacheddao.go
- pkg/core/cacheddao_test.go
- pkg/core/dao.go
- pkg/core/dao_test.go
- pkg/core/interop_neo.go
- pkg/core/interop_system.go
- pkg/core/interops.go
- pkg/core/mem_pool.go
- pkg/core/state/account.go
- pkg/vm/context.go
- pkg/vm/vm.go
Slow block import.
This improves 1.4M->1.5M import of 100K blocks by more than 43%.
> Optimize dao and things

- pkg/core/mem_pool.go
- pkg/core/mem_pool_test.go
First of all, it was wrong, it was not checking for inputs really, it compared
tx hashes for some reason, second, when it did compare inputs it compared only
the PrevIndex part of them which is also wrong.
Also, there is absolutely no reason to go through GetVerifiedTransactions()
here, we don't need this copy of pointers and it can also be outdated by the
time we're to finish our check.
Before:
BenchmarkTXPerformanceTest-4
5000            485506 ns/op           65886 B/op        409 allocs/op
ok      github.com/CityOfZion/neo-go/integration        3.212s
After:
enchmarkTXPerformanceTest-4
5000            371104 ns/op           44367 B/op        408 allocs/op
ok      github.com/CityOfZion/neo-go/integration        2.712s
...
...
> core: fix and speed up mempool Verify()

- pkg/vm/stack.go
- pkg/vm/stack_test.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
5% performance improvement on 100K blocks import in 1.4M->1.5M scenario. Plus some testing improvement.
> Some VM instructions optimization

- config/config.go
- pkg/core/blockchainer.go
- pkg/core/uint32.go
- pkg/network/metrics/metrics.go
- pkg/network/metrics/pprof.go
- pkg/rpc/wrappers/account_state.go
- fix a link in pprof
- goimports project
> *: small fixes

- pkg/compiler/codegen.go
- pkg/compiler/codegen_test.go
- pkg/vm/tests/binary_expr_test.go
> compiler: Add Mod token

- pkg/core/blockchain.go
- pkg/vm/vm.go
Block import performance.
This eliminates some easy to fix blocks, but the overall improvement in ~1-2%, so it's hardly visible in a 100K block import test. Still, it slightly reduces the DB pressure and eliminates useless hashing, so it's nice to have.
> Tiny vm and core speedups

- cli/server/server.go
- config/config.go
- integration/performance_test.go
- pkg/compiler/codegen.go
- pkg/core/block.go
- pkg/core/block_test.go
- pkg/core/transaction/output.go
- pkg/core/transaction/register_test.go
- pkg/core/transaction/transaction_test.go
- pkg/core/util_test.go
- pkg/crypto/address.go
- pkg/crypto/hash/merkle_tree.go
- pkg/crypto/hash/merkle_tree_test.go
- pkg/crypto/keys/aes256.go
- pkg/crypto/keys/nep2.go
- pkg/crypto/keys/publickey.go
- pkg/crypto/keys/publickey_test.go
- pkg/crypto/keys/wif.go
- pkg/encoding/address/address.go
- pkg/encoding/address/address_test.go
- pkg/encoding/base58/base58.go
- pkg/encoding/base58/base58_test.go
- pkg/encoding/base58/doc.go
- pkg/rpc/param.go
- pkg/rpc/param_test.go
- pkg/rpc/txBuilder.go
- pkg/rpc/wrappers/asset_state.go
- pkg/rpc/wrappers/validate_address.go
- pkg/smartcontract/param_context.go
This moves some functionality into micro-packages, improves testing, unexports some code and fixes bugs along the way.
> Refactor crypto

- pkg/network/payload/getblocks.go
- pkg/network/server.go
Fixes #577, tested with C# nodes connecting to neo-go privnet.
> network: implement getblocks command

- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/consensus/payload.go
- pkg/consensus/payload_test.go
- pkg/consensus/recovery_message_test.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
Verify script hash of the payload witness.
Closes #555 .
> consensus: verify payloads correctly

- pkg/core/interop_neo.go
- pkg/core/interop_neo_test.go
- pkg/core/interops.go
- pkg/core/interops_test.go
- pkg/vm/interop.go
Closes #422 .
I am not yet sure whether tests should belong to `vm` or `core`.
> core: implement Neo.Storage.Find interop

- cli/server/server.go
A pair of dump/restore bugs and some interoperability issues with C# nodes.
Right behind the "Merge" button.
> DB dump and restore fixes

- pkg/network/tcp_transport.go
> network: fix NPE in logging

- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
Closes #591 .
When system and network pressure is high it can be beneficial
to use transactions which and were already proposed.
The assumption is that they will be in other node's memory pool
with more probability.
> consensus: try to use previous proposal after ChangeView

- pkg/compiler/compiler.go
- pkg/compiler/compiler_test.go
- pkg/compiler/testdata/compile/test.go
coverage and unused functions
...
this patchset
...
> compiler: clean and tests

- pkg/network/server.go
Transactions were not really requested from the peers.
Use proper command type.
> Fix consensus transaction requests

- config/config.go
- config/protocol.mainnet.yml
- config/protocol.privnet.docker.four.yml
- config/protocol.privnet.docker.one.yml
- config/protocol.privnet.docker.single.yml
- config/protocol.privnet.docker.three.yml
- config/protocol.privnet.docker.two.yml
- config/protocol.privnet.yml
- config/protocol.testnet.yml
- config/protocol.unit_testnet.yml
- pkg/network/helper_test.go
- pkg/network/message.go
- pkg/network/payload/ping.go
- pkg/network/payload/ping_test.go
- pkg/network/peer.go
- pkg/network/server.go
- pkg/network/server_config.go
- pkg/network/tcp_peer.go
Node didn't support ping/pong requests processing.
...
This patchset replicated C# node behavior.
...
closes #430
> add ping pong processing

- config/protocol.mainnet.yml
- config/protocol.privnet.docker.four.yml
- config/protocol.privnet.docker.one.yml
- config/protocol.privnet.docker.single.yml
- config/protocol.privnet.docker.three.yml
- config/protocol.privnet.docker.two.yml
- config/protocol.privnet.yml
- config/protocol.testnet.yml
- config/protocol.unit_testnet.yml
- pkg/network/helper_test.go
- pkg/network/peer.go
- pkg/network/server.go
- pkg/network/tcp_peer.go
This improves upon #456 fixing some problems and making configured behaviour more predictable, albeit deviating a little from the C# implementation.
> Ping improvements

- pkg/network/helper_test.go
- pkg/network/peer.go
- pkg/network/server.go
- pkg/network/server_test.go
- pkg/network/tcp_peer.go
- pkg/network/tcp_peer_test.go
This one updates broadcasting a little giving more priority for everything related to consensus.
> Network peer updates

- config/config.go
- config/protocol.mainnet.yml
- config/protocol.privnet.docker.four.yml
- config/protocol.privnet.docker.one.yml
- config/protocol.privnet.docker.single.yml
- config/protocol.privnet.docker.three.yml
- config/protocol.privnet.docker.two.yml
- config/protocol.privnet.yml
- config/protocol.testnet.yml
- config/protocol.unit_testnet.yml
- pkg/core/blockchain.go
Allow tuning/experimenting with mempool.
> config: add MemPoolSize configuration parameter

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/interop_test.go
- pkg/interop/engine/engine.go
1. Implement interop for `APPCALL` support.
https://github.com/CityOfZion/neo-boa/blob/master/boa/interop/Neo/App.py
2. Fix a bug with stack pollution during handling `FromAddress`.
> compiler: implement AppCall interop

- pkg/network/helper_test.go
- pkg/network/peer.go
- pkg/network/server.go
- pkg/network/tcp_peer.go
getdata and ping/pong bugs.
Right here.
> Fix getdata and pings

- pkg/compiler/emit.go
- pkg/compiler/limit_test.go
- pkg/vm/bigint.go
- pkg/vm/bigint_test.go
- pkg/vm/json_test.go
- pkg/vm/serialization.go
- pkg/vm/stack.go
- pkg/vm/stack_item.go
> compiler: emit integers correctly

- go.mod
- go.sum
New version can send RecoveryMessage on ChangeView if Commit was sent.
> consensus: update dbft version

- go.mod
- pkg/consensus/consensus.go
#634, nspcc-dev/dbft#15, nspcc-dev/dbft#16, nspcc-dev/dbft#17, nspcc-dev/dbft#18.
Merge.
> Consensus update

- pkg/core/gas_price.go
> core: fix GAS price definitions

- pkg/network/tcp_peer.go
We can leak sending goroutines and stall broadcasts because of already gone
peers that happened to be cached by some s.Peers() user (more than 800 of
these can be seen in nodoka log along with (*Server).run blocking on
CMDGetAddr send):
Feb 10 16:35:15 nodoka neo-go[1563]: goroutine 41 [chan send, 3320 minutes]:
Feb 10 16:35:15 nodoka neo-go[1563]: github.com/CityOfZion/neo-go/pkg/network.(*TCPPeer).putPacketIntoQueue(...)
Feb 10 16:35:15 nodoka neo-go[1563]:         /go/src/github.com/CityOfZion/neo-go/pkg/network/tcp_peer.go:81
Feb 10 16:35:15 nodoka neo-go[1563]: github.com/CityOfZion/neo-go/pkg/network.(*TCPPeer).EnqueueHPPacket(0xc0083d57a0, 0xc017206100, 0x18, 0x40, 0x136a240, 0xc018ef9720)
Feb 10 16:35:15 nodoka neo-go[1563]: …
> network: fix networking stalls caused by stale peers

- pkg/rpc/server_helper_test.go
- pkg/rpc/server_test.go
- pkg/rpc/wrappers/block.go
> [rpc] Fix wrong answer for getblock method

- pkg/core/blockchain.go
- pkg/core/dao.go
- pkg/core/state/validator.go
- pkg/core/transaction/state_descriptor.go
- pkg/core/transaction/state_test.go
- pkg/crypto/keys/publickey.go
Completely broken voting system leading to testnet node not participating in consensus (as it doesn't see itself elected).
Some assorted fixes.
> Make voting system work

- pkg/core/blockchain.go
They may not really have a reference. Fixes #671.
> core: deal with bad transaction Inputs

- pkg/compiler/codegen.go
- pkg/compiler/for_test.go
Closes #674 .
Support basic `for .. range` loops.
> compiler: support for-range loops

- docs/rpc.md
- pkg/rpc/prometheus.go
- pkg/rpc/server.go
- pkg/rpc/server_test.go
- pkg/rpc/types.go
- pkg/rpc/wrappers/tx_output.go
> rpc: implement gettxout RPC

- pkg/compiler/codegen.go
- pkg/compiler/for_test.go
- pkg/compiler/switch_test.go
Closes #677  .
Implements 4-th point from #628 .
May be it looks a bit heavy, I am open for suggestions.
> compiler: support break statement in for loops and switch statements

- pkg/core/storage/memcached_store.go
- pkg/core/storage/memory_store.go
> storage: add locking into (*MemoryStore).Seek

- pkg/compiler/codegen.go
- pkg/compiler/func_scope.go
- pkg/vm/emit/emit.go
> compiler: use uint16 for labels

- pkg/rpc/client/rpc.go
- pkg/rpc/request/txTypes.go
> rpc: rename (*Client).SendToAddress to TransferAsset

- docs/rpc.md
- pkg/rpc/server/prometheus.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_helper_test.go
- pkg/rpc/server/server_test.go
> rpc: implement getrawmempool RPC

- docs/rpc.md
- pkg/rpc/server/prometheus.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
> rpc: implement gettransactionheight

- cli/flags/address.go
- cli/flags/util.go
- cli/wallet/wallet.go
This makes code less verbose and performs all parsing
before invoking main function.
> cli: implement AddressFlag

- docs/rpc.md
- pkg/core/blockchain.go
- pkg/core/blockchainer.go
- pkg/network/helper_test.go
- pkg/rpc/response/result/validator.go
- pkg/rpc/server/prometheus.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
> rpc: implement getvalidators

- pkg/compiler/codegen.go
- pkg/compiler/switch_test.go
> compiler: implement fallthrough in switch

- pkg/compiler/interop_test.go
- pkg/core/blockchain.go
- pkg/vm/context.go
- pkg/vm/json_test.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
> vm: add support for dynamic invocations in APPCALL

- docs/rpc.md
- pkg/rpc/response/result/unclaimed.go
- pkg/rpc/server/prometheus.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
> rpc: implement getunclaimed

- pkg/vm/context.go
- pkg/vm/stack.go
- pkg/vm/stack_item.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
> vm: implement EQUAL opcode properly

- cli/wallet/nep5.go
- pkg/rpc/client/nep5.go
We have TransferAsset for regular tokens, so it'd be nice to have TransferNEP5
for NEP5 ones. Relates to #599.
> rpc/client: add TransferNEP5 method to easily transfer tokens

- pkg/core/blockchain.go
> State tx verifications

- pkg/core/blockchain.go
> core: add owner hash to verified list for Register TX

- pkg/core/blockchain.go
- pkg/core/dao_test.go
- pkg/core/state/notification_event.go
- pkg/core/state/notification_event_test.go
- pkg/rpc/response/result/application_log.go
- pkg/smartcontract/parameter.go
- pkg/smartcontract/parameter_test.go
> core/state: marshal AppExecResult.Stack as an array

- cli/flags/fixed8.go
> cli: fix type in flags.Fixed8FromContext

- pkg/rpc/response/result/invoke.go
Follow C# implementation:
https://docs.neo.org/docs/en-us/reference/rpc/latest-version/api/invokefunction.html
> rpc: fix stack field name for invocation results

- README.md
- docs/cli.md
- docs/compiler.md
Goreportcard doesn't support branching, sorry: https://github.com/gojp/goreportcard/issues/96
And Godoc too: https://github.com/golang/gddo/issues/593
> README/docs: add 3.0 notice, update links to relative

- cli/smartcontract/smart_contract.go
> cli: check for method presence for invokefunction commands

- pkg/network/message.go
Follow neo-project/neo#710 changes.
> network: drop checksums from messages

- pkg/vm/vm.go
- pkg/vm/vm_test.go
Follow neo-project/neo-vm#257 change for Neo 3.
> vm: disallow negative shifts for SHL/SHR

- pkg/core/helper_test.go
- pkg/network/server_test.go
> core,network: shutdown services in tests properly

- pkg/core/helper_test.go
- pkg/internal/testchain/address.go
- pkg/rpc/server/server_test.go
Set up hash once and get header via provided chain.
> rpc: simplify RPC tests

- README.md
Fix some heading along the way.
> README: update with workshop links and block import examples

- go.mod
- go.sum
- pkg/rpc/client/client.go
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/client/wsclient.go
- pkg/rpc/client/wsclient_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_helper_test.go
- pkg/rpc/server/server_test.go
> RPC over websocket (2.x)

- go.mod
- go.sum
- pkg/rpc/client/client.go
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/client/wsclient.go
- pkg/rpc/client/wsclient_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_helper_test.go
- pkg/rpc/server/server_test.go
This is a port of #921 to the master branch.
> RPC over websocket

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/func_scope.go
- pkg/compiler/function_call_test.go
- pkg/compiler/return_test.go
> compiler: allow empty returns

- examples/token/nep5/nep5.go
> examples: Use "or" operator in transfer check of NEP5 token

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/slice_test.go
- pkg/compiler/struct_test.go
> compiler: support nested struct selectors

- pkg/vm/vm.go
- pkg/vm/vm_test.go
> vm: update stack size in SETITEM properly

- pkg/network/payload/getblocks.go
- pkg/network/payload/getblocks_test.go
- pkg/network/server.go
> protocol: refactor getblocks payload

- pkg/network/message.go
- pkg/network/message_string.go
- pkg/network/payload/getblockdata.go
- pkg/network/payload/getblockdata_test.go
- pkg/network/server.go
> protocol: implement getblockdata p2p command

- pkg/internal/testserdes/testing.go
- pkg/network/compress.go
- pkg/network/message.go
- pkg/network/message_test.go
> protocol: add payload compression

- config/protocol.mainnet.yml
- config/protocol.testnet.yml
New magic numbers, seed lists and testnet standby validators from neo-node.
> config: update testnet and mainnet configurations

- pkg/network/capability/capability.go
- pkg/network/capability/type.go
- pkg/network/discovery.go
- pkg/network/discovery_test.go
- pkg/network/helper_test.go
- pkg/network/payload/address.go
- pkg/network/payload/address_test.go
- pkg/network/payload/version.go
- pkg/network/payload/version_test.go
- pkg/network/peer.go
- pkg/network/server.go
- pkg/network/server_test.go
- pkg/network/tcp_peer.go
- pkg/network/tcp_peer_test.go
- pkg/network/tcp_transport.go
- pkg/network/transport.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/response/result/version.go
> protocol: add node capabilities

- pkg/core/dao/cacheddao.go
Lower Cached state shouldn't be changed until Persist. Fixes #994.
> dao: split GetStorageItem for Cached into external and internal versions

- pkg/core/mpt/base.go
- pkg/core/mpt/branch.go
- pkg/core/mpt/extension.go
- pkg/core/mpt/hash.go
- pkg/core/mpt/leaf.go
- pkg/core/mpt/node.go
- pkg/core/mpt/proof.go
- pkg/core/mpt/trie.go
~6h testnet block import didn't reach even 1M.
Release the handbrake (and import 1M blocks in 6m30s).
> Optimize mpt 2.x neox

- go.mod
- go.sum
The same one as #1007 and #1009, but for the master (somehow I've forgotten to create this PR yesterday).
> update dbft to include CountFailed and RecoveryMessage changes

- go.mod
- go.sum
- pkg/consensus/block.go
- pkg/consensus/block_test.go
- pkg/consensus/consensus.go
- pkg/consensus/prepare_request.go
- pkg/consensus/prepare_request_test.go
Duplicate of #1007 for master-2.x
> consensus: update dbft to include CountFailed and RecoveryMessage changes

- pkg/core/blockchain.go
> core: respect MaxFreeTransactionsPerBlock setting

- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/core/blockchain.go
- pkg/core/blockchainer.go
- pkg/core/cache/cache.go
- pkg/core/cache/cache_test.go
- pkg/core/state/mpt_root.go
- pkg/core/state/mpt_root_test.go
- pkg/network/helper_test.go
- pkg/network/server.go
- pkg/rpc/client/wsclient_test.go
- pkg/rpc/request/param.go
- pkg/rpc/request/param_test.go
- pkg/rpc/request/params.go
- pkg/rpc/response/result/mpt.go
- pkg/rpc/response/result/mpt_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
Implement missing RPC calls and P2P handlers.
> rpc: implement MPT-related RPC (2.x)

- pkg/network/server.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/response/result/version.go
- pkg/rpc/server/server.go
> rpc: update `getversion` RPC-call

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/interop_test.go
- pkg/interop/util/util.go
Closes #999 .
Support removing items from collections via REMOVE opcode.
> compiler: implement Remove builtin (2.x)

- go.mod
- go.sum
- pkg/consensus/consensus.go
> consensus: verify state root in PrepareRequest

- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/interop/context.go
- pkg/core/native/contract.go
- pkg/core/native/native_gas.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_nep5.go
- pkg/core/native_contract_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
- pkg/rpc/server/subscription_test.go
Closes #1060 .
After native contracts are deployed, single persist script is created
and executed at the start of every block persisting.
> core,native: persist native contract via VM

- config/protocol.mainnet.yml
- config/protocol.privnet.docker.four.yml
- config/protocol.privnet.docker.one.yml
- config/protocol.privnet.docker.single.yml
- config/protocol.privnet.docker.three.yml
- config/protocol.privnet.docker.two.yml
- config/protocol.privnet.yml
- config/protocol.testnet.yml
- config/protocol.unit_testnet.yml
- pkg/config/protocol_config.go
- pkg/consensus/consensus_test.go
- pkg/core/blockchain.go
- pkg/core/mempool/feer.go
- pkg/core/mempool/mem_pool.go
- pkg/core/mempool/mem_pool_test.go
- pkg/core/native_contract_test.go
- pkg/network/helper_test.go
- pkg/rpc/server/server_helper_test.go
> Remove logic related to free transactions

- pkg/network/message.go
- pkg/network/payload/payload.go
> Allow NullPayload only for CMDGetAddr

- pkg/core/blockchain.go
- pkg/core/blockchainer/blockchainer.go
- pkg/core/dao/cacheddao_test.go
- pkg/core/dao/dao.go
- pkg/core/dao/dao_test.go
- pkg/core/interop_neo.go
- pkg/core/interop_neo_test.go
- pkg/core/interop_system.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_nep5.go
- pkg/network/helper_test.go
- pkg/rpc/server/server.go
> core: store smartcontract items by id

- pkg/network/message.go
Recent 9f42108ef completely broke handshaking.
> message: fix Verack processsing

- pkg/compiler/codegen.go
Closes #961 .
Related #906 .
For slices gain is ~4x,  for maps with value variable ~1.5x (~2.x with the last commit)
> Implement for-range loop without iterators

- pkg/core/blockchain.go
- pkg/core/blockchainer.go
- pkg/core/dao/dao.go
- pkg/network/helper_test.go
- pkg/network/server.go
- pkg/network/tcp_peer.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
> Request verified state roots

- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
> rpc: add GetStorageByID RPC client method

- config/protocol.mainnet.yml
- config/protocol.testnet.yml
- go.mod
- go.sum
- pkg/config/protocol_config.go
- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/core/blockchain.go
- pkg/core/helper_test.go
- pkg/core/mempool/mem_pool.go
- pkg/core/native/blocked_accounts.go
- pkg/core/native/blocked_accounts_test.go
- pkg/core/native/contract.go
- pkg/core/native/policy.go
- pkg/core/native_policy_test.go
- pkg/network/compress.go
- pkg/network/message.go
- pkg/network/payload/payload.go
- pkg/rpc/client/policy.go
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/smartcontract/parameter.go
- pkg/smartcontract/parameter_test.go
> core: add native policy contract

- pkg/network/server.go
Closes #1074 .
CMDMempool returns hashes of transactions in mempool in chunks.
> network: implement CMDMempool command

- pkg/core/blockchain.go
- pkg/core/dao/dao.go
We don't want to do extra work.
> core,dao: use MPT only if it is enabled in config

- pkg/compiler/codegen.go
- pkg/compiler/compiler.go
- pkg/compiler/debug.go
- pkg/compiler/debug_test.go
> compiler: update debug.json format

- pkg/compiler/codegen.go
- pkg/compiler/slice_test.go
- pkg/compiler/struct_test.go
> Allow to omit types and struct field names in contracts

- pkg/core/native/native_neo.go
Closes #1094 .
Will test a bit.
> native: cache GetValidators result

- pkg/interop/crypto/crypto.go
Follow 7d786fac79b430b4ba4a53c6c934d276afc6d1fc update.
> interop: fix key recovery functions documentation

- pkg/rpc/client/rpc_test.go
- pkg/rpc/client/state.go
- pkg/rpc/server/server_test.go
> Add missing neox rpc client wrappers

- cli/wallet/multisig.go
- cli/wallet/nep5.go
- cli/wallet/wallet.go
- docs/cli.md
- pkg/consensus/consensus.go
- pkg/rpc/client/nep5.go
- pkg/rpc/client/rpc.go
Fix small bugs and one critical regarding merkle root construction.
> Fix `wallet nep5 transfer` command

- README.md
- docs/neox.md
Update 2.x documentation with neox info.
> docs: add neox documentation

- pkg/core/blockchain_test.go
- pkg/rpc/server/server.go
Same as #1113, but for master-2.x.
> Fix test failures 2.x

- pkg/core/blockchain_test.go
- pkg/rpc/server/server.go
I'm getting tired of these failing tests, so there is a fix.
> Fix test failures

- pkg/vm/cli/cli.go
Add `loadbase64` and fix some minor issues.
> VM CLI update

- pkg/compiler/codegen.go
- pkg/compiler/func_scope.go
- pkg/compiler/function_call_test.go
> Support variadic functions in compiler

- pkg/compiler/codegen.go
- pkg/compiler/function_call_test.go
> compiler: support `...` variadic calls

- .docker/privnet-entrypoint.sh
- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/consensus/recovery_message.go
- pkg/core/blockchain_test.go
- pkg/crypto/keys/publickey.go
- pkg/crypto/keys/publickey_test.go
- pkg/io/binaryReader.go
- pkg/io/binaryrw_test.go
- pkg/rpc/client/wsclient_test.go
- pkg/rpc/request/param.go
- pkg/rpc/request/param_test.go
- pkg/rpc/request/params.go
- pkg/rpc/server/server.go
Some good changes were made to master-2.x while master would also benefit from them.
Forward-port everything relevant to the master branch. The only original new change here is default ACC removal, other than that everything is already tested and proven in master-2.x.
> Forward port from 2.x

- pkg/consensus/consensus.go
- pkg/consensus/payload.go
> consensus: take payload hash based on data

- pkg/compiler/codegen.go
- pkg/compiler/func_scope.go
- pkg/compiler/global_test.go
- pkg/compiler/vars.go
> compiler: support variable shadowing

- cli/smartcontract/smart_contract.go
- pkg/rpc/client/nep5.go
- pkg/rpc/client/policy.go
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/request/txBuilder.go
#1134.
Fix it and improve some associated code.
@AlexVanin --- can you try it out? I don't have a properly set up private net at the moment (with non-multisig address owning any GAS).
> Fix deployment sysfee and invokes

- .docker/wallets/wallet1.json
- .docker/wallets/wallet1_solo.json
- .docker/wallets/wallet2.json
- .docker/wallets/wallet3.json
- .docker/wallets/wallet4.json
- pkg/consensus/testdata/wallet1.json
- pkg/consensus/testdata/wallet2.json
- pkg/consensus/testdata/wallet3.json
- pkg/consensus/testdata/wallet4.json
- pkg/wallet/account.go
- pkg/wallet/account_test.go
- pkg/wallet/testdata/wallet1.json
- pkg/wallet/testdata/wallet2.json
Related #1015.
This change is also pre-preview2.
https://github.com/neo-project/neo/pull/1199
> wallet: marshal script in base64

- cli/wallet/nep5.go
- examples/runtime/runtime.go
- examples/storage/storage.go
- examples/token/nep5/nep5.go
- examples/token/token.go
- pkg/compiler/codegen.go
- pkg/compiler/debug.go
- pkg/compiler/debug_test.go
1. Exclude unexported methods from manifest.json
2. Update examples in order to generate correct manifest.json files
3. Update ANT owner for workshop
> compiler, cli: update manifest.json format

- pkg/compiler/codegen.go
- pkg/compiler/interop_test.go
- pkg/compiler/syscall.go
- pkg/interop/runtime/runtime.go
#1152, #1153 and wrong trigger constants.
Merge.
> Interop and compiler fixes for 3.0

- pkg/compiler/codegen.go
- pkg/compiler/interop_test.go
> compiler: compile appcall with dynamic argument

- pkg/compiler/codegen.go
- pkg/compiler/slice_test.go
- pkg/compiler/struct_test.go
> Fix struct default init

- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/blockchainer/blockchainer.go
- pkg/core/helper_test.go
- pkg/core/mempool/feer.go
- pkg/core/mempool/mem_pool.go
- pkg/core/mempool/mem_pool_test.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_nep5.go
- pkg/core/state/nep5.go
- pkg/core/state/nep5_test.go
- pkg/network/helper_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_helper_test.go
- pkg/rpc/server/server_test.go
> core: store NEP5 transfers and balances as big.Int

- pkg/core/mempool/mem_pool.go
- pkg/core/mempool/mem_pool_test.go
> core: prevent concurrent map writes during (*mp).Verify

- go.mod
- go.sum
- pkg/consensus/block.go
- pkg/consensus/change_view.go
- pkg/consensus/change_view_test.go
- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/consensus/payload_test.go
- pkg/consensus/prepare_request.go
- pkg/consensus/prepare_request_test.go
- pkg/consensus/recovery_message.go
- pkg/consensus/recovery_message_test.go
- pkg/consensus/recovery_request.go
- pkg/consensus/recovery_request_test.go
- pkg/core/blockchain.go
- pkg/core/blockchainer/blockchainer.go
- pkg/core/native/native_neo.go
- pkg/network/helper_test.go
Our consensus is not compatible with C#.
Fix timestamps, add CV reasons, fix some other minor issues. This branch works fine in 4-node private network with 2 C# nodes and 2 neo-go nodes.
> Update dbft, add 64-bit timestamps and cv reasons

- examples/engine/engine.go
- pkg/compiler/codegen.go
- pkg/core/interop_system.go
> core, compiler: return tx from GetScriptContainer interop

- pkg/core/interop/context.go
- pkg/core/interops.go
- pkg/vm/interop.go
- pkg/vm/json_test.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
> core, vm: remove allowed triggers from syscalls

- pkg/compiler/codegen.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
Follow neo-project/neo-vm#317 .
Close #1208 .
> vm: make offset in PUSHA relative

- pkg/core/blockchain.go
- pkg/core/blockchainer/blockchainer.go
- pkg/core/dao/cacheddao.go
- pkg/core/dao/dao.go
- pkg/core/interop_neo.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_nep5.go
- pkg/core/state/nep5.go
- pkg/core/state/nep5_test.go
- pkg/core/storage/store.go
- pkg/network/helper_test.go
- pkg/rpc/server/server.go
> core: store contract IDs instead of hashes for NEP5Balances and Transfers

- pkg/network/compress.go
> network: add uncompressed payload size

- examples/token/nep5/nep5.go
- examples/token/token.go
- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/compiler.go
- pkg/compiler/debug.go
- pkg/compiler/func_scope.go
- pkg/compiler/global_test.go
- pkg/compiler/testdata/foo/foo.go
- pkg/compiler/testdata/multi/file1.go
- pkg/compiler/testdata/multi/file2.go
- pkg/compiler/testdata/strange/normal.go
- pkg/compiler/vm_test.go
> Allow to use exported variables and constants

- pkg/smartcontract/nef/nef.go
> smartcontract: calculate double-SHA256 for .nef files

- pkg/compiler/panic_test.go
- pkg/compiler/vm_test.go
- pkg/core/interop_neo.go
- pkg/core/interop_system.go
- pkg/core/interop_system_test.go
- pkg/core/native/interop.go
- pkg/vm/interop.go
- pkg/vm/stack.go
- pkg/vm/stackitem/item.go
- pkg/vm/stackitem/json.go
> Ensure strings are valid UTF-8 where appropriate

- pkg/core/native_policy_test.go
> core: fix native policy tests

- pkg/core/native/policy.go
- pkg/network/message.go
- pkg/network/message_string.go
- pkg/network/payload/getblockbyindex.go
- pkg/network/payload/getblockbyindex_test.go
- pkg/network/server.go
- pkg/network/server_test.go
- pkg/network/tcp_peer.go
> protocol: request blocks by index

- pkg/consensus/consensus.go
Closes #1270
But I still need to check whether the problem is solved.
> consensus: create recovery message with state root

- .circleci/config.yml
- .travis.yml
- Makefile
- README.md
- go.mod
Not as fancy as #1281, but let's cut it there too.
> [2.x] Drop go 1.12 support

- cli/smartcontract/smart_contract.go
- pkg/core/blockchain.go
- pkg/core/blockchainer.go
- pkg/core/interop_neo.go
- pkg/network/helper_test.go
- pkg/rpc/client/nep5.go
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/request/param.go
- pkg/rpc/request/param_test.go
- pkg/rpc/server/server.go
Closes #1275
Mostly ported from 3x
> rpc: use hashes for verifying in `invoke*` calls

- pkg/core/native_neo_test.go
> core: fix failing tests after merge

- pkg/core/interop_system.go
- pkg/core/interop_system_test.go
- pkg/core/native/contract.go
- pkg/smartcontract/param_type.go
- pkg/vm/context.go
- pkg/vm/emit/emit.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
> Check return values count for external contract calls

- config/protocol.mainnet.yml
- docs/neox.md
- go.mod
- go.sum
- pkg/consensus/change_view.go
- pkg/consensus/change_view_test.go
- pkg/consensus/commit.go
- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/consensus/payload.go
- pkg/consensus/payload_test.go
- pkg/consensus/prepare_request.go
- pkg/consensus/prepare_response.go
- pkg/consensus/recovery_message.go
- pkg/consensus/recovery_request.go
- pkg/consensus/recovery_request_test.go
- pkg/network/server.go
#1273.
Right there. To be updated with the real dbft commit.
> Stateroot relaying during commit 2.x

- pkg/consensus/payload_test.go
> consensus: add test for payload.Verify

- pkg/consensus/consensus.go
#1313 and potential problem with stateroots being sent before StateRootEnableIndex happened.
> Fix stateroot generation

- pkg/rpc/client/nep5.go
- pkg/rpc/server/client_test.go
Add missing argument and write tests.
> rpc: fix (*Client).BalanceOf

- go.mod
- go.sum
> go.mod: update dbft version

- pkg/consensus/consensus.go
> consensus: exit if wrong password is provided in configuration

- pkg/network/helper_test.go
- pkg/network/peer.go
- pkg/network/server.go
- pkg/network/tcp_peer.go
Node only receiving new blocks via ping-pong mechanism with a visible delay.
> Fix block synchronization

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/interop_test.go
> compiler: allow to alias interop packages

- pkg/core/blockchain_test.go
> core: fix failing TestGetTransaction

- pkg/compiler/codegen.go
- pkg/compiler/interop_test.go
- pkg/compiler/jumps_test.go
- pkg/vm/cli/cli.go
- pkg/vm/context.go
> Emit short jumps where possible

- pkg/vm/json_test.go
- pkg/vm/stackitem/item.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
Post-preview3 VM changes.
Make our VM up to date.
> Post-preview3 VM updates

- pkg/compiler/codegen.go
- pkg/compiler/func_scope.go
- pkg/compiler/function_call_test.go
- pkg/compiler/switch_test.go
- pkg/compiler/vm_test.go
> compiler: drop unused call results

- pkg/compiler/codegen.go
- pkg/compiler/constant_test.go
> compiler: support `iota`

- cli/flags/address_test.go
- cli/flags/fixed8_test.go
- cli/flags/util_test.go
- cli/options/options_test.go
- cli/server/dump_test.go
- cli/server/server.go
- cli/server/server_test.go
- cli/smartcontract/smart_contract_test.go
- pkg/core/storage/store.go
Added a set of naive tests for different cli packages.
> cli: add non-integrational tests for cli packages

- cli/smartcontract/smart_contract.go
- cli/smartcontract/smart_contract_test.go
Add support of array parameters to cli.
> cli: add support for nested arrays

- pkg/smartcontract/manifest/manifest.go
Update MaxManifestSize constant.
> smartcontract: increase MaxManifestSize

- pkg/rpc/request/txBuilder.go
- pkg/rpc/request/tx_builder_test.go
Should be done together with #1363. Also removed
CreateInvocationScript function as we don't have `Invoke` RPC-call
anymore.
> rpc: allow to use arrays in expandArrayIntoScript

- docs/compiler.md
- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/defer_test.go
- pkg/compiler/func_scope.go
- pkg/compiler/global_test.go
- pkg/compiler/if_test.go
- pkg/compiler/lambda_test.go
- pkg/compiler/panic_test.go
- pkg/vm/emit/emit.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
> Support `defer` statement

- pkg/network/blockqueue.go
- pkg/network/blockqueue_test.go
> network: restrict block queue size

- examples/token-sale/token_sale.go
Closes #1379
We should check owner witness before adding more tokens to circulation.
Also we shouldn't allow to add to circulation more than TokenSupply
tokens.
> examples: fix AddToCirculation method of TokenSale

- config/protocol.mainnet.yml
- config/protocol.testnet.yml
- pkg/config/protocol_config.go
- pkg/config/protocol_config_test.go
- pkg/core/blockchain.go
- pkg/core/interop_neo.go
And update default mainnet/testnet settings. Follow neo-project/neo#1888 and
neo-project/neo-node#656.
> config: allow configuring free gas depending on height

- go.mod
- go.sum
- pkg/consensus/consensus.go
- pkg/consensus/payload.go
- pkg/consensus/payload_test.go
- pkg/consensus/recovery_message_test.go
- pkg/core/block/block_base.go
- pkg/core/blockchain.go
- pkg/core/blockchainer/blockchainer.go
- pkg/core/dao/dao.go
- pkg/core/dao/dao_test.go
- pkg/core/interop/crypto/ecdsa.go
- pkg/core/interop/crypto/hash.go
- pkg/core/interop_neo_test.go
- pkg/core/interop_system_test.go
- pkg/core/mempool/feer.go
- pkg/core/mempool/mem_pool.go
- pkg/core/mempool/mem_pool_test.go
- pkg/core/state/mpt_root.go
- pkg/core/storage/leveldb_store.go
- pkg/core/transaction/transaction.go
- pkg/crypto/keys/private_key.go
- pkg/crypto/keys/publickey.go
- pkg/crypto/keys/publickey_test.go
- pkg/crypto/verifiable.go
- pkg/network/message.go
- pkg/network/server.go
- pkg/rpc/response/types.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_helper_test.go
> Improve TPS, part 2

- config/protocol.mainnet.yml
- config/protocol.testnet.yml
- pkg/config/protocol_config.go
- pkg/core/blockchain.go
- pkg/rpc/server/server.go
Add support for minimum fee policy and fix related things.
> Minimum network fee

- config/protocol.mainnet.yml
- config/protocol.testnet.yml
- pkg/config/protocol_config.go
- pkg/core/blockchain.go
See neo-project/neo-modules#336.
> core|config: make max(free)txperblock height-dependent

- docs/compiler.md
- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/slice_test.go
- pkg/interop/util/util.go
1. Emit error for subslicing of non-byte slices.
2. Support removing slice elements in-place.
> Support removing elements from slice.

- config/protocol.testnet.yml
> config: update free GAS height again

- pkg/consensus/consensus.go
There is a notification pushed into the channel when block is being added,
that notification is read by special goroutine that then forwards it to all
subscribers to that particular event. Consensus goroutine is one of that
subscribers, so for the system to properly function it has to read these
events, but at the same time it can generate new blocks inside, so in some
cases it can generate two blocks without ever reading from the subscription
channel and this will lead to a deadlock.
To avoid that we need to check subscription channel for events on every loop.
This was discovered after some timer changes in the dbft library.
> consensus: fix potential system deadlock

- pkg/consensus/consensus.go
Fixes:
panic: assignment to entry in nil map
goroutine 227 [running]:
github.com/nspcc-dev/neo-go/pkg/core/storage.(*MemoryStore).put(...)
/home/rik/dev/neo-go/pkg/core/storage/memory_store.go:53
github.com/nspcc-dev/neo-go/pkg/core/storage.(*MemoryStore).PutBatch(0xc00035f580, 0x110a680, 0xc000336750, 0x0, 0x0)
/home/rik/dev/neo-go/pkg/core/storage/memory_store.go:93 +0x286
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).addHeaders(0xc0000a2340, 0xc0001be301, 0xc00036d428, 0x1, 0x1, 0x0, 0x0)
/home/rik/dev/neo-go/pkg/core/blockchain.go:516 +0xd5a
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).AddBlock(0xc0000a2340, 0xc0000bc2c0, 0x0, 0x0)
/home/rik/dev/neo-go/pkg/core/blockchain.go:407 +0x9ca
github.com/nspcc-dev/neo-go/pkg/consensus.(*service).processBlock(0xc000152160, …
> consensus: wait goroutine to finish on Shutdown

- config/protocol.mainnet.yml
> config: follow freegasheight update

- pkg/core/blockchain.go
- pkg/core/state/notification_event.go
- pkg/core/state/notification_event_test.go
- pkg/rpc/server/server.go
> core: do not marshal block hash in application log

- pkg/core/blockchain.go
- pkg/core/blockchainer/blockchainer.go
- pkg/network/helper_test.go
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
> core, rpc: add GetCommittee method

- docs/rpc.md
- pkg/consensus/consensus.go
- pkg/core/blockchain.go
- pkg/core/blockchainer/blockchainer.go
- pkg/core/dao/cacheddao.go
- pkg/core/dao/dao.go
- pkg/core/mpt/hash.go
- pkg/core/state/nep5.go
- pkg/core/state/nep5_test.go
- pkg/encoding/bigint/bigint.go
- pkg/network/helper_test.go
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
Forward-port useful changes from 0.78.0 to master.
> Port from 2.x

- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/interop/context.go
- pkg/core/interop/contract/call.go
- pkg/core/interop_system.go
- pkg/core/interop_system_test.go
- pkg/core/interops.go
- pkg/core/native/contract.go
- pkg/core/native/interop.go
- pkg/core/native/native_neo.go
- pkg/core/native/oracle.go
- pkg/core/native/oracle_types.go
- pkg/core/native/oracle_types_test.go
- pkg/core/native_contract_test.go
- pkg/core/native_neo_test.go
- pkg/core/native_oracle_test.go
Implement basis for the oracle contract along with some tests.
> Implement Oracle contract

- pkg/core/blockchain_test.go
- pkg/core/interop/runtime/witness.go
- pkg/core/native_neo_test.go
- pkg/core/native_oracle_test.go
See neo-project/neo#1924 and neo-project/neo#1925.
Leaving tests for #1366.
> interop/runtime: allow calling script hash to pass CheckWitness

- cli/executor_test.go
- cli/multisig_test.go
- cli/nep5_test.go
- cli/wallet/multisig.go
- cli/wallet/nep5.go
- pkg/rpc/client/rpc.go
Better help, options and errors.
> CLI wallet usability improvements

- pkg/core/native/native_neo.go
- pkg/core/native/oracle.go
Introduced in bd1790bd , 83e94d3b .
Fix #1431.
Testing done:
1. Create dump.
2. Run node from restored dump.
> Initialize cache in native contracts properly

- pkg/core/native/native_neo.go
> native: remove unregistered candidate with 0 votes on NEO transfer

- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/native/contract.go
- pkg/core/native/designate.go
- pkg/core/native/oracle.go
- pkg/core/native/util.go
- pkg/core/native_designate_test.go
- pkg/core/native_oracle_test.go
> native: implement Designate contract

- pkg/core/native_designate_test.go
Merge conflict between #1450 and #1451.
...
...
> core: fix designate test

- pkg/consensus/prepare_request.go
- pkg/consensus/prepare_request_test.go
- pkg/core/block/block.go
- pkg/core/block/block_test.go
- pkg/core/native/policy.go
- pkg/core/native_policy_test.go
- pkg/network/payload/merkleblock.go
- pkg/network/payload/merkleblock_test.go
> core: add validation to policy methods

- cli/wallet/multisig.go
- pkg/consensus/consensus_test.go
- pkg/core/blockchain_test.go
- pkg/core/fee/calculate.go
- pkg/core/fee/opcode.go
- pkg/core/gas_price.go
- pkg/core/helper_test.go
- pkg/core/native/oracle.go
- pkg/core/util.go
- pkg/crypto/keys/publickey.go
- pkg/crypto/keys/sign_verify_test.go
- pkg/rpc/client/rpc.go
- pkg/rpc/server/client_test.go
- pkg/rpc/server/server_test.go
> Some fixes for core, crypto

- pkg/core/transaction/transaction.go
- pkg/core/transaction/witness.go
- pkg/core/transaction/witness_test.go
- pkg/network/payload/address.go
- pkg/network/payload/address_test.go
- pkg/network/payload/version.go
- pkg/network/server.go
- pkg/smartcontract/manifest/manifest.go
- pkg/smartcontract/nef/nef.go
- pkg/vm/stackitem/serialization.go
We don't have some useful limits C# node has.
Add them.
> Fix protocol limits

- pkg/core/blockchain.go
- pkg/core/native/policy.go
> core: add cache to Policy blocked accounts

- pkg/core/blockchain.go
- pkg/core/state/notification_event.go
- pkg/core/state/notification_event_test.go
- pkg/rpc/client/nep5.go
- pkg/rpc/client/policy.go
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/response/result/invoke.go
- pkg/rpc/server/server.go
> rpc, core: add FaultException to AppExecResult and Invoke* results

- pkg/core/interop/context.go
- pkg/core/interop/contract/call.go
- pkg/core/interop/runtime/util.go
- pkg/core/interop_system_test.go
- pkg/vm/vm.go
> core: remove error from runtime.GetInvocationCounter

- pkg/core/blockchain_test.go
- pkg/core/native/oracle.go
- pkg/core/native/oracle_types.go
- pkg/core/native/oracle_types_test.go
- pkg/core/state/oracle.go
- pkg/core/state/oracle_test.go
- pkg/smartcontract/contract.go
1. Move `OracleRequest` to state.
2. Abstract `M` calculating for  default vefirication script `(len-(len-1)/3)`
> Some small improvements

- pkg/network/discovery.go
- pkg/network/discovery_test.go
- pkg/network/server.go
> Fix empty discovery pool

- pkg/core/storage/boltdb_store.go
> storage: fix Get for BoltDB, fix #1482

- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
Related neo-project/neo#1995 .
> core: allow to invoke `verify` of native contracts

- pkg/vm/stack.go
- pkg/vm/vm.go
Optimize some very bad code and fix invocation counter checks.
> Minor VM fixes

- pkg/rpc/client/rpc_test.go
- pkg/rpc/response/result/invoke.go
- pkg/rpc/server/server.go
> rpc: add tx to invoke* results, support hex for uint160 params

- pkg/core/native/native_neo.go
> native: lower voting fee

- pkg/core/interop/runtime/witness.go
- pkg/core/interop_system_test.go
> core: add CheckWitness tests

- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/dao/dao.go
- pkg/core/dao/dao_test.go
- pkg/core/mempool/feer.go
- pkg/core/mempool/mem_pool.go
- pkg/core/mempool/mem_pool_test.go
- pkg/core/transaction/attribute.go
- pkg/core/transaction/attribute_test.go
- pkg/core/transaction/attrtype.go
- pkg/core/transaction/attrtype_string.go
- pkg/core/transaction/conflicts.go
- pkg/core/transaction/transaction.go
- pkg/core/transaction/transaction_test.go
- pkg/network/helper_test.go
- pkg/rpc/server/server_helper_test.go
> core: implement Conflicts transaction attribute

- pkg/core/interop_system.go
- pkg/core/interop_system_test.go
> core: adjust storage update fees

- cli/multisig_test.go
- cli/nep5_test.go
- cli/options/options_test.go
- cli/options_test.go
- cli/wallet/multisig.go
- cli/wallet/nep5.go
- cli/wallet/validator.go
- cli/wallet/wallet.go
- docs/rpc.md
- pkg/core/blockchain.go
- pkg/core/blockchainer/blockchainer.go
- pkg/core/native/contract.go
- pkg/network/helper_test.go
- pkg/rpc/client/client.go
- pkg/rpc/client/nep5.go
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/server/client_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
> rpc: allow to `getcontractstate` by id or name

- pkg/core/native/oracle.go
> native: add events to oracle contract

- config/protocol.mainnet.yml
- config/protocol.privnet.docker.four.yml
- config/protocol.privnet.docker.one.yml
- config/protocol.privnet.docker.single.yml
- config/protocol.privnet.docker.three.yml
- config/protocol.privnet.docker.two.yml
- config/protocol.privnet.yml
- config/protocol.testnet.yml
- config/protocol.unit_testnet.single.yml
- config/protocol.unit_testnet.yml
- pkg/config/protocol_config.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/interop_system.go
- pkg/core/transaction/oracle.go
- pkg/core/transaction/transaction.go
> Tune some limits

- pkg/rpc/request/types.go
- pkg/rpc/response/types.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
Close #1509
Port changes from #1514 to master-2x
> rpc: allow batch JSON-RPC requests

- pkg/core/transaction/oracle.go
> transaction: add new oracle response codes

- go.mod
- go.sum
- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/consensus/testdata/wallet1.json
- pkg/core/native/native_neo.go
> consensus: update NextConsensus only when committee is recalculated

- cli/main.go
- examples/timer/timer.go
> examples: add an example of binary.Itoa usage

- pkg/core/native/policy.go
> core: remove policy default values initialisation

- pkg/core/blockchain.go
- pkg/core/blockchainer.go
- pkg/core/mempool/feer.go
- pkg/core/mempool/mem_pool.go
- pkg/core/mempool/mem_pool_test.go
- pkg/network/server.go
- pkg/rpc/server/server_helper_test.go
> network: retransmit stale transactions

- pkg/core/mempool/mem_pool.go
- pkg/core/mempool/mem_pool_test.go
- pkg/network/server.go
> network: retransmit stale transactions (master)

- pkg/smartcontract/nef/nef.go
- pkg/smartcontract/nef/nef_test.go
It should be able to parse versions like `1.1.1-rc.1`.
Close #1540.
> smartcontract: fix nef.GetVersion

- cli/executor_test.go
- cli/wallet/nep5.go
- pkg/core/blockchain.go
- pkg/rpc/response/result/nep5.go
- pkg/rpc/response/result/tx_raw_output.go
- pkg/rpc/server/server.go
... help us to interact with C# nodes.
> rpc, cli: tiny compatibility fixes

- pkg/core/interop_system.go
We should check that the provided notification item does not exceed
the size limits.
> core: adjust System.Runtime.Notify interop

- pkg/config/protocol_config.go
- pkg/core/blockchain.go
- pkg/core/dao/dao.go
- pkg/core/mpt/base.go
- pkg/core/mpt/node.go
- pkg/core/mpt/node_test.go
- pkg/core/mpt/proof.go
- pkg/core/mpt/proof_test.go
- pkg/core/mpt/trie.go
- pkg/core/mpt/trie_test.go
Port #1503 to master.
TODO: testing (restore, local privnet).
> Implement MPT reference counting (master)

- pkg/core/blockchain_test.go
- pkg/core/helper_test.go
> core: add test for `RemoveUntraceableBlocks` setting

- pkg/core/blockchain_test.go
> core: add tests for `Blockchain.isTxStillRelevant()`

- pkg/consensus/consensus_test.go
- pkg/core/native/native_neo.go
Was changed in https://github.com/neo-project/neo/pull/1848. Affects
storage dumps.
> core: update committee every [committee length] blocks

- pkg/network/server.go
- pkg/network/server_test.go
Blockcache size is 2000, while max request size is 500.
Try to fetch blocks in chunks starting from current height.
Lower height has priority.
Close #1376 .
> network: fetch blocks in parallel

- cli/smartcontract/smart_contract.go
- go.mod
- go.sum
- pkg/vm/cli/cli.go
- pkg/vm/cli/cli_test.go
- pkg/vm/context.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
> Add tests for `vmcli`

- config/protocol.mainnet.yml
- config/protocol.testnet.yml
- config/protocol.unit_testnet.yml
With its default value set to `false`.
> config: add KeepOnlyLatestState setting where EnableStateRoot is set

- pkg/network/discovery.go
It happens from time to time in a four-node private network where there are
seeds (aka CNs) and not a lot of other nodes to connect to.
I don't know how to test for an infinite loop that has no side-effects, so no
test added here.
> network: drop requests to discovery pool when it can't be handled

- pkg/core/native/notary.go
- pkg/core/native_notary_test.go
Anyone can change deposit's `till` for free.
Set the default value in `onPayment` method.
> core: allow to change deposit's `till` for owner only

- pkg/compiler/codegen.go
- pkg/compiler/debug.go
- pkg/compiler/interop_test.go
Small QOL change. Can be useful to prevent small typos.
> compiler: enforce `Hash160` and `Hash256` size in literals

- cli/contract_test.go
- cli/executor_test.go
- cli/smartcontract/smart_contract.go
- pkg/rpc/response/result/invoke.go
- pkg/rpc/response/result/invoke_test.go
> cli/smartcontract: return error if deploy script failed to run

- cli/smartcontract/smart_contract.go
- cli/smartcontract/smart_contract_test.go
- examples/token-sale/token_sale.yml
- examples/token/token.yml
- internal/testchain/transaction.go
- pkg/compiler/compiler.go
- pkg/compiler/debug.go
- pkg/compiler/debug_test.go
- pkg/compiler/interop_test.go
- pkg/smartcontract/manifest/standard/nep17.go
> Set `Safe` flag in emitted manifest

- pkg/vm/stackitem/json.go
- pkg/vm/stackitem/json_test.go
Encode both `Buffer` and `ByteString` to UTF-8 bytes.
Follow https://github.com/neo-project/neo/pull/1715 .
> stackitem: fix JSON encoding

- pkg/core/mempool/mem_pool.go
- pkg/core/mempool/mem_pool_test.go
> [master-2.x] core: fix bug with mempool.verifiedMap

- pkg/core/blockchain.go
- pkg/core/helper_test.go
- pkg/core/native/management.go
- pkg/core/native/management_test.go
- pkg/core/native_management_test.go
> native: cache contract in Management contract

- cli/contract_test.go
- cli/smartcontract/smart_contract.go
> cli: allow to calculate contract hash before deployment

- config/protocol.unit_testnet.single.yml
- config/protocol.unit_testnet.yml
- pkg/core/native/management.go
- pkg/core/native_management_test.go
- pkg/core/native_policy_test.go
Changes ported from https://github.com/neo-project/neo/pull/2140, https://github.com/neo-project/neo/pull/2153 and https://github.com/neo-project/neo/pull/2150.
TBD:
> core: managment contract updates

- pkg/core/blockchain.go
- pkg/core/blockchainer/blockchainer.go
- pkg/network/helper_test.go
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/request/param.go
- pkg/rpc/request/param_test.go
- pkg/rpc/server/client_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
Not exactly the https://github.com/neo-project/neo-modules/pull/378#issuecomment-722652859 but changes ported from https://github.com/neo-project/neo-modules/pull/409.
> rpc: add `invokecontractverify` RPC-method

- pkg/consensus/payload_test.go
> consensus: update binary payload tests

- pkg/core/blockchain_test.go
- pkg/core/interop_system_test.go
- pkg/core/state/notification_event.go
- pkg/core/state/notification_event_test.go
- pkg/vm/stackitem/serialization.go
- pkg/vm/stackitem/type.go
It still lossy (it can't be otherwise), but now is done
similar to JSON serialization.### Problem
Close #1627 .
> vm: allow to serialize interop items

- pkg/core/native/management.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_nep17.go
- pkg/core/native/policy.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
> core: preview4 compatibility fixes

- pkg/core/transaction/oracle.go
Changes ported from https://github.com/neo-project/neo/pull/2164 for preview-4.
UPD: not for preview-4, I was wrong.
> core: add ProtocolNotSupported oracle response code

- pkg/core/blockchain.go
- pkg/network/message.go
- pkg/network/server.go
- pkg/network/tcp_peer.go
- pkg/rpc/response/result/tx_raw_output.go
- pkg/rpc/response/result/unclaimed.go
- pkg/rpc/server/server.go
- pkg/vm/cli/cli.go
- pkg/vm/context.go
- pkg/vm/vm.go
> Backport fixes from master to 2.x

- pkg/vm/cli/cli.go
- pkg/vm/cli/cli_test.go
Close #1585 .
I've decided not to implement (3) and (4) because of small practical utility.
> vmcli: use manifest for method execution

- cli/nep17_test.go
- cli/testdata/wallet1_solo.json
- cli/wallet/nep17.go
> cli: use default adress in transfer

- internal/testchain/transaction.go
- pkg/core/blockchain_test.go
- pkg/core/helper_test.go
- pkg/core/native/contract.go
- pkg/core/native/management.go
- pkg/core/native/native_neo.go
- pkg/core/native/notary.go
- pkg/core/native/policy.go
- pkg/core/native/util.go
- pkg/core/native_notary_test.go
- pkg/core/native_policy_test.go
> Check for committee witness in native contracts

- pkg/core/blockchain.go
- pkg/core/interop/contract/call.go
- pkg/core/interop_system_test.go
- pkg/core/native_management_test.go
- pkg/vm/context.go
- pkg/vm/vm.go
Depends on #1672 .
Closes #1644 .
> Implement CALLT opcode

- cli/candidate_test.go
- cli/wallet/validator.go
- pkg/consensus/consensus_test.go
- pkg/core/native/native_neo.go
> native: make registering as a candidate cost more

- pkg/vm/vm_test.go
> vm: add test for neo-project/neo-vm#393

- pkg/core/helper_test.go
- pkg/core/native/contract.go
- pkg/core/native/name_service.go
- pkg/core/native/name_service_test.go
- pkg/core/native/nativenames/names.go
- pkg/core/native/nonfungible.go
- pkg/core/native/util.go
- pkg/core/native_name_service_test.go
- pkg/core/native_policy_test.go
- pkg/core/state/nonfungible.go
- pkg/core/state/nonfungible_test.go
- pkg/vm/interop.go
> Implement NameService

- docs/rpc.md
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
See neo-project/neo-modules#504.
> rpc: add getblockheadercount call

- internal/fakechain/fakechain.go
- pkg/compiler/interop_test.go
- pkg/core/blockchain.go
- pkg/core/blockchainer/blockchainer.go
- pkg/core/helper_test.go
- pkg/core/interop/context.go
- pkg/core/interop_neo_test.go
- pkg/core/interop_system_test.go
- pkg/core/native/designate.go
- pkg/core/native/interop.go
- pkg/core/native/management.go
- pkg/core/native/management_test.go
- pkg/core/native/name_service.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_nep17.go
- pkg/core/native/nonfungible.go
- pkg/core/native/notary.go
- pkg/core/native/oracle.go
- pkg/core/native/policy.go
- pkg/core/native_contract_test.go
- pkg/core/native_oracle_test.go
- pkg/core/state/contract.go
- pkg/core/state/contract_test.go
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/server/client_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
> Implement `getnativecontracts` RPC

- examples/token/nep17/nep17.go
> examples: add `onNEP17Payment` invocation

- pkg/consensus/payload_test.go
Close #1685 .
Verify test was removed because verification is done outside `consensus` now.
> consensus/test: update binary payload data

- pkg/compiler/native_test.go
- pkg/interop/native/gas/gas.go
- pkg/interop/native/nameservice/name_service.go
- pkg/interop/native/neo/neo.go
> interop: allow transfer calls to read states

- pkg/compiler/debug_test.go
- pkg/core/native/ledger.go
- pkg/core/native/management.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_nep17.go
- pkg/core/native/nonfungible.go
- pkg/core/native_management_test.go
- pkg/smartcontract/manifest/manifest.go
- pkg/smartcontract/manifest/manifest_test.go
- scripts/compare-dumps.go
> core: preview-5 states difference fixes

- pkg/core/native/designate.go
> core: fix native designateAsRole method

- pkg/consensus/consensus.go
- pkg/io/binaryReader.go
- pkg/util/fixed8.go
- pkg/util/fixed8_test.go
Some assorted fixed from the master branch.
@fyrchik, I'm not sure we need #1754.
> [2.x] Backport from 3.0

- cli/flags/address.go
- cli/flags/address_test.go
- cli/smartcontract/smart_contract.go
- cli/wallet/nep17.go
- cli/wallet/wallet.go
> cli: support Uint160 hashes with 0x prefix

- pkg/core/notary_test.go
- pkg/services/notary/notary.go
> services: update Notary transaction size after completion

- .github/workflows/publish_to_dockerhub.yml
- pkg/core/oracle_test.go
Close #573
This workflow tags and publishes images to Dockerhub:
* ~~Every `push` to `master` branch~~
* Every release
For successful workflow runs the following secrets need to be set in the
repository `Secrets` section:
* `DOCKERHUB_USERNAME` - the username to publish images to DockerHub
* `DOCKERHUB_PASSWORD` - the password of `DOCKERHUB_USERNAME`
> github: setup github workflow to publish to DockerHub

- pkg/compiler/analysis.go
- pkg/compiler/func_scope.go
- pkg/compiler/inline.go
- pkg/compiler/inline_test.go
- pkg/compiler/syscall_test.go
- pkg/interop/binary/binary.go
> Allow to use inlined functions during global var init

- .github/workflows/publish_to_dockerhub.yml
It will help us to publish previous releases or intermediate refs.
> github: allow to publish image from any ref

- .github/workflows/publish_to_dockerhub.yml
* Fix cache folder
* Verbose `go mod download`
> github: fix go mod cache

- cli/smartcontract/smart_contract.go
Some invocations can't succeed without proper amount of system fee paid, for example contract migrations. But `invokefunction` always sets 0 there.
Additional parameter to specify system fee gas.
This is a preliminary test version, IIRC it couldn't contain fractional part and we can check for it.
> [2.x] cli: allow specifying system fee via -s for invocations

- pkg/core/blockchain.go
- pkg/core/dao/cacheddao.go
- pkg/core/dao/dao.go
- pkg/core/state/nep17.go
> dao: do not look up new NEP17 batch

- pkg/core/interops.go
> core/test: fix parameter count for `CreateMultisigAccount`

- pkg/core/native/designate.go
- pkg/core/native_designate_test.go
Port https://github.com/neo-project/neo/pull/2377 .
> native: add `NeoFSAlphabet` node role

- cli/wallet/wallet.go
- cli/wallet_test.go
- pkg/vm/contract_checks.go
- pkg/vm/contract_checks_test.go
Close #1810 .
```
> bin/neo-go wallet dump -w .docker/wallets/wallet1_solo.json --address NVNvVRW5Q5naSx2k2iZm7xRgtRNGuZppAK
1 out of 1 multisig contract:
02b3622bf4017bdfe317c58aed5f4c753f206b7db896046fa7d774bbc4bf7f8dc2
> bin/neo-go wallet dump -w .docker/wallets/wallet1_solo.json --address NUVPACMnKFhpuHjsRjhUvXz1XhqfGZYVtY
3 out of 4 multisig contract:
02103a7f7dd016558597f7960d27c516a4394fd968b9e65155eb4b013e4040406e
02a7bc55fe8684e0119768d104ba30795bdcc86619e864add26156723ed185cd62
02b3622bf4017bdfe317c58aed5f4c753f206b7db896046fa7d774bbc4bf7f8dc2
03d90c07df63e690ce77912e10ab51acc944b66860237b608c4f8f8309e71ee699
> bin/neo-go wallet dump -w .docker/wallets/wallet1_solo.json --address NbTiM6h8r99kpRtb428XcsUk1TzKed2gTc
Simple signature contract: …
```
> Allow to dump public keys in CLI

- cli/multisig_test.go
- cli/paramcontext/context.go
- cli/wallet/multisig.go
- cli/wallet/wallet.go
- pkg/smartcontract/context/context.go
- pkg/smartcontract/context/context_test.go
- pkg/smartcontract/context/item.go
- pkg/smartcontract/context/item_test.go
> cli: allow to sign dumped transaction by several non-multisig signers

- pkg/core/fee/opcode.go
> core/fee: alter opcode prices

- config/protocol.mainnet.yml
- config/protocol.privnet.docker.four.yml
- config/protocol.privnet.docker.one.yml
- config/protocol.privnet.docker.single.yml
- config/protocol.privnet.docker.three.yml
- config/protocol.privnet.docker.two.yml
- config/protocol.privnet.yml
- config/protocol.testnet.yml
- config/protocol.unit_testnet.single.yml
- config/protocol.unit_testnet.yml
- pkg/compiler/native_test.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/protocol_config.go
- pkg/config/testdata/protocol.test.yml
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/interop/context.go
- pkg/core/native/compatibility_test.go
- pkg/core/native/contract.go
- pkg/core/native/interop.go
- pkg/core/native/management.go
- pkg/core/native/nativenames/names.go
- pkg/core/native/nativenames_test.go
- pkg/core/native_contract_test.go
- pkg/core/state/contract.go
- pkg/rpc/server/server_test.go
> config: add NativeUpdateHistory

- pkg/compiler/syscall_test.go
- pkg/core/interop/interopnames/names.go
- pkg/core/interop_system.go
- pkg/core/interop_system_test.go
- pkg/core/interops.go
- pkg/interop/contract/contract.go
Ported https://github.com/neo-project/neo/pull/2400.
> core: remove System.Contract.IsStandard

- pkg/config/protocol_config.go
- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/core/block/block.go
- pkg/core/block/block_test.go
- pkg/core/blockchain.go
- pkg/network/server.go
Ported neo-modules#517:
1. Commit from https://github.com/nspcc-dev/neo-go/pull/1824#issuecomment-795847590 (the second commit is already implemented in 4df8a2ad36951efdf05c616bcd3c946d931af0d4)
2. Add `MaxBlockSize` setting (partially reverted https://github.com/nspcc-dev/neo-go/pull/1759/commits/ffd85dd51de5b237c7402534a7a272cdaba46404)
3. Add `MaxBlockSystemFee` setting
> consensus: add MaxBlockSize and MaxBlockSysFee settings

- pkg/rpc/client/native.go
- pkg/rpc/client/policy.go
- pkg/rpc/client/rpc_test.go
> Extend RPC client

- pkg/consensus/consensus.go
Issue: panic during mixed 4-nodes consensus setup:
```
2021-03-18T12:01:50.715Z	INFO	skip change view	{"nc": 0, "nf": 3}
2021-03-18T12:01:52.786Z	INFO	received ChangeView	{"validator": 0, "reason": "Timeout", "new view": 1}
2021-03-18T12:01:53.602Z	INFO	received ChangeView	{"validator": 2, "reason": "Timeout", "new view": 1}
2021-03-18T12:01:56.736Z	INFO	received ChangeView	{"validator": 1, "reason": "Timeout", "new view": 1}
2021-03-18T12:01:56.736Z	INFO	changing dbft view	{"height": 3, "view": 1, "index": 3, "role": "Backup"}
2021-03-18T12:02:01.758Z	INFO	received PrepareRequest	{"validator": 2, "tx": 0}
panic: interface conversion: block.Block is nil, not *consensus.neoBlock
goroutine 315 [running]:
github.com/nspcc-dev/neo-go/pkg/consensus.(*service).verifyBlock(0xc000419540, 0x0, …
```
> consensus: fix panic during verifyBlock

- pkg/consensus/payload_test.go
- pkg/consensus/prepare_request.go
- pkg/consensus/prepare_request_test.go
- pkg/consensus/recovery_message_test.go
> consensus: remove nonce from PrepareRequest

- pkg/compiler/native_test.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/helper_test.go
- pkg/core/native/designate.go
- pkg/core/native/nativeprices/prices.go
- pkg/core/native/noderoles/roles.go
- pkg/core/native/notary.go
- pkg/core/native/oracle.go
- pkg/core/native_designate_test.go
- pkg/core/native_notary_test.go
- pkg/core/native_oracle_test.go
- pkg/core/notary_test.go
- pkg/core/oracle_test.go
- pkg/core/stateroot_test.go
- pkg/rpc/client/native.go
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
> rpc: add (*Client).GetDesignatedByRole method

- pkg/config/oracle_config.go
- pkg/core/oracle_test.go
- pkg/services/oracle/neofs/neofs.go
- pkg/services/oracle/neofs/neofs_test.go
- pkg/services/oracle/oracle.go
- pkg/services/oracle/request.go
A number of problems.
A number of fixes.
> Fix oracle request processing

- cli/smartcontract/smart_contract.go
> cli/smartcontract: allow deploying contracts from multisig accounts

- README.md
- docs/consensus.md
- docs/oracle.md
- docs/stateroots.md
> More documentation

- pkg/core/blockchain.go
- pkg/core/state/nep5.go
One is related to #1833 (it doesn't change anything balance-wise, but might be useful for transfer tracking), the other one fixes #1900.
> NEP5 tracking fixes

- .github/workflows/codeql-analysis.yml
> experimental codeql workflow

- cli/contract_test.go
- cli/smartcontract/smart_contract.go
- cli/testdata/deploy/main.go
Close #1898.
Depends on #1906.
> cli: allow to provide 'data' for 'contract deploy' command

- pkg/core/notary_test.go
This test is failing from time to time.
> core: fix `Condition never satisfied` test error

- cli/wallet/wallet.go
- cli/wallet_test.go
This PR unifies wallet-related commands descriptions and arguments.
> cli: inspect and refactor wallet-related commands

- pkg/rpc/request/param.go
- pkg/rpc/request/txBuilder.go
- pkg/rpc/request/tx_builder_test.go
> rpc/request: allow to provide bool parameters

- pkg/core/native/designate.go
- pkg/core/native_designate_test.go
- pkg/interop/native/roles/roles.go
> native: emit `Designation` event on role update

- pkg/core/interop/storage/find.go
- pkg/core/interop_neo.go
- pkg/core/interop_neo_test.go
- pkg/core/native/nonfungible.go
> interop: strip full prefix in `System.Storage.Find`

- pkg/compiler/native_test.go
- pkg/compiler/syscall_test.go
- pkg/core/interop/interopnames/names.go
- pkg/core/interop/runtime/engine.go
- pkg/core/interop_system_test.go
- pkg/core/interops.go
- pkg/core/native/native_gas.go
- pkg/core/native_gas_test.go
- pkg/interop/native/gas/gas.go
- pkg/interop/runtime/runtime.go
> Implement burning GAS and refueling

- pkg/compiler/debug_test.go
- pkg/smartcontract/manifest/container.go
- pkg/smartcontract/manifest/container_test.go
- pkg/smartcontract/manifest/manifest.go
- pkg/smartcontract/manifest/manifest_test.go
- pkg/smartcontract/manifest/parameter.go
- pkg/smartcontract/manifest/permission.go
> smartcontract: use permission descriptors for manifest's trusts

- cli/nep11_test.go
- cli/nep17_test.go
- cli/testdata/verify.go
- cli/testdata/verify.yml
- cli/testdata/wallet1_solo.json
- cli/wallet/nep11.go
- cli/wallet/nep17.go
- examples/nft-nd/nft.go
- pkg/compiler/compiler_test.go
- pkg/compiler/native_test.go
- pkg/core/interop_system_test.go
- pkg/core/native/nonfungible.go
- pkg/core/native_name_service_test.go
- pkg/interop/native/nameservice/name_service.go
- pkg/rpc/client/nep11.go
- pkg/rpc/server/client_test.go
- pkg/smartcontract/manifest/standard/nep11.go
- pkg/smartcontract/manifest/standard/payable.go
> *: add `data` to NEP11 Transfer

- pkg/config/application_config.go
- pkg/core/blockchain.go
- pkg/network/extpool/pool.go
- pkg/network/extpool/pool_test.go
- pkg/network/server.go
- pkg/network/server_config.go
> Prevent network DoS attack using Extensible payloads 

- pkg/compiler/codegen.go
- pkg/compiler/debug.go
- pkg/compiler/debug_test.go
Close #1952 .
Also add local variables info to `_initialize` and `_deploy`.
> Emit debug info for static variables

- cli/testdata/testwallet.json
- cli/testdata/wallet1_solo.json
- cli/testdata/wallets/testwallet_NEO3.json
- docs/cli.md
- examples/my_wallet.json
- pkg/consensus/testdata/wallet1.json
- pkg/consensus/testdata/wallet2.json
- pkg/consensus/testdata/wallet3.json
- pkg/consensus/testdata/wallet4.json
- pkg/services/notary/testdata/notary1.json
- pkg/services/notary/testdata/notary2.json
- pkg/services/oracle/testdata/oracle1.json
- pkg/services/oracle/testdata/oracle2.json
- pkg/wallet/account.go
- pkg/wallet/testdata/wallet1.json
- pkg/wallet/testdata/wallet2.json
> wallet: rename `isdefault` to `isDefault`

- docs/cli.md
> docs: add node configuration docs.

- pkg/compiler/analysis.go
- pkg/compiler/native_test.go
- pkg/core/native/native_neo.go
- pkg/core/native_neo_test.go
- pkg/interop/native/neo/neo.go
> native/neo: add `getAccountState` method, close #1975

- pkg/vm/cli/cli.go
- pkg/vm/cli/cli_test.go
- pkg/vm/vm.go
> vm, cli: allow to specify flags while loading VM

- cli/candidate_test.go
- cli/wallet/validator.go
> cli: add description to `vote` command on how to `unvote`

- config/protocol.unit_testnet.yml
- pkg/core/mempool/mem_pool.go
- pkg/core/mempool/subscriptions.go
- pkg/core/mempool/subscriptions_test.go
- pkg/core/mempoolevent/event.go
- pkg/network/payload/notary_request.go
- pkg/network/server.go
- pkg/rpc/client/wsclient.go
- pkg/rpc/response/events.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
- pkg/rpc/server/subscription.go
- pkg/rpc/server/subscription_test.go
- pkg/services/notary/notary.go
- pkg/vm/cli/cli_test.go
> rpc: support NotaryRequest notifications for Notifications subsystem

- cli/testdata/verify.yml
- pkg/compiler/codegen.go
- pkg/compiler/compiler_test.go
- pkg/compiler/inline.go
- pkg/compiler/syscall_test.go
> compiler: check event name length in `runtime.Notify`

- cli/smartcontract/permission.go
- cli/smartcontract/smart_contract.go
- cli/smartcontract/smart_contract_test.go
- cli/testdata/deploy/neo-go.yml
- examples/nft-nd-nns/nns.yml
- examples/nft-nd/nft.yml
- internal/testchain/transaction.go
- pkg/compiler/compiler.go
- pkg/compiler/debug.go
- pkg/compiler/debug_test.go
- pkg/compiler/interop_test.go
> cli,compiler: allow to specify manifest permissions

- pkg/core/fee/opcode.go
> core: add price for CALLT instruction

- pkg/core/helper_test.go
- pkg/core/native/native_nep17.go
- pkg/core/native_gas_test.go
- pkg/core/native_neo_test.go
NEP17 transfer is prohibited if from account doesn't have enough funds.
This commit fixes states diff in block 92057 where account
NfuwpaQ1A2xaeVbxWe8FRtaRgaMa8yF3YM initiates two NEO roundtrips with
amount exceeding the account's balance:
block 92057: value mismatch for key +////xTbYWBH3r5qhRKZAPFPHabKfb2vhQ==: QQMhAkwBIQOZZwEA vs QQMhAkwBIQN/ZwEA
block 92057: value mismatch for key +v///ws=: kqlddcitCg== vs tphddcitCg==
block 92057: value mismatch for key +v///xTbYWBH3r5qhRKZAPFPHabKfb2vhQ==: QQEhBUWyDu0W vs QQEhBWmhDu0W
C#'s applog (contains False and False on stack for both transfers):
```
{
"id" : 1,
"jsonrpc" : "2.0",
"result" : {
"executions" : [
{
"gasconsumed" : "11955500",
"exception" : null,
"stack" : [
{
"value" : false,
"type" : "Boolean"
},
{
"value" : false,
"type" : …
```
> core: do not allow NEP17 roundtrip in case of insufficient funds

- README.md
Add CodeQL, Tests from GethubWorkflows and unify the style.
> readme: improve badges

- cli/wallet/nep11.go
- cli/wallet/nep17.go
> cli: remove `Can't find matching token in the wallet` warning

- pkg/smartcontract/manifest/manifest_test.go
- pkg/smartcontract/manifest/permission.go
> Fix bugs in manifest permissions

- pkg/core/native/native_neo.go
`storage.Seek()` is rather expensive and we need only last updated value
of gas per vote in `PostPersist()`.
For the first 100K testnet blocks with default configuration (`VerifyBlocks: true`) the speed up is 5-6x (350 vs 66 sec on my laptop).
> native: cache GAS per vote values

- pkg/core/interop/runtime/engine.go
- pkg/core/interop/storage/find.go
- pkg/core/interop_system_test.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_neo_candidate.go
- pkg/core/native/neo_types.go
- pkg/core/native/oracle.go
- pkg/core/native/oracle_types.go
- pkg/core/native/oracle_types_test.go
- pkg/core/native/std.go
- pkg/core/native/std_test.go
- pkg/core/native_management_test.go
- pkg/core/native_oracle_test.go
- pkg/core/state/contract.go
- pkg/core/state/native_state.go
- pkg/core/state/notification_event.go
- pkg/core/state/notification_event_test.go
- pkg/core/state/oracle.go
- pkg/core/state/oracle_test.go
- pkg/rpc/response/result/invoke.go
- pkg/vm/stackitem/item.go
- pkg/vm/stackitem/json.go
- pkg/vm/stackitem/serialization.go
- pkg/vm/stackitem/serialization_test.go
- pkg/vm/stackitem/type.go
Better error handling and some bug fixes.
> Improve stackitem package

- pkg/core/mpt/batch.go
- pkg/core/mpt/batch_test.go
- pkg/core/mpt/trie.go
- pkg/core/mpt/trie_test.go
The state difference occured at block 268056.
Fix #2044.
> Don't create an extension node for the last branch child

- .circleci/config.yml
- pkg/core/native/management.go
- pkg/network/discovery_test.go
- pkg/network/tcp_transport.go
- pkg/rpc/server/subscription_test.go
> Fix some test failures

- pkg/compiler/syscall_test.go
- pkg/core/interop/interopnames/names.go
- pkg/core/interop/runtime/util.go
- pkg/core/interop_system_test.go
- pkg/core/interops.go
- pkg/interop/runtime/runtime.go
> interop/runtime: add `System.Runtime.GetNetwork`, fix #2038

- pkg/vm/stackitem/item.go
- pkg/vm/stackitem/item_test.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
> Fix OOM on struct cloning

- CONTRIBUTING.md
> CONTRIBUTING.md: add section for benchmarks

- config/protocol.mainnet.yml
- config/protocol.privnet.docker.four.yml
- config/protocol.privnet.docker.one.yml
- config/protocol.privnet.docker.single.yml
- config/protocol.privnet.docker.three.yml
- config/protocol.privnet.docker.two.yml
- config/protocol.testnet.yml
- docs/oracle.md
- pkg/config/oracle_config.go
- pkg/core/oracle_test.go
- pkg/core/transaction/oracle.go
- pkg/core/transaction/oracleresponsecode_string.go
- pkg/services/oracle/request.go
- pkg/services/oracle/request_test.go
> Check oracle response Content-Type header

- README.md
- docs/consensus.md
> docs: add more info about running a CN node on public networks

- config/protocol.testnet.yml
- pkg/config/netmode/netmode.go
See neo-project/neo-node#798 and https://github.com/neo-project/neo-node/releases/tag/v3.0.0-rc4
> config: update testnet magic for RC4

- cli/contract_test.go
- cli/dump_test.go
- cli/multisig_test.go
- cli/nep11_test.go
- cli/nep17_test.go
- cli/wallet_test.go
- pkg/core/stateroot_test.go
- pkg/core/storage/boltdb_store_test.go
- pkg/vm/cli/cli_test.go
BoltDB test failed for me, but the problem is a bit wider. Refs. #1319.
> Improve temp file/dir handling in tests

- config/protocol.mainnet.yml
- config/protocol.testnet.yml
- pkg/compiler/native_test.go
- pkg/config/protocol_config.go
- pkg/consensus/consensus_test.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/native/compatibility_test.go
- pkg/core/native/contract.go
- pkg/core/native/native_gas.go
- pkg/core/native/nativenames_test.go
- scripts/compare-dumps_test.go
> config: add InitialGASSupply, fix #2073

- cli/wallet/validator.go
- pkg/rpc/client/native.go
- pkg/rpc/client/rpc_test.go
Using 1001 GAS for it is not always correct.
> Improve candidate registering

- config/protocol.mainnet.yml
- pkg/config/netmode/netmode.go
- pkg/core/interop_system_test.go
It's NEO3, see neo-project/neo-node#795.
> config: update mainnet magic

- cli/query/query.go
- cli/query_test.go
> Fix query command

- pkg/core/notary_test.go
- pkg/services/notary/notary.go
Related #2063.
Here is a scenario for a deadlock:
1. Notary pool is listening for events and possibly forms new transaction (`OnNewRequest`) which calls `Blockchain.PoolTx` in callback.
2. `AddBlock` removes stale transactions in mempool, and generates events on the way. As comment indicates, `RemoveStale` should run with blockchain mutex taken.
If `PoolTx` in (1) is called during (2), there will be a deadlock. Because `PoolTx` needs to take blockchain mutex on read.
Current solution: send events in a separate goroutine, but I am not yet convinced this fixes the problem completely, will do some more investigation.
> mempool: send events in a separate goroutine

- docs/compiler.md
> docs/compiler.md: document contract configuration

- pkg/core/blockchain.go
- pkg/core/dao/cacheddao.go
- pkg/core/interop/context.go
- pkg/core/native/ledger.go
This helps on core-rich machines crunching huge blocks.
> Improve big block processing

- pkg/core/fee/opcode.go
- pkg/core/fee/opcode_test.go
- pkg/core/native/native_gas.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_nep17.go
- pkg/core/state/native_state.go
- pkg/vm/opcode/isvalid_test.go
- pkg/vm/opcode/opcode.go
- pkg/vm/ref_counter.go
- pkg/vm/stack.go
- pkg/vm/vm.go
These don't change a lot, but still they're good and and they're local, so shouldn't be a problem.
> Microoptimizations

- config/protocol.mainnet.yml
- config/protocol.testnet.yml
- pkg/config/protocol_config.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
> core: turn off GAS generation at 8M height

- pkg/core/mpt/base.go
- pkg/core/mpt/bench_test.go
- pkg/core/transaction/bench_test.go
- pkg/io/binaryWriter.go
- pkg/network/message.go
- pkg/network/message_test.go
1. Add `Grow` method.
2. Improve `WriteU*` methods.
> Some io package improvements

- pkg/core/interop/context.go
- pkg/core/interop/crypto/ecdsa_test.go
- pkg/core/interop/gas_price.go
- pkg/vm/slot.go
- pkg/vm/stack.go
- pkg/vm/vm.go
These don't give much, just remove some allocations/useless calls. But they cost nothing at the same time.
> VM-related microoptimizations

- docs/cli.md
- pkg/config/protocol_config.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/blockchainer/blockchainer.go
- pkg/core/blockchainer/blockqueuer.go
- pkg/core/dao/dao.go
- pkg/core/dao/dao_test.go
- pkg/core/storage/store.go
- pkg/network/blockqueue.go
- pkg/network/server.go
Best of #2019.
This PR contains several changes that are related to StateExchange process but don't affect the regular code.
> core, network: prepare basis for Insole module

- docs/cli.md
- pkg/crypto/keys/publickey.go
- pkg/crypto/keys/publickey_test.go
- pkg/vm/cli/cli.go
- pkg/vm/cli/cli_test.go
> vm/cli: add public key -> address conversion, fix #2121

- pkg/core/interop/contract/call.go
- pkg/core/native_policy_test.go
> contract: block calls to contracts via Policy contracts

- pkg/core/transaction/transaction.go
- pkg/core/transaction/transaction_test.go
- pkg/io/binaryReader.go
- pkg/network/payload/notary_request.go
> Decoding speedup

- pkg/core/interop/contract/call.go
- pkg/core/interop/crypto/ecdsa.go
- pkg/core/interop/iterator/interop.go
- pkg/core/interop/runtime/engine.go
- pkg/core/interop/runtime/util.go
- pkg/core/interop/runtime/witness.go
- pkg/core/interop_system.go
- pkg/core/native/interop.go
- pkg/vm/context.go
- pkg/vm/stack.go
- pkg/vm/vm.go
> Another round of VM microoptimizations

- pkg/core/native/policy.go
- pkg/core/native_policy_test.go
> native/policy: disallow blocking native contracts

- pkg/core/mpt/batch.go
- pkg/core/mpt/batch_test.go
- pkg/core/mpt/compat_test.go
- pkg/core/mpt/trie.go
- pkg/core/mpt/trie_test.go
Port https://github.com/neo-project/neo-modules/pull/634, waiting for the reference PR to settle.
> core: allow empty MPT Leaf values

- docs/vm.md
- pkg/vm/cli/cli.go
- pkg/vm/cli/cli_test.go
- pkg/vm/context.go
- pkg/vm/slot.go
- pkg/vm/vm.go
> vm: allow to dump slots

- docs/rpc.md
- pkg/core/block/header.go
- pkg/core/interop/context.go
- pkg/core/native/native_nep17.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/response/result/block_header.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
- pkg/smartcontract/nef/nef_test.go
> rpc: request handlers audit

- .circleci/config.yml
- .golangci.yml
- pkg/core/blockchain.go
- pkg/core/native/native_neo.go
> Replace golint with revive

- pkg/core/interop/interopnames/names.go
> core: remove unused interopnames

- pkg/core/blockchain.go
- pkg/core/native/native_neo.go
It's more like making it work, not optimizing.
> NEO voter optimizations

- cli/multisig_test.go
- cli/query/query.go
- cli/query_test.go
- cli/util/convert.go
- cli/util/dump.go
1. Dump tx before signing, close #2167,
2. Testinvoke before signing, close #2168.
> Improve `wallet sign` command

- cli/contract_test.go
- cli/smartcontract/smart_contract.go
- cli/smartcontract/smart_contract_test.go
- cli/testdata/invalid4/invalid.go
- cli/testdata/invalid4/invalid.yml
- examples/engine/engine.yml
- examples/events/events.yml
- examples/iterator/iterator.yml
- examples/nft-nd-nns/nns.yml
- examples/nft-nd/nft.yml
- examples/oracle/oracle.yml
- examples/runtime/runtime.yml
- examples/storage/storage.yml
- examples/timer/timer.yml
- examples/token-sale/token_sale.yml
- examples/token/token.yml
- pkg/compiler/compiler.go
- pkg/rpc/server/testdata/test_contract.yml
- pkg/smartcontract/nef/nef.go
- pkg/smartcontract/nef/nef_test.go
> nef: add Source field

- pkg/core/mempool/mem_pool.go
- pkg/rpc/response/errors.go
> Reword some error messages

- pkg/rpc/response/result/version.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
See neo-project/neo-modules#642.
> rpc: add validatorscount to getversion response

- .github/workflows/publish_to_dockerhub.yml
- .github/workflows/run_tests.yml
Outdated Ubuntu images for test workflows.
Update them.
> .github: update ubuntu image for test workflows

- cli/server/dump.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/dao/dao.go
- pkg/core/dao/dao_test.go
- pkg/core/mpt/billet.go
- pkg/core/mpt/billet_test.go
- pkg/core/mpt/trie.go
- pkg/core/stateroot/module.go
- pkg/core/stateroot/store.go
- pkg/core/statesync/module.go
- pkg/core/statesync/module_test.go
- pkg/core/statesync_test.go
- pkg/core/storage/store.go
> Faster state switch

- pkg/services/oracle/filter.go
- pkg/services/oracle/request.go
> oracle: unify filtering and add log for error case

- config/protocol.privnet.docker.four.yml
- config/protocol.privnet.docker.one.yml
- config/protocol.privnet.docker.single.yml
- config/protocol.privnet.docker.three.yml
- config/protocol.privnet.docker.two.yml
- pkg/services/helpers/rpcbroadcaster/client.go
Otherwise the following error occurs:
```
first path segment in URL cannot contain colon
```
Thanks to @fyrchik.
So now we can build and run privnet, vote for oracles, deploy oracle contract, submit oracle request and successfully get the response.
> config: use http for oracle node addresses

- pkg/compiler/codegen.go
- pkg/compiler/defer_test.go
- pkg/compiler/inline.go
> Fix defers in functions using inlined calls

- pkg/compiler/vm_test.go
- pkg/core/blockchain.go
- pkg/core/interop/context.go
- pkg/core/interop/contract/call.go
- pkg/core/interop/runtime/util.go
- pkg/core/interop/runtime/util_test.go
- pkg/core/interop_system_test.go
- pkg/core/native_contract_test.go
- pkg/rpc/request/txBuilder.go
- pkg/rpc/request/tx_builder_test.go
- pkg/rpc/response/result/invoke.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
- pkg/services/oracle/response.go
- pkg/vm/cli/cli.go
- pkg/vm/context.go
- pkg/vm/invocation_tree.go
- pkg/vm/invocation_tree_test.go
- pkg/vm/vm.go
RPC interface is preliminary and subject to change as neo-project/neo-modules#657 evolves, but the rest of it should be fine.
See https://github.com/neo-project/neo/pull/2613/files#r753302881 also.
> Add invoked contract tracing

- go.mod
- go.sum
- pkg/core/mempool/mem_pool.go
- pkg/core/mempool/mem_pool_test.go
- pkg/core/native/native_neo.go
- pkg/core/native/util.go
- pkg/core/storage/memcached_store.go
- pkg/crypto/keys/publickey.go
- pkg/encoding/bigint/bigint.go
- pkg/io/binaryWriter.go
- pkg/vm/context.go
- pkg/vm/json_test.go
- pkg/vm/opcodebench_test.go
- pkg/vm/slot.go
- pkg/vm/slot_test.go
- pkg/vm/stackitem/item.go
- pkg/vm/stackitem/json.go
- pkg/vm/stackitem/serialization.go
- pkg/vm/vm.go
Mostly allocation optimizations that allow us to more reliably cross the target TPS line. (needs a rebase after #2270 merge).
> Optimizations part N

- pkg/core/native/native_gas.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_nep17.go
- pkg/core/transaction/transaction.go
- pkg/core/transaction/transaction_test.go
- pkg/crypto/hash/hash.go
- pkg/vm/vm.go
> Trivial microoptimizations

- pkg/neotest/chain/chain.go
- pkg/neotest/signer.go
- pkg/neotest/signer_test.go
> Improve signers handling in test framework

- pkg/core/native/contract.go
- pkg/core/native/native_gas.go
- pkg/core/native_gas_test.go
> core: fix GAS distribution to primary node when notary enabled

- cli/nep17_test.go
- cli/wallet/nep17.go
> cli: print zero balance of known token if `token` flag specified

- cli/server/dump.go
- pkg/core/storage/store.go
- pkg/core/storage/store_test.go
- pkg/rpc/response/result/invoke.go
- pkg/rpc/response/result/invoke_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
> Extend invokefunction results

- docs/node-configuration.md
- internal/fakechain/fakechain.go
- pkg/config/config.go
- pkg/config/protocol_config.go
- pkg/config/protocol_config_test.go
- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/blockchainer/blockchainer.go
- pkg/core/interop/context.go
- pkg/core/native/native_gas.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_test/neo_test.go
- pkg/core/native/notary.go
- pkg/core/util.go
- pkg/crypto/keys/publickey.go
- pkg/network/server.go
- pkg/network/server_test.go
- pkg/network/tcp_peer.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
- scripts/gendump/main.go
Seems to work, at least on the unit-test level, but might need a bit more care.
> Extendable validators

- .github/workflows/run_tests.yml
- cli/contract_test.go
- cli/dump_test.go
- cli/executor_test.go
- cli/multisig_test.go
- cli/server/server.go
- cli/server/server_test.go
- cli/server_test.go
- cli/smartcontract/manifest.go
- cli/smartcontract/smart_contract.go
- cli/util_test.go
- cli/wallet/wallet.go
- cli/wallet_test.go
- codecov.yml
> cli: improve coverage

- pkg/compiler/codegen.go
- pkg/compiler/defer_test.go
- pkg/compiler/func_scope.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
> compiler: properly process `defer` in conditional statements

- pkg/core/blockchain.go
- pkg/core/stateroot/module.go
- pkg/core/stateroot/store.go
- pkg/core/storage/boltdb_store.go
- pkg/core/storage/leveldb_store.go
- pkg/core/storage/memcached_store_test.go
- pkg/core/storage/memory_store.go
- pkg/core/storage/store.go
- pkg/core/storage/storeandbatch_test.go
> GC optimizations

- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/dao/dao.go
- pkg/core/dao/dao_test.go
- pkg/core/statesync/module_test.go
- pkg/core/statesync_test.go
- pkg/core/storage/store.go
- pkg/core/storage/store_test.go
> Some DAO deduplication

- pkg/smartcontract/context/context.go
- pkg/smartcontract/context/context_test.go
> smartcontract: add hash check to paramcontext

- cli/smartcontract/generate.go
- cli/smartcontract/generate_test.go
- cli/smartcontract/smart_contract.go
- pkg/smartcontract/binding/generate.go
- pkg/smartcontract/binding/override.go
- pkg/smartcontract/binding/override_test.go
- pkg/smartcontract/callflag/call_flags.go
- pkg/smartcontract/callflag/call_flags_test.go
- pkg/util/uint160.go
- pkg/util/uint160_test.go
Close #2221 .
TODO: test on NeoFS contracts and see what happens.
> cli/smartcontract: generate bindings to an existing contract

- cli/smartcontract/smart_contract.go
- cli/wallet/nep11.go
- cli/wallet/nep17.go
- pkg/rpc/client/client.go
- pkg/rpc/client/nep11.go
- pkg/rpc/client/nep17.go
- pkg/rpc/client/policy.go
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/client/wsclient.go
- pkg/rpc/client/wsclient_test.go
- pkg/rpc/request/types.go
- pkg/rpc/server/client_test.go
Close #2357 and fix several bugs along the way.
TODO:
> rpc: take care of RPC clients

- cli/contract_test.go
- cli/smartcontract/generate.go
- cli/smartcontract/generate_test.go
- cli/smartcontract/smart_contract.go
- pkg/compiler/codegen.go
- pkg/compiler/compiler.go
- pkg/compiler/debug.go
- pkg/compiler/debug_test.go
- pkg/compiler/inline.go
Close #2358.
Depends on #2349 .
> Emit configuration file for bindings generation

- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/dao/dao.go
- pkg/core/helper_test.go
> core: add tests for non-zero blockchain start

- pkg/core/oracle_test.go
- pkg/services/oracle/network.go
- pkg/services/oracle/network_test.go
- pkg/services/oracle/oracle.go
- pkg/services/oracle/request.go
> services: check Oracle response redirections

- pkg/vm/stackitem/json.go
- pkg/vm/stackitem/json_test.go
> stackitem: limit JSON size in `ToJSONWithTypes`

- pkg/services/oracle/filter_test.go
- pkg/services/oracle/jsonpath/jsonpath.go
- pkg/services/oracle/jsonpath/jsonpath_test.go
> jsonpath: restrict amount of intermediate objects

- pkg/vm/contract_checks.go
- pkg/vm/contract_checks_test.go
`IsScriptCorrect` is not expected to panic.
> vm: avoid panic in `IsScriptCorrect`

- pkg/network/compress.go
- pkg/network/fuzz_test.go
- pkg/network/message_test.go
> network: check compressed payload size in `decompress`

- cli/options/options.go
- cli/query/query.go
> cli: improve help text a bit

- .github/workflows/build.yml
- .github/workflows/publish_to_dockerhub.yml
- Makefile
- docs/consensus.md
Related to
https://github.com/nspcc-dev/neo-go/pull/2408#pullrequestreview-921289314.
> github: add job to check privnet image build

- internal/fakechain/fakechain.go
- pkg/core/blockchain.go
- pkg/core/blockchainer/blockchainer.go
- pkg/core/dao/dao.go
- pkg/core/interop_system.go
- pkg/core/native/designate.go
- pkg/core/native/management.go
- pkg/core/native/native_neo.go
- pkg/core/native/oracle.go
- pkg/core/native/policy.go
- pkg/core/state/storage_item.go
Unnecessary complexity and waste of memory.
Red.
> Eliminate GetStorageItems

- pkg/services/notary/notary.go
> services: avoid changes in mempooled main notary tx

- go.mod
- go.sum
Fetch https://github.com/nspcc-dev/dbft/pull/57.
> gomod: upgrade dBFT revision

- pkg/rpc/client/helper.go
> (rpc): fix typo's

- cli/executor_test.go
- cli/server/server.go
- docs/cli.md
- docs/node-configuration.md
- pkg/consensus/consensus.go
- pkg/network/blockqueue.go
- pkg/network/server.go
- pkg/network/server_test.go
- pkg/rpc/rpc_config.go
- pkg/rpc/server/client_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_helper_test.go
- pkg/rpc/server/server_test.go
- pkg/rpc/server/subscription_test.go
- pkg/services/notary/notary.go
- pkg/services/oracle/oracle.go
- pkg/services/stateroot/service.go
- pkg/services/stateroot/validators.go
Not completely tested yet, fixes #2433 and adds some building blocks for #1949.
> Add StartWhenSynchronized option for RPC server

- pkg/rpc/client/wsclient.go
- pkg/rpc/client/wsclient_test.go
> rpc: avoid panic during WSClient request after WS connection is closed

- pkg/core/native/contract.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_test/neo_test.go
- pkg/crypto/keys/publickey.go
- pkg/vm/emit/emit.go
> Check policy for committee members

- cli/wallet/validator.go
- cli/wallet/wallet.go
> cli: unify password-related prompts

- pkg/services/oracle/network.go
- pkg/services/oracle/oracle.go
Be compatible with neo-project/neo-modules#698.
> oracle: limit the number of redirections to 2

- config/protocol.testnet.yml
- pkg/config/netmode/netmode.go
Syncs well with compatible stateroots as of now.
> T5 testnet

- pkg/vm/stackitem/item.go
- pkg/vm/vm_test.go
> vm: adjust comparable limit for ByteArray

- CHANGELOG.md
- pkg/core/native/std.go
- pkg/core/native/std_test.go
- pkg/vm/stackitem/json.go
Mainnet incompatibilities.
Aquí.
> Mainnet fixes

- pkg/crypto/hash/hash.go
> crypto: adjust Checksum documentation

- CHANGELOG.md
- pkg/core/native/native_gas.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_nep17.go
- pkg/core/native/native_test/neo_test.go
See neo-project/neo#2734.
(it won't merge as of now, but it's needed for 0.98.5)
> neo: mint GAS after NEO transfer processing

- pkg/core/native/interop.go
> core: pop native call arguments after call invocation

- pkg/core/storage/memcached_store.go
> core: avoid concurrent map r/w during SeekAsync

- cli/input/input.go
- cli/input/readpass_unix.go
- cli/input/readpass_windows.go
> cli: use tty to handle password

- pkg/rpc/response/errors.go
- pkg/rpc/server/server.go
> rpc: differentiate log level for RPC errors

- pkg/rpc/server/server.go
Close #2505. Turns out that existing limit is too low to fit
`submitp2pnotaryrequest`.
Thanks to @alexvanin for discovering this.
> rpc: increase server-side WS read limit for websocket RPC message

- go.mod
- go.sum
> go.mod: update dbft, pick up cv fix

- pkg/core/interops.go
Fix DoS, follow neo-project/neo#2748.
> core: raise System.Runtime.GetNotifications fee

- pkg/rpc/response/result/invoke.go
- pkg/rpc/response/result/invoke_test.go
> rpc: always marshal FaultException

- pkg/vm/stackitem/item.go
- pkg/vm/stackitem/item_test.go
- pkg/vm/stackitem/json.go
- pkg/vm/stackitem/json_test.go
- pkg/vm/stackitem/type.go
> vm: stringify InteropInterface stackitem type as `InteropInterface`

- pkg/core/blockchain.go
- pkg/core/dao/dao.go
- pkg/core/interop/context.go
- pkg/core/interop/contract/call.go
- pkg/core/interop/runtime/engine.go
- pkg/core/interop_system_neotest_test.go
- pkg/core/native/designate.go
- pkg/core/native/management.go
- pkg/core/native/native_nep17.go
- pkg/core/native/oracle.go
- pkg/neotest/client.go
- pkg/vm/context.go
- pkg/vm/vm.go
Close #2506, close #2509.
TODO:
> core, vm: implement snapshot isolation

- pkg/consensus/prepare_request.go
- pkg/core/blockchain.go
- pkg/core/dao/dao.go
- pkg/core/interop/contract/call.go
- pkg/core/interop/runtime/engine.go
- pkg/core/interop/runtime/engine_test.go
- pkg/core/native/management.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_nep17.go
- pkg/core/native/neo_types.go
- pkg/core/native/oracle.go
- pkg/core/native/std.go
- pkg/core/native/std_test.go
- pkg/core/native/util.go
- pkg/core/state/native_state.go
- pkg/core/state/notification_event.go
- pkg/core/state/tokens.go
- pkg/encoding/bigint/bench_test.go
- pkg/encoding/bigint/bigint.go
- pkg/util/bench_test.go
- pkg/util/uint160.go
- pkg/util/uint256.go
- pkg/vm/stack.go
- pkg/vm/stackitem/serialization.go
- pkg/vm/vm.go
Nothing radical here, nitpicking mostly. I guess we've lost some numbers during cache rework done earlier, but I'm not yet sure how to improve that.
> Minor performance improvements

- pkg/rpc/client/wsclient.go
Ref.
https://github.com/nspcc-dev/neofs-node/pull/1480#issuecomment-1147256917.
> rpc: improve WS connection closure error a bit

- Makefile
Follow the https://github.com/nspcc-dev/neo-go/pull/2537#issuecomment-1147468063.
Close #2529.
> Makefile: alias `build` target as `neo-go`

- pkg/core/transaction/fuzz_test.go
It's been in my queue for quite some time, nothing sensational, but let it be in the repo.
> transaction: add fuzz-test, refs. #2374

- pkg/consensus/consensus.go
- pkg/network/server.go
- pkg/services/notary/notary.go
- pkg/services/stateroot/validators.go
Subscribers serveces forgetting to unsubscribe or close subscription channel.
Unsubscribe and close subscription channel where needed.
> *: properly unsubscribe from Blockchain events

- go.mod
- go.sum
nspcc-dev/dbft#60
Update dependency.
> go.mod: update dbft, pick up cv save fix

- docs/rpc.md
Extend our doc based on #2563 finding.
> Add JSON enum doc

- cli/contract_test.go
- cli/nep17_test.go
- cli/query_test.go
- cli/smartcontract/manifest.go
- cli/smartcontract/smart_contract.go
- cli/wallet/legacy.go
- cli/wallet/multisig.go
- cli/wallet/nep11.go
- cli/wallet/nep17.go
- cli/wallet/validator.go
- cli/wallet/wallet.go
- cli/wallet_test.go
- pkg/consensus/consensus.go
- pkg/services/stateroot/service_test.go
- pkg/wallet/regenerate_test.go
- pkg/wallet/wallet.go
> cli: allow to specify wallet via configuration file

- pkg/rpcclient/client.go
- pkg/rpcclient/helper.go
- pkg/rpcclient/invoker/invoker.go
- pkg/rpcclient/invoker/invoker_test.go
- pkg/rpcclient/native.go
- pkg/rpcclient/nep.go
- pkg/rpcclient/nep11.go
- pkg/rpcclient/policy.go
- pkg/rpcclient/rpc.go
- pkg/services/rpcsrv/client_test.go
- pkg/smartcontract/doc.go
- pkg/smartcontract/entry.go
- pkg/smartcontract/parameter.go
- pkg/smartcontract/parameter_test.go
A number of #2597-related changes to flush the queue more quickly. More to follow.
> Smartcontract Parameters and Invoker interface

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/compiler.go
- pkg/compiler/compiler_test.go
- pkg/smartcontract/manifest/group.go
- pkg/smartcontract/manifest/group_test.go
- pkg/smartcontract/manifest/manifest.go
> compiler: disallow unnamed parameters for exported methods of the main package

- .docker/wallets/wallet1.json
- .docker/wallets/wallet1_solo.json
- .docker/wallets/wallet2.json
- .docker/wallets/wallet3.json
- .docker/wallets/wallet4.json
- cli/testdata/testwallet.json
- cli/testdata/wallet1_solo.json
- cli/testdata/wallets/testwallet_NEO3.json
- docs/cli.md
- examples/my_wallet.json
- pkg/consensus/testdata/wallet1.json
- pkg/consensus/testdata/wallet2.json
- pkg/consensus/testdata/wallet3.json
- pkg/consensus/testdata/wallet4.json
- pkg/services/notary/testdata/notary1.json
- pkg/services/notary/testdata/notary2.json
- pkg/services/oracle/testdata/oracle1.json
- pkg/services/oracle/testdata/oracle2.json
- pkg/wallet/testdata/wallet1.json
- pkg/wallet/testdata/wallet2.json
- pkg/wallet/wallet.go
> Fix wallet version

- cli/paramcontext/context.go
- cli/smartcontract/smart_contract.go
- cli/wallet/nep11.go
- cli/wallet/nep17.go
- cli/wallet/validator.go
- docs/rpc.md
- pkg/neorpc/result/version.go
- pkg/rpcclient/actor/actor.go
- pkg/rpcclient/actor/actor_test.go
- pkg/rpcclient/actor/maker.go
- pkg/rpcclient/actor/maker_test.go
- pkg/rpcclient/nep17.go
- pkg/rpcclient/rpc.go
- pkg/services/rpcsrv/client_test.go
- pkg/services/rpcsrv/server.go
- pkg/services/rpcsrv/server_test.go
- pkg/smartcontract/doc_test.go
- pkg/smartcontract/parameter.go
- pkg/smartcontract/parameter_test.go
- pkg/wallet/account.go
#2597
A part of it. TBD: deprecation warnings, RPCActor/RPCInvoke -> RPC, passing validators history with the version.
> RPC client Actor interface

- cli/wallet/validator.go
> Use Actor more in the CLI

- pkg/core/native/management.go
- pkg/services/rpcsrv/server_test.go
Affects states, see
https://github.com/neo-project/neo/blob/28ab45a6eca51bacadfa2b84c27f445b40e50a24/src/Neo/SmartContract/Native/ContractManagement.cs#L155.
> core: fix native Management's hasMethod signature

- cli/query/query.go
- cli/wallet/nep17.go
- cli/wallet/wallet.go
- pkg/rpcclient/nep17.go
- pkg/rpcclient/nep17/nep17.go
- pkg/rpcclient/nep17/nep17_test.go
- pkg/rpcclient/neptoken/base.go
- pkg/rpcclient/neptoken/base_test.go
- pkg/rpcclient/unwrap/unwrap.go
- pkg/services/rpcsrv/client_test.go
Multitransfers need a bit more time since they will be a bit different.
> NEP-17 RPC client

- cli/smartcontract/smart_contract.go
- pkg/core/state/contract.go
- pkg/core/state/contract_test.go
- pkg/rpcclient/management/management.go
- pkg/rpcclient/management/management_test.go
- pkg/rpcclient/native.go
- pkg/rpcclient/oracle/oracle.go
- pkg/rpcclient/oracle/oracle_test.go
- pkg/services/rpcsrv/client_test.go
> More native contract RPC wrappers

- cli/query/query.go
- cli/wallet/nep17.go
- cli/wallet/validator.go
- cli/wallet/wallet.go
- pkg/rpcclient/actor/actor_test.go
- pkg/rpcclient/invoker/invoker.go
- pkg/rpcclient/invoker/invoker_test.go
- pkg/rpcclient/native.go
- pkg/rpcclient/neo/neo.go
- pkg/rpcclient/neo/neo_test.go
- pkg/rpcclient/rolemgmt/roles.go
- pkg/rpcclient/unwrap/unwrap.go
- pkg/rpcclient/unwrap/unwrap_test.go
- pkg/services/rpcsrv/client_test.go
> NEO RPC wrapper

- cli/wallet/nep11.go
- pkg/rpcclient/nep11.go
- pkg/rpcclient/nep11/base.go
- pkg/rpcclient/nep11/base_test.go
- pkg/rpcclient/nep11/divisible.go
- pkg/rpcclient/nep11/divisible_test.go
- pkg/rpcclient/nep11/nondivisible.go
- pkg/rpcclient/nep11/nondivisible_test.go
- pkg/rpcclient/rpc.go
- pkg/rpcclient/unwrap/unwrap.go
- pkg/rpcclient/unwrap/unwrap_test.go
- pkg/services/rpcsrv/client_test.go
To be rebased after #2650 merge.
> NEP-11 RPC wrapper

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/global_test.go
- pkg/compiler/init_test.go
- pkg/compiler/inline_test.go
- pkg/compiler/syscall_test.go
- pkg/compiler/testdata/foo/foo.go
- pkg/compiler/testdata/globalvar/funccall/main.go
- pkg/compiler/testdata/globalvar/main.go
- pkg/compiler/testdata/globalvar/nested1/main.go
- pkg/compiler/testdata/globalvar/nested2/main.go
- pkg/compiler/testdata/globalvar/nested3/main.go
- pkg/compiler/vardecl_test.go
- pkg/compiler/verify_test.go
- pkg/compiler/vm_test.go
> compiler: do not emit initialisation code for unused global vars

- .circleci/config.yml
- .golangci.yml
- cli/server_test.go
- cli/wallet/wallet.go
- pkg/core/blockchain.go
- pkg/core/blockchain_core_test.go
- pkg/core/dao/dao.go
- pkg/core/mpt/billet.go
- pkg/core/native/management.go
- pkg/core/native/notary.go
- pkg/core/storage/leveldb_store.go
- pkg/neorpc/errors.go
- pkg/neorpc/result/validator_test.go
- pkg/network/message.go
- pkg/network/server.go
- pkg/network/tcp_peer.go
- pkg/rpcclient/wsclient.go
- pkg/services/metrics/metrics.go
- pkg/services/oracle/network_test.go
- pkg/services/oracle/request.go
- pkg/services/oracle/response.go
- pkg/services/rpcsrv/server.go
- pkg/services/rpcsrv/server_test.go
- pkg/services/rpcsrv/subscription_test.go
- pkg/vm/cli/cli.go
- pkg/vm/stackitem/json.go
I've notice that we have some warnings from the linter about outdated checks.
> Update linter config

- Makefile
- README.md
- pkg/vm/cli/cli_test.go
Some Go 1.16 remnants and unstable `git describe`.
> Tiny build corrections

- cli/contract_test.go
- cli/nep11_test.go
- cli/options/options.go
- cli/smartcontract/smart_contract.go
- cli/wallet/nep11.go
> Historic calls from CLI

- pkg/smartcontract/builder.go
- pkg/smartcontract/builder_test.go
Which is useful in some cases.
> smartcontract: add Len to Builder

- scripts/update_deps.sh
Failing `Check internal dependencies` job.
Merge.
> scripts: update dependency-updator script

- docs/compiler.md
- pkg/compiler/compiler.go
- pkg/compiler/compiler_test.go
- pkg/compiler/inline.go
- pkg/compiler/interop_test.go
- pkg/smartcontract/param_type.go
- pkg/smartcontract/param_type_test.go
> compiler: enforce runtime.Notify parameters cast to proper type

- pkg/services/rpcsrv/server.go
Not broken enough CORS.
Break more of it.
> rpcsrv: handle preflight OPTIONS with CORS kludge, fix #2721

- docs/release-instruction.md
It can be simplified after b27e6918bd969cc07f738ba96c7f246f44ede319.
> docs: update release instruction

- cli/smartcontract/smart_contract.go
- cli/txctx/tx.go
- cli/wallet/candidate_test.go
- cli/wallet/nep11.go
- cli/wallet/nep17.go
- cli/wallet/validator.go
- cli/wallet/wallet.go
- cli/wallet/wallet_test.go
#2669
Code unification, nothing new is added here, so there are no new tests.
> Add ability to save any tx in the CLI

- CHANGELOG.md
Let's try our new release scheme.
> CHANGELOG: 0.99.4

- cli/vm/cli_test.go
- pkg/core/storage/boltdb_store.go
- pkg/core/storage/boltdb_store_test.go
> cli: properly cleanup state-dependand VM CLI

- pkg/network/helper_test.go
- pkg/network/peer.go
- pkg/network/server.go
- pkg/network/server_test.go
- pkg/network/tcp_peer.go
- pkg/network/tcp_peer_test.go
No core logic is changed here (pings are fixed a bit), but we have a bit less code after this.
> Some network code cleanup

- pkg/network/server.go
Until the consensus process starts for a new block and until it really needs some transactions we can spare some cycles by not delivering transactions to it. In tests this doesn't affect TPS, but makes block delays a bit more stable. Related to #2744, I think it also may cause timeouts during transaction processing (waiting on the consensus process channel while it does something dBFT-related).
> network: only call tx callback if we're waiting for transactions

- pkg/network/prometheus.go
- pkg/network/server.go
It can be useful to detect some performance issues.
> network: add prometheus histogram with cmd processing time

- docs/notifications.md
- pkg/neorpc/result/invoke.go
- pkg/neorpc/result/invoke_test.go
- pkg/neorpc/rpcevent/filter.go
- pkg/neorpc/rpcevent/filter_test.go
- pkg/neorpc/types.go
- pkg/rpcclient/actor/actor.go
- pkg/rpcclient/actor/actor_test.go
- pkg/rpcclient/actor/compat_test.go
- pkg/rpcclient/actor/maker_test.go
- pkg/rpcclient/actor/waiter.go
- pkg/rpcclient/actor/waiter_test.go
- pkg/rpcclient/client.go
- pkg/rpcclient/invoker/compat_test.go
- pkg/rpcclient/notary/actor.go
- pkg/rpcclient/notary/actor_test.go
- pkg/rpcclient/wsclient.go
- pkg/rpcclient/wsclient_test.go
- pkg/services/rpcsrv/client_test.go
- pkg/services/rpcsrv/server.go
- pkg/services/rpcsrv/subscription.go
> rpc: implement transaction awaiting

- pkg/network/discovery.go
- pkg/network/server.go
Fix #2745. I'll keep it going for a while locally on mainnet, but it seems to be fine.
> Fancy getaddr

- docs/notifications.md
- pkg/neorpc/types.go
- pkg/rpcclient/actor/waiter.go
- pkg/rpcclient/actor/waiter_test.go
- pkg/rpcclient/wsclient.go
- pkg/rpcclient/wsclient_test.go
> rpc: refactor WSClient subscriptions API

- cli/smartcontract/generate.go
- cli/smartcontract/generate_test.go
- cli/smartcontract/smart_contract.go
- cli/smartcontract/testdata/nameservice/nns.go
- cli/smartcontract/testdata/nameservice/nns.manifest.json
- cli/smartcontract/testdata/nex/nex.go
- cli/smartcontract/testdata/nex/nex.manifest.json
- docs/compiler.md
- pkg/rpcclient/unwrap/unwrap.go
- pkg/rpcclient/unwrap/unwrap_test.go
- pkg/smartcontract/binding/generate.go
- pkg/smartcontract/manifest/standard/comply.go
- pkg/smartcontract/manifest/standard/comply_test.go
- pkg/smartcontract/manifest/standard/nep11.go
- pkg/smartcontract/manifest/standard/nep17.go
- pkg/smartcontract/manifest/standard/payable.go
- pkg/smartcontract/manifest/standard/token.go
- pkg/smartcontract/rpcbinding/binding.go
#2705.
Reuse existing infrastructure as much as possible and create something emitting code that can be compiled. To be extended.
> Rpc wrapper autogeneration

- cli/server/server.go
- cli/server/server_test.go
- docs/cli.md
- internal/basicchain/basic.go
- pkg/core/blockchain.go
- pkg/core/blockchain_core_test.go
- pkg/core/blockchain_neotest_test.go
- pkg/core/dao/dao.go
- pkg/core/native/management.go
- pkg/core/native/management_test.go
- pkg/core/state/tokens.go
- pkg/core/stateroot/module.go
- pkg/core/storage/store.go
Close #2576.
Draft implementation, not all functionality is supported. TODO:
> core: implement state reset

- pkg/network/server.go
- pkg/network/server_test.go
Drop some load from dbft loop during consensus process.
> network: pre-filter transactions going into dbft

- pkg/network/server.go
Provide additional info for better user experience.
> network: adjust warning for deposit expiration

- .github/workflows/build.yml
- Makefile
Close #2790.
See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files for env files usage.
> .github: upgrade stale GithubActions workflow dependencies

- cli/server/server.go
- pkg/core/blockchain_neotest_test.go
- pkg/core/native/management.go
- pkg/core/native/management_test.go
> Fix node startup with broken contract

- pkg/services/rpcsrv/client_test.go
- pkg/services/rpcsrv/server.go
> rpcsrv: do not block blockchain events receiver by subscription requests

- cli/vm/cli.go
- cli/vm/cli_test.go
- pkg/vm/stackitem/serialization.go
- pkg/vm/stackitem/serialization_test.go
#2815 is caused by the pointer element that was omitted during serialization and then deserialization code saw things it's not supposed to see.
Handle pointers.
> Fix pointer serialization

- pkg/core/blockchain.go
- pkg/core/dao/dao.go
State reset doesn't work properly on large heights.
Presented in the PR.
> core: fix broken state reset

- pkg/rpcclient/actor/waiter.go
- pkg/rpcclient/actor/waiter_test.go
- pkg/rpcclient/notary/actor.go
- pkg/rpcclient/rpc.go
- pkg/services/rpcsrv/client_test.go
> Some actor/waiter interaction fixes

- CHANGELOG.md
> CHANGELOG: release 0.99.7

- config/protocol.mainnet.neofs.yml
> config: the network is past 2.7M non-upgraded

- cli/query/query_test.go
- internal/fakechain/fakechain.go
- internal/testchain/address.go
- internal/testchain/transaction.go
- pkg/consensus/consensus_test.go
- pkg/core/bench_test.go
- pkg/core/blockchain.go
- pkg/core/blockchain_core_test.go
- pkg/core/blockchain_neotest_test.go
- pkg/core/chaindump/dump.go
- pkg/core/dao/dao.go
- pkg/core/headerhashes.go
- pkg/core/helper_test.go
- pkg/core/interop/context.go
- pkg/core/native/ledger.go
- pkg/core/native/native_test/ledger_test.go
- pkg/core/prometheus.go
- pkg/core/statesync/module.go
- pkg/core/statesync/neotest_test.go
- pkg/core/util.go
- pkg/neotest/basic.go
- pkg/network/server.go
- pkg/services/rpcsrv/client_test.go
- pkg/services/rpcsrv/server.go
- pkg/services/rpcsrv/server_test.go
- scripts/gendump/main.go
Reading all of the hashes takes time, storing them requires a lot of memory.
Only get the ones we need an only when they are needed.
> Optimize startup time and memory usage

- ROADMAP.md
- config/protocol.mainnet.neofs.yml
- config/protocol.mainnet.yml
- config/protocol.privnet.docker.four.yml
- config/protocol.privnet.docker.one.yml
- config/protocol.privnet.docker.single.yml
- config/protocol.privnet.docker.three.yml
- config/protocol.privnet.docker.two.yml
- config/protocol.privnet.yml
- config/protocol.testnet.neofs.yml
- config/protocol.testnet.yml
- config/protocol.unit_testnet.single.yml
- config/protocol.unit_testnet.yml
- docs/node-configuration.md
- pkg/config/protocol_config.go
- pkg/config/protocol_config_test.go
- pkg/consensus/consensus_test.go
- pkg/core/blockchain.go
- pkg/neotest/chain/chain.go
- pkg/network/server_config.go
- pkg/network/tcp_peer.go
- pkg/services/rpcsrv/client_test.go
- pkg/services/rpcsrv/server.go
- pkg/services/rpcsrv/server_test.go
- pkg/services/stateroot/service.go
> TimePerBlock config

- config/protocol.mainnet.neofs.yml
> config: move Aspidochelone fork height for NeoFS mainnet again

- README.md
- cli/wallet/wallet.go
Probably needs to be updated after #2827.
> Minor documentation fixes

- pkg/rpcclient/wsclient.go
- pkg/services/rpcsrv/client_test.go
> rpcclient: fix filtered naive subscriptions receiver

- pkg/services/rpcsrv/server.go
It's more heavyweight at the same time, but should be OK for the purpose. Inspired by https://github.com/neo-project/neo-modules/issues/754#issuecomment-1345176986
> rpcsrv: use more robust NEP-11 divisibility check

- cli/smartcontract/generate.go
- cli/smartcontract/generate_test.go
> cli: mark required flags of `generate-*` command

- pkg/services/rpcsrv/server.go
- pkg/services/rpcsrv/server_test.go
> Fix findstates response difference

- config/protocol.privnet.docker.four.yml
- config/protocol.privnet.docker.one.yml
- config/protocol.privnet.docker.three.yml
- config/protocol.privnet.docker.two.yml
- docs/consensus.md
> Improve consensus doc and docker configs

- pkg/core/blockchain.go
- pkg/core/mempool/subscriptions.go
- pkg/network/server.go
- pkg/rpcclient/wsclient.go
Add a warning about received events modification where applicable.
> *: adjust subscription-related doc

- cli/wallet/wallet.go
- cli/wallet/wallet_test.go
> cli: refactor wallet import related commands

- pkg/rpcclient/actor/waiter.go
Waiter should close its channels, but WSClient can also do that and it can do that in a drain loop as well.
> actor: don't close already closed channel, fix #2932

- pkg/rpcclient/rpc.go
- pkg/rpcclient/rpc_test.go
- pkg/services/rpcsrv/client_test.go
> rpcclient: add GetProof and VerifyProof

- .golangci.yml
- internal/contracts/oracle_contract/go.mod
- pkg/core/dao/dao.go
- pkg/core/interop/storage/find.go
- pkg/core/native/management.go
- pkg/core/native/native_neo.go
- pkg/network/tcp_peer_test.go
- pkg/rpcclient/actor/doc_test.go
- pkg/rpcclient/invoker/doc_test.go
- pkg/smartcontract/doc_test.go
Fix #2948 
1. ~~Add `go.work` to orginatize go modules~~
2. Ignore `revive` linter  `unused-parameter` check for all files ~~and `empty-block` check for all `doc_test.go`s~~.
3.  Fix ~~2 places~~ all `empty-block` issue
4. ~~Configuration to show all linter issues in ci~~
> Fix lint jobs issues

- cli/wallet/wallet.go
- cli/wallet/wallet_test.go
The breaking part of #2887, see the https://github.com/nspcc-dev/neo-go/pull/2887#discussion_r1086851612.
Draft until a proximity to 0.102.0.
> cli: ask for NEP2 account label if not provided

- .github/workflows/dco.yml
Signed-off-by: anastasia prasolova <anastasia@nspcc.ru>
> [nspcc-dev/nspcc-infra#840]: Add DCO check

- docs/notary.md
> docs: improve Notary's `till` value documentation

- cli/vm/cli.go
- cli/vm/cli_test.go
- examples/runtime/runtime.go
- pkg/vm/context.go
- pkg/vm/debug_test.go
Ref. #3013, based on https://github.com/nspcc-dev/neo-go/pull/3013#issuecomment-1545949629.
TODO:
> cli: properly load specified method for `run` VM CLI command

- pkg/core/mempool/mem_pool_test.go
Ref. https://github.com/neo-project/neo/pull/2818#discussion_r1206658847.
> mempool: add test for concurrent conflicting tx addition

- cli/smartcontract/generate.go
- cli/smartcontract/generate_test.go
- cli/smartcontract/testdata/gas/gas.go
- cli/smartcontract/testdata/nameservice/nns.go
- cli/smartcontract/testdata/nex/nex.go
- cli/smartcontract/testdata/nonepiter/iter.go
- cli/smartcontract/testdata/notifications/rpcbindings.out
- cli/smartcontract/testdata/notifications/rpcbindings_extended.out
- cli/smartcontract/testdata/notifications/rpcbindings_guessed.out
- cli/smartcontract/testdata/structs/rpcbindings_dynamic_hash.out
- cli/smartcontract/testdata/types/rpcbindings_dynamic_hash.out
- cli/smartcontract/testdata/verifyrpc/verify.go
- pkg/smartcontract/binding/generate.go
- pkg/smartcontract/rpcbinding/binding.go
Close #3006 and make a light base for #3007.
Let's merge #3008 firstly, because it contains nice bindings template idents fixes. After that I'll rebase this PR onto master. Otherwise ready for review.
> cli: allow dynamic RPC binding contract hash

- pkg/vm/stackitem/json.go
- pkg/vm/stackitem/json_test.go
Close #3069.
The first commit fixes state difference at block 2336911@T5. After that the new state difference at block 2342940@T5 occurs:
```
state differs at 2342940, block 254985ed16cb865742971a93b16aa6888aa20ccc7082d56f9e59d2e53ca151ea
transaction 4c9e33b29bb75ae2a77e180f82879195fe541afa04aabe0e4a1a1ec858629938:
--- http://localhost:20332
+++ http://seed1t5.neo.org:20332
@@ -1,2 +1,2 @@
-(*result.ApplicationLog)(0xc00030f7c0)({
+(*result.ApplicationLog)(0xc000039840)({
Container: (util.Uint256) (len=32 cap=32) 38996258c81e1a4a0ebeaa04fa1a54fe959187820f187ea7e25ab79bb2339e4c,
@@ -9,3 +9,3 @@
Stack: ([]stackitem.Item) (len=1 cap=1) {
-    (*stackitem.Array)(0xc0002625a0)(Array)
+    (*stackitem.Array)(0xc0003e2840)(Array)
},
different state found
exit status 1
```
Something tells me that …
> vm: allow parsing scientific JSON numbers

- config/protocol.privnet.docker.four.yml
- config/protocol.privnet.docker.one.yml
- config/protocol.privnet.docker.single.yml
- config/protocol.privnet.docker.three.yml
- config/protocol.privnet.docker.two.yml
- examples/storage/storage.go
Ref. https://github.com/nspcc-dev/neo-go-sc-wrkshp/pull/38.
> examples, config: minor adjustments for workshop

- LICENSE.md
Adjust year and fit authors in one line.
> *: update LICENSE.md

- config/protocol.unit_testnet.yml
- docs/node-configuration.md
- docs/rpc.md
- pkg/config/config.go
- pkg/config/rpc_config.go
- pkg/core/blockchain.go
- pkg/core/stateroot/module.go
- pkg/neorpc/result/findstorage.go
- pkg/rpcclient/rpc.go
- pkg/rpcclient/rpc_test.go
- pkg/services/rpcsrv/client_test.go
- pkg/services/rpcsrv/server.go
- pkg/services/rpcsrv/server_test.go
Close #3095 and add a couple of extensions.
> rpcsrv, rpcclient: support `findstorage`, `findstoragehistoric` and `getstoragehistoric` calls

- pkg/config/hardfork.go
- pkg/config/protocol_config.go
- pkg/config/protocol_config_test.go
- pkg/core/blockchain.go
- pkg/core/blockchain_core_test.go
- pkg/core/interop/context.go
- pkg/core/interop/context_test.go
Follow the logic described in https://github.com/neo-project/neo/pull/2886#issuecomment-1674745298 and port the https://github.com/neo-project/neo/pull/2886.
Close #3096.
> core: adjust hardfork enabling logic

- pkg/smartcontract/zkpbinding/binding.go
> zkpbinding: fix example link

- pkg/neorpc/errors.go
- pkg/rpcclient/rpc_test.go
- pkg/rpcclient/wsclient_test.go
- pkg/services/rpcsrv/server_test.go
According to the initial proposal and https://github.com/neo-project/proposals/pull/156/files#diff-2b5f7c12a23f7dbe4cb46bbf4be6936882f8e0f0b3a4db9d8c58eb294b02e6ed.
> neorpc: adjust common error messages

- pkg/smartcontract/manifest/manifest_test.go
We already have tests for Permission deserialisation, so port the first part of https://github.com/neo-project/neo/pull/2948.
> manifest: add compatibility test for Permissions and Trust serialization

- pkg/services/rpcsrv/params/param.go
- pkg/services/rpcsrv/params/param_test.go
Inspired by https://github.com/neo-project/neo-modules/pull/845.
> rpcsrv/params: limit tx signers/witnesses

- pkg/wallet/wallet.go
> wallet: provide more detailed errors on failed NewWalletFromFile

- config/protocol.privnet.docker.one.yml
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/core/blockchain_neotest_test.go
> Forbid unknown YAML node configuration fields

- cli/options/options.go
- cli/smartcontract/manifest.go
- cli/smartcontract/smart_contract.go
- cli/util/cancel.go
- cli/util/convert.go
- cli/util/util_test.go
- docs/rpc.md
ref: https://github.com/nspcc-dev/neo-go/issues/3151
> cli: cancel transaction command

- docs/notifications.md
- pkg/rpcclient/wsclient.go
> Improve notification subsystem documentation

- pkg/neotest/signer.go
> neotest: adjust Signer documentation

- cli/options/options.go
- cli/smartcontract/manifest.go
- cli/smartcontract/smart_contract.go
- cli/util/cancel.go
- cli/wallet/legacy.go
- cli/wallet/multisig.go
- cli/wallet/nep17.go
- cli/wallet/validator.go
- cli/wallet/wallet.go
> cli: move actor handling

- docs/notifications.md
- pkg/core/blockchain.go
- pkg/neorpc/events.go
- pkg/neorpc/rpcevent/filter.go
- pkg/neorpc/rpcevent/filter_test.go
- pkg/rpcclient/wsclient.go
- pkg/rpcclient/wsclient_test.go
- pkg/services/rpcsrv/server.go
- pkg/services/rpcsrv/subscription_test.go
New header_of_added_block notification subscription.
Close: #2751
> rpc: add header_of_added_block event subscription

- cli/nep_test/nep11_test.go
- cli/nep_test/nep17_test.go
- cli/options/options.go
- cli/smartcontract/contract_test.go
- cli/smartcontract/smart_contract.go
- cli/txctx/tx.go
- cli/util/cancel.go
- cli/util/convert.go
- cli/util/send.go
- cli/util/util_test.go
- cli/wallet/candidate_test.go
- cli/wallet/multisig.go
- cli/wallet/nep11.go
- cli/wallet/nep17.go
- cli/wallet/validator.go
- cli/wallet/wallet.go
- cli/wallet/wallet_test.go
- internal/testcli/executor.go
- pkg/rpcclient/actor/actor.go
- pkg/rpcclient/actor/compat_test.go
- pkg/rpcclient/actor/waiter.go
- pkg/rpcclient/actor/waiter_test.go
- pkg/rpcclient/notary/actor_test.go
- pkg/rpcclient/waiter/waiter.go
- pkg/rpcclient/waiter/waiter_test.go
New --await flag. 
for commands:
```
wallet nep11 transfer
wallet nep17 transfer
wallet nep17 multitransfer
wallet candidate register
wallet candidate unregister
wallet candidate vote
wallet claim
wallet sign
contract invokefunction
contract deploy
util sendtx
util canceltx
util txdump
```
Closes #3244
> cli: add await flag for operations with transactions

- ROADMAP.md
- pkg/rpcclient/actor/actor.go
- pkg/rpcclient/notary/actor_test.go
- pkg/rpcclient/waiter/waiter.go
- pkg/rpcclient/waiter/waiter_test.go
- pkg/services/rpcsrv/client_test.go
> waiter: refactor naming and implement header-based WS transactions awaiting

- CHANGELOG.md
> CHANGELOG: release 0.105.1

- pkg/network/tcp_peer.go
Scenario:
1. Two messages were read from the connection `p.conn`
2. The first message has started to be processed
3. The second message was queued to be added to the channel `p.incoming`
4. Processing of the first message failed with an error
5. TCP peer is closed, but processing of the second message continues
Add `p.done` channel close handling.
> tcp_peer: Fix possible goroutine leak

- .github/workflows/build.yml
- .github/workflows/tests.yml
@AliceInHunterland, that's for you to have more fun fixing things.
> Add ARM-based MacOS tests

- pkg/rpcclient/wsclient_test.go
Add waiting for startSending to ensure that the client is ready before the server starts sending messages.
Close #3005
Close https://github.com/nspcc-dev/neo-go/issues/3312
> rpcclient: fix TestWSClientNonBlockingEvents

- cli/util/util_test.go
> cli: fix TestAwaitUtilCancelTx failing

- cli/txctx/tx.go
> cli: fix TestNEP17Transfer fail

- pkg/services/rpcsrv/subscription_test.go
> rpcsrv: properly cleanup testing WS reader and network server

- cli/util/util_test.go
- internal/testcli/executor.go
> cli: ensure all outcomes are handled in TestAwaitUtilCancelTx

- pkg/services/rpcsrv/subscription_test.go
> rpcsrv: fix TestWSClientsLimit

- pkg/neotest/chain/chain.go
Close #3403
Currently there is no way to customize log level when using neotest. As result, test output gets cluttered and hard to navigate.
Implemented Options structure that allows to customize logging behavior. In the future it can be used to customize other chain parameters without creating new constructor functions.
> neotest: add options to customize test chain

- scripts/compare-states/compare-states.go
> scripts: dump diff for OnPersist and PostPersist applog

- .github/workflows/tests.yml
- scripts/compare-states/compare-states.go
> scripts: fix linting

- CHANGELOG.md
> CHANGELOG: release 0.106.1

- config/protocol.mainnet.neofs.yml
- config/protocol.mainnet.yml
- config/protocol.testnet.yml
Ref. https://github.com/neo-project/neo/pull/3330.
> config: port Domovoi schedule

- scripts/compare-states/compare-states.go
> cli: fix flag alias in compare-states command

- pkg/config/config.go
- pkg/config/netmode/netmode.go
- pkg/core/blockchain_neotest_test.go
> netmode: add constant MainNetNeoFS and TestNetNeoFS

- go.mod
- go.sum
- pkg/consensus/block.go
- pkg/consensus/block_test.go
- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/consensus/crypto.go
- pkg/consensus/crypto_test.go
- pkg/consensus/payload.go
- pkg/consensus/recovery_message.go
DBFT 0.3.0 is not yet finalized, but this version seems to be working fine.
> dbft: update to AMEV-enabled version

- pkg/neorpc/result/version.go
- pkg/neorpc/result/version_test.go
- pkg/rpcclient/rpc_test.go
- pkg/services/rpcsrv/server.go
- pkg/services/rpcsrv/server_test.go
> rpcsrv: add seedlist and standbycommittee to `getversion`

- pkg/services/rpcsrv/subscription_test.go
TestWSClientsLimit failed in #3540 one more time, I'm just tired of it.
> rpcsrv: fix failing TestWSClientsLimit

- pkg/core/blockchain_neotest_test.go
> core: prove contract notifications count is not restricted

- cli/util/uploader.go
Close #3628
Close https://github.com/nspcc-dev/neo-go/issues/3634
> cli: fix `upload-bin` error handling

- cli/util/convert.go
- cli/util/upload_bin.go
- docs/neofs-blockstorage.md
> cli: add check of successful upload for `upload-bin`

- pkg/compiler/compiler.go
- pkg/core/blockchain.go
- pkg/core/mempool/mem_pool.go
- pkg/rpcclient/nep11/divisible.go
- pkg/services/rpcsrv/params/types.go
- pkg/vm/stackitem/item.go
> *: fix some dupword warnings

- pkg/io/size.go
- pkg/rpcclient/invoker/invoker_test.go
- pkg/smartcontract/parameter.go
- pkg/smartcontract/parameter_test.go
Inability to pass maps into calls.
Aquí.
> Extend smartcontract type conversions

- cli/util/upload_bin.go
- docs/neofs-blockstorage.md
- pkg/network/server.go
- pkg/services/blockfetcher/blockfetcher.go
- pkg/services/blockfetcher/blockfetcher_test.go
- pkg/services/oracle/neofs/neofs.go
Close #3568
Close #3564
Close #3644
Close #3699
> NeoFS BlockFetcher: add pool with retries

- pkg/services/rpcsrv/subscription_test.go
> rpcsrv: fix `TestFilteredSubscriptions`

- cli/util/upload_bin.go
- docs/neofs-blockstorage.md
Close https://github.com/nspcc-dev/neo-go/issues/3654
Close https://github.com/nspcc-dev/neo-go/issues/3714
> cli: change block timestamp attribute of objects in `upload-bin`

- CHANGELOG.md
- docs/node-configuration.md
Depends on #3725, #3749, #3750, #3751.
> CHANGELOG: release v0.107.2

- .gitmodules
> *: neo-vm submodule update dependency

- pkg/core/transaction/witness_condition.go
Rework 75d12081bfac0fdc4090c7061b0161ec77aba976 to follow https://github.com/neo-project/neo/pull/3761, let's have a real depth value in this constant.
> transaction: fix MaxConditionNesting

- pkg/core/block/header.go
- pkg/core/util_test.go
- pkg/services/blockfetcher/blockfetcher.go
> *: fix GetExpectedHeaderSize for genesis block case

- pkg/network/server.go
- pkg/network/tcp_peer.go
- pkg/rpcclient/unwrap/unwrap.go
make function comment match function name
...
...
> chore: make function comment match function name

- docs/node-configuration.md
- docs/rpc.md
- pkg/config/application_config.go
- pkg/config/rpc_config.go
- pkg/core/interop/iterator/interop.go
- pkg/neorpc/result/invoke.go
- pkg/neorpc/result/version.go
- pkg/neorpc/result/version_test.go
- pkg/rpcclient/invoker/invoker.go
- pkg/rpcclient/invoker/invoker_test.go
- pkg/rpcclient/unwrap/unwrap_test.go
- pkg/services/rpcsrv/client_test.go
- pkg/services/rpcsrv/server.go
- pkg/services/rpcsrv/server_test.go
> rpcsrv: add `SessionExpansionEnabled`

- pkg/network/server.go
- pkg/network/tcp_peer.go
No functional changes, just simpler code.
> network: replace timers with tickers

- internal/fakechain/fakechain.go
The comments and method names do not match.
...
Fix function name in comment
...
> chore: fix function name in comment

- pkg/core/transaction/witness_rule.go
> chore: fix comment

- pkg/network/server.go
- pkg/network/tcp_peer.go
> network: fix `(*TCPPeer).version` NPE

- docs/node-configuration.md
- pkg/config/p2p.go
- pkg/network/capability/capability.go
- pkg/network/capability/type.go
- pkg/network/helper_test.go
- pkg/network/message.go
- pkg/network/message_test.go
- pkg/network/payload/version_test.go
- pkg/network/peer.go
- pkg/network/server.go
- pkg/network/server_config.go
- pkg/network/server_test.go
- pkg/network/tcp_peer.go
> network: support `DisableCompression` capability

- CHANGELOG.md
- config/protocol.mainnet.neofs.yml
- config/protocol.mainnet.yml
- config/protocol.testnet.neofs.yml
- config/protocol.testnet.yml
- pkg/config/hardfork.go
Release 0.109.0 and enable Echidna.
> Release 0.109.0

- pkg/core/interop/context.go
- pkg/core/native/ledger.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_test/neo_test.go
> native: use Ledger's PostPersist as block persist checkpoint

- pkg/core/statesync/module.go
It's not critical since standard BC persist routine is running in background, but at the same time this change allows to save some progress in case of unexpected node shutdown during statesync process. Inspired by #3898.
> statesync: enforce DB persist after every statesync stage

- pkg/network/discovery.go
- pkg/network/discovery_test.go
- pkg/network/peer.go
Close #3902 and a couple of other bugs.
> network: improve seed discovery

- pkg/core/native/crypto_blspoints.go
- pkg/core/native/std.go
Some function name  are wrong in comment
Fix some function names in comment
> chore: fix some function names in comment

- cli/util/convert.go
- cli/util/upload_bin.go
- cli/util/util_test.go
- config/protocol.mainnet.neofs.yml
- config/protocol.mainnet.yml
- config/protocol.testnet.neofs.yml
- config/protocol.testnet.yml
- docs/neofs-blockstorage.md
- docs/node-configuration.md
- pkg/config/application_config_test.go
- pkg/config/neofsservice_config.go
- pkg/services/blockfetcher/blockfetcher.go
- pkg/services/helpers/neofs/blockstorage.go
> cli, blockfetcher: remove index files

- pkg/compiler/codegen.go
- pkg/core/mpt/base.go
- pkg/core/native/native_test/cryptolib_verification_test.go
fix some minor issues in comments
...
...
> *: fix some minor issues in comments

- pkg/neorpc/result/tokens.go
fix struct name in comment
...
> neorpc: fix struct name in comment

- ROADMAP.md
- config/protocol.privnet.yml
- config/protocol.unit_testnet.yml
- docs/node-configuration.md
- pkg/config/rpc_config.go
- pkg/services/rpcsrv/client_test.go
- pkg/services/rpcsrv/server.go
- pkg/services/rpcsrv/server_test.go
Close https://github.com/nspcc-dev/neo-go/issues/3528.
> config: replace `SessionExpirationTime` with `SessionLifetime`

- CHANGELOG.md
Make it more concise and update release date.
> CHANGELOG: editorial updates of v0.111.0

- cli/txctx/tx.go
- cli/util/send.go
- cli/wallet/multisig.go
- pkg/rpcclient/actor/actor.go
- pkg/rpcclient/actor/actor_test.go
- pkg/rpcclient/waiter/waiter.go
- pkg/rpcclient/waiter/waiter_test.go
- pkg/services/rpcsrv/client_test.go
> rpc: extend Waiter.Wait() with context

- cli/util/util_test.go
- cli/vm/cli.go
- cli/vm/cli_test.go
> cli: extend util convert with base64 public keys

- config/protocol.unit_testnet.yml
- docs/node-configuration.md
- docs/notifications.md
- pkg/config/config.go
- pkg/config/ledger_config.go
- pkg/config/rpc_config.go
- pkg/core/blockchain.go
- pkg/neorpc/events.go
- pkg/neorpc/filters.go
- pkg/neorpc/filters_test.go
- pkg/neorpc/result/mempool_event.go
- pkg/neorpc/rpcevent/filter.go
- pkg/neorpc/rpcevent/filter_test.go
- pkg/rpcclient/wsclient.go
- pkg/rpcclient/wsclient_test.go
- pkg/services/rpcsrv/client_test.go
- pkg/services/rpcsrv/server.go
- pkg/services/rpcsrv/subscription_test.go
> *: allow subscription for mempool events

- cli/smartcontract/testdata/rpcbindings/nft-d/rpcbindings.out
- cli/smartcontract/testdata/rpcbindings/nft-d/rpcbindings_dynamic_hash.out
- cli/smartcontract/testdata/rpcbindings/nft-nd/rpcbindings.out
- cli/smartcontract/testdata/rpcbindings/nft-nd/rpcbindings_dynamic_hash.out
- examples/nft-d/nft.go
- examples/nft-d/nft.yml
- examples/nft-nd-nns/nns.go
- examples/nft-nd-nns/nns.yml
- examples/nft-nd/nft.go
- examples/nft-nd/nft.yml
- examples/runtime/runtime.go
- examples/runtime/runtime.yml
- pkg/rpcclient/management/management.go
- pkg/rpcclient/management/management_test.go
- pkg/rpcclient/nep22/nep22.go
- pkg/rpcclient/nep22/nep22_test.go
- pkg/rpcclient/nep31/nep31.go
- pkg/rpcclient/nep31/nep31_test.go
- pkg/smartcontract/manifest/manifest.go
- pkg/smartcontract/manifest/standard/comply.go
- pkg/smartcontract/manifest/standard/comply_test.go
- pkg/smartcontract/manifest/standard/nep22.go
- pkg/smartcontract/manifest/standard/nep31.go
- pkg/smartcontract/rpcbinding/binding.go
> smartcontract: add support for nep-22/nep-31

- cli/server/cli_dump_test.go
- cli/server/server.go
> cli: support NEP-32

- pkg/core/native/native_neo.go
> core: remove Echidna compatibility code from registerCandidate

- pkg/compiler/codegen.go
- pkg/compiler/switch_test.go
> compiler: support handling SwitchStmt.Init

- pkg/core/mpt/batch.go
- pkg/core/native/native_nep17.go
- pkg/core/native/native_test/neo_test.go
fix inconsistent function name in comment
...
> chore: fix inconsistent function name in comment

- pkg/compiler/codegen.go
> compiler: fix panic when missing external package in imported one

- pkg/compiler/codegen.go
- pkg/compiler/map_test.go
- pkg/compiler/slice_test.go
> compiler: fix iterating over nil slice

- pkg/rpcclient/rpc.go
Inspired by https://github.com/nspcc-dev/neofs-contract/pull/530.
> rpcclient: improve getblockcount description
