nspcc-dev/neo-go

- pkg/core/transaction.go
- pkg/core/transaction_type.go
Walking through the repo to get up to speed and noticed that the `core/transaction.go` file had two types in it.
Move the `TransactionType` struct to an individual file to increase readability. 
- None
> Separate TransactionType to new file

- pkg/rpc/types.go
- pkg/vm/state.go
- pkg/vm/state_test.go
- pkg/vm/vm.go
State of VM, returned from RPC-node can be "HALT, BREAK", i.e. in contain multiple states simultaneously. This is because in C# implementation, vm.State is actually a set (enum with flags)
https://github.com/neo-project/neo-vm/blob/79c3aada150865036617fc4a785dbfe618c2e3b7/src/neo-vm/VMState.cs
Right now we cant parse response into a single state.
Make State a set with different flags ("NONE" means no flags).
All tests are passed, but I'm not sure if I've broken anything deep inside.
Let me know what you think.
> make State a set as in reference C# implementation

- pkg/rpc/errors.go
- pkg/rpc/params.go
- pkg/rpc/server.go
- pkg/rpc/server_test.go
- return errors like in C# code (neo-project/neo#587)
- update tests
- small refactoring
> Fix #140 (improve error messages)

- pkg/chain/chain.go
Chain acts as a basic struct around the chaindb, protecting the database from unauthorised writes.
This is done by un-exporting all of the save methods and only allowing them to be accessed via the chains exported methods, which first do verification on the item. 
Verification is not being implemented in this pr
> Add basic Chain package

- pkg/peer/config.go
- pkg/peer/peer.go
- pkg/peer/peer_test.go
- pkg/peer/responsehandlers.go
- pkg/peer/stall/stall.go
- pkg/peer/stall/stall_test.go
- Closes #239 
- moved response handlers to their own functions
- removed DefaultConfig from LocalConfig file
- passed peer as a parameter to all response handlers
- added peer start height
- refactored NewPeer function to be more concise and clear
- removed empty lines at end of functions
- Added AddMessage/RemoveMessage for Detector in outgoing and ingoing
requests for Block and Headers
> [Peer] Refactor

- pkg/vm/stack/Int.go
- pkg/vm/stack/array.go
- pkg/vm/stack/boolean.go
- pkg/vm/stack/bytearray.go
- pkg/vm/stack/context.go
- pkg/vm/stack/map.go
- pkg/vm/stack/map_test.go
- pkg/vm/stack/stackitem.go
- pkg/vm/stack/test_helper.go
Closes #167 
1) Added new file map.go, map_test.go
2) Added Map, Hash Method to Item interface
3) Implemented Hash Method for every stack items (Boolean, Array, Int, ...)
In the end, I have chosen to implement the `Map ` stack item as follow:
```go
type Map struct {
*abstractItem
val map[Item]Item
}
```
Please review the implementation of the `Map` stack item. Once it is approved I will implement the `Struct` Stack Item and merge to this PR.
> VM: Implement Map, Struct Stack Item:

- pkg/vm/compiler/codegen.go
This fixes #294 . Tests are passing.
> Use separate opcodes for string and number equality

- pkg/vm/compiler/codegen.go
Unfortunately d58fbe0c88b7848ce4d8ef300d594b7cc39f94cc didn't really fix the
problem because tinfo.Type (the expression resulting type) actually is a bool
and we need to check its parameters. Also, there is need to fix the NEQ
operation.
> compiler: fix string/numbers equality/inequality gen again

- pkg/connmgr/connmgr.go
- pkg/server/connmgr.go
- pkg/server/server.go
And make the node fail gracefully if it's unable to bind. Before this commit:
```
Server is starting up
Connection manager started
Error connecting to outbound  listen tcp 127.0.0.1:20332: bind: address already in use
We have connected successfully to:  127.0.0.1:20334
panic: runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6bbfa2]
goroutine 12 [running]:
github.com/CityOfZion/neo-go/pkg/connmgr.New.func1.1(0x0, 0x0)
/home/rik/dev/neo-go/pkg/connmgr/connmgr.go:47 +0x22
panic(0x718980, 0xa22f70)
/usr/lib64/go/1.12/src/runtime/panic.go:522 +0x1b5
github.com/CityOfZion/neo-go/pkg/connmgr.New.func1(0xc000013430, 0xc000013450, 0xc000013440, …
```
> connmgr: correctly pass binding error to the server

- _pkg.dev/crypto/privatekey/privatekey.go
- go.mod
- go.sum
- pkg/wallet/private_key.go
- prepare fork
- update go-modules
- update dependencies
---
Note: `anthdm/rfc6979` adds two dependencies
> Use our RFC6979 fork

- Dockerfile
- Makefile
- config/config.go
Makes `make run` work again and gives us reproducible builds.
> Make & config fixes

- .circleci/config.yml
- Dockerfile
- Makefile
Only version 2 is supported at the moment as per
https://circleci.com/docs/2.0/configuration-reference/#version-1
Not to confuse with top-level version which really can be 2.1.
> circleci: fix workflow version

- Dockerfile
- cli/server/server.go
- config/protocol.privnet.yml
-Now it's not required to pass config and it works as in Readme with
default location
-Fix RPC port which is used by privatenet by default
> Fix config for neo go cli

- pkg/vm/cli/cli.go
- pkg/vm/vm.go
This fixes two minor things observed in #96:
* running VM twice, which leads to instruction execution attempt for VM in FAULT state
* panicing with nil dereference (it's better to show some error message)
Before this patchset:
```
NEO-GO-VM > run
NEO-GO-VM > error encountered at instruction 6 (ROLL)
NEO-GO-VM > runtime error: invalid memory address or nil pointer dereference
FAULT
NEO-GO-VM > error encountered at instruction 7 (SETITEM)
NEO-GO-VM > interface conversion: interface {} is []vm.StackItem, not []uint8
```
After this patchset:
```
NEO-GO-VM > run
NEO-GO-VM > error encountered at instruction 6 (ROLL)
NEO-GO-VM > bad index
FAULT
```
> Minor VM fixes for #96

- pkg/vm/vm.go
- pkg/vm/vm_test.go
Reference VM implementation supports convertation from
Struct to Array via NEWARRAY and vice versa.
https://github.com/neo-project/neo-vm/pull/91
Some of the tests from the reference `neo-vm` repository fail due to no support of Array to Struct conversion.
Allow NEWARRAY to take STRUCT as an argument and vice versa.
> vm: implement Array <-> Struct conversion

- go.mod
- go.sum
- pkg/crypto/base58.go
- pkg/crypto/base58_test.go
- pkg/crypto/keys/publickey.go
Use more fast and reliable implementation. Add some tests for our wrappers,
deduplicate code in PublicKey.Adress(). Fixes #355.
> crypto: use mr-tron/base58 for base58

- pkg/vm/vm.go
- pkg/vm/vm_test.go
Add some tests also. Fixes #361.
> vm: fix not failing PUSHBYTES* on short read

- pkg/vm/vm.go
- pkg/vm/vm_test.go
Fixes #378.
LEFT applied to index which is greater than the string lengths, causes panic.
Check slice bounds before pushing a value.
> vm: do not fault on LEFT with big index

- pkg/vm/stack.go
- pkg/vm/vm_test.go
Fixes #372.
Also added tests for `NOT` and `SIGN` to check new behavior.
Also fixed a bug with `Bool` casting: it should be `!= 0` instead of `== 1`.
There are still missing cases for `Interop` and `Map` because they are not implemented.
> VM: implement stack item conversion

- .circleci/config.yml
- .travis.yml
- README.md
Go 1.11 is not supported upstream and it also breaks our precious VM for some
reason, so use better versions of Go. Fixes #384.
> update minimum supported version of Go to 1.12

- config/protocol.unit_testnet.yml
- pkg/core/blockchain_test.go
Should fix circleCI and now these tests using inmemory db.
Partially fixes #353
CircleCI:
```
--- FAIL: TestSize (0.00s)
Error Trace:	blockchain_test.go:180
blockchain_test.go:188
blockchain_test.go:161
Error:      	Expected nil, but got: 0xb
Test:       	TestSize
```
...
These unit tests are using inmemory db now.
...
> unitTests: fix for failing test

- pkg/vm/compiler/analysis.go
- pkg/vm/compiler/codegen.go
After changes in #391 some tests started to fail. This PR fixes codegen for `APPEND`.
> VM: fix codegen for APPEND

- pkg/vm/stack.go
- pkg/vm/tests/binary_expr_test.go
- pkg/vm/tests/for_test.go
- pkg/vm/tests/function_call_test.go
- pkg/vm/tests/if_test.go
- pkg/vm/tests/import_test.go
- pkg/vm/tests/struct_test.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
There are to more bugs specified in #196 . They include using `Array` as a pointer value and can me more prone to hidden bugs, so I will do this separately.
There are some tests in `pkg/vm/tests/` which fail. I am not sure if tests or codegen should be fixed. E.g. if user is expecting `Integer` we could emit `PUSH0, ADD` on top of `[]byte` item to return `Integer`. Or just make tests expect `[]byte{0}`. All this implicit conversions stuff is rather annoying both from user's and developer's point of view.
> VM: fix some bugs from JSON tests

- pkg/vm/stack_item.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
1. Arrays are reference types in NeoVM
https://github.com/neo-project/neo-vm/issues/201
https://github.com/neo-project/neo-vm/blob/master/tests/neo-vm.Tests/Tests/OpCodes/BitwiseLogic/EQUAL.json#L477
We need to compare pointer values in `EQUAL`.
2. Structs are cloned when `APPEND`ed
https://github.com/neo-project/neo-vm/blob/master/src/neo-vm/ExecutionEngine.cs#L966
> VM: compare Array by reference

- pkg/vm/vm.go
- pkg/vm/vm_test.go
JSON tests in neo-vm check stack state even in case of failure.
There are 2 corrections need to be done:
1. Pop items in `EQUAL` one-by-one.
2. Do not pop anything from stack in `OVER`.
I have also implemented operand restriction for `SHL`/`SHR`.
> VM: do not pop too many items from stack

- pkg/rpc/server_helper_test.go
- pkg/rpc/server_test.go
sendrawtransaction_negative was actually wrong in trying to get
SendTXResponse, it receives an error.
> rpc: check for error responses in tests

- pkg/core/block.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/blockchainer.go
- pkg/network/helper_test.go
- pkg/util/uint160.go
- pkg/util/uint160_test.go
- pkg/vm/vm.go
Changing `verifyBlocks` to `true` breaks synchronization with Testnet.
This set of fixes allows to proceed up to the block number 4586, the block number 4587 fails at `APPCALL` invocation at the moment, but that's for the next set of fixes (not sure how much time it would take).
> Various transaction verification fixes (testnet up to 4586)

- cli/vm/vm.go
- pkg/core/blockchain.go
- pkg/core/contract_state.go
- pkg/core/contract_state_test.go
- pkg/smartcontract/param_context.go
- pkg/vm/compiler/compiler.go
- pkg/vm/context.go
- pkg/vm/interop.go
- pkg/vm/stack.go
- pkg/vm/stack_item.go
- pkg/vm/tests/vm_test.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
This focuses on VM improvements necessary to make tx verification work. It's mostly related to interop functionality, but doesn't add interops at the moment (I want to add more of them before the first push). Fixes #295 along the way.
> Various verification fixes 2

- go.mod
Right now go.mod has no version, so `go` tries to insert it on every ocassion. It is rather annoying to remove it every time.
Add minimum go version to go.mod.
> Add minimum go version to go.mod

- pkg/vm/vm.go
- pkg/vm/vm_test.go
Arrays, Structs and Maps have maximum size defined as MaxArraySize.
We need to return an error in case collection becomes too big.
> Implement limitations on maximum collection size

- pkg/vm/context.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
There is a limit on max size an item is allowed to have.
https://github.com/neo-project/neo-vm/blob/master/src/neo-vm/ExecutionEngine.cs#L39
This PR implements checks in CAT and PUSHDATA4. One more step towards #373 .
> Restrict max item size on stack

- pkg/core/blockchain.go
- pkg/core/mem_pool.go
- pkg/core/mem_pool_test.go
- pkg/core/transaction/invocation.go
- pkg/core/transaction/transaction_test.go
- pkg/network/server.go
Transaction relaying (RPC to NEO) didn't really work
Added missing functionality, fixed some bugs, including #446.
> TX relaying fixes

- pkg/vm/vm.go
- pkg/vm/vm_test.go
There should be a limit on invocation stack size. This PR implements it.
See also #373 .
> vm: restrict max invocation stack size

- config/config.go
- config/protocol.mainnet.yml
- config/protocol.privnet.docker.four.yml
- config/protocol.privnet.docker.one.yml
- config/protocol.privnet.docker.three.yml
- config/protocol.privnet.docker.two.yml
- config/protocol.privnet.yml
- config/protocol.testnet.yml
- config/protocol.unit_testnet.yml
- pkg/network/server.go
- pkg/network/server_config.go
Without it node in privnet tries to reconnect to four existing nodes
indefinitely for no good reason.
...
...
> network: make minpeers configurable

- pkg/rpc/server.go
- pkg/rpc/server_test.go
Our node responds to some RPC methods in a different way from C# nodes.
Make our responses consistent with the C# node behaviour.
> Minor RPC fixes

- cli/server/server.go
- config/config.go
- config/protocol.mainnet.yml
- config/protocol.privnet.docker.four.yml
- config/protocol.privnet.docker.one.yml
- config/protocol.privnet.docker.three.yml
- config/protocol.privnet.docker.two.yml
- config/protocol.privnet.yml
- config/protocol.testnet.yml
- config/protocol.unit_testnet.yml
- go.mod
- pkg/core/storage/boltdb_store.go
- pkg/io/fileWriter.go
- pkg/io/fileWriter_test.go
- pkg/network/metrics/metrics.go
- pkg/network/server.go
- pkg/network/server_config.go
- pkg/network/server_test.go
- pkg/rpc/server.go
#460 
...
This patchset.
HowTo
1. Set up log path:
```
LogPath: "./log/neogo.log"
```
2. Set up binging address for node: (In config)
```
```
Additional options:
3. Set up separate RPC, Monitoring. Node addresses is the same as above but you can do it for each module.
```
RPC:
Address: 127.0.0.1
Enabled: true
EnableCORSWorkaround: false
Port: 20332
```
or
```
Monitoring:
Address: 127.0.0.1
Enabled: true
Port: 2112
```
...
> config: use logpath and address for server/rpc/monitoring

- pkg/network/tcp_peer.go
- pkg/network/tcp_peer_test.go
Otherwise the node might crash in `startProtocol` because of missing Version
field in the peer. And it also keeps the sequence correct, Version MUST be
sent first and ACKs can only follow it. A follow-up to #478.
> network: wait for both Version messages before ACKing

- pkg/vm/vm.go
- pkg/vm/vm_test.go
The last VM limit we need to implement is the restriction of BigInteger size. 
This PR implements it.
Closes #373 .
> vm: restrict BigInteger item size

- cli/server/server.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/blockchainer.go
- pkg/core/helper_test.go
- pkg/network/helper_test.go
- pkg/rpc/server_helper_test.go
- pkg/rpc/server_test.go
Before this patch the deferred function in Run() was actually never able to properly
close the Store, so we weren't syncing the latest state to the disk.
> core: add Close() to blockchainer, implement it to properly close chain

- cli/server/server.go
It was failing to process any blocks at all when (skip >= count) and in other
cases it processed wrong number of blocks. 
I had this patch sitting in the queue for more than a week.
> cli: fix skip usage in DB dump/restore

- pkg/vm/serialization.go
- pkg/vm/vm_test.go
When encountering already seen stack item we should fail
only if it is a collection. Duplicate Integers or ByteArrays are ok
because they can't lead to recursion.
> vm: fix a bug in collection serialize

- pkg/core/blockchain.go
- pkg/core/interop_neo.go
- pkg/core/interop_system.go
- pkg/core/interops.go
- pkg/core/notification_event.go
- pkg/core/storage/store.go
- pkg/vm/serialization.go
- pkg/vm/stack.go
- pkg/vm/stack_item.go
> Fix notifications and getreferences bugs

- pkg/network/tcp_peer.go
Right now message can be written in several `Write`'s so
concurrent calls to `writeMsg` can in theory interleave.
This commit fixes it.
> network: write messages atomically

- pkg/rpc/client.go
- pkg/rpc/param.go
- pkg/rpc/param_test.go
- pkg/rpc/params.go
- pkg/rpc/server.go
- pkg/rpc/server_test.go
- pkg/rpc/stack_param_test.go
This PR does 3 things:
- adds array parameter unmarshalling
- extend `Param` with convenient methods
- refactor tests into using tables to make it easier add new tests
> rpc: extend param unmarshaling

- pkg/core/block_base.go
- pkg/core/helper_test.go
Closes #514 .
Some other structures in `core/` them can actually fail (e.g. because they have interfaces as a structure fields) so I decided not to touch them.
> core: do not return error in block.getHashableData

- pkg/core/transaction/transaction.go
Unknown transaction types are wrong and should be treated as errors.
> Fix invalid tx type handling

- pkg/core/blockchain.go
- pkg/core/blockchain_state.go
Commit c80ee952a1a8a5a971cf2579d0985ee091cc39a5 removed temporary store used
to contain changes of the block being processed. It's wrong in that the block
changes should be applied to the database in a single transaction so that
there wouldn't be any intermediate state observed from the outside (which is
possible now). Also, this made changes commiting persist them to the
underlying store effectively making our persist loop a no-op (and not
producing `persist completed` log lines that we love so much).
Add the interim store back into the system.
> Fix interim block changes store

- cli/smartcontract/smart_contract.go
- pkg/rpc/rpc.go
We can only make test invocations.
Now we can send proper TXes to the net! Like this:
```
$ ./bin/neo-go contract invokefunction -e http://localhost:20331 -w KxDgvEKzgSBPPfuVfw67oPQBSjidEiqTHURKSDL1R7yGaGYAeYnr -g 0.00001 50befd26fdf6e4d957c11e078b24ebce6291456f
```
The only caveat is that you have to specify some gas for it not to fail verification.
> Proper blockchained invocation TX

- pkg/consensus/recovery_message.go
- pkg/consensus/recovery_message_test.go
- pkg/network/server.go
There is a small chance that before starting a consensus self-connection will be counted as valid because `PeerCount` returns all peers including those who haven't performed handshake yet.
This PR allows to count handshaked peers only.
> network: count only handshaked peers as connected

- pkg/core/blockchain.go
- pkg/core/interop_neo.go
- pkg/core/interop_neo_test.go
- pkg/core/interop_system.go
- pkg/smartcontract/trigger/trigger_type.go
Created separate go file with this constants. 
After merging #517 interop related files could be moved to separate package:
```
interops
interop_neo.go
interop_neo_test.go
interop_system.go
interops.go
```
And this constants could be moved there as well. One thing: `Application` trigger type is used in blockchain.go. But since we're not using other type there we can hide this param in separate constructor for `InteropContext`.
> core: add trigger types as constants. Closes #509

- pkg/core/interop_system.go
When 74590551 introduced this code we had no proper caching layer, so there
were these strange fallbacks in the code. fc0031e5 should'd removed them, but
failed to do so, so do it now and fix processing of transactions that touch
storage for the same key (address) in the same block.
> core: fix wrong data being read in interops (part of #501)

- pkg/rpc/param.go
- pkg/rpc/param_test.go
Use new Uint160DecodeStringLE() function.
> rpc: simplify uint160 handling

- pkg/consensus/consensus.go
- pkg/consensus/payload.go
- pkg/consensus/payload_test.go
- pkg/core/account_state.go
- pkg/core/asset_state.go
- pkg/core/asset_state_test.go
- pkg/core/block.go
- pkg/core/block_base.go
- pkg/core/block_test.go
- pkg/core/blockchain.go
- pkg/core/header_test.go
- pkg/core/helper_test.go
- pkg/core/interop_neo.go
- pkg/core/interop_neo_test.go
- pkg/core/mem_pool.go
- pkg/core/notification_event.go
- pkg/core/transaction/enrollment.go
- pkg/core/transaction/invocation.go
- pkg/core/transaction/register.go
- pkg/core/transaction/register_test.go
- pkg/core/transaction/transaction.go
- pkg/core/util.go
- pkg/io/binaryWriter.go
- pkg/io/binaryrw_test.go
- pkg/network/payload/headers_test.go
- pkg/rpc/txBuilder.go
- pkg/util/uint256.go
This set improves serialization/deserialization performance and, more importantly, simplifies memory management for some structures avoiding useless copying.
It adds some percents to the 1,4M blocks import test.
> Serialization and struct improvements

- pkg/core/blockchain.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
This change (closely related to the neo-project/neo#1321 proposal) speeds up
1.4M mainnet blocks import by 30%. Basically, we're eliminating key decoding
for block's multisignature that has the same keys most of the time.
Things I don't like about this patch:
* yet another parameter for verifyHashAgainstScript()
* vm keys are not copied in/out
But it's rather simple and solves the problem for this particular case, so I
think it's worth it.
> vm/core: improve block import speed with PublicKey caching

- go.mod
- go.sum
- pkg/io/binaryReader.go
- pkg/io/binaryWriter.go
- pkg/io/binaryrw_test.go
They were replaced with faster specialized versions earlier. The only obstacle on the way to removing them completely was dbft library, which is also updated in this PR.
> io: remove Read/Write LE/BE

- integration/README.md
- integration/performance_test.go
Goal was to measure TX/Sec as in https://github.com/neo-project/neo/issues/1321
In order to run it:
```
$ cd integration
$ go test -bench=. -benchmem
```
Result 1 (without singing TX):
```
10000            402421 ns/op          177370 B/op         90 allocs/op
PASS
ok      github.com/CityOfZion/neo-go/integration        4.360s
```
Meaning that we have 10 000 tx'es per 4.360s. It's 2294 TX / Sec.
Result 2 (with singing TX):
```
4743            398582 ns/op          132878 B/op        467 allocs/op
PASS
ok      github.com/CityOfZion/neo-go/integration        2.530s
```
Meaning that we have 4743 tx'es per 2.530s. It's 1874 TX / Sec.
Next step would be to run performance test with e2e scenario.
> performance: add performance test

- pkg/consensus/payload_test.go
Generated payload should not contain any witness.
I will possibly refactor `Verify` to perform more correct verification instead of just appending scripts.
> consensus: fix payload sign test

- README.md
- cli/server/server.go
- config/config.go
- config/protocol.mainnet.yml
- config/protocol.privnet.docker.four.yml
- config/protocol.privnet.docker.one.yml
- config/protocol.privnet.docker.three.yml
- config/protocol.privnet.docker.two.yml
- config/protocol.privnet.yml
- config/protocol.testnet.yml
- config/protocol.unit_testnet.yml
- pkg/network/metrics/metrics.go
- pkg/network/metrics/pprof.go
- pkg/network/metrics/prometheus.go
Since we have some perf issues from time to time it is good to have pprof debugger
Usage: 
addr (host + port) + 
```
"/debug/pprof/"
"/debug/pprof/cmdline"
"/debug/pprof/profile"
"/debug/pprof/symbol"
"/debug/pprof/trace"
```
Link for documentation: https://golang.org/pkg/net/http/pprof/
> network: add Pprof metrics

- pkg/vm/context.go
- pkg/vm/stack.go
- pkg/vm/stack_item.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
Severe problems with copied stack items that lead to inconsistent behaviour compared to C# node. 
C# node actually implements DUP in the same way we did, but it does create a new element when accessing some particular value (like `BigInt()` or `Bytes()`) so this doesn't produce any visible side-effects. In our case I think it's more appropriate to fix the DUP (and its variants) itself avoiding useless allocations in the VM.
> Fix duping and add tests

- pkg/compiler/codegen.go
- pkg/vm/tests/slice_test.go
Implement assignement to a variable slice index.
Fixes #564 .
> compiler: implement assignment to a variable index

- pkg/core/blockchain.go
- pkg/core/interops.go
- pkg/vm/interop.go
- pkg/vm/json_test.go
- pkg/vm/tests/vm_test.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
This solves two problems:
* adds support for shortened SYSCALL form that uses IDs (similar to #434, but
for NEO 2.0, supporting both forms), which is important for compatibility
with C# node and mainnet chain that uses it from some height
* reworks interop plugging to use callbacks rather than appending to the map,
these map mangling functions are clearly visible in the VM profiling
statistics and we want spawning a VM to be fast, so it makes sense
optimizing it. This change moves most of the work to the init() phase
making VM setup cheaper.
Our 100K (1.4M->1.5M) block import time improves by ~4% with this change.
> vm/core: add ID support for SYSCALL, redo interop registration

- pkg/vm/stack.go
Updating stack size is noticeable during db import from a dump. This PR speeds up (hopefully!) both of stack size update routines.
I will do some measurements later.
> vm: don't refcount simple items

- pkg/compiler/codegen.go
- pkg/compiler/return_test.go
This PR implements support for multiple return functions.
Closes #562 .
> compiler: implement multiple return support

- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
This is a possible reason for a panic in certain circumstances (thanks @im-kulikov):
```
goroutine 226 [running]:
github.com/CityOfZion/neo-go/pkg/core.(*Blockchain).GetValidators(0xc00013e160, 0xc000cf4000, 0x24f7, 0x24f7, 0xd1a35d37ae62d3b6, 0xc0038bb5b0, 0x40e40e, 0xc2ea00, 0xc003b9ad48)
github.com/CityOfZion/neo-go@/pkg/core/blockchain.go:1180 +0x7fe
github.com/CityOfZion/neo-go/pkg/consensus.(*service).getValidators(0xc00078efc0, 0xc004420000, 0x24f7, 0x24f7, 0xb05110, 0xdb8080, 0xc003b9ac60)
github.com/CityOfZion/neo-go@/pkg/consensus/consensus.go:367 +0x1fc
github.com/nspcc-dev/dbft.(*DBFT).processMissingTx(0xc000154280)
github.com/nspcc-dev/dbft@v0.0.0-20191213082456-c81c7a796775/dbft.go:335 +0x25d
github.com/nspcc-dev/dbft.(*DBFT).onPrepareRequest(0xc000154280, 0xdd8da0, …
```
> consensus: return nil interface from getTx

- cli/wallet/wallet.go
- pkg/consensus/consensus.go
- pkg/crypto/keys/nep2.go
- pkg/crypto/keys/nep2_test.go
- pkg/wallet/account.go
- pkg/wallet/account_test.go
Unimplemented `open` command, bad API, #26.
I don't think `open` is actually of any use for our wallet, so I've renamed it to `dump` and implemented it fixing some things along the way. It's a part of #26, but I'm not going to implement more of it at the moment, it's just that I had this patchset half-baked already from the previous experiments.
> Wallet dump and keys/wallet API improvements

- cli/server/server.go
- pkg/network/tcp_transport.go
- pkg/rpc/server.go
Tune logs for benchmarking and fix some things. Related to #284.
> Logging fixes

- pkg/network/helper_test.go
- pkg/network/message.go
- pkg/network/peer.go
- pkg/network/server.go
- pkg/network/tcp_peer.go
- pkg/network/tcp_peer_test.go
- pkg/network/tcp_transport.go
#590 and some other bugs.
This is an initial version that just solves the #590. We need to expand it later with more complex gossiping logic (we have broadcasting instead of that now everywhere).
> Network queues

- pkg/consensus/consensus_test.go
Avoid test failures like this one:
```
=== RUN   TestService_OnPayload
==================
WARNING: DATA RACE
Read at 0x00c00015a843 by goroutine 112:
testing.(*common).logDepth()
/usr/local/go/src/testing/testing.go:665 +0xa1
testing.(*common).Logf()
/usr/local/go/src/testing/testing.go:658 +0x8f
testing.(*T).Logf()
<autogenerated>:1 +0x75
go.uber.org/zap/zaptest.testingWriter.Write()
/go/pkg/mod/go.uber.org/zap@v1.10.0/zaptest/logger.go:130 +0x11f
go.uber.org/zap/zaptest.(*testingWriter).Write()
<autogenerated>:1 +0xa9
go.uber.org/zap/zapcore.(*ioCore).Write()
/go/pkg/mod/go.uber.org/zap@v1.10.0/zapcore/core.go:90 +0x1c3
go.uber.org/zap/zapcore.(*CheckedEntry).Write()
/go/pkg/mod/go.uber.org/zap@v1.10.0/zapcore/entry.go:215 +0x1e7
go.uber.org/zap.(*Logger).Info() …
```
> consensus: close chain in tests

- cli/server/server.go
- integration/performance_test.go
- pkg/network/server.go
- pkg/rpc/server_helper_test.go
It can return nil in two cases, so we're better return an error and handle
it.
> Fix SIGSEGV on bad consensus config

- config/config.go
- config/protocol.mainnet.yml
- config/protocol.testnet.yml
- pkg/core/blockchain.go
- pkg/core/gas_price.go
- pkg/core/gas_price_test.go
- pkg/rpc/server.go
- pkg/util/fixed8.go
- pkg/util/fixed8_test.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
Closes #607 .
2 parameters of `getPrice` are actually excessive, because they can be received via `VM`.
I was also thinking about generic pre-instruction hook `func(*vm.VM)` so that GAS calculation is fully transparent for VM, but was not sure if it will be simpler.
> vm: calculate GAS spent

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/verify_test.go
- pkg/interop/crypto/crypto.go
Closes #616 .
Add VerifyECDSA interop for signature verification.
It is converted to VERIFY opcode.
TODO: currently investigating on CHECKMULTISIG possibility in compiler.
> compiler: implement ECDSA signature verification

- pkg/compiler/codegen.go
- pkg/compiler/for_test.go
Make it possible to use `for` loop with a single condition.
> compiler: support for loops with no init/post condition

- pkg/compiler/codegen.go
- pkg/compiler/slice_test.go
Support using variables in slice literals.
Right know something like is necessary:
```golang
var nums []int
nums = append(nums, first)
nums = append(nums, second)
```
After this PR it will be possible to just:
```golang
nums := []int{first, second}
```
> compiler: support variables in slice literals

- pkg/compiler/codegen.go
- pkg/compiler/map_test.go
1. Support map literals.
2. Support string indices.
> compiler: support map literals

- pkg/compiler/byte_conversion_test.go
- pkg/compiler/codegen.go
- pkg/compiler/interop_test.go
Also load constants directly on stack, not by name (as with variables).
> compiler: allow to convert string constants to []byte

- .docker/privnet-entrypoint.sh
- Dockerfile
- Makefile
- Update command to build and publish images
- Use nspcc-dev docker hub repository
- Add command to publish neo-go images
- Add a single node chain dump to image (`1600-privnet-blocks-single.acc.gz`)
- Add the possibility to import a different dump of chains
- import dump only if `node` subcommand passed
- ACC env variable default value is `6000-privnet-blocks.acc.gz`
- ACC env variable can be declared in `docker-compose`
- ACC env variable can be one of:
    - `/6000-privnet-blocks.acc.gz`
    - `/1600-privnet-blocks-single.acc.gz`
    - custom path to dump of blockchain
> Prepare build and publish images

- pkg/compiler/codegen.go
- pkg/compiler/switch_test.go
Most of the time writing something like
```golang
switch operation {
case "Add":
...
case "Remove":
...
}
```
is more readable than `if-then-else` chain. This PR implements basic support for `switch` statements.
Implements 1 & 2 from #628 .
> compiler: implement switch statement support

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/panic_test.go
Right now there is no simple way to throw an error during smart-contract execution.
This PR implements `panic` support:
- `panic(nil)` translates to `THROW` opcode
- `panic(message)` logs `message` and `THROW`s. `message` should be a string.
There is also a minor refactoring for cleaner argument processing.
> compiler: support panic builtin

- pkg/consensus/consensus.go
While decoding payload, local implementations of Recovery*
messages were used, but when creating RecoveryMessage inside dBFT
library default NewRecoveryMessage was invoked. This lead to parsing
errors.
> consensus: use our implementations of Recovery* messages

- pkg/compiler/codegen.go
- pkg/compiler/return_test.go
When using underscore it does not appear in the list of local variables, so it can't be assigned.
In this commit the value is dropped.
> compiler: fix a bug with assignment to underscore

- pkg/rpc/server.go
- pkg/rpc/server_test.go
Returning error string as a result (not an error) is utterly wrong, but C#
implementation just returns a zero balance for unknown addresses, so we should
follow that.
> rpc: fix getaccountstate/getunspents for unknown addresses

- pkg/compiler/codegen.go
Because the constants are loaded directly via `emitLoadConst`, there is no need to store
them in an array of locals. It can have a big overhead, because it
is done at the beginning of every function.
This PR reduced size of neofs smart-contract by almost a factor of 2. We have a lot of string constants and many functions.
> compiler: do not store constants as variables

- pkg/network/discovery.go
- pkg/network/helper_test.go
- pkg/network/peer.go
- pkg/network/server.go
- pkg/network/tcp_peer.go
Wrong connect/disconnect handling leading to connectivity issues (unable to reconnect/not attempting to reconnect/dead peers). Sub-optimal outgoing message queue management.
This fixes connects/disconnects and give more priority to direct unicast communication between nodes. The set is well-tested now (as a part of `proto-fixes` branch), the latest change was done on January 29th. It even makes our consensus (before the latest changes) survive the neo-bench test more often than not.
> Networking improvements

- pkg/consensus/consensus_test.go
- pkg/consensus/payload.go
- pkg/core/block/block_test.go
- pkg/core/dao_test.go
- pkg/core/transaction/transaction.go
- pkg/core/transaction/transaction_test.go
Serializing unserializable.
Forbid that.
> Forbid encoding incomplete transactions

- pkg/util/array.go
- pkg/util/array_test.go
Be consistent.
That `if` was introduced in b257a06f3 . It was before wrong condition `i < j` was replaced with the right one `i <= j`. `ArrayReverse` works for slices of length <= 1 even without this.
> util: always copy argument in ArrayReverse

- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/core/blockchain.go
- pkg/core/blockchainer.go
- pkg/core/mempool/mem_pool.go
- pkg/core/mempool/mem_pool_test.go
- pkg/core/mempool/prometheus.go
- pkg/network/blockqueue.go
- pkg/network/blockqueue_test.go
- pkg/network/helper_test.go
- pkg/network/server.go
Our mempool sucks.
Make it great again! This allows us easily make 1000 Tx/s in 4-nodes privnet, fixes potential double spends and improves mempool testing coverage.
> Fix mempool and chain locking

- pkg/core/interop_system.go
- pkg/vm/interop.go
- pkg/vm/serialization.go
- pkg/vm/vm_test.go
Node fails to sync with testnet:
```
Feb 07 00:04:19 nodoka neo-go[1747]: 2020-02-07T00:04:19.838+0300        WARN        blockQueue: failed adding block into the blockchain        {"error": "failed to store notifications: not supported", "blockHeight": 713984, "nextIndex": 713985}
```
Don't attempt to store bad notifications.
> Handle bad notifications

- go.sum
- pkg/compiler/codegen.go
- pkg/compiler/interop_test.go
- pkg/interop/engine/engine.go
1. Make AppCall accept varargs.
2. Fix a bug with argument order on stack.
> compiler: refactor AppCall

- pkg/core/blockchain.go
Lack of FreeGasLimit in privnet leads to "gas limit exceeding" in case of transactions with small amount of GAS to be used for invoke operation (< real cost of the transaction).
Fixed constraint in case when FreeGasLimit == 0. So now we are able to perform transactions in privnet with FreeGasLimit = 0 for free.
...
> core: fix FreeGasLimit constraint

- pkg/core/blockchain.go
All of these places deal strictly with the chain and shouldn't ever be
bothered with mempool. It also fixes a deadlock on reverification of
non-standard tx:
```
1 @ 0x42f62f 0x43fbe9 0x43fbbf 0x43f95d 0x967059 0x966f66 0x972c7c 0x974e13 0x97a5d9 0x97bdf0 0x976147 0x966cc0 0x970f70 0x96c8cb 0x9ba858 0x45ca51
0x43f95c	sync.runtime_SemacquireMutex+0x3c							/usr/local/go/src/runtime/sema.go:71
0x967058	sync.(*RWMutex).RLock+0x128								/usr/local/go/src/sync/rwmutex.go:50
0x966f65	github.com/CityOfZion/neo-go/pkg/core/mempool.(*Pool).TryGetValue+0x35			/go/src/github.com/CityOfZion/neo-go/pkg/core/mempool/mem_pool.go:229
0x972c7b	github.com/CityOfZion/neo-go/pkg/core.(*Blockchain).GetTransaction+0x4b			/go/src/github.com/CityOfZion/neo-go/pkg/core/blockchain.go:782
0x974e12 …
```
> core: get transactions from dao when mempool should not be used

- pkg/compiler/codegen.go
- pkg/compiler/slice_test.go
- pkg/vm/context.go
Closes #630 .
Old implementation could view 0x62 byte in
a script as a JMP instruction irregardless of whether it is
a real opcode or a part of a parameter of another instruction.
In this commit instructions are decoded together with parameters
during jump label rewriting.
> compiler: rewrite jump targets properly

- pkg/network/tcp_peer.go
We can still lock the (*Server).run with dead peers:
Feb 13 16:14:50 neo-go-node-2 neo-go[9448]: goroutine 40 [select, 871 minutes]:
Feb 13 16:14:50 neo-go-node-2 neo-go[9448]: github.com/CityOfZion/neo-go/pkg/network.(*TCPPeer).putPacketIntoQueue(0xc030ab5320, 0xc02f251f20, 0xc00af0dcc0, 0x18, 0x40, 0x100000000000000, 0xffffffffffffffff)
Feb 13 16:14:50 neo-go-node-2 neo-go[9448]: #011/go/src/github.com/CityOfZion/neo-go/pkg/network/tcp_peer.go:82 +0xf4
Feb 13 16:14:50 neo-go-node-2 neo-go[9448]: github.com/CityOfZion/neo-go/pkg/network.(*TCPPeer).EnqueueHPPacket(0xc030ab5320, 0xc00af0dcc0, 0x18, 0x40, 0x1367240, 0xc03090ef98)
Feb 13 16:14:50 neo-go-node-2 neo-go[9448]: #011/go/src/github.com/CityOfZion/neo-go/pkg/network/tcp_peer.go:124 +0x52
Feb 13 16:14:50 neo-go-node-2 neo-go[9448]: …
> network: change the disconnect procedure

- pkg/compiler/codegen.go
- pkg/compiler/struct_test.go
While initializing a struct, it is a top item on ALTSTACK.
This means that if we need to load a local variable,
DUPFROMALTSTACK won't longer push an array of locals on stack
but rather a currently initializing struct.
Closes #656.
> compiler: support initializing struct fields from a variable

- pkg/core/transaction/attribute.go
- pkg/core/transaction/output.go
- pkg/core/transaction/witness.go
- `Attribute` should have 2 fields (usage, data)
- `VOut` should have 4 (5) fields (asset, value, address, n)
- `Script` should have 2 fields (invocation, verification)
> Add JSON tags for RPC response types

- pkg/consensus/consensus_test.go
- pkg/core/blockchain.go
As C# node does it. Technically it's only needed for consensus and could be
implemented in the appropriate package, but for better compatibility with C#
node we're better returning it sorted right here.
> core: sort GetValidators() result

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/for_test.go
- pkg/compiler/slice_test.go
Implement sub-slice support. Only bytearrays are considered.
> compiler: support sub-slicing

- cli/server/dump.go
- cli/server/server.go
- config/config.go
- pkg/core/blockchain.go
- pkg/core/storage/memcached_store.go
- pkg/core/storage/memcached_store_test.go
- scripts/compare-dumps
Dump all storage changes in a format similar to
https://github.com/NeoResearch/neo-storage-audit/
There are 2 differences with `neo-storage-audit` though:
1. We unify `Changed` and `Added` operations, as all `Changed` can be restored base on dump itself.
2. We count as `Deleted` all entries with which `storage.Delete` was invoked, not only items which were really deleted.
> cli: add possibility to dump storage changes on restore

- pkg/consensus/payload_test.go
- pkg/consensus/recovery_message.go
- pkg/consensus/recovery_message_test.go
PrepareRequest inside RecoveryMessage should contain both
message type and view.
> consensus: provide message type and view inside RecoveryMessage

- cli/wallet/wallet.go
- pkg/smartcontract/param_context.go
- pkg/wallet/account.go
- pkg/wallet/account_test.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
Support some of the capabilities outlined in #26 .
- import WIF
- import WIF + multisig
- export WIF
Fix some minor bugs.
> cli: implement wallet import/export functionality

- docs/rpc.md
- pkg/rpc/server/prometheus.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
> rpc: implement getblocksysfee RPC

- pkg/core/blockchain.go
It makes little sense queueing up several persistence goroutines (or actually
even running them concurrently).
> core: reschedule the next persist in a second from previous one

- pkg/core/blockchain.go
- pkg/core/blockchainer.go
- pkg/core/dao.go
- pkg/core/dao_test.go
- pkg/core/interop_neo.go
- pkg/core/transaction/claim.go
- pkg/core/transaction/inout.go
- pkg/core/transaction/input.go
- pkg/core/transaction/input_test.go
- pkg/core/transaction/transaction.go
- pkg/network/helper_test.go
Missing some checks for these transactions. Broken SpentCoin tracking logic.
> Claim and enrollment TX verification fixes

- pkg/core/mempool/mem_pool.go
- pkg/core/mempool/mem_pool_test.go
- pkg/core/transaction/input.go
> Claim TX verification for mempool

- pkg/network/discovery.go
- pkg/network/discovery_test.go
- pkg/network/helper_test.go
- pkg/network/server.go
Deadlocks on connection overflow and server shutdown.
Merge button.
> Network conn overflow and shutdown

- pkg/compiler/codegen.go
- pkg/compiler/for_test.go
Current implementation of short-circuting is just plain wrong.
It doesn't even handle simple assignements like
`a := x == 1 && y == 2`.
Closes #699, #701.
> compiler: do not short-circuit in complex conditions

- pkg/core/mempool/mem_pool.go
- pkg/network/server.go
> network: batch transactions on broadcast

- integration/performance_test.go
- pkg/compiler/compiler_test.go
- pkg/compiler/vm_test.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/gas_price_test.go
- pkg/core/helper_test.go
- pkg/core/transaction/register_test.go
- pkg/core/util_test.go
- pkg/crypto/hash/merkle_tree_test.go
- pkg/encoding/address/address_test.go
- pkg/network/server_test.go
- pkg/smartcontract/contract_test.go
- pkg/vm/json_test.go
- pkg/vm/vm_test.go
- pkg/wallet/account_test.go
1. Headers need to be verified on adding.
2. Get rid of global variables in core tests.
Maybe now there is no need to verify block if it's header matches header in headerlist.
> core: verify headers in AddHeaders()

- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
During networked synchronization we expect there to be a lot of duplicate
headers received and it makes no sense for us reverifying them.
> core: don't reverify stale headers in addHeader

- pkg/core/interop_neo_test.go
- pkg/core/interop_system.go
trigger.Type is not present in `makeStackItem`.
> core: convert trigger.Type to byte when pushing on stack

- pkg/core/blockchain.go
Avoid failures like this:
fatal error: concurrent map writes
goroutine 103 [running]:
runtime.throw(0xca6fe3, 0x15)
/usr/lib64/go/1.12/src/runtime/panic.go:617 +0x72 fp=0xc000687988 sp=0xc000687958 pc=0x42d8d2
runtime.mapassign(0xb9d4a0, 0xc0000b1f80, 0xc000687a6c, 0x13bd940)
/usr/lib64/go/1.12/src/runtime/map.go:590 +0x5e3 fp=0xc000687a10 sp=0xc000687988 pc=0x40e2a3
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).verifyHashAgainstScript(0xc0000f8000, 0x1300d1f5a3d348be, 0x78607089e4fe9fab, 0xc0a21e4f71, 0xc000d16070, 0x1e2b8881f8178e92, 0xd589cfa965287bb8, 0x24a4e4f292ebc797, 0xb90d3120d878e619, 0xc0001d01e0, ...)
/home/rik/dev/neo-go/pkg/core/blockchain.go:1866 +0x371 fp=0xc000687ad8 sp=0xc000687a10 pc=0x984ed1
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).verifyHeaderWitnesses(0 …
> core: protect (*Blockchain).keyCache with a lock

- pkg/network/tcp_transport.go
You have to try to trigger that, but in the event of server shutdown before it
actually started listening Close will easily panic like this:
2020-03-05T11:48:08.660+0300    INFO    node started    {"blockHeight": 6458, "headerHeight": 15605}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x9d5f0a]
github.com/nspcc-dev/neo-go/pkg/network.(*TCPTransport).Close(0xc000fd7050)
/home/rik/dev/neo-go/pkg/network/tcp_transport.go:78 +0x2a
github.com/nspcc-dev/neo-go/pkg/network.(*Server).Shutdown(0xc000182280)
/home/rik/dev/neo-go/pkg/network/server.go:190 +0x189
github.com/nspcc-dev/neo-go/cli/server.startServer(0xc000200160, 0x0, 0x0)
/home/rik/dev/neo-go/cli/server/server.go:367 +0x79e …
> network: add a nil check in (*TCPTransport).Close, prevent panic

- docs/rpc.md
- pkg/rpc/response/result/block_header.go
- pkg/rpc/server/prometheus.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
> rpc: implement getblockheader RPC

- pkg/core/blockchain.go
There is no need to keep Balances and Unclaimed slices
sorted, we need only to remove a single element.
> core: get rid of unnecessary copies

- pkg/core/interop_neo.go
- pkg/core/interop_neo_test.go
- pkg/core/interop_system.go
C# uses ToArray() or UintXXX(bytes) here which interprets hashes as they
should be interpreted (BE, although they always convert to LE when converting
to String just for the fun of it). It leads to state difference for us at
block 2025204 where even though we have the same value for the key, the key
itself differs, ours:
dd2b538e2a0c1db1ae5061c15be14f916bd1e678e512ffcda6d9499d8e7fe97ee71fd6b8004583d9afe09cc4dadbd5deb63d01e061009b7cffdaa674beae0f930ebe6085af900093e5fe56b34a5c220ccdcf6efc336fc5000000000000000000000000000000000010
theirs:
dd2b538e2a0c1db1ae5061c15be14f916bd1e67861e0013db6ded5dbdac49ce0afd9834500b8d61fe77ee97f8e9d49d9a6cdff12e5009b7cffdaa674beae0f930ebe6085af900093e5fe56b34a5c220ccdcf6efc336fc5000000000000000000000000000000000010
In this key there is a tx hash encoded …
> core: fix wrong endian used in interop functions

- pkg/rpc/response/result/block.go
- Nonce should not trim leading zeros
- NextConsensus should returns address (uint160 -> base58)
see changes
> [rpc/server] fix getblock verbose response

- pkg/core/interop_neo.go
> Fix contract description limit

- pkg/core/interop_neo.go
State difference with C# node in block 1444901.
Broken by 9f7018503a12d4c6c7ae1e6e6a2835569f3bf502. Almost the same problem as
in 01082a8988cf049673e1857415f08534e879b512 (though it is deterministic now,
just not the way the contract expects).
> Fix GetReferences interop regression

- cli/flags/address.go
- cli/wallet/wallet.go
Right now a bizarre error message can occur if an address flag was not
set: `wallet contains no account for 'AFmseVrdL9f9oyCzZefL9tG6UbvhPbdYzM'`.
This bug is 10x worse if it occures in `transfer` --from flag.
> cli: do not allow default value for an empty address

- go.sum
The reason `go mod` replaces `nspcc-dev` with `CityOfZion` is probably that in previous versions this module was `CityOfZion`.
> *: go mod tidy

- pkg/compiler/codegen.go
- pkg/compiler/function_call_test.go
- pkg/compiler/vm_test.go
When `return` or `break` statement is encountered inside
a for/range/switch statement, top stack items can be auxilliary.
They need to be cleaned up before returning from the function.
Related to #683 .
The only unfixed test RN is a function call used as a statement.
> compiler: clean up stack on branch statements

- pkg/network/discovery.go
Why a deadlock can occur:
1. `(*DefaultDiscovery).run()` has a for loop over `requestCh` channel.
2. `(*DefaultDiscovery).RequestRemote()` send to this channel while holding a mutex.
3. `(*DefaultDiscovery).RegisterBadAddr()` tries to take mutex for write.
4. Second select-case can't take mutex for read because of (3).
> network: fix possible deadlock in DefaultDiscovery

- cli/wallet/nep5.go
- cli/wallet/wallet.go
- pkg/core/state/nep5_test.go
- pkg/rpc/client/nep5.go
- pkg/util/fixed8.go
- pkg/util/fixed8_test.go
- pkg/wallet/token.go
- pkg/wallet/token_test.go
- pkg/wallet/wallet.go
1. Query balance.
2. Transfer funds.
Closes #709 .
> cli: implement NEP5-related commands

- pkg/rpc/client/doc.go
- pkg/rpc/client/rpc.go
Implemented following RPC client methods:
- getapplicationlog
- getassetstate
- getbestblockhash
- getblockcount
- getblockhash
- getblockheader
- getblocksysfee
- getconnectioncount
- getcontractstate
- getpeers
- getrawmempool
- getstorage
- gettransactionheight
- gettxout
- getunclaimed
- getvalidators
- getversion
- submitblock
- validateaddress
> rpc: implement missing RPC client methods

- cli/smartcontract/smart_contract.go
- pkg/core/gas_price.go
- pkg/rpc/client/rpc.go
- pkg/rpc/request/txBuilder.go
- pkg/smartcontract/deployment_price.go
Real GAS needed to deploy smartcontract was not calculated, so one could only try different GAS values to see which one fits. Wallets were also not integrated properly into this part of the CLI.
> Use wallet in smartcontract deploy/invoke commands and calculate GAS properly

- pkg/core/blockchain.go
- pkg/core/blockchainer.go
- pkg/core/cacheddao.go
- pkg/core/dao.go
- pkg/core/state/account.go
- pkg/core/state/nep5.go
- pkg/core/state/nep5_test.go
- pkg/core/storage/store.go
- pkg/network/helper_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
Track NEP5-related things separately from account.
> core: store NEP5 balances separately from account

- pkg/rpc/response/result/application_log.go
Problem: cannot marshall empty raw message from appExecResult.Stack
Solution: add handler for case when appExecResult.Stack is an empty string
> rpc: bug with empty stack marshalling in getapplicationlog

- pkg/rpc/request/param.go
ERROR   Error encountered with rpc request      {"error": "expected string size of 40 got 42",...
> rpc: fix invocations of contracts using hash160

- config/config.go
closes #680
Problem: cannot connect to neo-go node with a client with default ping
timeouts values
Solution: added default config values for PingInterval=30 and PingTimeout=90
> config: add default ping timeouts config value

- pkg/rpc/response/result/nep5.go
Asset hash should be returned without leading `0x` in little-endian.
> rpc: marshal Asset hash in LE in getnep5balances RPC

- pkg/core/interop_neo.go
Fixes difference in state changes at mainnet's block 2442790 because contract
migration in b4eb2dc35226e6520ee4e09a56197dff91547b50a7f57edc82930fc18c75dffc
doesn't actually transfer the storage state, it only deletes the old one.
And add an error check just in case.
> core: fix contract's state migration and don't swallow errors

- pkg/core/blockchain.go
- pkg/core/state/account.go
- pkg/core/state/unclaimed.go
- pkg/core/state/unclaimed_test.go
- pkg/rpc/response/result/unclaimed.go
- pkg/rpc/server/server.go
Yet another attempt to speed up block processing on db restore.
This way we will not unmarshal every unspent, thus won't perform excessive copying.
> core/state: do not unmarshal Unclaimed balances in account

- cli/server/dump.go
- cli/server/server.go
If DB restore was interrupted, next restore will overwrite last written file.
This commit allows to append dumps to an existing file.
> cli: allow to reuse existing dumps

- cli/flags/fixed8.go
- cli/smartcontract/smart_contract.go
- cli/wallet/nep5.go
- pkg/core/dao.go
- pkg/core/transaction/transaction.go
- pkg/rpc/client/rpc.go
- pkg/rpc/request/txBuilder.go
1. Parse `Fixed8` from string in cli instead of float.
2. Implement `transaction.AddVerificationHash()` for convenience.
> cli: implement Fixed8Flag

- cli/wallet/nep5.go
- cli/wallet/wallet.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
1. Remove accounts.
2. Remove tokens.
3. Import custom contracts.
Closes #26. Seems like everything is implemented :)
> cli: implement `wallet remove-account`

- pkg/core/blockchain.go
- pkg/core/mempool/mem_pool.go
- pkg/core/mempool/mem_pool_test.go
Missing some checks for Issue transactions.
Add them.
> Fix issue tx verification

- config/config.go
- config/protocol.mainnet.yml
- config/protocol.privnet.yml
- config/protocol.testnet.yml
- pkg/rpc/server/server.go
To generate test certificate:
```bash
openssl genrsa -out https-server.key 2048
openssl ecparam -genkey -name secp384r1 -out https-server.key
openssl req -new -x509 -sha256 -key https-server.key -out https-server.crt -days 3650
```
When testing in a postman, disable certificate checking.
> rpc: support https

- pkg/smartcontract/param_type.go
- pkg/smartcontract/param_type_test.go
- pkg/smartcontract/parameter.go
- pkg/smartcontract/parameter_test.go
It is done so in C# implementation, we better be
as compatible as possible.
Closes #770.
> smartcontract: marshal Integer values to JSON-strings

- pkg/vm/stack_item.go
- pkg/vm/stack_test.go
Perform automatic conversion of non-standard integer types to
int64 if possible.
Closes #776.
> vm: allow to push integer-like items to stack

- pkg/vm/vm.go
- pkg/vm/vm_test.go
When divisor is negative, the result is truncated towards
zero.
https://dotnetfiddle.net/qWwtyN
Closes #768 .
> vm: use truncated division for Integers

- pkg/vm/cli/cli.go
- pkg/vm/stack_item.go
It is more correct upconvert to int64 if needed,
so precision is never lost.
> vm: make NewBigInteger accept int64

- cli/wallet/nep5.go
- pkg/rpc/response/result/account_state.go
- pkg/rpc/response/result/asset_state.go
- pkg/rpc/response/result/contract_state.go
- pkg/rpc/server/server_test.go
- pkg/smartcontract/parameter.go
- pkg/util/uint160.go
- pkg/util/uint160_test.go
- pkg/wallet/token.go
- pkg/wallet/token_test.go
> util: JSONify uint160 using LE instead of BE

- pkg/crypto/keys/publickey.go
- pkg/crypto/keys/publickey_test.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/response/result/block_header.go
- pkg/rpc/response/result/contract_state.go
- pkg/rpc/response/result/nep5.go
- pkg/rpc/server/server_test.go
closes #716 
Minor bug fixes for json marshalling of the following fields:
- `result.Header.NextConsensus`
- `result.ContractState.Script`
- `result.NEP5Balances.Balances`
- `result.Validator.PublicKey`
> rpc: add testing to RPC client package

- pkg/core/cacheddao.go
- pkg/core/dao.go
When flushing many key-value pairs, cost of a buffer grow (reallocation) can become significant.
This PR reduces it by reusing the same buffer for `(*cacheddao).Persist()`.
> core: reuse buffers in persist()

- pkg/smartcontract/param_type.go
It is a single byte anyway.
Now `contract init` works properly.
> smartcontract: do not require pointer in MarshalYAML

- pkg/rpc/request/param.go
Parameters can be sent as string.
Related #774.
> rpc: allow to unmarshal integer params from string

- go.mod
- go.sum
- pkg/core/storage/boltdb_store.go
Also import lib as declared in it's go.mod:
via `go.etcd.io/bbolt`.
> go.mod: update boltdb to v1.3.4

- .circleci/config.yml
> .circleci: add go1.14 tests

- pkg/vm/vm.go
It is different from other JMP* and
+2 should be added to paramter.
Related #452 .
https://github.com/neo-project/neo-vm/blob/master-2.x/src/neo-vm/ExecutionEngine.cs#L1175
> vm: fix offset for CALLI opcode

- pkg/compiler/codegen.go
- pkg/compiler/for_test.go
Easiest way to make infinite loops.
> compiler: allow for loops with empty condition

- examples/storage/storage.go
- pkg/compiler/syscall.go
- pkg/interop/iterator/iterator.go
> examples: expand storage smartcontract with find() usage example

- pkg/core/helper_test.go
- pkg/rpc/client/nep5.go
- pkg/vm/emit/emit.go
- pkg/vm/emit/emit_test.go
It is nice to have a typical task of calling contract method
with specific arguments incapsulated inside some function.
> emit: implement AppCallWithOperationAndArgs

- pkg/vm/serialization.go
- pkg/vm/vm_test.go
C# pushes value and key to the stack of non-serialized items, so key gets
serialized first followed by value. Fixes #806.
Notice though that neither IDictionary in C#, nor map in Go have elements
ordered, so we can easily get a difference in KV pairs order and it would be
impossible to fix.
> vm: make map serialization more compatible with C#

- pkg/core/storage/memcached_store.go
- pkg/core/storage/memcached_store_test.go
Most of the time it's persisted into the MemoryStore or MemCachedStore, when
that's the case there is no real need to go through the Batch mechanism as it
incurs multiple copies of the data.
Importing 1.5M mainnet blocks with verification turned off, before:
real    12m39,484s
user    20m48,300s
sys     2m25,022s
After:
real    11m15,053s
user    18m2,755s
sys     2m4,162s
So it's around 10% improvement which looks good enough.
> storage: optimize (*MemCachedStore).Persist for memory-backed ps

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/slice_test.go
- pkg/compiler/struct_test.go
> compiler: declare compoud types with var keyword

- pkg/vm/stack_item_test.go
> vm: add tests to stack_item.go

- Makefile
After moving Version variable to another package, `Makefile` should also be changed.
> Makefile: set config.Version properly

- pkg/compiler/assign_test.go
- pkg/compiler/func_scope.go
When calculating number of local variables, only
defining assignments (i.e. via `:=`) must be taken into account.
> compiler: calculate stack size more precisely

- docs/cli.md
In #589 `wallet open` command was renamed to `wallet dump`.
In #757 `wallet create` command was renamed to `wallet init`.
Update documentation with correct command examples.
> docs: update wallet operations examples in cli documentation

- pkg/core/interop_neo.go
- pkg/smartcontract/parameter.go
- pkg/smartcontract/parameter_test.go
- pkg/vm/interop.go
- pkg/vm/interop_iterators.go
- pkg/vm/serialization.go
- pkg/vm/stack.go
- pkg/vm/stack_item.go
- pkg/vm/stack_item_test.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
#809 and unstable map serialization (neo-project/neo#1513).
This patchset allows us to proceed with mainnet dump up to #817.
> Rework maps

- examples/token/nep5/nep5.go
- examples/token/token.go
Add Mint(...) to NEP5 for initial tokens supply.
> examples: add nep5 mint function

- pkg/vm/vm.go
- pkg/vm/vm_test.go
Mimic C#'s `%` behavior. https://dotnetfiddle.net/BaVazY
Related 4b44190 (#773).
> vm: use truncated division in MOD

- pkg/vm/vm.go
- pkg/vm/vm_test.go
Do it as in reference implementation: a >> -b == a << b.
https://dotnetfiddle.net/bCzPFI
> vm: handle negative arguments in SHL/SHR

- pkg/core/blockchain.go
- pkg/core/blockchainer.go
- pkg/core/cacheddao.go
- pkg/core/cacheddao_test.go
- pkg/core/dao.go
- pkg/core/dao_test.go
- pkg/core/gas_price_test.go
- pkg/core/interop_neo_test.go
- pkg/core/interops.go
- pkg/core/interops_test.go
- pkg/network/helper_test.go
- pkg/rpc/server/server.go
Fixes #817 where invoked contract missed updated account information because
it got it one layer below cachedDao used to process the block.
> core: wrap cached dao properly, don't miss cached data

- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/dao/cacheddao.go
- pkg/core/dao/cacheddao_test.go
- pkg/core/dao/dao.go
- pkg/core/dao/dao_test.go
- pkg/core/dao/uint32.go
- pkg/core/gas_price_test.go
- pkg/core/interop_neo.go
- pkg/core/interop_neo_test.go
- pkg/core/interop_system.go
- pkg/core/interops.go
- pkg/core/interops_test.go
Move `DAO` and `Blockchainer` into a separate packages.
This is needed to be able to declare interops outside of core package (which will be done in another PR). Related #778, #781 .
> core: split into several packages

- pkg/vm/vm_test.go
Add missing tests for:
- CALL* VM instructions
- Bit and numeric instructions
> vm: missing tests for CALL* instructions

- config/protocol.mainnet.yml
- config/protocol.privnet.docker.four.yml
- config/protocol.privnet.docker.one.yml
- config/protocol.privnet.docker.single.yml
- config/protocol.privnet.docker.three.yml
- config/protocol.privnet.docker.two.yml
- config/protocol.privnet.yml
- config/protocol.testnet.yml
- config/protocol.unit_testnet.yml
- pkg/core/storage/badgerdb_store.go
- pkg/core/storage/badgerdb_store_test.go
- pkg/core/storage/store.go
- pkg/core/storage/store_config.go
- pkg/core/storage/storeandbatch_test.go
> storage: add support of BadgerDB

- pkg/smartcontract/param_type.go
- pkg/vm/opcode/opcode.go
- pkg/vm/stack_item.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
Implement `PUSHNULL` and `ISNULL` opcodes.
Closes #786 .
> vm: support NULL stack item 

- pkg/core/blockchain.go
Discussed in #781, but we may merge something else before that, so let's make an explicit PR just for that.
> core: bump DB version to make it differ from 2.0 branch

- pkg/core/interop_neo_test.go
We need signature to always be invalid, thus invert it's first byte.
RN if it was always set to zero which worked 255/256 times.
> core: fix typo in TestECDSAVerify

- pkg/consensus/cache_test.go
- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/consensus/payload.go
- pkg/consensus/payload_test.go
- pkg/consensus/recovery_message.go
- pkg/consensus/recovery_message_test.go
> consensus: added partial message decoding

- pkg/consensus/cache_test.go
- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/consensus/payload.go
- pkg/consensus/payload_test.go
- pkg/consensus/recovery_message.go
- pkg/consensus/recovery_message_test.go
> consensus: partial consensus message decoding

- pkg/consensus/payload.go
- pkg/consensus/payload_test.go
It's not used really and NEO3 doesn't have it on the wire.
> consensus: drop timestamp from outer payload

- pkg/consensus/block.go
- pkg/consensus/payload.go
- pkg/core/block/block_base.go
- pkg/core/blockchain.go
- pkg/core/helper_test.go
- pkg/core/interop/context.go
- pkg/core/interop/crypto/ecdsa.go
- pkg/core/interop_neo_test.go
- pkg/core/interop_system.go
- pkg/crypto/verifiable.go
Allow to verify arbitrary containers.
Related #834 . (partially closes).
There is one more method `GetScriptHashesForVerifying()`, which is used in `runtime.CheckWitness`, but it requires native contracts to be implemented and some refactoring (as it needs to be a method of `Transaction` and to accept `*Blockchain`).
> core,crypto: implement Verifiable interface

- pkg/rpc/client/nep5.go
In #856 I forgot to add validUntilBlock to NEP5 transfer transaction,
so added now.
> rpc: add validUntilBlock to transferNEP5

- .docker/wallets/wallet1.json
- .docker/wallets/wallet1_solo.json
- .docker/wallets/wallet2.json
- .docker/wallets/wallet3.json
- .docker/wallets/wallet4.json
- pkg/consensus/testdata/wallet1.json
- pkg/consensus/testdata/wallet2.json
- pkg/consensus/testdata/wallet3.json
- pkg/consensus/testdata/wallet4.json
- pkg/wallet/regenerate_test.go
- pkg/wallet/testdata/wallet1.json
- pkg/wallet/testdata/wallet2.json
- pkg/wallet/wallet.go
When changing accounts or VM, it is useful to be able to
regenerate all wallets easy and fast.
> wallet: add test for regenerating test/docker wallets

- pkg/consensus/consensus_test.go
- pkg/core/helper_test.go
- pkg/internal/testchain/address.go
- pkg/rpc/server/server_test.go
Our test chain is used in core,rpc and (in future) interop packages.
It is better to have all related declarations in one place to avoid
code duplication.
This is a part of work towards moving `newTestChain` in a separate package.
> core,test: move helper functions for testchain to the internal package

- cli/smartcontract/smart_contract.go
- pkg/compiler/compiler.go
- pkg/compiler/debug.go
- pkg/compiler/debug_test.go
- pkg/rpc/request/txBuilder.go
- pkg/smartcontract/contract_details.go
A part of integration with NEO Blockchain Toolkit (see #902). To be
able to deploy smart-contract compiled with neo-go compiler via NEO
Express, we have to generate additional .abi.json file. This file
contains the following information:
- hash of the compiled contract
- smart-contract metadata (title, description, version, author,
email, has-storage, has-dynamic-invoke, is-payable)
- smart-contract entry point
- functions
- events
However, this .abi.json file is slightly different from the one,
described in manifest.go, so we have to add auxilaury stractures for
json marshalling. The .abi.json format used by NEO-Express is described
[here](https://github.com/neo-project/neo-devpack-dotnet/blob/master/src/Neo.Compiler.MSIL/FuncExport.cs#L66).
> compiler: add ability to generate .abi.json file

- pkg/rpc/server/server_test.go
Tests failing after #925 merge (which worked before the merge because they missed #898 changes).
Fix it.
> Fix RPC submitblock test

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/func_scope.go
- pkg/compiler/function_call_test.go
- pkg/compiler/return_test.go
> compiler: allow to use `return` with no arguments

- pkg/compiler/codegen.go
- pkg/compiler/function_call_test.go
Go supports declaring multiple arguments of the same type without
duplicating type name. Now we support this too.
Closes #933.
> compiler: support implicit type in function arguments

- examples/token/nep5/nep5.go
`CanTransfer` function checks if `to` and `from` values are correct script hashes. If one of these values is correct and one incorrect, then function returns false positive result. It uses `and` operator which requires both `to` and `from` script hashes to be incorrect to fail transaction.
Instead transaction must fail if at least one argument is incorrect, so it should be `or` operator.
> examples: Use "or" operator in transfer check of NEP5 token

- pkg/rpc/client/wsclient.go
- pkg/rpc/client/wsclient_test.go
`NewWS()` does not check error when new client is created. It can cause panic at `cl.cli = nil` expression.
Check error when new client is created.
> rpc/client: handle client creation error in new wsclient

- pkg/compiler/codegen.go
- pkg/compiler/slice_test.go
- pkg/compiler/struct_test.go
Support using "in-place" assignment operations with struct fields and slice elements.
Closes #953.
> compiler: support using OP= with struct fields and slice elements

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/debug.go
- pkg/compiler/for_test.go
- pkg/compiler/func_scope.go
- pkg/compiler/global_test.go
- pkg/compiler/slice_test.go
- pkg/compiler/struct_test.go
- pkg/compiler/type_test.go
- pkg/compiler/types.go
1. Make type info processing more unified and clear.
2. Simplify some processing of index expressions, reuse code.
3. Emit default values in a generic way.
4. Support for-range loops with value variable. Reimplement `range` via `Iterator`.
5. Support for-range over maps.
6. Port of #954.
> compiler: refactor typeinfo functions

- pkg/core/blockchain.go
- pkg/core/dao/cacheddao.go
- pkg/core/dao/dao.go
- pkg/core/dao/storage_item.go
- pkg/core/interop_neo.go
- pkg/core/interop_system.go
The order of `Storage.Find` is the following:
1. Iterate through items not contained in cache.
2. Iterate through cache.
Closes #822  .
> Cache storage operations across same block tx executions

- pkg/vm/cli/cli.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
#965.
Fix it and improve vm cli a bit.
> Fix pickitem and vm cli 2.x

- pkg/network/message.go
- pkg/network/payload/version.go
- pkg/network/payload/version_test.go
- pkg/network/server.go
- pkg/network/server_test.go
> protocol: move magic exchange to version payload

- pkg/core/interop_system.go
- pkg/crypto/keys/publickey.go
- pkg/crypto/keys/publickey_test.go
> Add key size checks 2.x

- pkg/vm/stack.go
Closes #966.
Logs were pretty helpful.
```2020-05-21T17:45:51.808+0300    WARN    contract invocation failed      {"tx": "71c43cc32ae5336622d7105d1c96387c8cca6c948beac29edfef46712ba5ffeb", "block": 3960417, "error": "error encountered at instruction 14802 (JMPIFNOT): can't convert to bool: Map"}```
> vm: allow to convert Map item to bool

- pkg/vm/vm.go
It's the same as with APPEND and VALUES.
> vm: clone struct item on SETITEM, close #972

- Dockerfile
- Makefile
A NeoGo build in docker is useful for test purposes.
Current Dockerfile is designed to work on developer's laptop only. The PR makes build in docker clean and independent of host filesystem, what allows to include NeoGo instance in test installations.
> Clean build in Dockerfile

- pkg/core/interop_neo.go
Fix a bug introduced in 8ed77f0d.
Draft until will test restore to that height.
Fix #978.
> core: fix a typo in GetUnspentCoins interop

- cli/server/server.go
Diff dumps provided by NGD contain index of the first block as a first item.
Also do proper error handling.
> cli: support DB restore from diff

- pkg/core/blockchain.go
- pkg/core/dao/cacheddao.go
- pkg/core/dao/dao.go
- pkg/core/interop_neo.go
- pkg/core/interop_system.go
- pkg/core/storage_find.go
- pkg/vm/interop.go
- pkg/vm/interop_iterators.go
Fix #988 .
Reproduce behavior of the reference realization:
- if item was Put in cache after it was encountered during
Storage.Find, it must appear twice
- checking if item is in cache must be performed in real-time
during `Iterator.Next()`
Need too retest #822 .
> vm,dao: return storage iterator from DAO in Storage.Find interop

- pkg/network/message_test.go
After #980 there were outdated fields present in message test.
> network: remove outdated fields

- pkg/core/interop_neo.go
- pkg/core/interop_neo_test.go
- pkg/core/native/native_neo.go
Closes #909
We need to match elements order with C# implementation.
Perhaps, we don't even need to change return value of `dao.GetStorageItems(WithKey)` as Storage.Find and NEO.getRegisteredVelidators are the only places where we have to keep elements sorted.
> core: sort results of Storage.Find interop and NEO.getRegisterValidators

- go.mod
- go.sum
- pkg/consensus/block.go
- pkg/consensus/block_test.go
- pkg/consensus/consensus.go
- pkg/consensus/prepare_request.go
- pkg/consensus/prepare_request_test.go
dbft interface changed a little also because of Neo 3 changes, but it still is
compatible with Neo 2.
Merging to neox-2.x first and then to master-2.x
> consensus: update dbft to include CountFailed and RecoveryMessage changes

- pkg/consensus/commit.go
- pkg/consensus/consensus.go
- pkg/consensus/prepare_request.go
- pkg/core/blockchain.go
- pkg/core/blockchainer.go
- pkg/core/dao/dao.go
- pkg/core/mpt/helpers.go
- pkg/core/state/mpt_root.go
- pkg/core/state/mpt_root_test.go
- pkg/network/helper_test.go
- pkg/network/message.go
- pkg/network/payload/inventory.go
- pkg/network/payload/state_root.go
- pkg/network/payload/state_root_test.go
- pkg/network/server.go
Save state root info in storage.
I have tested this with testnet blocks up until 500000 (will test further), state root is equal to that of C# node `bde4717c11aa1c44d05b9bff1eabc796e205bab639e8b2aae8093f4cb10fdaf5`.
Our full neo-go privnet consensus setup works as expected.
> core: update MPT during block processing

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/func_scope.go
- pkg/compiler/interop_test.go
- pkg/compiler/testdata/block/block.go
- pkg/compiler/testdata/util/equals.go
Closes #913 .
Provide package info in the `funcScope` to check if function is defined
insided an interop package. As a good side-effect bytecode for builtins from `util`
is no longer emitted.
Related #941.
> compiler: process interop together with package

- go.mod
- go.sum
- pkg/consensus/recovery_message.go
Update dbft and fix recovery message processing.
> Consensus fixes 2.x neox

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/debug.go
- pkg/compiler/slice_test.go
- pkg/compiler/struct_test.go
Closes #949 .
There is no way we can distinguish `[]int(nil)` from `[]int{}` without substantial effort. And even then array is a reference type so it's instance is equal only to itself in NeoVM.
There is a simple workaround for checking if slice is empty: `len(arr) == 0`.
1. Emit error on comparison with `nil`
2. Fix type dispatch during `!=` processing.
> compiler: set default values for complex struct fields (2.x)

- pkg/compiler/assign_test.go
- pkg/compiler/syscall.go
- pkg/core/interop/json/json.go
- pkg/core/interop/json/json_test.go
- pkg/core/interops.go
- pkg/interop/json/json.go
- pkg/vm/context.go
- pkg/vm/contract_checks.go
- pkg/vm/interop.go
- pkg/vm/stackitem/item.go
- pkg/vm/stackitem/json.go
- pkg/vm/stackitem/json_test.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
Closes #1030.
There is a separate `ToJSON` function (instead of `MarshalJSON`) because it is more convenient.
Interops have some restrictions, for example marshaled integer must not exceed `2^53` while in `Integer` items marshaled in RPC can be 32-bytes wide.
> Implement System.Json.* interops

- pkg/consensus/payload_test.go
- pkg/consensus/recovery_message.go
Add state root signature to `commitCompact` in `recoveryMessage`.
> consensus: fix commitCompact payload

- pkg/consensus/recovery_message.go
- pkg/io/binaryReader.go
- pkg/io/binaryrw_test.go
```
Jun 12 06:29:45 nodoka neo-go[2976]: panic: runtime error: makeslice: len out of range
Jun 12 06:29:45 nodoka neo-go[2976]: goroutine 645 [running]:
Jun 12 06:29:45 nodoka neo-go[2976]: github.com/nspcc-dev/neo-go/pkg/io.(*BinReader).ReadVarBytes(0xc033febd00, 0xc03174d380, 0xc033942184, 0x40)
Jun 12 06:29:45 nodoka neo-go[2976]: #011/home/rik/dev/neo-go2/pkg/io/binaryReader.go:173 +0x4e
Jun 12 06:29:45 nodoka neo-go[2976]: github.com/nspcc-dev/neo-go/pkg/consensus.(*commitCompact).DecodeBinary(0xc033942180, 0xc033febd00)
Jun 12 06:29:45 nodoka neo-go[2976]: #011/home/rik/dev/neo-go2/pkg/consensus/recovery_message.go:115 +0x6d
Jun 12 06:29:45 nodoka neo-go[2976]: github.com/nspcc-dev/neo-go/pkg/io.(*BinReader).ReadArray(0xc033febd00, 0xc3eb40, 0xc033942020, 0x0, 0x0, 0x0)
Jun 12 …
```
> Allow to restrict slice size in `io.ReadVarBytes()`

- .docker/privnet-entrypoint.sh
When I run neo-go in docker image I see these line in logs:
```
sh: missing ]
```
Shell requires to have white space before `]` symbol in condition check. Now condition is not checked and 6k-block dump is not restored. 
Fix entry point script.
> docker: fix shell condition check in entrypoint script

- config/protocol.testnet.yml
- config/protocol.unit_testnet.yml
- pkg/config/protocol_config.go
- pkg/consensus/commit.go
- pkg/consensus/consensus.go
- pkg/consensus/payload.go
- pkg/consensus/payload_test.go
- pkg/consensus/prepare_request.go
- pkg/consensus/recovery_message.go
- pkg/core/blockchain.go
- pkg/core/interops.go
- pkg/io/binaryReader.go
- pkg/network/server.go
- pkg/network/tcp_peer.go
Closes #1085 (merge will follow).
There were 3 ways to handle multiple wire formats for consensus messages:
1. Using global variables
2. Renaming `EncodeBinary` to `EncodeGeneric(BinWriter, config)`
3. Providing context directly to `BinWriter`.
I have chosen 3rd, because 2nd is rather verbose, and 1st can lead to problems, though it is a final version and maybe we can afford having global.
> Enable state root exchange base on config

- go.mod
- go.sum
- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
Pick up the following changes:
* recovery message sending fix
* tx re-requests on sendRecoveryRequest
* proposed block checks fix
* timeout calculation fix for InitializeConsensus
* removal of TxPerBlock which is irrelevant for neo-go (policying is done by
the node, not dbft library)
> consensus: update dbft library (neox-2.x)

- pkg/compiler/codegen.go
- pkg/compiler/convert_test.go
- pkg/compiler/types.go
Close #960 .
Close #1092 .
1. Do not fail for `int(...)` conversions.
2. Convert to `ByteString` for `[]byte -> string` conversions.
3. Emit proper conversions for type assertions.
> Support type conversions

- cli/wallet/multisig.go
- cli/wallet/nep5.go
- cli/wallet/wallet.go
In #1104 wallet path argument has changed from `--path` to `--wallet` but cli application still getting wallet path with `ctx.String("path")` instead of `ctx.String("wallet")`.
Replace `ctx.String("path")` with `ctx.String("wallet")` in cli wallet commands.
> cli: update wallet path argument name in cli context

- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/core/cache/cache_test.go
When CN is not up to date with the network is synchonizes blocks first and
only then starts consensus process. But while synchronizing it receives
consensus payloads and tries to process them even though messages reader
routine is not started yet. This leads to lots of goroutines waiting to send
their messages:
Jun 25 23:55:53 nodoka neo-go[32733]: goroutine 1639919 [chan send, 4 minutes]:
Jun 25 23:55:53 nodoka neo-go[32733]: github.com/nspcc-dev/neo-go/pkg/consensus.(*service).OnPayload(0xc0000ecb40, 0xc005bd7680)
Jun 25 23:55:53 nodoka neo-go[32733]: #011/go/src/github.com/nspcc-dev/neo-go/pkg/consensus/consensus.go:329 +0x31b
Jun 25 23:55:53 nodoka neo-go[32733]: github.com/nspcc-dev/neo-go/pkg/network.(*Server).handleConsensusCmd(...)
Jun 25 23:55:53 nodoka neo-go[32733]: …
> consensus: prevent synchronization stalls

- pkg/consensus/consensus.go
- pkg/consensus/payload.go
- pkg/consensus/payload_test.go
- pkg/network/message.go
Consensus payload's hash now depends on the network node is operating
in.
Fix #1119 .
> consensus: add network magic to hash data

- pkg/rpc/client/nep5.go
Neo and Gas script hashes are flipped.
Update values.
> cli: update hardcoded script hashes for neo and gas contracts

- pkg/vm/vm.go
> Extend PrintOps for JMP* and INIT* instructions

- pkg/consensus/consensus.go
- pkg/core/blockchain.go
- pkg/core/native/native_gas.go
- pkg/core/native/native_neo.go
- pkg/crypto/keys/publickey.go
- pkg/crypto/keys/publickey_test.go
- pkg/smartcontract/context/context_test.go
There could possibly be a bug which nonetheless doesn't lead to invalid state.
Fix #1119 .
> Copy validators when returning to the outside

- pkg/consensus/consensus.go
After 5c2f69bd2cff98382b4b458462d488e1945f3f37 there's an `invalid
message` panic when trying to run 4-nodes private network:
```
=> Try to restore blocks before running node
2020-06-30T08:59:39.696Z	INFO	no storage version found! creating genesis block
2020-06-30T08:59:39.696Z	INFO	service is running	{"service": "Prometheus", "endpoint": ":20001"}
2020-06-30T08:59:39.696Z	INFO	service hasn't started since it's disabled	{"service": "Pprof"}
_   ____________        __________
/ | / / ____/ __ \      / ____/ __ \
/  |/ / __/ / / / /_____/ / __/ / / /
/ /|  / /___/ /_/ /_____/ /_/ / /_/ /
/_/ |_/_____/\____/      \____/\____/
2020-06-30T08:59:39.696Z	INFO	starting rpc-server	{"endpoint": ":30333"}
2020-06-30T08:59:39.696Z	INFO	node started	{"blockHeight": 0, "headerHeight": 0}
/NEO-GO:/ …
```
> consensus: prevent `invalid message` panic

- cli/smartcontract/smart_contract.go
- pkg/compiler/compiler.go
1. Use `.manifest.json` for contract deployment.
2. Generate `.manifest.json` and `.debug.json` independently.
> compiler, cli: update ContractCompile and ContractDeploy methods

- pkg/config/config.go
It costs us nothing and makes API much more flexible.
> config: allow to specify config path directly

- pkg/core/transaction/transaction.go
- pkg/core/transaction/transaction_test.go
- pkg/rpc/client/rpc_test.go
Closes #1141 .
`FeePerByte()` takes much less time in benchmark now.
> Cache `transaction.FeePerByte()`

- pkg/rpc/request/param.go
- pkg/rpc/request/param_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
Fix #1143 .
Also extend `getnep5transfers`.
> rpc: support stringified address in getnep5balances RPC

- cli/smartcontract/smart_contract.go
- pkg/rpc/client/nep5.go
- pkg/rpc/client/rpc.go
1. Add specified cosigners to invocation transaction.
2. Parse cosigners properly.
> cli: fixes for contract deployment and invocation

- pkg/rpc/server/server.go
- pkg/vm/stackitem/serialization.go
1. Add ability to deserialise Buffer item.
2. Wrap error of `getapplicationlog` RPC response.
> vm: fix stackitem deserialisation

- pkg/core/dao/cacheddao.go
- pkg/core/interop_neo.go
Fixes #1144. It's quite simple approach, we just update balance info right
upon contract migration. It will slow down migration transactions, but it
takes about 1-2 seconds to Seek through balances at mainnet's 3.8M, so the
approach should still work good enough. The other idea was to make lazy
updates (maintaining contract migration map), but it's more complicated to
implement (and implies that a balance get might also do a write).
There also is a concern about memory usage, it can give a spike of some tens
of megabytes, but that also is considered to be acceptable.
I'm still running it against mainnet chain, at 2.2M+ it's compatible with the old version wrt storage changes. Still need to get to the current state to check if it fixes the bug really.
> Fix nep5 balances migration (2.x)

- pkg/rpc/request/param.go
- pkg/rpc/request/param_test.go
- pkg/rpc/request/txBuilder.go
- pkg/rpc/request/tx_builder_test.go
> rpc/request: decode bytearray as base64, fix #1151

- Dockerfile
Useragent version wasn't set when building from Dockerfile. Fixed.
> dockerfile: fix useragent version

- pkg/vm/context.go
- pkg/vm/json_test.go
- pkg/vm/vm.go
It's tied to the current contract, not to VM.
> vm: fix INITSSLOT, it's context-wide, not VM-wide

- pkg/crypto/keys/publickey.go
Closes #1110 .
When one works with legacy (NEO2) wallets, it is useful to have access
to old verification script formats.
> keys: support returning legacy verification script

- integration/performance_test.go
- pkg/core/blockchain.go
- pkg/core/interop_neo_test.go
- pkg/core/mempool/mem_pool_test.go
- pkg/core/transaction/attr_usage.go
- pkg/core/transaction/attribute.go
- pkg/core/transaction/attrusage_string.go
They're not supported in Neo 3. Also change data encoding to base64 following
Neo 3 changes.
> transaction: drop old attributes

- pkg/rpc/server/server.go
GetScriptContainer() interop can try to get this transaction and this attempt
will lead to hash calculation with transaction serialization, but transaction
can't be successfully serialized if it doesn't have a script set, so this
makes test invocations fail.
> rpc: set transaction's script for test invocation

- pkg/core/interop/context.go
- pkg/core/interop/runtime/witness.go
- pkg/core/interops.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_nep5.go
- pkg/core/native/policy.go
It's impossible to transfer native assets from contract's address. And we have nasty old #924. 
Add caller check to transfer and deal with script hash getters.
> Add calling scripthash check to native nep5 transfers

- pkg/network/server.go
We can't lock them (or there will be a deadlock), but we need to fix this:
fatal error: concurrent map iteration and map write
runtime.throw(0xdec086, 0x26)
/usr/lib64/go/1.12/src/runtime/panic.go:617 +0x72 fp=0xc02fec2bf8 sp=0xc02fec2bc8 pc=0x42d932
runtime.mapiternext(0xc02fec2d40)
/usr/lib64/go/1.12/src/runtime/map.go:860 +0x597 fp=0xc02fec2c80 sp=0xc02fec2bf8 pc=0x40efe7
github.com/nspcc-dev/neo-go/pkg/network.(*Server).Shutdown(0xc0000fc160)
/home/rik/dev/neo-go2/pkg/network/server.go:194 +0x238 fp=0xc02fec2db0 sp=0xc02fec2c80 pc=0xa89da8
github.com/nspcc-dev/neo-go/cli/server.startServer(0xc0000fcc60, 0x0, 0x0)
/home/rik/dev/neo-go2/cli/server/server.go:399 +0x7a9 fp=0xc02fec3820 sp=0xc02fec2db0 pc=0xae2079
...
> network: copy peers for Shutdown iteration

- pkg/core/blockchain.go
After transaction unification and UTXO removal storeBlock became quite simple
and doesn't require any refactoring any more.
> core: remove stale storeBlock comment, fix #365

- pkg/compiler/codegen.go
- pkg/compiler/syscall.go
- pkg/core/interop_neo.go
- pkg/core/interop_neo_test.go
- pkg/core/interop_system.go
- pkg/core/interop_system_test.go
- pkg/core/interops.go
- pkg/interop/binary/binary.go
- pkg/interop/blockchain/blockchain.go
- pkg/interop/contract/contract.go
- pkg/smartcontract/manifest/manifest.go
- pkg/smartcontract/manifest/manifest_test.go
- pkg/smartcontract/manifest/method.go
First part of #1055.
1. Were added:
- System.Binary.Base64Encode
- System.Binary.Base64Decode
- System.Contract.GetCallFlags
2. Were fixed:
- System.Blockchain.GetContract
- System.Blockchain.GetTransactionFromBlock
- System.Contract.CallEx
- System.Contract.Create
- System.Contract.IsStandard
- System.Contract.Update
3. No errors in:
- System.Binary.Deserialize
- System.Binary.Serialize
- System.Blockchain.GetBlock
- System.Blockchain.GetHeight
- System.Blockchain.GetTransaction
- System.Blockchain.GetTransactionHeight
- System.Contract.CreateStandardAccount
- System.Contract.Destroy
4. Separate adjustment is needed (see #1181)
- System.Contract.Call
- System.Contract.CallEx
> interop: post-preview2 adjustment

- pkg/core/dao/cacheddao.go
- pkg/core/interop_neo.go
- pkg/network/server.go
- pkg/rpc/request/param.go
- pkg/rpc/request/param_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
2.x branch has accumulated some useful changes.
Forward-port them to master.
> Forward port from 2.x

- pkg/vm/vm.go
neo-vm doesn't copy altstack on CALL, so it effectively is cleared.
> vm: clear altstack on CALL, fix #1158

- pkg/core/blockchain.go
- pkg/network/server.go
When synchronizing with stateroot-enabled network from genesis and if
stateroot is not enabled in block zero we were failing to update state height
because initially it's updated with a jump from 0 to StateRootEnableIndex, so
we should allow that to happen to have correct state height.
> core: fix stateroot height update for testnet

- cli/wallet/multisig.go
- cli/wallet/nep5.go
- pkg/rpc/client/nep5.go
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/response/result/relay_result.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
These RPC calls should return hashes instead of boolean values.
> rpc: adjust `sendrawtransaction` and `submitblock` RPC calls

- pkg/compiler/vm_test.go
- pkg/vm/context.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
Close #1210 .
Also remove alt.stack mentions.
> Remove return value count

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/syscall.go
- pkg/core/interop/crypto/hash.go
- pkg/core/interop/crypto/hash_test.go
- pkg/core/interop/crypto/interop.go
- pkg/core/interop_system.go
- pkg/core/interops.go
- pkg/core/native/interop.go
- pkg/interop/crypto/crypto.go
- pkg/interop/storage/storage.go
The third part of #1055.
1. Neo.Crypto.RIPEMD160 was added. (closes #1193)
2. Were fixed:
System.Storage.GetContext
System.Storage.GetReadOnlyContext
System.Storage.Put
System.Storage.PutEx
Neo.Native.Deploy
3. No errors in:
System.Storage.Delete
System.Storage.Find
System.Storage.Get
System.Storage.AsReadOnly
Neo.Crypto.VerifyWithECDsaSecp256r1
Neo.Crypto.VerifyWithECDsaSecp256k1
Neo.Crypto.CheckMultisigWithECDsaSecp256r1
Neo.Crypto.CheckMultisigWithECDsaSecp256k1
Neo.Crypto.SHA256
For the rest of them there are separate issues, so that' the last part of 1055.
> interop: post-preview2 adjustment, part 3

- pkg/core/interop/crypto/ecdsa_test.go
- pkg/core/interop_neo_test.go
- pkg/crypto/keys/private_key.go
- pkg/crypto/keys/sign_verify_test.go
1. Pad R and S when computing signature in `Secp256k1` test.
2. Ensure public key is invalid in interop test.
Fix #1223.
> crypto: fix failing Secp256r1 test

- pkg/core/blockchain.go
- pkg/core/native/policy.go
Disallow costly verification methods. We put this limit in policy
contract as it may be a subject to change in future.
In fact this value also overrides gas limit for header verification.
Close #1202.
> core: restrict maximum gas allow for verification

- pkg/vm/cli/cli.go
Support everything from https://github.com/neo-project/neo-node/pull/535 . Checked examples from there.
Also support swapping endianness for arbitrary hex strings.
Close #1207 .
> cli: implement conversion helpers

- .docker/docker-compose.yml
- cli/wallet/nep5.go
- config/protocol.privnet.docker.single.yml
- pkg/rpc/client/nep5.go
I have introduces another command and left `transfer` untouched for backwards compatibility and ease of use. Maybe we should just change API for `transfer`.
Usage example: `./neogo wallet nep5 multitransfer -w wallet1_solo.json --from NVNvVRW5Q5naSx2k2iZm7xRgtRNGuZppAK --token neo -r http://127.0.0.1:30333 NYqxsNMHxDg3T19APYP27mBZFfauC4zngR:2 NVNvVRW5Q5naSx2k2iZm7xRgtRNGuZppAK:3`
Don't allow to transfer multiple assets in a single command as it seems overcomplicated.
Close #940 .
> Generate multitransfer NEP5 transactions on client

- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/native_contract_test.go
- pkg/core/native_policy_test.go
- pkg/core/state/notification_event.go
- pkg/core/state/notification_event_test.go
- pkg/rpc/response/result/application_log.go
- pkg/rpc/response/result/raw_mempool.go
- pkg/rpc/response/result/tx_raw_output.go
- pkg/rpc/server/server.go
- pkg/vm/json_test.go
- pkg/vm/state.go
- pkg/vm/state_test.go
- pkg/vm/vm.go
> rpc: update `getrawmempool` and `getrawtransaction` RPC-calls

- pkg/core/blockchain.go
- pkg/core/blockchainer/blockchainer.go
- pkg/core/dao/dao.go
- pkg/core/mpt/base.go
- pkg/core/mpt/branch.go
- pkg/core/mpt/doc.go
- pkg/core/mpt/extension.go
- pkg/core/mpt/hash.go
- pkg/core/mpt/helpers.go
- pkg/core/mpt/leaf.go
- pkg/core/mpt/node.go
- pkg/core/mpt/node_test.go
- pkg/core/mpt/proof.go
- pkg/core/mpt/proof_test.go
- pkg/core/mpt/trie.go
- pkg/core/mpt/trie_test.go
- pkg/core/prometheus.go
- pkg/core/state/mpt_root.go
- pkg/core/state/mpt_root_test.go
- pkg/core/storage/store.go
- pkg/network/helper_test.go
Close #851 .
P2P/Consensus/RPC are not ported.
The only difference is that storage keys and values now are serialized in a straight-forward way.
> Implement MPT

- pkg/network/compress.go
It's a protocol level error when uncompressed payload size doesn't match the
one specified in the header.
> network: handle length mismatch in decompression routine

- pkg/consensus/consensus.go
- pkg/core/blockchain.go
- pkg/core/blockchainer/blockchainer.go
- pkg/core/native/policy.go
- pkg/core/native_policy_test.go
- pkg/network/helper_test.go
> core, consensus: add maxBlockSystemFee to native Policy

- cli/wallet/nep5.go
- pkg/rpc/client/nep5.go
Like this:
```
./neogo wallet nep5 multitransfer -w wallet1_solo.json
--from NVNvVRW5Q5naSx2k2iZm7xRgtRNGuZppAK -r http://127.0.0.1:30333
neo:NYqxsNMHxDg3T19APYP27mBZFfauC4zngR:2
neo:NVNvVRW5Q5naSx2k2iZm7xRgtRNGuZppAK:3
gas:NYqxsNMHxDg3T19APYP27mBZFfauC4zngR:2
```
Close #1256 .
> cli: allow to transfer multiple tokens in `multitransfer`

- cli/main.go
- cli/util/convert.go
- pkg/vm/cli/cli.go
> Allow to use `vm parse` directly

- docs/notifications.md
- pkg/rpc/client/wsclient.go
- pkg/rpc/client/wsclient_test.go
- pkg/rpc/request/param.go
- pkg/rpc/request/param_test.go
- pkg/rpc/server/subscription.go
- pkg/rpc/server/subscription_test.go
> rpc: filter subscriptions' notifications by name

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/compiler.go
- pkg/compiler/init_test.go
- pkg/compiler/testdata/pkg1/pkg1.go
- pkg/compiler/testdata/pkg2/pkg2.go
- pkg/compiler/testdata/pkg3/pkg3.go
Process `init()` functions after global variables has been processed.
It's body is saved into the `_initialize` method where all
initialization is performed.
Close #1253.
> compiler: allow to use `init` function

- pkg/core/interop/runtime/util.go
- pkg/core/interop_system.go
- pkg/vm/stackitem/item.go
- pkg/vm/stackitem/item_test.go
> Disallow changing notifications

- pkg/core/blockchain.go
Follow neo-project/neo#1776. Looks very suspicious to me as it severely limits
verification scripts, but we have to be compatible at this point.
> core: restrict verification scripts with CallFlags.None

- docs/compiler.md
- pkg/compiler/codegen.go
- pkg/compiler/pointer_test.go
Close #1032 .
Things to discuss:
1. Do we need to support taking pointers from the variable? This can be done by using `Array(Struct)` wrapper instead of `Struct -> Array`, but doesn't worth the effort IMO.
2. Do we need to copy struct when passing it as a parameter? This way we become more compatible with the Go spec, but again does it worth the effort? While simple struct copy can be done with `Struct -> Array -> Struct` conversion, this won't copy non-pointer struct fields, so we need to do something different.
> Support pointers in compiler

- pkg/core/blockchain.go
- pkg/core/blockchainer.go
- pkg/core/dao/cacheddao.go
- pkg/core/dao/dao.go
- pkg/core/state/nep5.go
- pkg/core/state/nep5_test.go
- pkg/core/state/transfer_log.go
- pkg/core/storage/store.go
- pkg/network/helper_test.go
- pkg/rpc/response/result/utxo.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
Reuse `NEP5TransferLog` for everything.
> Implement `getutxotransfers` RPC (2.x)

- pkg/rpc/client/rpc_test.go
- pkg/rpc/response/result/mpt.go
Follow neo-project/neo#1808. Note that this is an incompatible change, but
this feature is still considered to be experimental upstream.
> rpc: use lowercase JSON field names for StateHeight

- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
Set default value for the first timestamp to a week ago.
> rpc: provide timestamps in `getnep5transfers`

- pkg/core/blockchain.go
- pkg/core/state/transfer_log.go
- pkg/rpc/response/result/utxo.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
Close #1287 .
The only thing that bothers me is that `total_amount` field is somewhat meaningless now.
> rpc: adjust `getutxotransfers` RPC

- pkg/compiler/util_test.go
- pkg/core/interop/callback/callback.go
- pkg/core/interop/callback/method.go
- pkg/core/interop/callback/pointer.go
- pkg/core/interop/callback/syscall.go
- pkg/core/interop/context.go
- pkg/core/interop/crypto/ecdsa.go
- pkg/core/interop/crypto/hash.go
- pkg/core/interop/enumerator/interop.go
- pkg/core/interop/iterator/interop.go
- pkg/core/interop/json/json.go
- pkg/core/interop/runtime/util.go
- pkg/core/interop/runtime/witness.go
- pkg/core/interop_neo.go
- pkg/core/interop_neo_test.go
- pkg/core/interop_system.go
- pkg/core/interop_system_test.go
- pkg/core/interops_test.go
- pkg/core/native/interop.go
- pkg/core/native/native_nep5.go
- pkg/core/native_contract_test.go
- pkg/vm/vm.go
Closes #1200
I made an example of such call, but not sure if this testcase covers the problem. If so, than we are able to perform calls from native contracts and it might be necessary to implement a separate method for such calls.
> core: contractCall from native contracts

- pkg/core/blockchain.go
- pkg/core/blockchainer/blockchainer.go
- pkg/network/helper_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
Close #1280 .
1. Replace `GetNEP5TransferLog` with `ForEachNEP5Transfer`.
2. Allow to use timestamps in the request. (they are now in ms).
> Port `getnep5transfers` changes to master

- docs/compiler.md
- examples/runtime/runtime.go
- examples/token-sale/token_sale.go
- pkg/interop/runtime/runtime.go
We now support using exported constants, so there is no
need in declaring functions. All functions from `interop/`
are not to be compiled.
Fix #1298.
> compiler: use constants in interops

- cli/smartcontract/smart_contract.go
- examples/engine/engine.go
- examples/engine/engine.yml
- examples/iterator/iterator.go
- examples/iterator/iterator.yml
- examples/runtime/runtime.go
- examples/runtime/runtime.yml
- examples/storage/storage.go
- examples/storage/storage.yml
- examples/token-sale/token_sale.go
- examples/token-sale/token_sale.yml
- examples/token/nep5/nep5.go
- examples/token/token.go
- examples/token/token.yml
- pkg/compiler/compiler.go
- pkg/compiler/debug.go
- pkg/compiler/debug_test.go
- pkg/compiler/interop_test.go
- pkg/core/helper_test.go
> examples: update examples

- cli/smartcontract/smart_contract.go
There was an empty byte array while trying to restore .nef from bytes
after a34ba92d4.
> cli: fix `contract inspect` command

- cli/wallet/multisig.go
- cli/wallet/nep5.go
- cli/wallet/validator.go
- cli/wallet/wallet.go
Implement `wallet candidate (un)register`.
Move `wallet vote` to `wallet candidate vote`.
Close #1283 .
> Support (un)registering candidate in CLI

- pkg/rpc/client/rpc_test.go
- pkg/rpc/response/result/application_log.go
Following https://github.com/neo-project/neo-modules/issues/318
> rpc: marshal `getapplicationlog` stack as []stackitem.Item

- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/interop_system_test.go
- pkg/smartcontract/manifest/manifest.go
> Add tests for `verifyTx` and `verifyHeader`

- pkg/core/native/native_nep5.go
According to manifest, OnPersist.ReturnType is void, so we shouldn't
return anything from it. It's not so important, as we drop this value at
the end of OnPersist invocation.
> core: fix getOnPersistWrapper for native contracts

- pkg/network/message.go
We don't react on this command, but we should be able to decode it.
> network: decode CMDNotFound

- cli/wallet/validator.go
- pkg/rpc/client/client.go
- pkg/rpc/client/nep5.go
- pkg/rpc/client/rpc.go
- pkg/rpc/server/client_test.go
- pkg/vm/context.go
- pkg/vm/debug_test.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
- pkg/wallet/account.go
To calculate network fee properly we must know type of every
signer (simple, multisig, contract). Providing scripts is the most
simple and flexible way to know this.
Also add tests for some functions from `client` package.
Close #1304.
> rpc/client: provide scripts in AddNetworkFee

- pkg/consensus/recovery_message.go
Fixes wrong hash calculated for prepare request leading to bad prepare
response and inability to run heterogeneous 2+2 Go/C# nodes consensus.
> consensus: payloads from recovery messages are network-dependent too

- pkg/core/native/native_neo.go
- pkg/core/native_neo_test.go
There is no need in writing the same value again and again.
Closes #1337.
> native: do not rewrite NextValidators in (*NEO).OnPersist()

- docs/compiler.md
- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/init_test.go
- pkg/compiler/slice_test.go
- pkg/compiler/types.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
1. Support `make` for everything and `copy` for byte slices.
2. Fix bug in MEMCPY.
> Fix MEMCPY, support `copy` and `make` in compiler

- pkg/rpc/client/nep5.go
- pkg/rpc/server/client_test.go
Specify scope explicitly.
Fix #1354.
Testing done: `make env_single` + query from issue executes with `HALT`.
> rpc/client: provide sender in `CreateNEP5MultiTransferTx`

- pkg/rpc/request/param.go
- pkg/rpc/request/param_test.go
Support using `0x<hash>` in `getapplicationlog` etc.
> rpc: support 0x form of Uint256 in requests

- pkg/rpc/request/param.go
- pkg/rpc/request/param_test.go
> rpc: support 0x form of Uint256 in requests (2.x)

- pkg/compiler/codegen.go
- pkg/compiler/defer_test.go
- pkg/compiler/for_test.go
- pkg/compiler/func_scope.go
- pkg/compiler/slice_test.go
- pkg/compiler/switch_test.go
It was incorrectly parsed as void call.
@roman-khimov @AnnaShaleva do we have any other structures where expression value is used but not assigned to a variable? (besides `if` and `switch`). Maybe I forgot something.
Also do some other improvements for void calls processing (handle `recover` and `copy`).
> compiler: fix a bug with type conversion in switch

- pkg/core/blockchain.go
- pkg/rpc/server/server_test.go
When this vout:
{
"n" : 0,
"address" : "ASkbjwosE3aKyGtDQkEgqhNq3Zpv8Xkt14",
"asset" : "0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b",
"value" : "606"
},
Becomes this transfer:
{
"txid" : "0x192ab8e422aed6ac868cb329d6f9af20964134b591908c736d32a2fd8a51d7bf",
"amount" : "60600000000",
"block_index" : 6113653,
"timestamp" : 1599199074
}
Something is wrong here.
> core: fix NEO UTXO tracking, drop Fixed8 multiplier

- pkg/core/native/contract.go
Close #1389 .
I have decided to exclude `Policy` instead of enumerating `NEO` and `GAS`, because calling `onPersist` seems like a default behaviour and can be tested.
> core: do not persist Policy contract

- pkg/core/transaction/transaction.go
- pkg/rpc/response/result/tx_raw_output.go
- pkg/rpc/server/server_test.go
We had a kludge for getrawtransaction to set this useless field, but
7e371588a7186a13786abb246395b3f52d066873 broke it. Add it right into the
decoder now to fix all types of queries (getblock/getrawtransaction/gettxout).
Fixes #1392.
> transaction: set output position when decoding

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/global_test.go
- pkg/compiler/map_test.go
1. Don't allocate slots for constants.
2. Don't allocate slots for `_` variables.
3. Support `delete()` builtin.
> Small compiler improvements

- pkg/core/blockchain.go
- pkg/core/blockchainer.go
- pkg/core/state/nep5.go
- pkg/core/state/nep5_test.go
- pkg/network/helper_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
Suppose we want to get 10 most recent transfers, without this change we would either set start date to 0 (forcing server to return everything) or try to guess it (making multiple queries).
With limits in place we can set start date to 0, but still get only 10 transfers.
> Add limits to get(nep5|utxo)transfers

- cli/server/server.go
Close #1307 .
Testing done:
1. Imported test dump, and exported it with roots.
2. Imported test dump with roots with no errors, including incremental import (`--count 1 --start x`).
3. Block dump files exported with and without `--state` argument don't differ.
> Allow to import state roots from dump

- docs/rpc.md
- pkg/rpc/client/doc.go
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/response/result/nep5.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
This adds paging to get*transfers and adds a new getalltransfertx call. It can be updated based on feedback from testing (especially in output types), but in general the logic should be the same --- we're returning transaction-grouped transfers, both NEP5 and UTXO in the same feed.
> Getalltransfertx 2.x

- docs/rpc.md
- pkg/rpc/response/result/nep5.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
The same they're displayed for transactions.
> rpc/server: use strings for sys and net fees in TransferTx

- pkg/consensus/consensus.go
- pkg/core/block/block.go
- pkg/core/block/block_test.go
- pkg/core/helper_test.go
- pkg/core/util.go
- pkg/crypto/hash/merkle_bench_test.go
- pkg/crypto/hash/merkle_tree.go
- pkg/crypto/hash/merkle_tree_test.go
- pkg/internal/testchain/address.go
NewMerkleTree is a memory hog, we can do better than that:
BenchmarkMerkle/NewMerkleTree-8                       13          88434670 ns/op        20828207 B/op     300035 allocs/op
BenchmarkMerkle/CalcMerkleRoot-8                      15          69264150 ns/op               0 B/op          0 allocs/op
> hash: introduce memory-optimized merkle root hash calculation routine

- pkg/rpc/server/server_test.go
I think it's caused by connection limits server-side, we never close
connection on the client.
> rpc/server: fix "websocket: bad handshake" during testing

- pkg/rpc/client/rpc_test.go
It was done in 770c8d774c , probably by accident.
> rpc/client: use standard errors package in tests

- pkg/compiler/codegen.go
- pkg/compiler/func_scope.go
- pkg/compiler/slice_test.go
- pkg/compiler/struct_test.go
1. Support variables in slice-literals.
2. Don't count function invocation inside literal as a void call.
I think, `analyzeVoidCalls` can be somehow rewritten in future, because there were too much bugs with it.
> Support variables in slice literals.

- pkg/core/native/native_neo.go
- pkg/core/native_neo_test.go
> native: cache GASPerBlock values

- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/interop/runtime/witness.go
We should pay attention to the previously consumed gas during tx
witnesses verification.
> core: take into account gasConsumed during tx witnesses verification

- docs/compiler.md
- pkg/vm/stackitem/item.go
- pkg/vm/stackitem/item_test.go
- pkg/vm/stackitem/json.go
- pkg/vm/stackitem/json_test.go
- pkg/vm/vm.go
- pkg/vm/vm_test.go
1. Add MaxComparableSize to restrict the length of comparable ByteArray stack items.
2. Add test to check reference counter after PACK-UNPACK and PACK-UNPACK-PACK scripts. Reference issue: https://github.com/neo-project/neo-vm/pull/370. BTW, there might be a mistake in https://github.com/neo-project/neo-vm/pull/370#issuecomment-699735735 because the following tests are passed by C# node:
```
[TestMethod]
public void TestPackUnpack()
{
using (var engine = new ExecutionEngine())
{
using (var script = new ScriptBuilder())
{
int size = 1000;
byte[] args = new BigInteger(size).ToByteArray();
for (int i = 0; i < size; i++)
{
script.Emit(OpCode.PUSH1);
}
script.Emit(OpCode.PUSHINT16, args);
script.Emit(OpCode.PACK);
script.Emit(OpCode.UNPACK);
engine.LoadScript(script.ToArray()); …
```
> vm: add MaxComparableSize and check reference counter after PACK-UNPACK

- pkg/rpc/client/nep5.go
We should also pay attention to the VM state before adding system fee to
the transaction. We shouldn't allow adding system fee in case if
the transaction script is bad.
> rpc: check VM state in (*Client).CreateTXFromScript

- cli/smartcontract/smart_contract.go
- cli/smartcontract/smart_contract_test.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/transaction/signer.go
- pkg/core/transaction/transaction.go
- pkg/core/transaction/transaction_test.go
- pkg/core/transaction/witness_scope.go
- pkg/core/transaction/witness_scope_string.go
- pkg/core/util.go
- pkg/rpc/client/rpc.go
- pkg/rpc/request/param_test.go
- pkg/rpc/server/server.go
Follow missed change from neo-project/neo#1816 .
`None` may be used for any signer. Currently it is used
for sender to only pay fees, or to sign tx attributes.
> transaction: rename FeeOnly to None

- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
We don't have `getvalidators` RPS call, there's only
`getnextblockvalidators` in the reference implementation.
> rpc: getvalidators -> getnextblockvalidators

- pkg/core/blockchain.go
- pkg/core/native/contract.go
- pkg/core/native/native_gas.go
- pkg/core/native/native_neo.go
4-nodes private network is failing after restoring from dump:
```
$ docker logs neo_go_node_one
=> Try to restore blocks before running node
2020-09-30T11:55:49.122Z	INFO	no storage version found! creating genesis block
2020-09-30T11:55:49.124Z	INFO	service hasn't started since it's disabled	{"service": "Pprof"}
2020-09-30T11:55:49.124Z	INFO	service hasn't started since it's disabled	{"service": "Prometheus"}
2020-09-30T11:55:49.124Z	INFO	skipped genesis block	{"hash": "3792eaa22c196399a114666fd491c4b9ac52491d9abb1f633a8036a8ac81e4db"}
2020-09-30T11:55:49.141Z	INFO	shutting down service	{"service": "Pprof", "endpoint": ":30001"}
2020-09-30T11:55:49.141Z	INFO	shutting down service	{"service": "Prometheus", "endpoint": ":40001"}
2020-09-30T11:55:49.141Z	INFO	blockchain persist completed …
```
> core: fix cache for (NEO).nextValidators and (NEO).committee

- pkg/core/interop_system.go
- pkg/core/interop_system_test.go
If `Put` creates new key, its length should contribute
to a GAS cost of the syscall.
Fix #1457 .
> core: calculate gas for `System.Storage.Put` correctly

- pkg/core/interop_neo.go
- pkg/core/interop_system_test.go
- pkg/vm/stack.go
Null means absense of script or manifest, empty
byte-slice is an error.
Related #1459.
> core: allow Null in `System.Contract.Update`

- pkg/vm/stackitem/item.go
- pkg/vm/stackitem/item_test.go
- pkg/vm/vm_test.go
Determine size as in reference implementation instead of
`big.Int.BitLen()`
Close #1437.
I have decided to implement only this check instead of generic `Size` to optimize for most frequent path (small ints).
> vm: handle very big int creation properly

- cli/multisig_test.go
- cli/paramcontext/context.go
- cli/smartcontract/smart_contract.go
- cli/wallet/multisig.go
- cli/wallet/nep5.go
It allows to invoke native contracts as committee
from CLI in privnet, e.g. to set new oracle nodes.
Also don't require `--out` flag in `multisig sign` if tx is to be pushed.
> cli: allow to send multisig deploy/invoke tx

- pkg/rpc/request/params.go
- pkg/rpc/server/server.go
Add Stringer to Params, if we're not printing Debug messages (which usually is
the case), it won't be called at all. Micro-optimization.
> server: don't always Sprintf params for logger

- pkg/core/native/designate.go
- pkg/core/native/native_nep5.go
- pkg/core/native/oracle.go
- pkg/core/native/policy.go
- pkg/core/native/util.go
- pkg/core/native_contract_test.go
> native: provide `name` method for all contracts

- pkg/core/dao/dao.go
- pkg/core/storage/store.go
Close #1468.
We should copy the key to avoid bytes substitution. Otherwise, there's a
chance that at the end of dao.Store.Seek(...) execution some keys won't
be the same as the original keys found inside saveToMap function.
> core: copy storage item key in simple.GetStorageItems

- pkg/core/blockchain.go
They're no longer valid if `ValidUntilBlock == curheight`. Should fix node stalls problem for @alexvanin.
> core: drop stale transactions from the mempool

- cli/smartcontract/smart_contract.go
- examples/runtime/runtime.go
- examples/timer/timer.go
- examples/timer/timer.yml
- pkg/compiler/func_scope.go
- pkg/compiler/if_test.go
- pkg/compiler/return_test.go
- pkg/core/interop/contract/call.go
- pkg/core/interop_neo.go
- pkg/core/interop_system_test.go
- pkg/vm/context.go
- pkg/vm/vm.go
Close #1466
I don't see any use-cases of `_deploy` method among our existing examples, so I created a new one (which is also an example for `contract.Update` and `contract.Destroy` interops).
Draft because the `timer` contract invocation fails on `migrate` with 
```
2020-10-10T20:02:43.675+0300	WARN	contract invocation failed	{"tx": "b2d11386c6a30aba0ef068e952a5f74146cc612baa7682abee2b4eeb79acbb09", "block": 333, "error": "error encountered at instruction 188 (NOT): runtime error: invalid memory address or nil pointer dereference"}
```
Still investigating.
UPD: that was a compiler issue. Fixed, but we can think about the other cases when we `DROP` the results of function calls which are actually used by the code.
> examples: add _deploy usage examples

- pkg/compiler/codegen.go
- pkg/compiler/function_call_test.go
While optimizing jumps (done in cfa62e7) old offsets should be compared
with the method offset before optimization, not with
the constantly changing value.
> compiler: fix manifest method offset

- pkg/vm/opcodebench_test.go
For future optimizations and price adjustments.
Not the prettiest piece of code in the world, but it gives some interesting results.
> vm: add opcode benchmark

- pkg/compiler/func_scope.go
- pkg/compiler/function_call_test.go
Call result is not used only if it occurs inside a `ExprStmt`.
Otherwise (`IfStmt`, `BinExpr`...) it is used.
Fix #1495.
> compiler: refactor void calls processing

- pkg/core/state/notification_event.go
- pkg/rpc/server/server.go
- pkg/rpc/server/subscription.go
Close #1494. Marshalling went wrong due to the incorrect pointers usage.
Reproduced and fixed.
> rpc: fix Matches and marshalling for notification events

- cli/candidate_test.go
- cli/contract_test.go
- cli/multisig_test.go
- cli/nep5_test.go
- cli/options/options.go
- cli/options/options_test.go
- cli/smartcontract/smart_contract.go
- cli/wallet_test.go
- pkg/rpc/client/client.go
- pkg/rpc/client/doc_test.go
- pkg/rpc/client/nep5.go
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/client/wsclient.go
- pkg/rpc/client/wsclient_test.go
- pkg/rpc/response/result/invoke.go
- pkg/rpc/response/result/version.go
- pkg/rpc/server/client_test.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
1. Use base64 encoding for `Invoke.Script`
2. Add `Network` to `Version` RPC result
> rpc, cli: use base64 script encoding for Invoke* calls; add Magic to `getversion` RPC call

- cli/options/options.go
Should be done in 590be7a. I removed
network flags from RPC, but we still need them for server-related
cli commands.
> cli: fixed removed network arguments

- pkg/config/protocol_config.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/transaction/attribute.go
- pkg/core/transaction/attribute_test.go
- pkg/core/transaction/attrtype.go
- pkg/core/transaction/attrtype_string.go
- pkg/core/transaction/not_valid_before.go
- pkg/core/transaction/reserved.go
- pkg/core/transaction/transaction.go
- pkg/core/transaction/transaction_test.go
> core: implement NotValidBefore and Reserved tx attributes

- docs/rpc.md
- pkg/core/blockchain.go
- pkg/core/state/nep5.go
- pkg/rpc/client/rpc.go
- pkg/rpc/response/result/nep5.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
RPC call to get all UTXO and NEP5 transfers for a given block.
This tries to use the same output format as `getalltransfertx`, but I don't like the way NEP-5 transfers are represented there (two events instead of one). This output format was fine for that function because it implied that the other (sender or receiver) address is the one from the request, but this doesn't work for blocks. So this likely to be changed based on feedback from our partners.
> Getblocktransfertx RPC API for 2.x

- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/native/designate.go
- pkg/core/native/oracle.go
- pkg/core/native_designate_test.go
- pkg/core/native_oracle_test.go
Follow neo-project/neo#2007. Fix getDesignatedByRole price along the way.
> native: implement designate contract history retention

- pkg/vm/vm.go
Before:
BenchmarkOpcodes/REVERSEITEMS/buffer/1M-8                   1680            758747 ns/op
After:
BenchmarkOpcodes/REVERSEITEMS/buffer/1M-8                   2649            442720 ns/op
> vm: improve REVERSEITEMS for 1M Buffer

- pkg/compiler/syscall.go
- pkg/core/interop/binary/itoa.go
- pkg/core/interop/binary/itoa_test.go
- pkg/core/interop/interopnames/names.go
- pkg/core/interops.go
- pkg/interop/binary/binary.go
They follow C# conversion rules, but differ from our `bigint` module
conversions:
1. String must be big-endian.
2. Sign extension is 4-bit in size (single hex character)
and not 8-byte.
Close #1527 .
> core: implement `System.Binary.Atoi/Itoa` syscalls

- pkg/core/mempool/mem_pool_test.go
Failing test:
```
=== RUN   TestMempoolAddRemoveConflicts
--- FAIL: TestMempoolAddRemoveConflicts (0.00s)
mem_pool_test.go:376:
Error Trace:	mem_pool_test.go:376
Error:      	Not equal:
expected: 4
actual  : 3
Test:       	TestMempoolAddRemoveConflicts
```
Do not randomize test data.
> core: fix failing mempool test

- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/response/result/invoke.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
Changes ported from https://github.com/neo-project/neo-modules/pull/394.
> rpc: use base64 for `submitblock` and `sendrawtransaction`

- pkg/core/native/native_neo.go
This lead to incorrect calculations.
> native: decode storage item in `Seek`

- pkg/core/native/oracle.go
The reference implementation does not store NodeList. This commit fixes
state difference for genesis block.
> core: remove NodeList from Oracle storage

- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
This commit fixes the difference between Go and C# nodes:
Go:
```
{
"jsonrpc" : "2.0",
"result" : {
"received" : [
{
"blockindex" : 65,
"txhash" : "0x394f851cf167d664c0dbcf98e2e64f2da23022fd7943dcb914492529de20a945",
"transfernotifyindex" : 0,
"timestamp" : 1605535020126,
"transferaddress" : "NUVPACMnKFhpuHjsRjhUvXz1XhqfGZYVtY",
"amount" : "29999999",
"assethash" : "0x668e0c1f9d7b70a99dd9e06eadd4c784d641afbc"
}
],
"address" : "NULwe3UAHckN2fzNdcVg31tDiaYtMDwANt",
"sent" : []
},
"id" : 1
}
```
C#:
```
{
"id" : 1,
"result" : {
"address" : "NULwe3UAHckN2fzNdcVg31tDiaYtMDwANt",
"sent" : [],
"received" : [
{
"transferaddress" : "NUVPACMnKFhpuHjsRjhUvXz1XhqfGZYVtY",
"timestamp" : 1605535020126,
"txhash" : "0x394f851cf167d664c0dbcf98e2e64f2da23022fd7943dcb914492529de20a945",
"blockindex" : 65, …
```
> rpc: adjust NEP5 transfers amount JSON marshalling

- pkg/config/protocol_config.go
- pkg/core/blockchain.go
- pkg/core/dao/dao.go
- pkg/core/mpt/base.go
- pkg/core/mpt/node.go
- pkg/core/mpt/node_test.go
- pkg/core/mpt/proof.go
- pkg/core/mpt/proof_test.go
- pkg/core/mpt/trie.go
- pkg/core/mpt/trie_test.go
- pkg/rpc/response/result/mpt_test.go
Results for a full testnet dump (5003730 blocks):
```
real    106m36,227s
user    192m32,855s
sys     14m45,739s
13G     .
real    121m10,446s
user    231m6,476s
sys     17m0,014s
9,0G    .
real    123m35,329s
user    284m21,860s
sys     22m32,090s
9,5G    .
```
First 2M mainnet blocks (will publish 2M-3M later). Note, generation GC starts every 200k blocks, so not all garbage was collected).
```
real    46m31,497s
user    76m51,146s
sys     5m52,001s
12G     .
real    44m28,469s
user    74m43,983s
sys     5m20,414s
13G     .
real    44m22,258s
user    74m16,260s
sys     5m5,966s
11G     .
```
First 3M mainnet blocks (same note for generational GC):
```
real    644m50,778s
user    1223m8,365s
sys     69m23,930s
56G     chains
real    698m50,998s
user    1019m11,077s
sys     85m33,651s
46G …
```
> Implement reference counting in MPT

- pkg/network/helper_test.go
- pkg/network/peer.go
- pkg/network/server.go
- pkg/network/tcp_peer.go
> network: treat unsolicited addr commands as errors

- pkg/config/protocol_config.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/dao/dao.go
Remove blocks with `height <= current height - MaxTraceableBlocks`
together with transactions.
Close #1560 .
For bench MaxTraceableBlocks=10 was set.
For dump with 5000 blocks, 100 tx per block results are roughly the same.
For dump with 100 blocks, 10_000 tx per block results begin to vary:
```
./neogo db restore --unittest --in ./chain.acc  465,80s user 28,98s system 242% cpu 3:23,65 total
754M    chains
./neogo db restore --unittest --in ./chain.acc  425,11s user 28,69s system 228% cpu 3:18,92 total
908M    chains
```
> core: remove old blocks and transactions

- cli/contract_test.go
- cli/smartcontract/smart_contract.go
- cli/testdata/invalid1/invalid.go
- cli/testdata/invalid1/invalid.yml
- cli/testdata/invalid2/invalid.go
- cli/testdata/invalid2/invalid.yml
- cli/testdata/invalid3/invalid.go
- cli/testdata/invalid3/invalid.yml
- examples/engine/engine.yml
- examples/iterator/iterator.go
- examples/iterator/iterator.yml
- examples/token-sale/token_sale.go
- examples/token-sale/token_sale.yml
- examples/token/nep17/nep17.go
- examples/token/token.go
- examples/token/token.yml
- pkg/compiler/codegen.go
- pkg/compiler/compiler.go
- pkg/compiler/debug.go
- pkg/smartcontract/manifest/manifest.go
- pkg/smartcontract/manifest/standard/comply.go
- pkg/smartcontract/manifest/standard/comply_test.go
- pkg/smartcontract/manifest/standard/doc.go
- pkg/smartcontract/manifest/standard/nep17.go
There are some standards (NEP5, etc.) which impose
some restrictions on what methods and events a contract
must contain and their signatures. This commit supports
checking if arbitrary manifest complies with the standard.
> manifest: support interface checking

- pkg/core/native/native_gas.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_nep17.go
- pkg/core/native/notary.go
- pkg/core/native/oracle.go
OnPayment method should be called during GAS distribution
and NEO transfer.
Close #1571 .
> native: call `onPayment` only during `transfer`

- pkg/core/mempool/mem_pool.go
- pkg/core/mempool/mem_pool_test.go
- pkg/core/native/oracle.go
If tx with the same oracle response ID is already in mempool,
replace it if network fee of added transaction is higher and
return error otherwise.
Close #1569 .
> mempool: correctly handle tx with oracle response

- pkg/network/message.go
- pkg/network/message_test.go
- pkg/network/payload/address_test.go
- pkg/network/payload/inventory_test.go
- pkg/network/payload/merkleblock.go
Unexpectedly enough, found 2 bugs related to `MerkleBlock` serialization.
Related #1579 .
Will do remaining tests in next PRs.
> network: add tests for `Message` serialization

- cli/flags/fixed8.go
- cli/flags/fixed8_test.go
- cli/nep17_test.go
- cli/smartcontract/smart_contract.go
- cli/wallet/nep17.go
- pkg/core/helper_test.go
- pkg/core/state/notification_event.go
- pkg/core/transaction/transaction.go
- pkg/core/transaction/transaction_test.go
- pkg/encoding/fixedn/decimal.go
- pkg/encoding/fixedn/decimal_test.go
- pkg/encoding/fixedn/fixed8.go
- pkg/encoding/fixedn/fixed8_test.go
- pkg/rpc/client/rpc.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/response/result/invoke.go
- pkg/rpc/response/result/invoke_test.go
- pkg/rpc/response/result/unclaimed_gas.go
- pkg/rpc/rpc_config.go
Close #1570 .
We use `big.Int` there, so I've implemented functions in `util`. They could be used in future in other places.
> Return FP strings for getunclaimedgas

- pkg/network/blockqueue_test.go
- pkg/network/discovery.go
- pkg/network/discovery_test.go
- pkg/network/helper_test.go
- pkg/network/message_test.go
- pkg/network/server.go
- pkg/network/server_test.go
Fixed 3 bugs:
1.  `GetBlocks` should sent exactly `Count` blocks.
2. `requestTx` couldn't didn't send anything if amount of hashes was small.
3. `requestTx` could panic, but luckily (or unluckily) (2) made this event rather unprobable.
`network.testChain` is rather ugly now, this should be fixed in #1472 . Now there are more specific requirements on what we could do with testchain in tests.
> network: add tests for most of the commands

- pkg/compiler/debug_test.go
- pkg/core/interop/context.go
- pkg/core/interop/contract/call.go
- pkg/core/native/designate.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_nep17.go
- pkg/core/native/notary.go
- pkg/core/native/oracle.go
- pkg/core/native/policy.go
- pkg/core/native_contract_test.go
- pkg/smartcontract/manifest/manifest.go
- pkg/smartcontract/manifest/manifest_test.go
- pkg/smartcontract/manifest/method.go
- pkg/smartcontract/manifest/standard/comply.go
- pkg/smartcontract/manifest/standard/comply_test.go
`interop.Contex.AddMethod` sets `Safe` flag for native
contracts. This allows not to forget to change manifest
when changing call flags.
Also fixed invalid `Safe` flags for `Notary` and `Designate` contracts.
Close #1594 .
I think, we can also change compiler to emit appropriate flags but this isn't straightforward because of lambda functions. Created a separate task for discussion #1596.
> manifest: add `Safe` flag to method descriptor

- examples/events/events.go
- examples/events/events.yml
- pkg/compiler/codegen.go
- pkg/compiler/debug.go
- pkg/compiler/debug_test.go
Distinguish between VM types which are used in debugger and smartcontract ones which are used in
manifest. We can't save only one of them, because conversion in either
side is lossy:
1. VM has `Array` and `Struct` but smartcontract only has `Array`.
2. Smartcontract has `Hash160` etc, which are all `ByteString` or
`Buffer` in VM.
And to spice things a bit more, return type in debugger can be `Void`,
which corresponds to no real stackitem type (as it must exist).
> compiler: save both VM and smartcontract types

- pkg/compiler/compiler_test.go
- pkg/vm/cli/cli_test.go
In some cases, `Run()` can read from input before we have written
anything to it.
Close #1601.
Can be reproduced with `time.Sleep` between `newTestVMCLI` and `runProg`.
Also fix a bug in compiler tests.
> vmcli/test: run shell after providing input

- pkg/config/protocol_config.go
- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/blockchainer/blockchainer.go
- pkg/core/blockchainer/policer.go
- pkg/core/helper_test.go
- pkg/core/mempool/mem_pool.go
- pkg/core/mempool/mem_pool_test.go
- pkg/core/native/notary.go
- pkg/core/native/policy.go
- pkg/core/native/util.go
- pkg/core/native_notary_test.go
- pkg/core/native_policy_test.go
- pkg/network/helper_test.go
- pkg/network/message.go
- pkg/network/notary_feer.go
- pkg/network/payload/inventory.go
- pkg/network/payload/inventory_test.go
- pkg/network/payload/notary_request.go
- pkg/network/payload/notary_request_test.go
- pkg/network/server.go
- pkg/network/server_test.go
> network: add notary request payload

- pkg/core/mempool/mem_pool.go
- pkg/core/mempool/mem_pool_test.go
Transaction is added to verifiedMap before OOM check, so we may have a
case when OOM occurs during tx1 pooling, but mp.containsKey(tx1)
returns `true` after this. Fixed.
> core: fix bug with mempool.verifiedMap

- go.mod
- go.sum
- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
Not doing this can possibly lead to the same node being validator
again and again.
> consensus: validate timestamp in `verifyBlock()`

- pkg/core/native/oracle.go
- pkg/core/native_oracle_test.go
Changes ported from https://github.com/neo-project/neo/pull/2159.
We haven't the same problem with `_deploy` invocations, but we have a bug with Oracle callbacks.
> core: restrict allowed Oracle callbacks

- pkg/network/helper_test.go
- pkg/network/message.go
- pkg/network/peer.go
- pkg/network/server.go
- pkg/network/tcp_peer.go
Right now a single slow peer can slow down whole network.
Do broadcast in 2 parts:
1. Perform non-blocking send to all peers if possible.
2. Perform blocking sends until message is sent to 2/3 of good peers.
Note that this is only about local queues, so in practice (1) will be the most common thing, unless we have a very slow neighbour. I am only concerned about the situation when messages are created faster than they can be send but as shown by benchmarks, this is rarely the case.
Related #1629.
> network: support non-blocking broadcast

- pkg/core/blockchain.go
- pkg/core/dao/dao.go
- pkg/core/mpt/base.go
- pkg/core/mpt/trie.go
- pkg/core/native_management_test.go
- pkg/core/storage/memory_store.go
- pkg/io/binaryBufWriter.go
I had concerns about copying when refcount is enabled, but it still seems to be better under high load and roughly the same on average. I think refcount needs more care later (e.g. using `sync.Pool` or even local `Trie` pool specially for slices contained in refcount map).
According to pprof most memory is consumed in `HashNode.EncodeBinary`. This is most likely due to expansion of `Branch` or `Extension` nodes during `Trie` update. Optimization done here is the only one which gives consistent improvements in terms of both running time and memory usage.
Other things which I tested:
1. Preallocate slice for hash nodes -- no noticeable improvements.
2. Implement `Size() int` for all nodes and preallocate -- better than master, but slower than this PR irregardless of other optimizations.
I …
> mpt: do not allocate new buffer when updating dirty node

- pkg/core/native/native_neo.go
Don't need to pay attention to key prefix while sorting.
> core: fix (*NEO).getCandidates

- pkg/core/mpt/base.go
- pkg/core/mpt/trie.go
- pkg/io/binaryBufWriter.go
Revert commit with cache reuse. It causes problems and doesn't add much compared to the second optimisation.
> Hotfixes for testnet

- cli/nep17_test.go
- cli/wallet/nep17.go
Fix #1652 .
Changed CLI directly because RPC needs to stay compatible.
Also fix balance tests to match full line, not just prefix.
> cli: output nep17 balance using decimals

- pkg/core/native/management.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_nep17.go
- pkg/core/native/policy.go
Partially reverts 33386065bc01b549db8f95a6358c62a11faada0a, see neo-project/neo#2183.
> native: use Hash160 method parameters where appropriate

- pkg/core/blockchain.go
- pkg/core/dao/dao.go
- pkg/core/mpt/batch.go
- pkg/core/mpt/batch_test.go
- pkg/core/mpt/helpers.go
When updating MPT via multiple `Put` there is substantial overhead as intermediate nodes are updated on each put. However we care only about the state on block boundaries.
This PR adds support for put in batches which doesn't calculate hashes for intermediate nodes.
There is no meaningful difference on benchmark of 4 nodes, but single node seems to benefit from this.
Restore times are also much less (40% gain for 10k tx per block, and 15% for 1 tx per block), same for memory consumption:
```
TotalAlloc (MiB): 16116
Mallocs: 224004004
Frees: 206607635
PauseTotalNs: 2669760
GCCPUFraction:: 0.03410
./neogo db restore --unittest --in ./chain50x10000.acc --dump before  62,49s user 0,88s system 170% cpu 37,103 total
TotalAlloc (MiB): 9654
Mallocs: 151838952
Frees: 139728189
PauseTotalNs: …
```
> mpt: support put in batches

- pkg/core/native/contract.go
- pkg/core/native/designate.go
- pkg/core/native/oracle.go
Role management doesn't need oracles, but oracles do need role management. See neo-project/neo#2187.
> native: swap oracle and role management init

- pkg/core/mempool/mem_pool.go
- pkg/core/mempool/mem_pool_test.go
Unlucky transaction could also have OracleResponce attribute.
> core: fix mempool.Add

- pkg/network/discovery.go
- pkg/network/discovery_test.go
1) It duplicates registration in `version` message handler and no valid
connection can work without version exchange.
2) On public networks we have seed nodes defined by names, so we register
connections to them using these names, but then if connection is dropped we
delist them by IP:PORT combinations which can lead to zero PeerCount() with
all seeds still being registered as connected in the discovery subsystem
and thus no reconnection attempts being made.
> network: don't register addresses before version handshake

- go.mod
- go.sum
- pkg/consensus/cache_test.go
- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/consensus/payload.go
- pkg/consensus/payload_test.go
- pkg/consensus/prepare_request.go
- pkg/consensus/recovery_message.go
- pkg/consensus/recovery_message_test.go
- pkg/network/message.go
- pkg/network/message_string.go
- pkg/network/message_test.go
- pkg/network/payload/extensible.go
- pkg/network/payload/extensible_test.go
- pkg/network/payload/inventory.go
- pkg/network/payload/inventory_test.go
- pkg/network/server.go
- pkg/network/server_test.go
Close #1663 .
Sender whitelist will be done in another PR.
> Introduce extensible payloads

- pkg/core/transaction/transaction.go
- pkg/core/transaction/transaction_test.go
- pkg/encoding/fixedn/fixed8.go
- pkg/encoding/fixedn/fixed8_test.go
Some transactions failed to unmarshal with `txid doesn't match transaction hash`.
> Fix transaction fee marshalling

- cli/wallet/wallet.go
- pkg/core/blockchain.go
- pkg/core/interop/contract/call.go
- pkg/core/interop_system_test.go
- pkg/core/native/management.go
- pkg/core/native_management_test.go
- pkg/smartcontract/manifest/manifest.go
- pkg/smartcontract/manifest/standard/comply.go
- pkg/smartcontract/manifest/standard/comply_test.go
- pkg/vm/cli/cli.go
Multiple methods with different parameter count can co-exist.
As I understand, only native contracts are affected currently.
Close #1683 .
> core: allow to overload contract methods

- pkg/consensus/consensus.go
- pkg/consensus/consensus_test.go
- pkg/core/blockchain.go
- pkg/core/blockchainer/blockchainer.go
- pkg/core/native/designate.go
- pkg/core/native/oracle.go
- pkg/core/native_designate_test.go
- pkg/network/extpool/pool.go
- pkg/network/extpool/pool_test.go
- pkg/network/helper_test.go
- pkg/network/server.go
- pkg/network/server_test.go
We should store them in one place.
Close #1663 .
> Add pool for `Extensible` payloads

- pkg/core/native/management.go
- pkg/core/native/native_neo.go
- pkg/core/native/notary.go
- pkg/core/native/policy.go
- pkg/core/native_neo_test.go
- pkg/core/native_notary_test.go
- pkg/core/native_policy_test.go
Fail execution if tx is not signed by committee.
Close #1694 .
Related #1678 (set/getprice test).
> native: unify committee checks

- cli/testdata/deploy/main.go
- cli/testdata/deploy/sub/put.go
- examples/runtime/runtime.go
- examples/timer/timer.go
- pkg/compiler/codegen.go
- pkg/compiler/debug.go
- pkg/compiler/debug_test.go
- pkg/core/interop/context.go
- pkg/core/interop_system_test.go
- pkg/core/native/interop.go
- pkg/core/native/management.go
- pkg/core/native_management_test.go
Close #1682 .
Also follow https://github.com/neo-project/neo/pull/2241/ .
> Provide additional data on deployment

- pkg/consensus/consensus.go
- pkg/network/payload/extensible.go
2+2 Go/C# consensus.
This makes it work with preview5 C# nodes:
```
2021/02/04 13:57:49 empty block: 6
2021/02/04 13:57:50 CPU: 1.047%, Mem: 398.176MB
2021/02/04 13:57:51 (#7/122) 122 Tx's in 5010 ms 24.351297 tps
2021/02/04 13:57:56 (#8/252) 252 Tx's in 5020 ms 50.199203 tps
2021/02/04 13:58:00 CPU: 2.029%, Mem: 437.016MB
2021/02/04 13:58:01 (#9/249) 249 Tx's in 5011 ms 49.690681 tps
2021/02/04 13:58:06 (#10/252) 252 Tx's in 5017 ms 50.229221 tps
```
> Consensus compatibility

- pkg/consensus/consensus.go
Nodes happily reused zero-length proposals from previous blocks.
Disallow that.
> Fix previous proposal handling in consensus

- pkg/core/native/compatibility_test.go
- pkg/core/native/native_neo.go
> native: fix `getCommittee` name

- pkg/network/payload/headers.go
- pkg/network/payload/headers_test.go
> payload: treat zero-length headers as error

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/convert_test.go
- pkg/compiler/debug.go
- pkg/compiler/debug_test.go
- pkg/compiler/native_test.go
- pkg/compiler/testdata/types/types.go
- pkg/core/native/compatibility_test.go
- pkg/interop/native/gas/gas.go
- pkg/interop/native/ledger/block.go
- pkg/interop/native/ledger/ledger.go
- pkg/interop/native/ledger/transaction.go
- pkg/interop/native/management/contract.go
- pkg/interop/native/management/management.go
- pkg/interop/native/nameservice/name_service.go
- pkg/interop/native/neo/neo.go
- pkg/interop/native/notary/notary.go
- pkg/interop/native/oracle/oracle.go
- pkg/interop/native/policy/policy.go
- pkg/interop/native/roles/roles.go
- pkg/interop/runtime/engine.go
Implement first part of #1691 (without inlining).
Also allow more type conversions to take place.
> Represent native contracts as interop packages

- pkg/core/native_name_service_test.go
Fix #1710 .
We should look for the timestamp of the block with `register`.
> core/tests: fix NameService test

- cli/testdata/deploy/neo-go.yml
- pkg/core/blockchain.go
- pkg/core/blockchain_test.go
- pkg/core/interop_system_test.go
- pkg/core/native/management.go
- pkg/core/native/management_test.go
- pkg/core/native_management_test.go
- pkg/crypto/keys/publickey.go
- pkg/smartcontract/manifest/abi.go
- pkg/smartcontract/manifest/abi_test.go
- pkg/smartcontract/manifest/event.go
- pkg/smartcontract/manifest/event_test.go
- pkg/smartcontract/manifest/group.go
- pkg/smartcontract/manifest/group_test.go
- pkg/smartcontract/manifest/manifest.go
- pkg/smartcontract/manifest/manifest_test.go
- pkg/smartcontract/manifest/method.go
- pkg/smartcontract/manifest/method_test.go
- pkg/smartcontract/manifest/parameter.go
- pkg/smartcontract/manifest/parameter_test.go
- pkg/smartcontract/manifest/permission.go
- pkg/smartcontract/manifest/permission_test.go
- pkg/util/bitfield/bitfield.go
- pkg/util/bitfield/bitfield_test.go
- pkg/vm/context.go
- pkg/vm/contract_checks.go
- pkg/vm/contract_checks_test.go
- pkg/vm/opcode/opcode.go
- pkg/vm/opcode/opcode_test.go
- pkg/vm/vm.go
> Manifest and script checks

- cli/executor_test.go
- cli/input/input.go
- cli/smartcontract/smart_contract.go
- cli/vm/vm.go
- cli/wallet/validator.go
- cli/wallet/wallet.go
- cli/wallet_test.go
- go.mod
- go.sum
Close #1688 .
Maybe we should allow only letters and numbers for account names and exclude spaces + punctuation.
> Handle terminal escape codes correctly in CLI

- pkg/compiler/codegen.go
- pkg/compiler/function_call_test.go
- pkg/core/helper_test.go
Close #1728 .
Because `_initialize` and `_deploy` methods encompass multiple
Go functions, their offsets are stored differently and need
special treatment.
> compiler: adjust init/_deploy method offsets during optimization

- pkg/rpc/client/nep17.go
Makes no sense disabling it with writes enabled. Fixes #1725.
@alexvanin --- does it fix the problem for you?
> client: allow transfer method to read states

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/func_scope.go
- pkg/compiler/inline.go
- pkg/compiler/inline_test.go
- pkg/compiler/testdata/inline/a/a.go
- pkg/compiler/testdata/inline/b/b.go
- pkg/compiler/testdata/inline/inline.go
- pkg/compiler/types.go
- pkg/compiler/vars.go
Depends on #1702 .
Close #1691 .
Base for #941.
Haven't implemented general case, but enough to cover all our needs.
Current restrictions (none of them is a problem for wrappers):
1. Parameter in inline function can't be assigned to.
2. There should be exactly 1 exit point (`return`).
3. No `defer`s in inlined functions.
4. No recursion.
None of them is difficult to fix, but I don't see much value in doing this now without some real use-case.
> Allow to inline internal wrappers in compiler

- pkg/core/blockchain_test.go
- pkg/core/interop_system_test.go
- pkg/core/mpt/batch.go
- pkg/core/mpt/batch_test.go
- pkg/core/mpt/trie.go
- pkg/core/mpt/trie_test.go
This bug was here before batch were intoduced.
`Delete` is allowed to be called on missing keys with
HALT result, MPT needs to take this into account.
> mpt: allow to remove non-existent keys in batch

- pkg/compiler/codegen.go
- pkg/compiler/slice_test.go
Close #1749 .
I works, but I am currently thinking how we can handle byte varargs in a more general way, including user-defined functions.
> Append bytes bigger than 0x79 properly

- docs/rpc.md
- pkg/core/blockchain.go
- pkg/core/blockchainer.go
- pkg/core/state/nep5.go
- pkg/core/state/nep5_test.go
- pkg/core/transaction/asset_type.go
- pkg/core/transaction/publish.go
- pkg/core/transaction/register.go
- pkg/network/helper_test.go
- pkg/rpc/client/rpc_test.go
- pkg/rpc/response/result/asset_state.go
- pkg/rpc/response/result/block.go
- pkg/rpc/response/result/peers.go
- pkg/rpc/response/result/peers_test.go
- pkg/rpc/response/result/tx_output.go
- pkg/rpc/server/server.go
- pkg/rpc/server/server_test.go
RPC audit.
Lots of minor problems were found and fixed, but two problems stand out: system fee calculations (that affect available GAS estimations) and NEP5 balance switch from int64 to big.Int (because there are tokens that easily overflow int64).
> [2.x] RPC compatibility (and other) fixes and docs

- pkg/compiler/syscall.go
- pkg/core/interop/interopnames/names.go
- pkg/core/interop_system.go
- pkg/core/interop_system_test.go
- pkg/core/interops.go
- pkg/interop/contract/contract.go
> core: add System.Contract.CreateMultisigAccount

- pkg/compiler/compiler.go
- pkg/compiler/compiler_test.go
- pkg/core/native/name_service_test.go
- pkg/core/native/nonfungible_test.go
- pkg/smartcontract/manifest/manifest.go
- pkg/smartcontract/manifest/standard/check.go
- pkg/smartcontract/manifest/standard/comply.go
- pkg/smartcontract/manifest/standard/comply_test.go
- pkg/smartcontract/manifest/standard/nep11.go
- pkg/smartcontract/manifest/standard/nep17.go
- pkg/smartcontract/manifest/standard/payable.go
- pkg/smartcontract/manifest/standard/token.go
Close #1713 .
1. `name` method is missing  because it is provided in manifest.
2. Return type of `properties` method is `Map`, not string in JSON.
> smartcontract: add NEP-11 standard check

- .circleci/config.yml
> circleci: update Go build version

- cli/wallet/validator.go
- pkg/compiler/interop_test.go
- pkg/compiler/native_test.go
- pkg/core/interop/contract/call.go
- pkg/core/interops.go
- pkg/core/native/designate.go
- pkg/core/native/management.go
- pkg/core/native/name_service.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_nep17.go
- pkg/core/native/nonfungible.go
- pkg/core/native/notary.go
- pkg/core/native/oracle.go
- pkg/core/native/policy.go
- pkg/interop/native/management/management.go
- pkg/interop/native/nameservice/name_service.go
- pkg/interop/native/neo/neo.go
- pkg/interop/native/notary/notary.go
- pkg/interop/native/oracle/oracle.go
- pkg/interop/native/policy/policy.go
- pkg/interop/native/roles/roles.go
Replace `WriteStates` with `States`.
Follow neo-project/neo#2339.
Close #1775.
Related #1725.
> core: fix native method call flags

- pkg/rpc/response/errors.go
- pkg/rpc/server/server.go
These changes do not break the compatibility with the C# node response.
It is useful for the end-user to be aware of the failed validation reason.
Also, the `cause` will be displayed at the running node log.
> rpc: detalize `submit*` RPC validation error

- pkg/compiler/codegen.go
- pkg/compiler/inline.go
- pkg/compiler/inline_test.go
- pkg/compiler/vm_test.go
> Process `return` in inlined functions properly.

- pkg/vm/stackitem/json.go
- pkg/vm/stackitem/json_test.go
Close #1790 .
Decoding uses `json.Decoder` which handles everything for us.
To my current understanding error cannot occur during marshalling of a valid string.
> stackitem: escape control characters in `ToJSON()`

- pkg/consensus/consensus_test.go
Fix #1800 .
The test executed before `TestService_GetVerified` is `TestService_NextConsensus`, where chain is not closed.
Haven't reproduced it locally, happens only on CI. This can be a reason for this race.
> consensus/test: add missing `t.Cleanup()`

- cli/contract_test.go
- cli/executor_test.go
- cli/nep17_test.go
- cli/smartcontract/smart_contract.go
- cli/testdata/verify.go
- cli/testdata/verify.yml
- cli/testdata/wallet1_solo.json
- cli/wallet/validator.go
- pkg/rpc/client/nep17.go
- pkg/rpc/client/rpc.go
- pkg/rpc/server/client_test.go
We need cosigners' accounts to calculate the network fee properly.
> rpc, cli: allow to provide cosigners accounts to (*Client).CreateTxFromScript

- pkg/interop/contract/contract.go
Introduced in #1720.
Close #1803.
> interop: fix CreateMultisigAccount interop

- pkg/interop/storage/storage.go
The same bug as in #1804.
Also checked the rest of interops, they're OK. Maybe we need some test for such bugs.
> interop: fix ConvertContextToReadOnly interop

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/import_test.go
> compiler: fix import alias handling

- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/constant_test.go
- pkg/compiler/convert_test.go
- pkg/compiler/syscall_test.go
- pkg/interop/contract/contract.go
- pkg/interop/convert/convert.go
- pkg/interop/math/math.go
- pkg/interop/neogointernal/opcode.go
- pkg/interop/runtime/runtime.go
- pkg/interop/storage/storage.go
Close #1793 .
Also:
1. Don't convert syscall results.
2. Simplify `convert.To*` handling in compiler.
3. Add other missing interops (`ABS`, `SIGN`, `MAX`, `MIN`).
> Add syscalls for POW and SQRT opcodes

- pkg/compiler/syscall_test.go
- pkg/core/interops.go
- pkg/interop/contract/contract.go
Fix 2 bugs along the way.
This is obviously needed (#1806, #1804).
> compiler: add test for syscall handling

- pkg/core/native/native_neo.go
- pkg/core/native/nonfungible.go
- pkg/smartcontract/manifest/standard/nep11.go
> native: use proper types in manifest

- pkg/core/native/native_neo.go
See neo-project/neo#2392, neo-project/neo#2391.
> native: change getCommittee/getNextBlockValidators price

- pkg/services/oracle/filter.go
- pkg/services/oracle/neofs/neofs.go
- pkg/services/oracle/neofs/neofs_test.go
- pkg/services/oracle/request.go
See also https://github.com/neo-project/neo-modules/issues/555 .
> Use filters with NeoFS responses

- README.md
- cli/contract_test.go
- examples/README.md
- examples/my_wallet.json
- examples/runtime/runtime.go
- examples/timer/timer.go
- examples/token-sale/token_sale.go
- examples/token/token.go
- pkg/compiler/compiler_test.go
- pkg/wallet/wallet_test.go
Update to the new valid one after the signature scheme changes.
> examples: update owner address

- config/protocol.testnet.yml
- pkg/config/netmode/netmode.go
It's 827601742, N3T1, see https://github.com/neo-project/neo-node/releases/tag/v3.0.0-rc1
> config: adjust default testnet magic for RC1 testnet

- pkg/network/discovery.go
- pkg/network/server.go
Node trying to establish tens of connections to the same peers.
> Fix too many connections attempted

- pkg/rpc/server/server.go
Proper network should have it set to `true` and client should know about it.
> rpc/server: fix getversion reply for staterootinheader extension

- pkg/core/blockchain.go
- pkg/core/native_management_test.go
- pkg/core/stateroot/module.go
- pkg/core/stateroot/store.go
- pkg/services/stateroot/network.go
- pkg/services/stateroot/service.go
- pkg/services/stateroot/signature.go
- pkg/services/stateroot/validators.go
They're broken.
Make them a little less broken.
> Fix broken stateroots

- pkg/core/blockchainer/policer.go
- pkg/rpc/client/rpc.go
- pkg/rpc/server/client_test.go
- pkg/rpc/server/server.go
> rpc: add `calculatenetworkfee` RPC method

- pkg/core/native/native_neo.go
- scripts/compare-dumps.go
- scripts/compare-dumps_test.go
> core: RC1 states dumps compatibility fixes

- pkg/core/interop/runtime/engine.go
- pkg/core/interop/runtime/engine_test.go
- pkg/vm/vm.go
**Does not** affects states.
This PR includes the following fixes:
1. More detailed error message during SYSCALL invocation
2. System.Runtime.Notify refactoring
3. THROW opcode handling refactoring
> vm: minor C# compatibility fixes

- pkg/core/native/native_gas.go
- pkg/core/native/native_neo.go
- pkg/core/native/native_nep17.go
Not from DAO's items with storage.STNEP17Balances prefix, because
changes are reflected there only after notifications processing. And
this happens only after the transaction script is executed, but there
might be cases when we need to get the balance that was updated
earlier during the same transaction processing.
Affects storage dumps.
This PR makes us compatible with the C# nodes up to 44k of the RC1 testnet.
> core: get native nep17 balance from contract storage

- pkg/compiler/func_scope.go
- pkg/compiler/inline_test.go
- pkg/compiler/testdata/inline/inline.go
This simple code:
```
// OracleCallback is called by Oracle contract when the request is finished.
func OracleCallback(url []byte, data []byte, code int, res []byte) {
if code != 0 {
panic("oracle request failed for " + string(url) + " with " + std.Itoa(code, 10))
}
runtime.Log("oracle result for " + string(url) + ":" + string(res))
}
```
Fails with
```
error encountered at instruction 1 (SYSCALL): error during call from native: error encountered at instruction 205 (STLOC2): runtime error: index out of range [2] with length 2
```
Which means that the code generated is just plain wrong because it initializes two local slots and then uses all three of them.
#1878 would be a better one, but this one suffices for now.
> Compiler inlining fixes

- pkg/core/blockchain.go
Fix #1867, revert part of bf20db09e05fae4d7e3ef142b823bab8df32ce7e.
> core: restore MPT collapsing logic

- pkg/core/interop_neo.go
Fixes #1873. NewByteArray() doesn't copy the slice, so we need to do it
ourselves.
> core: fix key clashes in Storage.Find

- pkg/rpc/server/server.go
> rpc/server: be more specific in some sendrawtransaction error cases

- pkg/core/blockchain.go
Refs. #1900. It won't fail like that, but still worth fixing.
> core: ignore non-numeric "amounts" in Transfer events

- cli/candidate_test.go
- cli/contract_test.go
- cli/multisig_test.go
- cli/nep17_test.go
- cli/smartcontract/smart_contract.go
- cli/wallet/multisig.go
- cli/wallet/nep17.go
- cli/wallet/validator.go
- cli/wallet/wallet.go
- cli/wallet_test.go
We have a lot of places where `cli.StringFlag` is used instead of `flags.AdddressFlag`.
Also close #1895.
> cli: refactor AddressFlag usages

- cli/nep17_test.go
- cli/smartcontract/smart_contract.go
- cli/smartcontract/smart_contract_test.go
- cli/wallet/nep17.go
- config/protocol.unit_testnet.single.yml
- pkg/rpc/client/nep17.go
- pkg/smartcontract/parameter.go
- pkg/smartcontract/parameter_test.go
- pkg/vm/emit/emit.go
Close #1896.
Implemented only for single transfer, because multitransfer syntax doesn't allow to easily parse data for each token. However, we may add an ability to provide one common data parameter for all multitransfer tokens via the last argument.
> cli: allow to pass 'data' for nep17 transfer command

- cli/smartcontract/smart_contract.go
- cli/smartcontract/smart_contract_test.go
- pkg/rpc/request/param.go
> cli, rpc: use CalledByEntry as a default cosigner's scope

- cli/contract_test.go
- pkg/rpc/client/rpc.go
- pkg/rpc/server/client_test.go
- pkg/wallet/account.go
Close #1894.
We need to construct a witness for each provided cosigner. If we can't do that, we shouldn't send the transaction to RPC server and an error should be returned.
> rpc: properly construct cosigners' witnesses in SignAndPushInvocationTx

- cli/contract_test.go
- cli/multisig_test.go
- cli/smartcontract/smart_contract.go
- cli/wallet_test.go
> cli: unify 'contract deploy' and 'contract invoke*'

- pkg/core/native/nonfungible.go
It's not so important because native NNS will be removed, but let's fix it.
> core: add NEP11 to nonfungible supported standards list

- pkg/rpc/client/rpc_test.go
- pkg/rpc/response/result/version.go
Follow neo-modules/neo-core changes. We don't rename structure fields though
to stay compatible with current code (and we do have netmode.Magic to justify
that also).
> rpc: rename magic to network in JSON

- pkg/config/application_config.go
- pkg/network/server.go
- pkg/network/server_config.go
> network: add ability to specify port for P2P version exchange

- cli/cmdargs/parser.go
- cli/contract_test.go
- cli/nep11_test.go
- cli/nep17_test.go
- cli/wallet/nep11.go
- cli/wallet/nep17.go
- cli/wallet/wallet.go
- examples/nft-nd/nft.go
- examples/nft-nd/nft.yml
- pkg/config/config.go
- pkg/rpc/client/helper.go
- pkg/rpc/client/nep.go
- pkg/rpc/client/nep11.go
- pkg/rpc/client/nep17.go
- pkg/rpc/response/result/invoke.go
- pkg/rpc/rpc_config.go
- pkg/rpc/server/client_test.go
- pkg/rpc/server/server.go
- pkg/smartcontract/manifest/manifest.go
- pkg/vm/interop.go
- pkg/wallet/token.go
- pkg/wallet/token_test.go
- pkg/wallet/wallet_test.go
Close #1860, close #1864.
TODO:
> cli: support NEP11-related commands

- cli/server/server.go
- docs/cli.md
> cli: reload RPC-server TLS config on SIGHUP

- config/protocol.testnet.yml
It's 'N3T2', see https://github.com/neo-project/neo-node/releases/tag/v3.0.0-rc2
> config: update testnet magic number for N3 RC2 testnet

- pkg/core/stateroot_test.go
- pkg/services/stateroot/network.go
- pkg/services/stateroot/service.go
- pkg/services/stateroot/signature.go
- pkg/services/stateroot/validators.go
#1922 originally, but some additional fixes were also needed.
> Single stateroot sender

- pkg/compiler/native_test.go
- pkg/core/native/std.go
- pkg/core/native/std_test.go
- pkg/interop/native/std/std.go
> Add Itoa/Atoi overloads, add string-related methods to Std contract

- pkg/config/protocol_config.go
- pkg/core/blockchain.go
- pkg/core/helper_test.go
- pkg/core/native/notary.go
- pkg/core/native_notary_test.go
- pkg/core/transaction/transaction.go
- pkg/services/oracle/response.go
> config: make `MaxValidUntilBlockIncrement` configurable

- cli/nep17_test.go
- cli/testdata/wallet1_solo.json
- pkg/compiler/analysis.go
- pkg/compiler/codegen.go
- pkg/compiler/debug_test.go
- pkg/compiler/defer_test.go
- pkg/compiler/func_scope.go
- pkg/compiler/function_call_test.go
- pkg/compiler/inline.go
- pkg/compiler/inline_test.go
- pkg/compiler/syscall_test.go
There are multiple cases:
1. For simple functions and `_deploy` their locals count is updated in `writeJumps`.
2. For `init` functions we accumulate locals count across the calls.
3. In addition to (2) when globals are initialized using inlined function, auxiliary locals need to be added as well.
Close #1878 .
> compiler: drop `countLocals` logic

- pkg/rpc/request/txBuilder.go
- pkg/rpc/request/tx_builder_test.go
- pkg/rpc/server/server_test.go
Disallow strings or integers.
Related #1919 .
> rpc/request: handle bool parameters correctly

- pkg/core/native/std.go
- pkg/core/native/std_test.go
Close #1974 .
There is a possible bug: `CheckEncode` appends to the provided slice directly, which bothers me a bit. However I haven't found ways to exploit this because it returns new slice and all our buffer opcodes return new slice too.
> native/std: add base58Check* methods

- pkg/compiler/native_test.go
- pkg/interop/native/std/std.go
> compiler: add `Base58Check*` interop wrappers

- examples/nft-nd-nns/nns.go
- pkg/core/nonnative_name_service_test.go
Refs. https://github.com/neo-project/non-native-contracts/pull/3
> examples: fix IPv6 bounds check

- cli/cmdargs/parser.go
- cli/cmdargs/parser_test.go
- cli/smartcontract/smart_contract.go
The syntax is `CalledByEntry,CustomContracts:hash1:hash2`.
This way we need to perform validation (don't combine `Global` with other scopes separately).
Another solution is `CalledByEntry,CustomContracts,CustomGroups:hash1:hash2:key1:key2` but it is non-intuitive.
> cli: allow to specify CustomContracts/Groups signer

- cli/candidate_test.go
- cli/wallet/validator.go
- pkg/core/state/native_state.go
> cli: add `wallet candidate getstate`

- pkg/compiler/codegen.go
- pkg/compiler/inline.go
- pkg/compiler/inline_test.go
- pkg/compiler/testdata/foo/foo.go
- pkg/compiler/vars.go
- pkg/compiler/vm_test.go
Close #1881, #1879.
If expression has no side-effects we can traverse it in inline function in old context (contains import maps and local bindings).
This also unifies all different cases (local variable, global variable, struct field access etc.).
The heuristic for "no side-effects" is "no function calls".
> Allow to inline selector statements

- pkg/network/server.go
It's the first thing done in tryStartServices(), so checking it here doesn't
make much sense.
> network: drop useless flag check

- pkg/compiler/codegen.go
- pkg/compiler/compiler.go
- pkg/compiler/compiler_test.go
- pkg/compiler/inline.go
Only direct invocations are considered. The check can be disabled
with '--no-events' compiler option.
Close #1994 .
I have been thinking about introducing generic warnings mechanism but stopped, because our compiler doesn't seem _that_ complicated. It could be used e.g. in #1990, but I haven't yet come up with more cases for it to be useful.
> compiler: disallow `runtime.Notify` in `Verify` function

- pkg/rpc/client/rpc.go
- pkg/rpc/response/result/netfee.go
- pkg/rpc/server/server.go
C#:
{
"jsonrpc": "2.0",
"id": 2,
"result": {
"networkfee": "1185120"
}
}
Go:
{
"id": 2,
"jsonrpc": "2.0",
"result": 1185120
}
Thanks @csmuller for finding it.
> rpc: wrap calculatenetworkfee result in a structure

- pkg/core/mpt/batch_test.go
- pkg/core/mpt/compat_test.go
- pkg/core/mpt/extension.go
- pkg/core/mpt/node.go
- pkg/core/mpt/node_test.go
- pkg/core/mpt/trie.go
- pkg/core/mpt/trie_test.go
> Add MPT compatibility tests

- pkg/vm/stackitem/json.go
This commit fixes the following Go vs C# state diff:
block 74613: value mismatch for key EwAAAHN0cmVhbXMvDg==: eyJpZCI6MTQsInN0YXJ0IjoxNjIyNTAwMjAwMDAwLCJzdG9wIjoxNjIyNTAyMDAwMDAwLCJkZXBvc2l0IjoxMDAwMDAwMDAsInJlbWFpbmluZyI6MTAwMDAwMDAwLCJzZW5kZXIiOiJmeEY4RDl2ZFU3K0gwcDV3NTlyWllMNytNSlE9IiwicmVjaXBpZW50IjoiSVV6c3pveFV0S1NGVnlZRGczSmdTQTFlbTFNPSJ9 vs eyJpZCI6MTQsInN0YXJ0IjoxNjIyNTAwMjAwMDAwLCJzdG9wIjoxNjIyNTAyMDAwMDAwLCJkZXBvc2l0IjoxMDAwMDAwMDAsInJlbWFpbmluZyI6MTAwMDAwMDAwLCJzZW5kZXIiOiJmeEY4RDl2ZFU3XHUwMDJCSDBwNXc1OXJaWUw3XHUwMDJCTUpRPSIsInJlY2lwaWVudCI6IklVenN6b3hVdEtTRlZ5WURnM0pnU0ExZW0xTT0ifQ==
I.e.:
```
{"id":14,"start":1622500200000,"stop":1622502000000,"deposit":100000000,"remaining":100000000,"sender":"fxF8D9vdU7+H0p5w59rZYL7+MJQ=","recipient":"IUzszoxUtKSFVyYDg3JgSA1em1M="}
```
vs …
> vm: serialize `+` rune as `\u002B` for byte-contained stackitems

- cli/nep11_test.go
- examples/nft-nd/nft.go
Test `TestNEP11_OwnerOf_BalanceOf_Transfer` fails due to insufficient system fee while minting HASHY token.
Use constant-length token IDs.
> examples: use base64 encoding to create HASHY token ID

- cli/nep11_test.go
- cli/smartcontract/smart_contract.go
- cli/testdata/testwallet.json
- cli/testdata/wallet1_solo.json
- cli/wallet/legacy.go
- cli/wallet/validator.go
- cli/wallet/wallet.go
- cli/wallet_test.go
- pkg/consensus/consensus.go
- pkg/core/helper_test.go
- pkg/core/notary_test.go
- pkg/core/oracle_test.go
- pkg/core/stateroot_test.go
- pkg/crypto/keys/nep2.go
- pkg/crypto/keys/nep2_test.go
- pkg/rpc/server/client_test.go
- pkg/services/notary/node.go
- pkg/services/notary/node_test.go
- pkg/services/notary/notary.go
- pkg/services/notary/testdata/notary1.json
- pkg/services/notary/testdata/notary2.json
- pkg/services/oracle/nodes.go
- pkg/services/oracle/oracle.go
- pkg/services/stateroot/service.go
- pkg/wallet/account.go
- pkg/wallet/account_test.go
- pkg/wallet/regenerate_test.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
This PR should fix `Tests` Github Workflow failing due to timeout while decrypting account:
```
2021-05-31T08:30:46.4452214Z goroutine 4306 [runnable]:
2021-05-31T08:30:46.4452963Z golang.org/x/crypto/scrypt.salsaXOR(0xc00034d7e8, 0xc00017d980, 0x1a0, 0x1a0, 0xc00017dcc0, 0xd0, 0xd0)
2021-05-31T08:30:46.4454249Z 	/home/runner/go/pkg/mod/golang.org/x/crypto@v0.0.0-20190701094942-4def268fd1a4/scrypt/scrypt.go:34 +0x118b
2021-05-31T08:30:46.4455237Z golang.org/x/crypto/scrypt.blockMix(0xc00034d7e8, 0xc00017d800, 0x200, 0x200, 0xc00017dc00, 0x100, 0x100, 0x8)
2021-05-31T08:30:46.4456510Z 	/home/runner/go/pkg/mod/golang.org/x/crypto@v0.0.0-20190701094942-4def268fd1a4/scrypt/scrypt.go:134 +0x258
2021-05-31T08:30:46.4457470Z golang.org/x/crypto/scrypt.smix(0xc00045fc00, 0x400, 0x400, 0x8, …
```
> crypto: use non-default scrypt parameters for encrypting/decrypting

- pkg/core/native/native_neo.go
State diff at block 151376 due to invalid order of candidates returned from native NEO `getCandidates` [call](https://github.com/Ashuaidehao/CommitteeInfoContract/blob/main/src/CommitteeInfoContract.cs#L31).
(*NEO).GetCandidates along with getCandidatesCall use candidates sorted
by serialized ECPoint bytes. See ref. [GetCandidates](https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/Native/NeoToken.cs#L333) and [Seek](https://github.com/neo-project/neo/blob/master/src/neo/Persistence/DataCache.cs#L368).
(*NEO).computeCommitteeMembers use candidates sorted by votes, and then
by deserialized ECPoint, i.e. using default ECPoint comparator. See ref. [ComputeCommetteeMembers](https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/Native/NeoToken.cs#L397) and …
> core: fix the way candidates are sorted

- pkg/network/discovery.go
- pkg/network/discovery_test.go
Noticed by @532910:
```
1880ms 18.80% 43.00%    10000ms   100%  github.com/nspcc-dev/neo-go/pkg/network.(*DefaultDiscovery).run
```
Backport some fixes from master.
> Fix infinite loop in discoverer

- examples/nft-nd-nns/nns.yml
- examples/nft-nd/nft.yml
- examples/oracle/oracle.yml
- examples/timer/timer.yml
- examples/token/token.yml
Manifest files should contain permission section if contract makes invocations with writing scope. However not every example contracts adopted this change.
> Fix permissions in example manifests

- cli/smartcontract/smart_contract.go
- pkg/compiler/codegen.go
- pkg/compiler/compiler.go
- pkg/compiler/compiler_test.go
- pkg/compiler/debug.go
- pkg/compiler/inline.go
- pkg/compiler/testdata/runh/hash.go
- pkg/rpc/server/testdata/test_contract.yml
> Check manifest permissions at compile-time
